Fix IIS partial preload is not working due to directory separator
wp-media/wp-rocket pull request #2251
Opened 2020-01-15 13:28 UTC by crystinutzaa

**Thank you for wanting to contribute to WP Rocket! Before submitting a pull request, please check that you’ve completed the following steps:**
- Please make sure that there aren’t existing pull requests attempting to address the issue mentioned.
- Check for related issues on the issue tracker.
- Non-trivial changes should be discussed on an issue first.
- Let us know you’re working on the issue.
- Develop in a topic branch, not master.

**Things to add in the pull request to help us:**
- Provide useful pull request description.
- Follow project commit guidelines.
- Write a good description of your PR.
- Link to the Github issue in the description.

2020-01-15 13:44 UTC, hellofromtonya commented
@crystinutzaa Needs tests with it to ensure the changes work and don't break anything.

2020-01-15 15:01 UTC, Tabrisrp commented
You have a WP function, wp_normalize_path, to handle this kind of issues: https://developer.wordpress.org/reference/functions/wp_normalize_path/

2020-01-15 15:26 UTC, Screenfeed requested changes

2020-01-15 15:26 UTC, Screenfeed commented on inc/classes/subscriber/preload/class-partial-preload-subscriber.php
> +				$file_path = str_replace( $data['home_path'], '', $file_path );
Good luck when `$data['home_path']` is equal to `/`, or when it is equal to `/foo` and `$file_path` is equal to `/foo/foobar/file.html` :s 
I think `preg_replace()` + `preg_quote()` will save us. Something like this (to test):
```php
$data['home_path'] = trailingslashit( wp_normalize_path( $data['home_path'] ) );
$file_path         = wp_normalize_path( $file_path );
$file_path         = preg_replace( '@^' . preg_quote( $data['home_path'], '@' ) . '@', '', $file_path );
$this->urls[]      = $data['home_url'] . $file_path;
```

2020-05-13 21:26 UTC, Screenfeed approved these changes

2020-05-13 22:11 UTC, hellofromtonya requested changes
Blocking the merge of this PR. Why? We need to figure out how to handle both files and directories for both Linux and IIS.

2023-10-19 13:32 UTC, closed without merging