Use filter_var instead of filter_input to validate REMOTE_ADDR
wp-media/wp-rocket pull request #2420
Opened 2020-03-12 22:40 UTC by Tabrisrp

Customer website was in a redirect loop after update to 3.5.

After digging, I found out that `filter_input` was returning a `NULL` value instead of the IP when we check for it in the Cloudflare flexible SSL code.

There seems to be a bug with `filter_input` and FastCGI, so that would impact some setups: https://www.php.net/manual/en/function.filter-input.php#115960

Using `filter_var` with the global SERVER variable directly solves the issue. Confirmed on the customer website.

2020-03-12 22:46 UTC, Screenfeed requested changes

2020-03-12 22:46 UTC, Screenfeed commented on inc/common/cloudflare-flexible-ssl.php
>  	if ( ! isset( $original_ip ) ) {
`filter_var()` doesn't return `null`, but `false`.
```suggestion
	if ( empty( $original_ip ) ) {
```

2020-03-12 22:48 UTC, Screenfeed approved these changes

2020-03-12 23:00 UTC, crystinutzaa approved these changes

2020-03-12 23:45 UTC, hellofromtonya commented
@Tabrisrp We use `filter_input()` throughout the plugin. Is this the only place where it impacted the issue?

2020-03-13 00:10 UTC, hellofromtonya approved these changes

2020-03-13 00:10 UTC, hellofromtonya commented
This is ready for QA. @arunbasillal @piotrbak @vmanthos

2020-03-13 14:33 UTC, hellofromtonya commented
This PR is a bandaid. We are switching from a PHP specific filtering handler to one for vars. Why? There's something in the customer's stack or .ini configuration that is interfering. A bandaid of switching to `filter_var` provides the customer relief for whatever is wrong in his stack.

My assessment here is this:

- This is a bandaid.
- `filter_input()` is more secure and built for this instance.
- Rocket is not influencing or contributing to the problem. It's not the root cause.
- Safe and secure enough:
     - This code is not saving to the database, writing to a file, or rendering to the browser. Therefore, the implementation in this PR is safe and secure enough for the intent of how this works.
- I'll keep working with the PHP core team to find out why and what the right approach.

2020-03-13 16:31 UTC, hellofromtonya requested changes
This PR is blocked from merging until:

1. We can reproduce the problem.
2. We have confidence that Rocket’s code is the root cause of the problem.
3. We have confidence that this PR won’t negatively impact any other customers.

2020-05-24 11:58 UTC, closed without merging