[WIP] Closes #2448 - Use specific CPCSS on frontend Part 6
wp-media/wp-rocket pull request #2541
Opened 2020-04-15 10:14 UTC by crystinutzaa

Sub-Card for epic #2377.

This card is for tasks related to the frontend.

### Tasks
#### inc/classes/optimization/CSS/class-critical-css.php
- [ ] Update method `get_current_page_critical_css` to use the specific CPCSS for the page if it exists
- [ ] Write unit tests
- [ ] Write integration tests

2020-04-16 20:16 UTC, remyperona requested changes

2020-04-16 20:16 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +		if ( ( rocket_has_constant( 'DONOTROCKETOPTIMIZE' ) && rocket_get_constant( 'DONOTROCKETOPTIMIZE' ) ) || ( rocket_has_constant( 'DONOTASYNCCSS' ) && rocket_get_constant( 'DONOTASYNCCSS' ) ) ) {
```suggestion
		if ( rocket_get_constant( 'DONOTROCKETOPTIMIZE' ) || rocket_get_constant( 'DONOTASYNCCSS' ) ) {
```

2020-04-16 20:16 UTC, Tabrisrp commented on tests/Integration/inc/Engine/CriticalPath/CriticalCSS/getCurrentPageCriticalCss.php
> +namespace WP_Rocket\Tests\Integration\inc\Engine\CriticalPath\CriticalCSS;
```suggestion
namespace WP_Rocket\Tests\Integration\inc\Engine\CriticalPath\CriticalCSSSubscriber;
```

2020-04-16 20:16 UTC, Tabrisrp commented on tests/Integration/inc/Engine/CriticalPath/CriticalCSS/getCurrentPageCriticalCss.php
> + * @covers \WP_Rocket\Engine\CriticalPath\CriticalCSS::get_current_page_critical_css
```suggestion
 * @covers \WP_Rocket\Engine\CriticalPath\CriticalCSSSubscriber::insert_critical_css_buffer
```

2020-04-16 20:16 UTC, Tabrisrp commented on tests/Integration/inc/Engine/CriticalPath/CriticalCSS/getCurrentPageCriticalCss.php
> +class Test_GetCurrentPageCriticalCSS extends FilesystemTestCase {
```suggestion
class Test_InsertCriticalCssBuffer extends FilesystemTestCase {
```

2020-04-21 21:17 UTC, hellofromtonya approved these changes

2020-04-22 12:47 UTC, Screenfeed approved these changes

2020-04-22 13:19 UTC, Tabrisrp commented
@wp-media/dev-qa ready for QA

2020-04-22 13:20 UTC, remyperona approved these changes

2020-04-23 14:35 UTC, arunbasillal commented
- Added `wp-content\cache\critical-css\1\posts\post-1.css`
- The post with the ID `1` used this CPCSS
- Every other post used the default CPCSS

Looking good 👍 

I tried to repeat it for `page` but couldn't make it work. 

@Tabrisrp Is this update only for `posts`? Will there be another one for `pages`? Wondering if I missed something.

2020-04-23 14:39 UTC, Tabrisrp commented
@arunbasillal `posts` is the generic folder for any "post type", i.e. it can be a post, a page, any other CPT. The type identified by the filename, using `post_type-id.css`

2020-04-23 14:56 UTC, arunbasillal approved these changes
Thanks @Tabrisrp 

Following this - https://github.com/wp-media/wp-rocket/pull/2541#issuecomment-618431191

- Tested by adding `\wp-content\cache\critical-css\1\posts\page-2.css`
- Page with ID 2 has specific CPCSS
- Other pages had the common CPCSS

All good 👍

2020-04-23 15:18 UTC, merged