Fixes #2491 Correctly delete all files for a date archives
wp-media/wp-rocket pull request #2736
Opened 2020-06-08 20:59 UTC by Tabrisrp

Fixes #2491 

- [x] Deprecate `get_rocket_post_dates_urls()`
- [x] Remove dates archives from default purge urls list in `rocket_get_purge_urls()`
- [x] Add `WP_Rocket\Engine\Cache\Purge` class
- [x] Add callback method to purge the dates archives in `PurgeActionsSubscriber`
- [ ] Add tests

2020-06-09 20:06 UTC, Tabrisrp commented
I'm thinking we will want to refactor part of the code happening in `purge_dates_archives()`, as it's very close to what Ahmed wrote in this PR for `rocket_clean_home()` https://github.com/wp-media/wp-rocket/pull/2688

Possibly have a function to deal with files + pagination entries deletion only.

2020-06-11 18:01 UTC, hellofromtonya requested changes
The `Purge::purge_dates_archive()` has too many different tasks in it. Break it up into separate, specific increments of behavior via private methods.

2020-06-11 18:42 UTC, Tabrisrp commented on inc/Engine/Cache/Purge.php
> +			}
Done in https://github.com/wp-media/wp-rocket/pull/2736/commits/e6325eee259298f3e7329236f197c7d58cbaae04

2020-06-11 18:42 UTC, Tabrisrp commented on inc/Engine/Cache/Purge.php
> +				}
Done in https://github.com/wp-media/wp-rocket/pull/2736/commits/e6325eee259298f3e7329236f197c7d58cbaae04

2020-06-11 18:42 UTC, Tabrisrp commented on inc/Engine/Cache/Purge.php
> +				foreach ( $iterator as $item ) {
Done in https://github.com/wp-media/wp-rocket/pull/2736/commits/e6325eee259298f3e7329236f197c7d58cbaae04

2020-06-11 18:53 UTC, hellofromtonya approved these changes

2020-06-11 19:11 UTC, Tabrisrp commented
@wp-media/dev-qa Ready for QA.

With this change, when a post is updated, the cache files & hidden files for dates archives should be correctly deleted, whatever format they use (index.html, index-mobile.html_gzip, index-https-webp.html, etc). Hidden files are `.mobile-active` and `.no-webp`

2020-06-11 19:15 UTC, crystinutzaa approved these changes

2020-06-16 17:48 UTC, arunbasillal approved these changes
- Recreated the issue with current master branch. Left over files
![image](https://user-images.githubusercontent.com/5751474/84806007-b75e2b00-b022-11ea-9f0d-7ff2586dd590.png)
- Repeated the same in fix branch. Everything was cleared 👍 
- Cleared WP Rocket cache, everything was cleared 👍 
- Executed `rocket_clean_post` and it worked as before 👍 
- Nothing logged in `debug.log` 👍 

@Tabrisrp Do you think I missed anything? Should I test any more scenarios?

2020-06-16 18:17 UTC, Tabrisrp commented
The method is hooked on `rocket_clean_post`, so you pretty much did what was needed 👍

2020-06-16 18:18 UTC, merged