replace <?php file starter with our WP_CACHE constant using regular e…
wp-media/wp-rocket pull request #2740
Opened 2020-06-09 11:37 UTC by engahmeds3ed

Closes #2537 
Here I will add after the php starter keyword `<?php` our constant `WP_CACHE` not to replace the full line with the constant.
That will solve the following issues:-
1. If there is a comment starter or a single line comment on the first line beside `<?php`, it won't be removed.
2. The default case is that `<?php` will be alone in the first line.

2020-06-11 20:45 UTC, remyperona approved these changes

2020-06-11 20:54 UTC, hellofromtonya requested changes

2020-06-11 20:54 UTC, hellofromtonya commented on tests/Integration/inc/functions/setRocketWpCacheDefine.php
> +	}
Formatting

```suggestion
	public function tearDown() {
		remove_filter( 'rocket_wp_config_name', [ $this, 'setWpCacheFilePath' ] );
		parent::tearDown();
	}
```

2020-06-11 20:54 UTC, hellofromtonya commented on tests/Integration/inc/functions/setRocketWpCacheDefine.php
> +		add_filter( 'rocket_wp_config_name', [$this, 'setWpCacheFilePath'] );
Formatting

```suggestion
		add_filter( 'rocket_wp_config_name', [ $this, 'setWpCacheFilePath' ] );
```

2020-06-11 21:12 UTC, hellofromtonya approved these changes

2020-06-11 21:12 UTC, hellofromtonya commented
@wp-media/dev-qa This PR is ready for QA.

2020-06-12 17:45 UTC, crystinutzaa approved these changes

2020-06-16 17:05 UTC, arunbasillal requested changes
- Recreated the issue using `master` branch
![image](https://user-images.githubusercontent.com/5751474/84804643-b1ffe100-b020-11ea-8a03-b0b3164f339c.png)

- Retested this in fix branch. Issue is fixed for the specific case
![image](https://user-images.githubusercontent.com/5751474/84805005-33577380-b021-11ea-9451-f4bc4d66ec9a.png)

However, the value doesn't change on WP Rocket deactivation. 

I tested this with the normal state of `wp-config.php` and the same issue. WP Rocket adds `define('WP_CACHE', true); // Added by WP Rocket` but does not set it to false. 

Video: https://youtu.be/3mlRA4naQuI

2020-06-17 10:12 UTC, engahmeds3ed commented
Thanks @arunbasillal , checking now

2020-06-17 11:25 UTC, engahmeds3ed commented
@hellofromtonya @Tabrisrp @crystinutzaa @arunbasillal I adjusted the code to check if the constant is already found and the value to be changed, so I will leave it and if value changed, such as on deactivation, I will replace this line with the new line with the new value

2020-06-17 13:57 UTC, remyperona approved these changes

2020-06-17 18:25 UTC, arunbasillal approved these changes
- Retested this. Added correctly on activation 
![image](https://user-images.githubusercontent.com/5751474/84934454-f9f03800-b0f4-11ea-9354-93b8fd65f9d7.png)

- Updated correctly on deactivation
![image](https://user-images.githubusercontent.com/5751474/84934511-0aa0ae00-b0f5-11ea-82fa-65ecabb3aae6.png)

- Updated correctly on re-activation. 
- When `define('WP_CACHE', true);` was missing and WP Rocket was active, this was added back on refresh of admin. 

**Note:** A trivial thing I noticed is that if the `wp-config.php` is as normal, then there is an extra space added. 
![image](https://user-images.githubusercontent.com/5751474/84934793-71be6280-b0f5-11ea-96e2-69d421f78a4b.png)

This is not the case with current master branch. No extra space is added 
![image](https://user-images.githubusercontent.com/5751474/84934901-97e40280-b0f5-11ea-93f9-b2a48961bc70.png)

Don't think this will cause issues. I tried deactivating and reactivating WP Rocket many times, but new lines were not added on each activation and deactivation 👍 

I will leave it upto the Dev team to see if this should be changed. Good from my side.

2020-06-17 19:40 UTC, merged