Closes #2738 Include 3rd Party CSS into concatenation - exclude_css sanitization (3/3)
wp-media/wp-rocket pull request #2769
Opened 2020-06-12 19:59 UTC by crystinutzaa

Sub-task for epic #2689 

### `exclude_css` sanitization
Edit the sanitization of exclude_css input field and allow external URL.

Effort S

2020-06-12 20:13 UTC, Tabrisrp commented on inc/functions/formatting.php
> +	return sanitize_text_field( \rocket_remove_url_protocol( strtok( $file, '?' ) ) );
```suggestion
	return sanitize_text_field( rocket_remove_url_protocol( strtok( $file, '?' ) ) );
```

2020-06-12 20:23 UTC, hellofromtonya requested changes
Need unit tests for this new function `rocket_validate_css()`.

2020-06-12 20:23 UTC, hellofromtonya commented on tests/Unit/inc/Engine/Admin/Settings/Settings/sanitizeCallback.php
> +		} );
For this use the `StubTrait:: stubWpParseUrl()` instead.

2020-06-12 20:23 UTC, hellofromtonya commented on inc/functions/formatting.php
> +		return $file;
Let's combine these to be more concise and performant.

```suggestion
		return rocket_clean_exclude_file( trim( $file ) );
```

2020-06-12 20:42 UTC, crystinutzaa commented
@hellofromtonya do we really need Unit test for that new function?
The current Unit test & Integration which I added calls this function and we can consider that is tested.

2020-06-12 21:02 UTC, hellofromtonya commented
@crystinutzaa Yes we do. Why? Unit tests test in isolation. The test for the sanitizer callback should mock this new function and any other functions too.

2020-06-12 21:14 UTC, hellofromtonya requested changes

2020-06-12 21:14 UTC, hellofromtonya commented on tests/Unit/inc/Engine/Admin/Settings/Settings/sanitizeCallback.php
> +		Functions\when( 'rocket_valid_key' )->justReturn( true );
@crystinutzaa You'll want to also mock the new `rocket_validate_css()` function too as it's a dependency to this callback but external to it.

2020-06-16 21:03 UTC, remyperona approved these changes

2020-06-16 21:30 UTC, hellofromtonya approved these changes

2020-06-17 11:57 UTC, crystinutzaa commented
@wp-media/dev-qa ready for testing

2020-06-17 20:24 UTC, arunbasillal approved these changes
- Tried adding `https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css` with master branch to Exclude CSS text area. Result 
![image](https://user-images.githubusercontent.com/5751474/84946405-485a0280-b106-11ea-8091-5cd72d165be5.png)

- Repeated the same with feature branch. Result 
![image](https://user-images.githubusercontent.com/5751474/84946494-73445680-b106-11ea-8bd6-51b0ac348e2b.png)

@crystinutzaa That is the only test needed for this PR right? It is not supposed to do anything in the front end or anywhere else I believe

2020-06-17 20:50 UTC, crystinutzaa commented
@arunbasillal yes, this is the only test needed 👍

2020-06-17 20:51 UTC, merged