Fix #2800 fallback cpcss css files are not loaded async
wp-media/wp-rocket pull request #2802
Opened 2020-06-22 21:48 UTC by crystinutzaa

This was introduced while refactoring the Critical Path code. 
I identified while doing the PR https://github.com/wp-media/wp-rocket/pull/2786 .
This should be included in the next minor release v3.6.1

When using Fallback CPCSS, the CSS files are not loaded asynchronously anymore.

Steps to reproduce

Enter CSS into Fallback CPCSS field (also take appropriate steps to apply it, delete existing cpcss, stop automatic regeneration.
Observe the the CPCSS is correctly inserted into the page, but the CSS files are loaded normally and render-blocking

2020-06-22 21:57 UTC, remyperona requested changes

2020-06-22 21:57 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +		if ( ! $this->critical_css->get_current_page_critical_css() && ! $this->options->get( 'critical_css', '' ) ) {
```suggestion
		if ( empty( $this->critical_css->get_current_page_critical_css() ) && empty( $this->options->get( 'critical_css', '' ) ) ) {
```

2020-06-22 21:59 UTC, remyperona approved these changes

2020-06-22 22:54 UTC, hellofromtonya approved these changes

2020-06-22 22:56 UTC, hellofromtonya commented
@arunbasillal @Davidacu This PR is ready for QA. 
🔥 We'd like to include it with the 3.6.1 release please. 🔥

2020-06-23 16:47 UTC, arunbasillal approved these changes
- Recreated the issue with current master branch on main mega site. Deleted CPCSS for front page and added fallback CPCSS. CSS files were loaded with `rel='stylesheet'`.
- Updated to the fix branch and repeated the test. Fallback CPCSS was used and CSS files were loaded with `rel='preload'` as expected 👍 
- CPCSS was applied correctly on other pages for which WP Rocket generated CPCSS. 👍 
- Nothing was logged in `debug.log`

Looking good 🚀

2020-06-23 16:59 UTC, merged