Fix #2772 Load Google Fonts async
wp-media/wp-rocket pull request #2834
Opened 2020-06-30 19:54 UTC by crystinutzaa

### Scope a solution ✅ 
#### inc/Engine/Optimization/GoogleFonts/Combine.php
- Rename the class to `Optimize`, to have it make more sense about what it is doing now
- Add a class alias in `deprecated/3.6.php` for the old name
- Add a new method `preload()` to add a preload link on the page for the Google Fonts link
- Add a new method `async()` to use the `media="print"` solution for asynchronous, non-blocking fetching of the link
- Add a new method `fallback()` to insert a `noscript` fallback in the footer
- Use the 3 above methods in the `optimize()` method to apply everything needed

We'll also have to make sure we don't double apply those optimization when `Optimize CSS Delivery` is enabled at the same time as `Optimize Google Fonts`.

### Estimate the effort ✅ 
Effort `[M]`

2020-06-30 19:58 UTC, crystinutzaa commented
Blocking this one due to [DOM Module](https://github.com/wp-media/module-dom)
Exactly as in PR https://github.com/wp-media/wp-rocket/pull/2786 , we need DomDocument to be able to handle easily the link attributes.

2020-07-08 11:01 UTC, hellofromtonya commented
The async css part of this PR is already done in PR 2786 as any `<link rel="stylesheet"...>` gets the async css treatment. You can see it here in the [Async CSS test data](https://github.com/wp-media/wp-rocket/blob/master/tests/Fixtures/inc/Engine/CriticalPath/content/twentyseventeen-async_css.html#L37-L38) where the Google fonts `<link>`:

original:

```html
<link rel="stylesheet" id="twentyseventeen-fonts-css" href="https://fonts.googleapis.com/css?family=Libre+Franklin%3A300%2C300i%2C400%2C400i%2C600%2C600i%2C800%2C800i&amp;subset=latin%2Clatin-ext&amp;display=fallback" media="all">
```

after Async CSS runs:

```html
<link rel="preload" href="https://fonts.googleapis.com/css?family=Libre+Franklin%3A300%2C300i%2C400%2C400i%2C600%2C600i%2C800%2C800i&amp;subset=latin%2Clatin-ext&amp;display=fallback" as="style">
<link rel="stylesheet" id="twentyseventeen-fonts-css" href="https://fonts.googleapis.com/css?family=Libre+Franklin%3A300%2C300i%2C400%2C400i%2C600%2C600i%2C800%2C800i&amp;subset=latin%2Clatin-ext&amp;display=fallback" media="print" onload="this.onload=null;this.media='all'">
```

2020-07-08 14:13 UTC, Tabrisrp commented
I believe this PR is to do this when the `Optimize CSS Delivery` option is not enabled, but the `Optimize Google Fonts` is

2020-07-08 14:18 UTC, hellofromtonya commented
>I believe this PR is to do this when the Optimize CSS Delivery option is not enabled, but the Optimize Google Fonts is

Then let's not duplicate code here. Instead, refactor to reuse. How? 

- Pull the `AsyncCSS` class out of `CriticalPath` module. 
- Add a specific implementation for the query and rules into each module.

2020-07-16 12:00 UTC, remyperona requested changes

2020-07-16 12:27 UTC, crystinutzaa commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +			rocket_get_constant( 'DONOTASYNCCSS' )
Which one: `DONOTASYNCCSS` ?

2020-07-16 12:39 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +			rocket_get_constant( 'DONOTASYNCCSS' )
Yes

2020-07-16 12:51 UTC, remyperona approved these changes

2020-07-16 14:18 UTC, GeekPress commented
I noticed that this enhancement relay on « Optimize CSS Delivery » option turned on.

Why don't we directly apply this enhancement? What is the relation with our CPCSS? I suppose that even if we use CPCSS, we will still have a small FOUC on fonts as the CSS doesn't depend to the internal CSS.

2020-07-16 14:24 UTC, GeekPress commented
@arunbasillal What are thoughts about that? 
https://github.com/wp-media/wp-rocket/pull/2834#issuecomment-659443323

2020-07-16 14:46 UTC, hellofromtonya commented
>I noticed that this enhancement relay on « Optimize CSS Delivery » option turned on.
>
>Why don't we directly apply this enhancement? What is the relation with our CPCSS? I suppose that even if we use CPCSS, we will still have a small FOUC on fonts as the CSS doesn't depend to the internal CSS.

@GeekPress Where are you noticing this?

Looking at this PR, each option separately handles how async css is applied.

How? We moved the `AsyncCSS` out of the Critical Path module and are now using for any async css needs. Both the Optimize CSS Delivery and Google Font Optimization use it separately. In other words, Google Font Optimization is not dependent upon OCD and OCD is not dependent upon Google Font Optimization. They are separated.

2020-07-16 14:50 UTC, GeekPress commented
@hellofromtonya Don't this check if the Optimize CSS Delivery is on?
https://github.com/wp-media/wp-rocket/pull/2834/files#diff-5ac8e03c0609dc96a4285b6984b74d66R612

2020-07-16 14:52 UTC, hellofromtonya commented
> Don't this check if the Optimize CSS Delivery is on?

Yes for the Optimize CSS Delivery only, i.e. not Google Fonts Optimization.

2020-07-16 14:58 UTC, GeekPress commented
> Yes for the Optimize CSS Delivery only, i.e. not Google Fonts Optimization.

Ok, thanks for the confirmation 😇

2021-06-21 15:28 UTC, closed without merging