Enhancement/2814 auto compat wp com
wp-media/wp-rocket pull request #2851
Opened 2020-07-07 18:10 UTC by iCaspar

This PR addresses issues #2814 and #2299 

- Adds a filter `rocket_generate_advanced_cache_file` that can be set to `false` in order to short-circuit writing the `advanced-cache.php` file.
- Checks for WPCOMSH_VERSION constant in `rocket_activate()` and `rocket_deactivate()` to handle activation/deactivation issues with `advanced-cache.php` incompatibility on WP.com.
- Adds a WordPressCom 3rd-party Subscriber to handle WP.com-specific settings.

2020-07-07 18:17 UTC, iCaspar commented
@Tabrisrp Note that in the new filter, I've set the default to `true` and the short-circuit to `false` -- it seemed more intuitive to say `true` => `write the file` and `false` => `don't write the file`.

2020-07-07 19:22 UTC, remyperona requested changes

2020-07-07 19:22 UTC, Tabrisrp commented on inc/main.php
> +		add_filter( 'rocket_generate_advanced_cache_file', __return_false() );
```suggestion
		add_filter( 'rocket_generate_advanced_cache_file', '__return_false' );
```

2020-07-07 19:22 UTC, Tabrisrp commented on inc/ThirdParty/Hostings/WordPressCom.php
> +			'rocket_cache_mandatory_cookies'      => 'return_false',
```suggestion
			'rocket_cache_mandatory_cookies'      => 'return_empty_array',
```

2020-07-09 11:52 UTC, iCaspar commented
Adding `Blocked` until we complete the new work on the Activate/Deactivate refactoring going on in PR #2860

2020-07-13 14:06 UTC, GeekPress commented
@iCaspar @Tabrisrp  A message shared by Lucy:

> Just in case..... their support said we should be able to use this: https://developer.wordpress.org/reference/functions/wp_cache_flush/

2020-07-24 14:19 UTC, Tabrisrp commented
One more thing to do in this PR, after [this comment](https://github.com/wp-media/wp-rocket/pull/2860#pullrequestreview-454431642)

For `Pressable`:
- Add the `Activation/DeactivationInterface`, and implement the 2 methods
- As we do for `WPEngine`, prevent writing the `WP_CACHE`constant in wp-config.php: https://github.com/wp-media/wp-rocket/blob/1afc7ebdf3b5166b74c9a7f8f172555a7cbb5aae/inc/ThirdParty/Hostings/WPEngine.php#L70

In `Engine\Cache\WPCache::should_set_wp_cache_constant()`, remove the check for `IS_PRESSABLE`, as it will be directly handled by the `Pressable` class

In `Activation` & `Deactivation` classes, add `Pressable` in the static `$(de)activators` array, and add the class to the service providers too

2020-07-27 15:22 UTC, remyperona approved these changes

2020-07-27 15:42 UTC, Tabrisrp commented
@wp-media/qa Ready for QA, acceptance criteria are in the original post

2020-07-27 22:14 UTC, Davidacu reviewed
The Test execution details can be found [here](https://docs.google.com/spreadsheets/d/1kkoOx8tKpVurH7h9B50-AN9JdHzvbK_WHqXroEz5guU/edit?usp=sharing)


Passed | 7
-- | --
Failed | 1
Blocked | 0
Not Executed | 0
Total | 8

1. The failed case is about not writing to `advanced-cache.php` file when hosted in WP Engine.
it looks like we still write to this file during activation. https://i.imgur.com/dVBICJp.png
2. Another issue I noticed is that is not possible to deactivate the plugin when hosted in wordpress.com
any ideas? https://screencast-o-matic.com/watch/cYit3jEBEV

2020-07-28 14:39 UTC, Tabrisrp commented
@Davidacu The issue with `advanced-cache.php` should be fixed with my latest commit

For the deactivation issue on wp.com, I looked into it, and it's expected because of the necessity to rename the plugin folder name to bypass the ban. Once the ban is lifted, the deactivation will work correctly.

2020-07-29 02:21 UTC, Davidacu requested changes
Looks like I found new issues after this change:

**Pressable**:
1. Notice about writing permissions for `wp-config.php` when trying to deactivate the plugin https://i.imgur.com/47IakuT.png
2. a PHP notice in the debug.log `Undefined property: batcache::$status_header in /wordpress/drop-ins/advanced-cache.php on line 211`

All other cases reported before passed.

2020-07-29 13:56 UTC, Davidacu approved these changes
>Notice about writing permissions for wp-config.php when trying to deactivate the plugin https://i.imgur.com/47IakuT.png

Please disregard the above issue, sorry I was using the wrong build 🤦‍♂️, this is not reproducible in feature branch .

>a PHP notice in the debug.log Undefined property: batcache::$status_header in /wordpress/drop-ins/advanced-cache.php on line 211

And this issue above I discussed with @Tabrisrp is not related to us.
Approving this PR.

2020-07-29 13:59 UTC, merged