[WIP] Feature/2576 add query string bypass
wp-media/wp-rocket pull request #2910
Opened 2020-07-21 14:31 UTC by iCaspar

Adds the query string bypass feature: #2576 

Add a new function to the API: `rocket_bypass()` checking for query string `?nowprocket` in current url.

Add conditional bail-outs to processes to be short-circuited by the query string.

    Conversion of dynamic CSS/JS files to static files
    Disable Emoji
    Disable WordPress embeds
    Heartbeat settings
    Preload fonts

2020-07-21 14:37 UTC, iCaspar commented
3 erring unit tests as of here need to be updated to stub the new function.

2020-07-30 18:18 UTC, remyperona requested changes

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Heartbeat/ServiceProvider.php
> +			->withArgument( $options );
```suggestion
		$this->getContainer()->share( 'heartbeat_subscriber', 'WP_Rocket\Engine\Heartbeat\HeartbeatSubscriber' )
			->withArgument( $this->getContainer()->get( 'options' ) );
```

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Embeds/EmbedsSubscriber.php
> +use function rocket_bypass;
Is the import required?

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Embeds/EmbedsSubscriber.php
> +	 * @access public
```suggestion
```

We don't need the access in the docblock, it's already indicated by the `public` keyword in the method declaration

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Embeds/EmbedsSubscriber.php
> +		if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
```suggestion
		if ( rocket_get_constant( 'REST_REQUEST' ) ) {
```

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Embeds/EmbedsSubscriber.php
> +			WP_ROCKET_ASSETS_JS_URL . 'editor/editor.js',
```suggestion
			rocket_get_constant( 'WP_ROCKET_ASSETS_JS_URL' ) . 'editor/editor.js',
```

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Embeds/EmbedsSubscriber.php
> +			WP_ROCKET_VERSION,
```suggestion
			rocket_get_constant( 'WP_ROCKET_VERSION' ),
```

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Embeds/EmbedsSubscriber.php
> +		return true;
We can simplify this as a one liner

```suggestion
		return ( ! rocket_bypass() || (bool) $this->options->get( 'embeds', 0 ) );
```

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Emojis/EmojisSubscriber.php
> +	 * @access public
```suggestion
```

2020-07-30 18:18 UTC, Tabrisrp commented on inc/Engine/Media/Emojis/EmojisSubscriber.php
> +		return true;
```suggestion
		return ( ! rocket_bypass() || (bool) $this->options->get( 'emoji', 0 ) );
```

2020-08-03 19:10 UTC, remyperona approved these changes

2020-08-03 19:15 UTC, Tabrisrp commented
@wp-media/qa This PR is ready for QA, acceptance criteria in the OP

2020-08-05 23:11 UTC, Davidacu approved these changes
86% pass rate. 10 Passed, 1 blocked , 1 failed.
Please find the details of the test execution report attached
[testrail-report-13.pdf](https://github.com/wp-media/wp-rocket/files/5031656/testrail-report-13.pdf)

The failure is due to a known [issue ](https://github.com/wp-media/wp-rocket/issues/2293)with heartbeat, but this is out of the scope of this PR.
The blocked case is because we currently don't have a script or plugin that can trigger the heartbeat calls from the frontend, and the issue mentioned above.
Everything else is looking good 👍

2020-08-06 11:59 UTC, merged