Preserve WP_CACHE & advanced-cache.php if on multisite with WPR active on other sites
wp-media/wp-rocket pull request #2951
Opened 2020-07-27 19:33 UTC by Tabrisrp

When on a multisite configuration, all sites share the same `wp-config.php` & `advanced-cache.php` files.

When deactivating WP Rocket on a sub-site, the `WP_CACHE` value & the `advanced-cache.php` content should be preserved, except if this site was the last one with WP Rocket active. We check this on deactivation by looking at the number of config files found in `wp-content/wp-rocket-config`.

When adding the new deactivation process, this behaviour was not preserved (oversight on my part). This PR is fixing that, reverting it to the intended, while still using the new process.

As comparison, here is how the code looked on version 3.6.2.1: https://github.com/wp-media/wp-rocket/blob/b1fdd13fbe78c8fc54f26a586061fd79b9a1966b/inc/main.php#L154

2020-07-27 19:47 UTC, iCaspar approved these changes

2020-07-27 20:49 UTC, Tabrisrp commented
@wp-media/qa Ready for QA, acceptance criteria in the opening comment

2020-07-28 01:05 UTC, Davidacu reviewed
There seems to be something wrong with multisite installations, for what I have noticed, the behavior in `3.6.2.1` is the expected behavior described in this issue, and the behavior in `fix/multisite-deactivation` seems to be the exact problem described in this ticket.

**Testing Environment**: local

**branch**: `3.6.2.1`

Could not reproduce the issue with deactivation
- when deactivating the plugin on a subsite and other subsites have the plugin activated,
  nothing is written to wp-config.php nor advanced-cache.php
- when activating the plugin on a subsite, the files that seem to be modified are advanced-cache.php and .htaccess

**branch**: `fix/multisite-deactivation`

The issue with deactivation is reproduced.
- when deactivating the plugin on a subsite, and other subsites have the plugin activated,
  the WP_CACHE=false is written to wp-config.php.
  then if you go to plugins section of a subsite that has the plugin activated the value of WP_CACHE=true is written to wp-config.php
  https://screencast-o-matic.com/watch/cYiuckEgit
- when activating the plugin on a subsite, `wp-config.php` , `advanced-cache.php` and `.htaccess` are modified.

2020-07-28 12:14 UTC, Tabrisrp commented
@iCaspar requesting a new code review, because I realized I didn't modify the correct methods, and the code was not working.

2020-07-28 12:39 UTC, iCaspar requested changes

2020-07-28 12:39 UTC, iCaspar commented on inc/Engine/Cache/WPCache.php
> +	 * @return bool
We are actually returning void here.

2020-07-28 14:40 UTC, Tabrisrp commented
@Davidacu This is ready for QA again, sorry about the first one

2020-07-29 01:27 UTC, Davidacu reviewed
Find the test results attached.  
[testrail-report-multisite-activation-deactivation.pdf](https://github.com/wp-media/wp-rocket/files/4991954/testrail-report-multisite-activation-deactivation.pdf)
3/4 cases **Passed**
1/4 cases **Failed**
There is one failed case, which actually I want to confirm if it should be a failure or not.
The failed case is T14, I would expect that if activating the plugin on Site 1, when I activate the plugin on Site 2 it should not write to `.htacess` or `advanced-cache.php` but it does, if this is not really an issue then everything is looking good!

![image](https://user-images.githubusercontent.com/4731836/88745601-b7fcdd80-d107-11ea-808d-4fe3db2bb799.png)

2020-07-29 12:02 UTC, Tabrisrp commented
@Davidacu That is expected, it's the same behaviour on the current production version. It's not ideal, but it's also out of scope of this PR, so it's ok

2020-07-29 13:26 UTC, merged