Fixes #2846 Correctly exclude jQuery from combine when WP is in a subfolder
wp-media/wp-rocket pull request #3059
Opened 2020-09-01 20:32 UTC by Tabrisrp

Fixes #2846 

### Code changes
Instead of directly using the value from the `src` property for jQuery, we check if the `host` is set for it. If not, we call `site_url()` to make sure we get the absolute URL for the file, and then keep only the path.

This is reverting to how we did it previously.

2020-09-11 18:15 UTC, iCaspar approved these changes

2020-09-11 18:15 UTC, iCaspar commented
@wp-media/qa Ready for QA

2020-09-11 21:19 UTC, Davidacu requested changes
- The jQuery library loaded from `/wp-includes/js/jquery/` is not combined as expected in https://rocketlabsqa.dev/ 👍 
- The jQuery library loaded from `/wp-includes/js/jquery/` is still combined when wp is installed in a  subdirectory 🐞 http://mega.wp-rocket.me/qa/
- The jQuery library hosted in external sources such as cloudfare and ajax.googleapis is combined in both type of wp installs 🐞  (these are supposed to be excluded from combine js right?)
Can be tested here:
https://rocketlabsqa.dev/combine-js/
http://mega.wp-rocket.me/qa/combine-js

Find the test results attached
[testrail-report-30.pdf](https://github.com/wp-media/wp-rocket/files/5211555/testrail-report-30.pdf)

2020-09-15 18:41 UTC, Tabrisrp commented
@iCaspar Can you re-review my latest changes?
@Davidacu Thank you for the reports, found the issues, ready for another QA

2020-09-15 19:00 UTC, iCaspar approved these changes

2020-09-16 14:22 UTC, piotrbak approved these changes
- The jQuery library loaded from `/wp-includes/js/jquery/` is not combined as expected in https://rocketlabsqa.dev/
- The jQuery library loaded from `/wp-includes/js/jquery/` is not combined as expected in subdirectory http://mega.wp-rocket.me/qa/
- The jQuery library hosted by external sources such as Cloudflare and ajax.googleapis is not combined in both cases. Tested with deregistering the original jQuery code and registering the new one:
https://snippi.com/s/in79atv with https:// protocol and relative one //.
- If the jQuery is not registered, just added into the source using the `/wp-includes/js/jquery/` path it is not being combined too.

2020-09-16 14:45 UTC, merged