Auto exclude preload delay js scripts
wp-media/wp-rocket pull request #3095
Opened 2020-09-14 16:29 UTC by GeekPress

This PR will automatically exclude our Preload and Delay JS inline scripts. It will ensure us that these features will always work. By being included into the combined JS files, our features can stop to work if a JS error is triggered.

Slack conversation: https://wp-media.slack.com/archives/GUT7FLHF1/p1599831075030100

2020-09-14 16:58 UTC, hellofromtonya requested changes

2020-09-14 16:58 UTC, hellofromtonya commented on inc/Engine/Optimization/Minify/JS/Combine.php
> +			'RocketPreloadLinks',
The `RocketLazyLoadScripts` and `RocketPreloadLinks` variable names are not present in the minified scripts as we use a mangler in the gulp task to further reduce the bytes in each of the scripts.

However, we do retain the `RocketBrowserCompatibilityChecker` name. All 3 of these scripts have that variable name in them. Therefore, we can simplify this to just `RocketBrowserCompatibilityChecker`.

2020-09-15 12:32 UTC, hellofromtonya approved these changes

2020-09-15 12:41 UTC, hellofromtonya commented
@wp-media/qa This PR is ready for QA.

How to test?

1. Turn on the Delay JS and Preload Links features.
2. Turn on the Combine JS feature.
3. Check that these 3 inline scripts are not combined but are actually in the HTML as separate `<script>` elements:
   
```
<script id="rocket-browser-checker-js-after">...the script code....</script>
<script id="rocket-delay-js-js-after">...the script code....</script>
<script id="rocket-preload-links-js-extra">...the script code....</script>
<script id="rocket-preload-links-js-after">...the script code....</script>
```

2020-09-15 14:49 UTC, piotrbak approved these changes
It worked as expected. Scripts mentioned by @hellofromtonya are not combined. The following script wasn't combined in the previous version too:
`<script id='rocket-preload-links-js-extra'>`

It's good to add that this specific one is added above the combined JS file.

2020-09-15 15:31 UTC, merged