Add pixel-caffiene/frontend.js to auto-delay list
wp-media/wp-rocket pull request #3098
Opened 2020-09-14 17:31 UTC by iCaspar

Closes #3088.

2020-09-21 16:52 UTC, Tabrisrp requested changes
In addition, you need to add a new method to hook on the upgrade routine, to add this new script to the saved user list in the settings

2020-09-22 18:37 UTC, iCaspar commented
Modified the current set_options_on_update() to check for the new script and add if it's not already there. Ready for another look @Tabrisrp .

2020-09-22 19:54 UTC, Tabrisrp approved these changes

2020-09-23 13:01 UTC, iCaspar commented
@wp-media/qa This one is ready for your magic!

2020-09-23 20:40 UTC, Tabrisrp approved these changes

2020-09-23 20:41 UTC, Tabrisrp commented
@wp-media/qa Ready for QA

- The pixel-caffeine script should be delayed too
- The script path should be added automatically to the default list
- The script path should be added to the saved value in the option if the `fbq` pattern is also present, but not if it's not

2020-09-24 12:08 UTC, iCaspar commented
@Tabrisrp Just a last quick check on the integration tests I added there. QA can continue during review.

2020-09-24 13:04 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Optimization/DelayJS/Admin/Subscriber/optionUpdate372.php
> +		global $wp_filter;
```suggestion
```

2020-09-24 13:04 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Optimization/DelayJS/Admin/Subscriber/optionUpdate372.php
> +class Test_optionUpdate372 extends TestCase{
```suggestion
class Test_optionUpdate372 extends TestCase {
```

2020-09-24 13:05 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Optimization/DelayJS/Admin/Settings/optionUpdate372.php
> +class Test_OptionUpdate372 extends TestCase{
```suggestion
class Test_OptionUpdate372 extends TestCase {
```

2020-09-24 13:06 UTC, Tabrisrp approved these changes
just minor formatting

2020-09-24 15:13 UTC, piotrbak approved these changes
Worked as expected, tested scenarios:
- Should add the new string to the default list during the clean installation
- Should add the new string to the default list after the update when the list was default one
- Should not add the new string to the default list after the update when the string was already added there
- Should not add pixel caffeine script if fbq( script is not present on the list
- Should validate Delay JS is compatible with pixel caffeine

2020-09-24 15:14 UTC, merged

2020-10-09 10:09 UTC, antoscarface commented
Hi, I'm the Pixel Caffeine developer :) Just a heads up: first of all thank you for adding this into WP Rocket. Secondly, I've already fixed my self this into the latest version of Pixel Caffeine (before to notice this PR, I'm seeing it only now!) by splitting the main `<script>`, which include global variables definition and the Facebook Pixel snippet initialization, loading them separately, so WP Rocket will delay the snippet init, but not the global variable's definition, in order to prevent the `aepc_something not found` error.

Anyway, that's great you added directly the frontend.js file, it makes sense as well.
Thank you :)