Remove google/recaptcha from DelayJS on Update to 3.7.2
wp-media/wp-rocket pull request #3141
Opened 2020-09-24 13:27 UTC by iCaspar

Closes #3075 

Removes `google.com/recaptcha/api.js` from the default list of scripts to delay with DelayJS.
Adds a check for `google.com/recaptcha/api.js` present in settings for delayJS, and removes if present on update.
Revises DelayJS default and update tests.

2020-09-24 13:30 UTC, iCaspar commented
@wp-media/qa Acceptance criteria:

1. When installing new or upgrading from a version < 3.7, `google.com/recaptcha/api.js` script should not be present in default list of scripts to delay.
2. When upgrading from varsion 3.7+ , if `google.com/recaptcha/api.js` was present in list of scripts to delay, it should be removed after upgrading.

2020-09-24 18:08 UTC, Tabrisrp approved these changes

2020-09-24 19:49 UTC, piotrbak requested changes
1. When installing new or upgrading from a version < 3.7, google.com/recaptcha/api.js script should not be present in the default list of scripts to delay. 👍
2. When upgrading from version 3.7+, if google.com/recaptcha/api.js was present in the list of scripts to delay, it should be removed after upgrading. 🛑
`It's not automatically removed, only after restoring the defaults`
3. DelayJS should not cause errors when using ReCaptcha with the CF7 plugin. 👍

2020-09-25 13:52 UTC, piotrbak approved these changes
2. When upgrading from version 3.7+, if google.com/recaptcha/api.js was present in the list of scripts to delay, it should be removed after upgrading. 👍

Thanks @iCaspar for your help with the upgrade process. The above was tested when the list was default, custom and if everything is okay when it's empty.

2020-09-25 14:52 UTC, merged