Fix #3209 avada lazyload is detected as always active
wp-media/wp-rocket pull request #3217
Opened 2020-10-16 15:57 UTC by alfonso100

Proposing a fix for [#3209](https://github.com/wp-media/wp-rocket/issues/3209)
(thank you @engahmeds3ed for the help!)

starting from Avada 7.2 version the `lazy_load` value is never empty, it’d be one of:
- none
- wordpress
- avada

Added verifications for the "none" value to deactivate and disable our LazyLoad option, while keeping the "empty" value verification for backward compatibility

2020-10-20 13:21 UTC, Tabrisrp commented
I'm not sure this is the best approach. When selecting `none` in Avada, it means "neither the WordPress lazyload, nor the Avada one", but it doesn't extend to WP Rocket itself.

How about deactivating WP Rocket lazyload only when the `Avada` value is selected?

This is the one value that _can_ conflict with our own lazyload, the other won't cause any issue.

2020-10-26 19:05 UTC, Tabrisrp requested changes

2020-10-26 19:05 UTC, Tabrisrp commented on inc/3rd-party/themes/avada.php
> +	return true;
```
if  ( ( 'Avada' !== $current_theme->get( 'Name' ) ) {
    return false;
}

if ( empty( $avada_options['lazy_load'] ) ) {
        return false;
}

if (  ! empty( $avada_options['lazy_load'] && 'avada' !== $avada_options['lazy_load']  ) ) {
	return false;
}

return true;
```

2020-10-26 19:05 UTC, Tabrisrp commented on inc/3rd-party/themes/avada.php
> +add_action( 'fusion_cache_reset_after', 'rocket_avada_clear_cache_fusion_patcher' );
```suggestion
add_action( 'fusion_cache_reset_after', 'rocket_avada_clear_cache_fusion_patcher' );

```

2020-10-28 19:38 UTC, Tabrisrp approved these changes

2020-10-28 20:04 UTC, alfonso100 commented
Tested this on MEGA/Avada, confirmed to be working as expected with Avada 7.2

2020-10-28 20:07 UTC, merged