Closes #2773 Remove beta tester option from the plugin
wp-media/wp-rocket pull request #3290
Opened 2020-11-10 19:32 UTC by Tabrisrp

Closes #2773 

Remove all code related to our beta tester option in the plugin

2020-11-12 13:21 UTC, iCaspar requested changes

2020-11-12 13:21 UTC, iCaspar commented on inc/classes/subscriber/Plugin/class-updater-api-common-subscriber.php
> +		return sprintf( 'WP-Rocket|%s%s|%s|%s|%s|%s;', $this->plugin_version, '', $consumer_key, $consumer_email, esc_url( $this->site_url ), $php_version );
Is there any reason we can't remove that `$bonus` from the sprint string altogether?
`return sprintf( 'WP-Rocket|%s|%s|%s|%s|%s;', $this->plugin_version, $consumer_key, $consumer_email, esc_url( $this->site_url ), $php_version );`

2020-11-12 13:43 UTC, iCaspar approved these changes

2020-11-13 20:33 UTC, piotrbak approved these changes
Worked as expected, no problems there:
[testrail-report-69.pdf](https://github.com/wp-media/wp-rocket/files/5539184/testrail-report-69.pdf)

2020-11-16 13:57 UTC, merged