Fix for #3232 - Sanitization on exclude from combination fields preve…
wp-media/wp-rocket pull request #3295
Opened 2020-11-11 15:59 UTC by alfonso100

Proposing fix for https://github.com/wp-media/wp-rocket/issues/3232 per @Tabrisrp [suggestion here](https://github.com/wp-media/wp-rocket/issues/3232#issuecomment-723099183)

Sanitization on exclude from combination fields prevents from excluding certain scripts.

Applied changes: 
- returning `true` if the file is internal at [rocket_is_internal_file](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L135). Props to @vmanthos on this one.

- replacing `sanitize_text_field()` by `esc_url_raw()` at  [rocket_validate_css()](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L113-L118) and [rocket_validate_js()](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L102)

2020-11-11 22:05 UTC, Tabrisrp commented on inc/functions/formatting.php
> +		return esc_url_raw( rocket_clean_exclude_file( trim( $file ) ) );
You should keep `rocket_sanitize_css` here

2020-11-11 22:06 UTC, Tabrisrp requested changes
One change to fix

2020-11-12 13:32 UTC, alfonso100 commented
Ooops! reverted this change. thank you Remy!

2020-11-12 13:49 UTC, Tabrisrp approved these changes

2020-11-12 13:55 UTC, Tabrisrp commented
@wp-media/qa Ready for QA

2020-11-12 16:49 UTC, piotrbak approved these changes
Worked as expected.
[testrail-report-67.pdf](https://github.com/wp-media/wp-rocket/files/5531990/testrail-report-67.pdf)

2020-11-12 16:57 UTC, merged

2020-12-04 12:57 UTC, piotrbak commented
@Tabrisrp @arunbasillal @alfonso100 I checked all possible combinations, it looks like adding the external alone, without .css or .js extension is not possible with that update:

3.7.5:
- example.com/(.*).js 👍
- example.com 👍

3.7.6:
- example.com/(.*).js 👍
- example.com 👎