[WIP] Closes #3267 Remove Cache Lifespan “Minutes” Frequency
wp-media/wp-rocket pull request #3298
Opened 2020-11-13 03:57 UTC by engahmeds3ed

Closes #3267 

### Code changes

- Move `inc/classes/Cache/class-expired-cache-purge.php` and `inc/classes/subscriber/Cache/class-expired-cache-purge-subscriber.php` to the new architecture. Group them in `inc/Engine/Cache/PurgeExpired/`, rename the files & classes
- Add class alias for the moved classes above, in the `deprecated/3.8.php` file

#### `WP_Rocket\Engine\Cache\PurgeExpired\PurgeExpiredCache`
- Add a method `update_lifespan_value()` to update the lifespan value if it was using the minutes value before
- Add tests

#### `WP_Rocket\Engine\Cache\PurgeExpired\Subscriber`
- Remove `clean_expired_cache_scheduled_event()` method and the associated event
- Add a callback on `wp_rocket_upgrader`, calling `PurgeExpiredCache::update_lifespan_value()`
- Add tests

#### `WP_Rocket\Engine\Admin\Settings\Page`
- Update the `purge_cron_interval` index, to remove the `MINUTE_IN_SECONDS` choice

#### `WP_Rocket\Engine\Admin\Settings\Settings`
- Update `sanitize_callback()`, to remove the `MINUTE_IN_SECONDS` choice in`$allowed_cron_units`
- Remove the conditional checking for a value < 10 minutes

2020-11-13 14:50 UTC, Tabrisrp requested changes

2020-11-13 14:50 UTC, Tabrisrp commented on inc/Engine/Cache/PurgeExpired/PurgeExpiredCache.php
>  	 * @access private
You can remove all the `@access` in this class too

2020-11-13 14:50 UTC, Tabrisrp commented on inc/Engine/Cache/PurgeExpired/Subscriber.php
>  	 * @access private
Same here, remove all `@access`

2020-11-13 14:50 UTC, Tabrisrp commented on inc/Engine/Cache/PurgeExpired/PurgeExpiredCache.php
> +	 * @param int $old_lifespan Old value in minutes.
missing the second param doc

2020-11-13 14:50 UTC, Tabrisrp commented on inc/Engine/Cache/ServiceProvider.php
> +			 ->withArgument( $this->getContainer()->get( 'expired_cache_purge' ) );
```suggestion
		$this->getContainer()->add( 'expired_cache_purge', 'WP_Rocket\Engine\Cache\PurgeExpired\PurgeExpiredCache' )
			 ->withArgument( rocket_get_constant( 'WP_ROCKET_CACHE_PATH' ) );
		$this->getContainer()->share( 'expired_cache_purge_subscriber', 'WP_Rocket\Engine\Cache\PurgeExpired\Subscriber' )
			 ->withArgument( $this->getContainer()->get( 'options' ) )
			 ->withArgument( $this->getContainer()->get( 'expired_cache_purge' ) );
```

No need to assign it to a variable if it's used only once

2020-11-16 14:56 UTC, Tabrisrp approved these changes

2020-11-16 14:56 UTC, Tabrisrp commented
@wp-media/qa Ready for QA

2020-11-16 18:02 UTC, piotrbak commented
@Tabrisrp @engahmeds3ed I'm just waiting to confirm that the expired purge works as expected (need to wait one hour now :D ).

When downgrading to the previous version, we're receiving this PHP notice in the WP Debug log:
`[16-Nov-2020 17:59:12 UTC] PHP Notice:  Undefined property: stdClass::$class in C:\Users\pbak\Local Sites\version\app\public\wp-content\plugins\wp-rocket\views\settings\page-sections\dashboard.php on line 76`

What do you think?

https://snippi.com/s/cpye6nc

2020-11-17 21:22 UTC, piotrbak approved these changes
@Tabrisrp As we talked, if this notice is not related to this change, then other tests passed.

2020-11-17 21:27 UTC, merged