Fix respect site's trailing slash settings
wp-media/wp-rocket pull request #3354
Opened 2020-11-24 15:24 UTC by engahmeds3ed

fixes #1392

2020-11-27 14:31 UTC, Tabrisrp approved these changes

2020-11-27 14:42 UTC, Tabrisrp commented on inc/functions/htaccess.php
> +	$rules .= 'RewriteCond %{REQUEST_URI} !wp-admin' . PHP_EOL;
```suggestion
	$rules .= 'RewriteCond %{REQUEST_URI} !(?:^|/)wp\-admin(?:/|$)' . PHP_EOL;
```

2020-11-27 14:50 UTC, Tabrisrp requested changes
~~In the `AdminSubscriber`, you can add a new method hooked on `wp_rocket_upgrade`, to update the `htaccess` file when updating to version 3.8~~

2020-11-27 16:10 UTC, Tabrisrp approved these changes

2020-11-27 16:49 UTC, engahmeds3ed commented
@wp-media/qa You need to check this change carefully please.

I'm sure you know what to do exactly but I'm highlighting some scenarios that need to be check here:-

1. Site is using apache with htaccess and no pages on cache and update permalink structure to use trailing slash and try open any inner page of website with no trailing slash you should be redirected to trailing slash url and try again with the same steps with setting permalink structure to no trailing slash.

2. Try again with cached pages the same at point 1

3. Try with nginx ( it should redirect not cached pages only as we can't control nginx rules )

4. Try opening admin page and make sure that there is no redirection there

5. If you can install any plugin that changes admin login url to be sure that admin page doesn't go into redirection loop.

6. When upgrading, `.htaccess` should be flushed.

7. Vasilis saw some issues before when he enabled `Separate cache files for mobile devices` option so please make sure of that.

2020-11-30 20:38 UTC, piotrbak commented
@Tabrisrp @engahmeds3ed I can see a couple of issues here and will move forward with the further investigation with external plugins tomorrow. Here's what I've found so far:

1. Multisite on subdirectory:
- When permalinks settings are saved on site A, it changes the trailing settings on the site B
- Sites are using `domain.com/site1/wp-admin/` paths. Since `/wp-admin/` is not at the [beginning](https://github.com/wp-media/wp-rocket/blob/7bbc33a45f12503e105c084e779ad4448ab2c39b/inc/functions/htaccess.php#L712), we're rewriting admin URLs to the trailing slashes (also the resources):
![image](https://user-images.githubusercontent.com/26767037/100660172-8ca22d80-3349-11eb-9384-a3068d1f02b0.png)
2. We're checking if the Force Trailing Slash plugin [exists](https://github.com/wp-media/wp-rocket/blob/7bbc33a45f12503e105c084e779ad4448ab2c39b/inc/functions/htaccess.php#L142), but we're not doing this for the one that [removes the trailing slash](https://github.com/wp-media/wp-rocket-helpers/blob/78142b653c120020103c85d382dc2a346dbcba17/htaccess/wp-rocket-htaccess-remove-trailing-slash/wp-rocket-htaccess-remove-trailing-slash.php#L27). It can end up with a redirect loop.
3. The redirect loop can be a potential issue for people that are using the cache, their WordPress is set to use `/` but they have a custom .htaccess that points to the non `/`, and vice versa. But seems to be an edge case.
4. I still need to check this with some plugins that are:
-Hiding `wp-admin`
-Changing the images URLs, I think ShortPixel was doing it
- etc.

This seems to be a challenging update.

2020-11-30 21:13 UTC, Tabrisrp commented
I agree that it's quite risky to go ahead with it like this.

@arunbasillal Maybe this can be delayed and refined more? As far as I know, this was not originally planned for this major version.

It could be good for us to take a bit more time on this one, see if we need to exclude multisite, do more compatibility testing, etc. Especially since we're in the last week of the 3.8 sprint.

The change itself has zero impact on performance, it's more of a QoL change for some customers, and possibly reduce tickets. But right now, there is a risk to have more tickets than solving them.

2020-12-01 10:38 UTC, arunbasillal commented
@Tabrisrp I agree with you. If you think this needs more time, definitely yes. (cc @webtrainingwheels)
But can we plan this for another upcoming sprint so that we do not loose the momentum?

2020-12-01 13:25 UTC, Tabrisrp commented
@arunbasillal Yes, we continue working on it, but it's no longer tied on the 3.8 release.

Your output could be useful for the following too: should this be applied automatically in the `.htaccess`, or should we put it behind a filter to enable it?

My current thinking is that since:
- it doesn't affect performance of the website
- it solves something that is not a real issue as long as you have canonical link on the page
- it comes with risks of conflicts or errors

It might be better to make it opt-in. That would avoid unnecessary tickets, while still allowing the customers who want to preserve this behaviour to do so.

2022-10-21 08:35 UTC, maxplateau commented
Hello, I think not respecting trailing slash is a huge issue and i have a solution :
You just need to add a test at the end of the function can_init_process() in class-tests.php file.

// Don't process if not trailing slash
if( substr($this->get_request_uri_base(),-1) != "/" ) {
	return false;
}

My code just check if the uri is ending with a slash and if it's not then the cache is not processed.

Please add this code in your next update. Thanks !

2023-07-25 10:26 UTC, closed without merging