Fix Fatal error "Path cannot be empty" when combining not readable or not found file
wp-media/wp-rocket pull request #3446
Opened 2020-12-25 15:23 UTC by engahmeds3ed

Fixes https://github.com/wp-media/wp-rocket/issues/3422

2020-12-28 12:30 UTC, iCaspar requested changes

2020-12-28 12:30 UTC, iCaspar commented on inc/Engine/Optimization/Minify/CSS/Combine.php
>  				$filepath     = $this->get_file_path( $style['url'] );
Remove extra spacing before `=` here to pass phpcs

2020-12-29 15:44 UTC, iCaspar approved these changes

2020-12-29 16:55 UTC, engahmeds3ed commented
@wp-media/qa ready for QA.

2020-12-30 16:04 UTC, piotrbak approved these changes
Worked as expected:
[testrail-report-94.pdf](https://github.com/wp-media/wp-rocket/files/5754807/testrail-report-94.pdf)

2021-01-04 15:48 UTC, merged