Fix 3465
wp-media/wp-rocket pull request #3505
Opened 2021-01-19 15:59 UTC by jorgemartine00

Added **.platformsh.site** to $staging list
https://github.com/wp-media/wp-rocket/issues/3465

2021-01-19 16:54 UTC, Tabrisrp approved these changes

2021-01-21 16:33 UTC, Tabrisrp commented
@wp-media/qa ready for QA

2021-01-25 14:53 UTC, piotrbak commented
@Tabrisrp @jorgemartine00 This is very misleading:
1. In the title of the PR and Issue we're mentioning the `.platform.sh`
2. In the `Grooming` section and in the description we have `.platformsh.site`
3. In the code there's `.platform.sh` exclusion
4. I assume that the correct exclusion is the `.platformsh.site`, so we need to correct this.

We need to be strict about that since the change also needs to be done on our website level:
https://github.com/wp-media/wp-rocket/issues/3465#issuecomment-756863123

2021-01-25 14:54 UTC, piotrbak requested changes
Please see the above, we need to address the correct exlusion.

2021-01-25 15:50 UTC, Tabrisrp requested changes

2021-01-25 15:50 UTC, Tabrisrp commented on inc/functions/api.php
> +		'.platform.sh',
```suggestion
		'.platformsh.site',
```

2021-01-25 15:51 UTC, Tabrisrp commented
@piotrbak You're right, I reviewed this too fast on Friday. Updated my review with the change needed.

`platform.sh` is the hosting provider, `.platformsh.site` is the domain used.

2021-01-27 14:43 UTC, Tabrisrp approved these changes

2021-01-27 16:57 UTC, piotrbak approved these changes
Worked as expected, adding a comment on the issue that we also need to handle it on the website side.
[testrail-report-115.pdf](https://github.com/wp-media/wp-rocket/files/5881778/testrail-report-115.pdf)

2021-01-27 18:59 UTC, merged