Fixes #3450 AMP Markup Incompatibilities with preload links and delay JS features
wp-media/wp-rocket pull request #3508
Opened 2021-01-19 18:23 UTC by iCaspar

Closes #3450.

Add a `do_rocket_preload_links` filter to allow/disallow disable preload links feature.
Add a `do_rocket_delay_js` filter to allow/disallow delay JS feature.

Hook `return_false()` to new filters in AMP subscriber to prevent incompatible HTML.

2021-01-19 19:50 UTC, crystinutzaa approved these changes

2021-01-19 19:52 UTC, iCaspar commented
@wp-media/qa This is ready for QA. Please see #3450 for criteria that should be fixed, it is very well laid out there.

2021-01-20 15:28 UTC, Tabrisrp requested changes
the `do_rocket_` is the naming we used early one, before having any kind of coding standards.

Moving forward, let's always prefix our filters corectly with `rocket_`, for consistency.

2021-01-20 15:28 UTC, Tabrisrp commented on inc/Engine/Optimization/DelayJS/HTML.php
> +		if ( ! (bool) apply_filters( 'do_rocket_delay_js', true ) ) { // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
```suggestion
		if ( ! (bool) apply_filters( 'rocket_do_delay_js', true ) ) {
```

2021-01-20 15:28 UTC, Tabrisrp commented on inc/Engine/Preload/Links/Subscriber.php
> +		if ( ! (bool) apply_filters( 'do_rocket_preload_links', true ) ) { //phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
```suggestion
		if ( ! (bool) apply_filters( 'rocket_do_preload_links', true ) ) {
```

2021-01-20 15:28 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/AMP.php
> +		add_filter( 'do_rocket_preload_links', '__return_false' );
```suggestion
		add_filter( 'rocket_do_delay_js', '__return_false' );
		add_filter( 'rocket_do_preload_links', '__return_false' );
```

2021-01-20 15:28 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Optimization/DelayJS/Subscriber/delayJs.php
> +		remove_filter( 'do_rocket_delay_js', '__return_false' );
```suggestion
		remove_filter( 'rocket_do_delay_js', '__return_false' );
```

2021-01-20 15:28 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Optimization/DelayJS/Subscriber/delayJs.php
> +			add_filter( 'do_rocket_delay_js', 'return_false' );
```suggestion
			add_filter( 'rocket_do_delay_js', 'return_false' );
```

2021-01-20 15:28 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Preload/Links/Subscriber/addPreloadScript.php
> +		remove_filter( 'do_rocket_preload_links', '__return_false' );
```suggestion
		remove_filter( 'rocket_do_preload_links', '__return_false' );
```

2021-01-20 15:28 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Preload/Links/Subscriber/addPreloadScript.php
> +			add_filter( 'do_rocket_preload_links' , '__return_false' );
```suggestion
			add_filter( 'rocket_do_preload_links' , '__return_false' );
```

2021-01-20 15:28 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php
> +			$this->assertFalse( has_filter( 'do_rocket_preload_links', '__return_false' ) );
```suggestion
			$this->assertFalse( has_filter( 'rocket_do_delay_js', '__return_false' ) );
			$this->assertFalse( has_filter( 'rocket_do_preload_links', '__return_false' ) );
```

2021-01-20 15:28 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php
> +			$this->assertNotFalse( has_filter( 'do_rocket_preload_links', '__return_false' ) );
```suggestion
			$this->assertNotFalse( has_filter( 'rocket_do_delay_js', '__return_false' ) );
			$this->assertNotFalse( has_filter( 'rocket_do_preload_links', '__return_false' ) );
```

2021-01-20 15:28 UTC, Tabrisrp commented on tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php
> +			$this->assertFalse( has_filter( 'do_rocket_preload_links', '__return_false' ) );
```suggestion
			$this->assertFalse( has_filter( 'rocket_do_delay_js', '__return_false' ) );
			$this->assertFalse( has_filter( 'rocket_do_preload_links', '__return_false' ) );
```

2021-01-20 21:53 UTC, Tabrisrp approved these changes

2021-01-22 21:54 UTC, Tabrisrp commented
@wp-media/qa ready for QA

2021-01-25 14:04 UTC, piotrbak approved these changes
Worked as expected:
[testrail-report-112.pdf](https://github.com/wp-media/wp-rocket/files/5867059/testrail-report-112.pdf)

2021-01-25 16:46 UTC, merged