Fixes #1495: Fix check that allows the cache_root to be built correctly.
wp-media/wp-rocket pull request #3517
Opened 2021-01-22 12:19 UTC by Ozmodiar

Fix for #1495.

This issue was actually quite breaking for us. Because of the fact that the needle and the haystack are not in the correct order, the DOCUMENT_ROOT was not replaced with an empty string causing the path in the RewriteCond to be incorrectly structured. Without the change proposed we ended up with an htaccess like this (snippet):

```
RewriteCond "%{DOCUMENT_ROOT}/var/web/vd17118/releases/20210104103636/wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}%{ENV:WPR_WEBP}.html%{ENV:WPR_ENC}" -f

RewriteRule .* "/var/web/vd17118/releases/20210104103636/wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}%{ENV:WPR_WEBP}.html%{ENV:WPR_ENC}" [L]
```

This means the cache files are never found and thus never hit.

In my case, this were the values:
`ABSPATH=/var/web/vd17118/releases/20210104103636/`
`WP_ROCKET_CACHE_PATH=/var/web/vd17118/releases/20210104103636/wp-content/cache/wp-rocket/`

I'm not a Wordpress developer so let me know if anything else is needed on my part to get this merged.

Thanks!

2021-01-22 21:39 UTC, Tabrisrp approved these changes

2021-01-22 21:53 UTC, Tabrisrp commented
@wp-media/qa ready for QA

2021-01-25 12:13 UTC, piotrbak commented
@Tabrisrp Should I only test the regression on regular Apache as this is fixed for the customer? Or should I try to prepare a custom environment for that? What do you think?

2021-01-25 15:48 UTC, Tabrisrp commented
@piotrbak You can do the regression test, which should be enough.

2021-01-26 19:47 UTC, piotrbak commented
@Tabrisrp I tested this on 3 different environments. 
1. With symlinks where I could reproduce the issue, it helped
2. On two different Apaches where it worked too

Making this change will cause a small change in the .htaccess though:
`RewriteRule .* "/wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}%{ENV:WPR_WEBP}.html%{ENV:WPR_ENC}" [L]`

will become:

`RewriteRule .* "wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}%{ENV:WPR_WEBP}.html%{ENV:WPR_ENC}" [L]`

Note the lack of the `/` in the second example. In my cases, everything worked as expected. I'm thinking if there's any potential risk because of this. What do you think?

2021-01-26 20:03 UTC, Tabrisrp commented
I'm wondering if it could lead to issues in unusual structure where the `htaccess` and the `WP_CONTENT` directory are not in the same repository. To be safe, I'm going to suggest a change on the PR to preserve the leading slash.

2021-01-26 20:03 UTC, Tabrisrp requested changes

2021-01-26 20:03 UTC, Tabrisrp commented on inc/functions/htaccess.php
>  		$cache_root = str_replace( sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ), '', WP_ROCKET_CACHE_PATH );
```suggestion
		$cache_root = '/' . ltrim( '/', str_replace( sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ), '', WP_ROCKET_CACHE_PATH ) );
```

2021-01-26 20:05 UTC, Tabrisrp requested changes
preserve leading slash

2021-01-26 20:06 UTC, Tabrisrp commented on inc/functions/htaccess.php
> +		$cache_root = '/' . ltrim( '/', str_replace( sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ), '', WP_ROCKET_CACHE_PATH ) );
```suggestion
		$cache_root = '/' . ltrim( str_replace( sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ), '', WP_ROCKET_CACHE_PATH ), '/' );
```

2021-01-26 20:07 UTC, Tabrisrp commented
@piotrbak I updated the PR, the leading slash should be preserved now

2021-01-26 20:59 UTC, piotrbak commented
@Tabrisrp On all environments I'm using we're setting this rule in this line:
https://github.com/wp-media/wp-rocket/blob/60284bffbcd0810eba2a263376b5314c2983019e/inc/functions/htaccess.php#L203

It means that the `/` is still missing

2021-01-26 21:05 UTC, Tabrisrp commented on inc/functions/htaccess.php
>  		$cache_root = $site_root . str_replace( ABSPATH, '', WP_ROCKET_CACHE_PATH );
```suggestion
		$cache_root = '/' . ltrim( $site_root . str_replace( ABSPATH, '', WP_ROCKET_CACHE_PATH ), '/' );
```

2021-01-26 21:06 UTC, Tabrisrp approved these changes

2021-01-26 21:31 UTC, piotrbak approved these changes
Worked as expected now:
[testrail-report-114.pdf](https://github.com/wp-media/wp-rocket/files/5876254/testrail-report-114.pdf)

2021-01-27 14:25 UTC, Tabrisrp commented
@Ozmodiar Thank you for your contribution! The fix will be included in the next release of the plugin 👍🏼

2021-01-27 14:26 UTC, merged