Fix get_rocket_cdn_cnames()
wp-media/wp-rocket pull request #3558
Opened 2021-02-04 13:51 UTC by vmanthos

Fixes #3332.

2021-02-04 14:15 UTC, Tabrisrp requested changes
One small change for the PHP Docblock to reflect the update in the code

2021-02-04 14:15 UTC, Tabrisrp commented on inc/functions/api.php
>  	 * @param array $hosts List of CNAMES.
```suggestion
	 * @param array $hosts List of CNAMES.
	 * @param array $zone  Array of CDN zones.
```

2021-02-04 15:12 UTC, Tabrisrp approved these changes

2021-02-04 15:16 UTC, Tabrisrp commented
@wp-media/qa Ready for QA

2021-02-09 20:00 UTC, piotrbak approved these changes
Worked as expected:
[testrail-report-125.pdf](https://github.com/wp-media/wp-rocket/files/5953943/testrail-report-125.pdf)

2021-02-09 20:10 UTC, merged