Fixes #3498 Turn off "Delay JS" option when Safe Mode is activated
wp-media/wp-rocket pull request #3574
Opened 2021-02-09 13:39 UTC by GeekPress

Closes #3498

2021-02-12 15:03 UTC, Tabrisrp requested changes
Fixtures for the automated tests need to be updated

2021-02-15 07:43 UTC, GeekPress commented
@Tabrisrp Unit and Integration tests have been updated.

2021-02-15 20:26 UTC, Tabrisrp approved these changes

2021-02-16 12:01 UTC, Mai-Saad reviewed
@GeekPress I have a couple of questions:
1- Do we need to display safe mode msg even if LazyLoad, File Optimization, Embeds, and CDN options are disabled?
2- Shall the safe mode option, delete the CDN name? (currently, it`s still there)

2021-02-16 14:38 UTC, GeekPress commented
@Mai-Saad 

> 1- Do we need to display safe mode msg even if LazyLoad, File Optimization, Embeds, and CDN options are disabled?

I don't know if adding an exclusion to detect all options turned off and not displaying it on this case worth it.

> 2- Shall the safe mode option, delete the CDN name? (currently, it`s still there)

it's a good thing. If we delete it, it will require an extra step for the users to reconfigure their CDN.

2021-02-16 15:37 UTC, Mai-Saad approved these changes
Works as expected
[testrail-report-132.pdf](https://github.com/wp-media/wp-rocket/files/5989734/testrail-report-132.pdf)

2021-02-16 19:48 UTC, merged