Fix the NextGEN gallery regression
wp-media/wp-rocket pull request #3575
Opened 2021-02-09 14:18 UTC by vmanthos

Fixes #3568.

Solution based on the following comment: https://github.com/wp-media/wp-rocket/issues/3568#issuecomment-775919146

2021-02-09 15:08 UTC, Tabrisrp requested changes

2021-02-09 15:08 UTC, Tabrisrp commented on inc/classes/subscriber/third-party/plugins/class-ngg-subscriber.php
>  	 *
```suggestion
	 *
	 * @param bool $valid_request Indicates if the current request is valid for the NGG resource manager.
	 *
```

2021-02-10 13:19 UTC, Tabrisrp approved these changes

2021-02-10 13:52 UTC, piotrbak commented
@Tabrisrp This one will be pretty hard to check. I think we'll be able to check only 2 scenarios:
1. NextGen + one of the affected plugins
2. NextGen itself

Do you think this is enough?

2021-02-10 14:17 UTC, Tabrisrp commented
@piotrbak Could we validate the change on customers website affected by the issue?

2021-02-10 14:20 UTC, piotrbak commented
@Tabrisrp I'm albo to reproduce it and also will try on customer's site

2021-02-10 15:13 UTC, piotrbak approved these changes
@Tabrisrp Tested on customer's site, reproduced on my own, and tested too:
[testrail-report-128.pdf](https://github.com/wp-media/wp-rocket/files/5959025/testrail-report-128.pdf)

2021-02-10 15:15 UTC, merged