remove empty values in $purge_urls array
wp-media/wp-rocket pull request #3579
Opened 2021-02-09 21:00 UTC by NataliaDrause

fix #3238

Tested with a variety of values passed into the $purge_urls array. Tests and notes added in the ticket: https://secure.helpscout.net/conversation/1413525677/236164/

Another possible solution is to replace the double `array_flip()` with `array_unique()`:
`return array_unique( $purge_urls );`

But this is supposedly less performant and didn't show different results. 

All the values that didn't return _false_ (such as random strings, integers, _true_ boolean) and were passed into the $purge_urls array caused PHP notices regardless of the method `array_flip()` or `array_unique()` is used, but didn't cause the Warning from the GH issue.
Example: _PHP Notice: Trying to access array offset on value of type null in .../wp-content/plugins/wp-rocket/inc/functions/files.php on line 540_

2021-02-12 15:38 UTC, Tabrisrp requested changes

2021-02-12 15:38 UTC, Tabrisrp commented on inc/common/purge.php
> +	$purge_urls = array_filter( $purge_urls );
```suggestion
	$purge_urls = array_filter( $purge_urls );
```
```suggestion
	$purge_urls = array_filter( $purge_urls, 'is_string' );
```

This change will ensure we only preserve string values in the array

2021-02-12 19:35 UTC, Tabrisrp approved these changes

2021-02-18 17:54 UTC, Mai-Saad approved these changes
The PR itself working as expected, other issues exist in the clear cache itself when combined with AMP /Cookie/ user cache

2021-02-18 18:58 UTC, merged