Fix/2839-remove-age-verified-compatibility-files
wp-media/wp-rocket pull request #3585
Opened 2021-02-11 15:09 UTC by jorgemartine00

## Description

- Adds functions from **age-verify.php** to `inc/deprecated/3.8.php`
- Deletes **age-verify.php**
- Removes `require` for age-verify.php from inc/3rd-party/3rd-party.php

Fixes # 2839
https://github.com/wp-media/wp-rocket/issues/2839

## Type of change

- [x] Enhancement (non-breaking change which changes functionality)

## Is the solution different from the one proposed during the grooming?
No

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-02-12 19:13 UTC, Tabrisrp requested changes

2021-02-12 19:13 UTC, Tabrisrp commented on inc/deprecated/3.8.php
> +endif;
You don't need to keep that part, we only want to keep the deprecated functions to make sure there is no errors

2021-02-12 19:13 UTC, Tabrisrp commented on inc/deprecated/3.8.php
> + * @since 2.7
```suggestion
 * @since 3.8.6 deprecated
 * @since 2.7
```

2021-02-12 19:13 UTC, Tabrisrp commented on inc/deprecated/3.8.php
> + * @since 2.7
```suggestion
 * @since 3.8.6 deprecated
 * @since 2.7
```

2021-02-12 19:13 UTC, Tabrisrp commented on inc/deprecated/3.8.php
> +add_action( 'activate_age-verify/age-verify.php', 'rocket_activate_age_verify', 11 );
```suggestion
```

2021-02-12 19:13 UTC, Tabrisrp commented on inc/deprecated/3.8.php
> +add_action( 'deactivate_age-verify/age-verify.php', 'rocket_deactivate_age_verify', 11 );
```suggestion
```

2021-02-12 19:13 UTC, Tabrisrp commented on inc/deprecated/3.8.php
> + * @since 2.7
```suggestion
 * @since 3.8.6 deprecated
 * @since 2.7
```

2021-02-17 19:46 UTC, Tabrisrp approved these changes

2021-02-18 17:34 UTC, piotrbak approved these changes
Worked as expected:
[testrail-report-133.pdf](https://github.com/wp-media/wp-rocket/files/6004715/testrail-report-133.pdf)

2021-02-18 18:57 UTC, merged