Fixes #3605 Replace deprecated jQuery methods
wp-media/wp-rocket pull request #3606
Opened 2021-02-18 17:44 UTC by Tabrisrp

## Description

Replace the deprecated jQuery methods by the corresponding ones for the current jQuery version. This is to make sure we are compatible with WordPress once jQuery migrate is removed from core (currently planned for 5.8)

Fixes #3605

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Tested with `SCRIPT_DEBUG` enabled, and looking at the browser console to see warnings displayed on the `plugins.php` page and WP Rocket settings page

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2021-02-22 14:46 UTC, iCaspar approved these changes

2021-02-22 15:14 UTC, crystinutzaa approved these changes

2021-02-22 16:37 UTC, engahmeds3ed requested changes

2021-02-22 16:37 UTC, engahmeds3ed commented on assets/js/wpr-modal.js
> +    aElem.bind('keyup', function(e){
this old code isn't working at all, please try the following one is working.
```
$(document).on('keyup', function(e){
        if( aElem.length > 0 && 27 === e.keyCode ){ // ECHAP
            refThis.close();
            return false;
        }
    });
```

2021-02-22 16:37 UTC, engahmeds3ed commented on assets/js/wpr-modal.js
>          if(refThis.hiddenDetails.val() != ''){
```suggestion
        if( '' !== refThis.hiddenDetails.val() ){
```

2021-02-22 18:16 UTC, engahmeds3ed approved these changes

2021-02-23 14:32 UTC, piotrbak requested changes
@Tabrisrp When refreshing the license info we're still getting deprecation warning in the `wpr-admin.js`:
`JQMIGRATE: jQuery.fn.blur() event shorthand is deprecated`

2021-02-23 14:41 UTC, Tabrisrp commented
@piotrbak Thank you I missed this one, it's updated!

2021-02-23 18:08 UTC, piotrbak commented
@Tabrisrp I scanned our files for the deprecated functions from the:
https://github.com/jquery/jquery-migrate/blob/master/warnings.md

I'm not sure whether they're JS or jQuery though, please examine them:
- `micromodal.min.js` `.bind()`
- `wpr-admin-common.js` `.ready()`
- `wpr-admin.js` `.ready()` `.easing()` `.type` `.isArray()` `.css()`
- `wpr-modal.js` `.ready()` `.css()`

If they're not related, then we're ready to merge it.

2021-02-23 19:50 UTC, Tabrisrp commented
@piotrbak Had a second look, everything is fine.

2021-02-23 20:45 UTC, piotrbak approved these changes

2021-02-23 21:49 UTC, merged