Minify the resources content at warmup
wp-media/wp-rocket pull request #3829
Opened 2021-04-22 14:04 UTC by engahmeds3ed

## Description

Minify resources' content at warmup as this also will solve some issues like sending all imports to the top of the file before calling treeshaker.

2021-04-22 15:45 UTC, Tabrisrp requested changes
Small suggestions

2021-04-22 15:45 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +		$minifier->add( $data['css'] );
```suggestion
		$minifier = new MinifyCSS( $data['css'] );
```

2021-04-22 15:45 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcher.php
> +		$minifier->add( $contents );
```suggestion
		$minifier = new MinifyCSS( $contents );
```

2021-04-23 11:47 UTC, iCaspar requested changes

2021-04-23 11:47 UTC, iCaspar commented on inc/Engine/Optimization/CSSTrait.php
> +	public function match_charsets( array $match ) : string {
This is for internal use only, should be `private`

2021-04-23 11:58 UTC, iCaspar approved these changes

2021-04-23 12:54 UTC, piotrbak approved these changes
Good to go! 🎉 
[testrail-report-168.pdf](https://github.com/wp-media/wp-rocket/files/6365426/testrail-report-168.pdf)

2021-04-23 12:57 UTC, merged