Fix #3877 Delete RUCSS tables on multisite sub-sites when uninstalling WP Rocket
wp-media/wp-rocket pull request #3878
Opened 2021-05-04 15:51 UTC by engahmeds3ed

## Description

In multisite, Remove all subsites' DB tables created by us

Fixes #3877

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [ ] Manually on our multisite staging site

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-05-04 17:04 UTC, iCaspar requested changes

2021-05-04 17:04 UTC, iCaspar commented on inc/Engine/WPRocketUninstall.php
> +			}
The duplication here seems wrong.
Can we maybe extract these lines into it's own private function, please.
Maybe the main function is `remove_all_rucss_database_tables()` and the extracted one is `drop_usedcss_and_resources_tables()`

2021-05-05 13:58 UTC, Tabrisrp approved these changes

2021-05-06 13:45 UTC, Mai-Saad approved these changes
Works as expected but here are 2 comments already on the trunk. ( not related to this PR)
1- Settings of WPR is different in each site when activating WPR on each site separately after fresh installation
2- We over-write advanced-cache.php with each site activation with the same content, Why do we need to overwrite with the same value?

2021-05-06 18:26 UTC, merged