fixes #3395 - Uncaught TypeError in wpr-cpcss.js, when CPCSS buttons not displayed
wp-media/wp-rocket pull request #3918
Opened 2021-05-17 20:54 UTC by jorgemartine00

fixes #3395 - Uncaught TypeError in wpr-cpcss.js, where CPCSS buttons are not displayed

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (3395)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?
None had been posted yet.

Please describe in this section any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added change on test site
- [ ] Added change temporarily on client's site

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-02 16:34 UTC, Tabrisrp commented
@wp-media/php I think we should still also update the JS to avoid trying to do operations on a not existent node, what do you think?

2022-01-05 16:36 UTC, vg-robin commented
> @wp-media/php I think we should still also update the JS to avoid trying to do operations on a not existent node, what do you think?

Any update on this? Seems there's plenty of plugins that don't show the metabox when post-editing (one called Easy Watermark brought me here), so there's still a need for those existence checks in the JavaScript.

2022-01-19 14:06 UTC, iCaspar requested changes

2022-01-19 14:06 UTC, iCaspar commented on inc/Engine/CriticalPath/Admin/Post.php
> +			return __( 'This feature is not available for not public post types.', 'rocket' );
Phrasing seems a bit odd here. Maybe:
```suggestion
			return __( 'This feature is not available for non-public post types.', 'rocket' );
```

2022-01-24 13:56 UTC, iCaspar approved these changes

2022-01-31 09:53 UTC, Mai-Saad approved these changes
Working as expected
[testrail-report-343.pdf](https://github.com/wp-media/wp-rocket/files/7969768/testrail-report-343.pdf)

2022-02-01 14:01 UTC, merged