remove beacon btn if white label is true
wp-media/wp-rocket pull request #3965
Opened 2021-05-28 12:02 UTC by mostafa-hisham

## Description

When Whitelabel is active remove beacon button and script  also  Ask support button

Fixes #2876

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Yes I also hide the "Ask support button" in the dashboard in "wp-rocket/views/settings/page-sections/dashboard.php"
with this condition

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-01 18:14 UTC, engahmeds3ed requested changes
@mostafa-hisham it's a good opportunity to see our request changes in this issue.
Those are suggestions to make code better.

2021-06-01 18:14 UTC, engahmeds3ed commented on inc/Engine/Admin/Beacon/Beacon.php
> +			rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT' )
please reverse the order of this condition.
Why?
It's a performance-wise thing, so if the white label is active => it will not check if the current user can, and checking a constant is faster than anything else.

2021-06-01 18:14 UTC, engahmeds3ed commented on tests/Integration/inc/Engine/Admin/Beacon/Beacon/insertScript.php
> +		$this->white_label = ( $config['white_label'] );
no need to enclose the config item between `()`

2021-06-01 18:14 UTC, engahmeds3ed commented on tests/Integration/inc/Engine/Admin/Beacon/Beacon/insertScript.php
> +			$this->assertEquals( '', $this->getActualHtml() );
I think you can use the following assertion
```suggestion
			$this->assertEmpty( $this->getActualHtml() );
```

2021-06-01 18:14 UTC, engahmeds3ed commented on tests/Integration/inc/Engine/Admin/Beacon/Beacon/insertScript.php
> +	function locale_cb() {
why splitting this line into two lines and check the same issue with this file methods below

2021-06-01 18:14 UTC, engahmeds3ed commented on views/settings/page-sections/dashboard.php
> +				<?php if ( ! rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT' ) ) : ?>
I think it's better to use `if(){ }` instead of `if endif;` to make it easy to maintain as IDE will highlight brackets to easily know start/end.

2021-06-02 11:28 UTC, engahmeds3ed approved these changes
Awesome job.

2021-06-02 13:57 UTC, piotrbak approved these changes
Good to go!
[testrail-report-187.pdf](https://github.com/wp-media/wp-rocket/files/6585018/testrail-report-187.pdf)

2021-06-02 13:58 UTC, merged