show banner if licence older than 14 days and update tests
wp-media/wp-rocket pull request #4024
Opened 2021-06-09 14:36 UTC by mostafa-hisham

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3807

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Is the solution different from the one proposed during the grooming?

Not really I just rewrite the condition 
to be like this
`if ( ( 14 * DAY_IN_SECONDS ) > time() - $this->user->get_creation_date() ) {
		return false;
}`

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] update fixtures and unit test
- [x] run unit tests
- [x] run integration tests for goup (AdminOnly) 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-06-10 13:36 UTC, engahmeds3ed requested changes

2021-06-10 13:36 UTC, engahmeds3ed commented on inc/Engine/License/Upgrade.php
> +		if ( ( 14 * DAY_IN_SECONDS ) > time() - $this->user->get_creation_date() ) {
u can create a private method to handle this condition, u may call it `is_new_user`, so we bailout here if the user is a new user (registered for less than 14 days)

2021-06-10 14:57 UTC, engahmeds3ed approved these changes

2021-06-18 07:11 UTC, Mai-Saad approved these changes
Works as expected, existing issues not related to this PR.
[testrail-report-195.pdf](https://github.com/wp-media/wp-rocket/files/6674990/testrail-report-195.pdf)

2021-06-18 13:59 UTC, Tabrisrp commented
@mostafa-hisham You can merge this PR 👍🏼

For the merge strategy, use "squash and merge", which helps us keep a clean history in git.

2021-06-18 20:12 UTC, merged