Change sidebar text and link w/check for locale
wp-media/wp-rocket pull request #4026
Opened 2021-06-09 20:13 UTC by iCaspar

## Description

Fixes #3913 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality) -- provides desired new info on mobile WPR settings

## Is the solution different from the one proposed during the grooming?

Same as groomed.

## How Has This Been Tested?

Checked locally in browser with locale US, links to English version
Changed locale to Français de Belgique, link changed to French version

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-06-10 14:08 UTC, Tabrisrp requested changes

2021-06-10 14:08 UTC, Tabrisrp commented on views/settings/partials/sidebar.php
> +	}
Couple of things here:
- no need for the `__()` calls, we won't translate the URL itself
- We should handle the URL value outside of the `href` for readability
- Avoid using `else`

2021-06-10 14:08 UTC, Tabrisrp commented on views/settings/partials/sidebar.php
>  	<a href="<?php echo esc_url( __( 'https://wp-rocket.me/blog/the-truth-about-google-pagespeed-insights/?utm_source=wp_plugin&utm_medium=wp_rocket', 'rocket' ) ); ?>" target="_blank" class="wpr-Sideba
This should be modified too, as per the original issue, as we're also replacing this part

2021-06-10 16:47 UTC, Tabrisrp approved these changes

2021-06-16 15:22 UTC, Mai-Saad reviewed
Works as expected on CH, FF, Safari, Opera. .. remain check if we will do any changes as per discussion here https://wp-media.slack.com/archives/GUKB44GNN/p1623854793027600

2021-06-17 20:14 UTC, merged