Fix/3282 lite speed compatibility
wp-media/wp-rocket pull request #4132
Opened 2021-07-06 07:09 UTC by mostafa-hisham

## Description

I fixed the problem and changed the class to the new structure
the oe thing that is still missing is to make the old class deprecated in 3.9.php that I created in Godaddy VIP issue

Fixes #3282 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [x]  uint and integration test
- [ ] We need to test this on LiteSpeed server to make sure that it will work 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-03 13:01 UTC, Tabrisrp approved these changes

2021-08-03 18:31 UTC, piotrbak commented
@mostafa-hisham The new approach doesn't seem to work. There are two things:
1. There's a lot of confusion in the ticket. The correct value in the array is `X-LSCACHE` not `X_LSCACHE`
2. The new approach with `wp_headers` doesn't seem to work at all. I replaced https://github.com/wp-media/wp-rocket/blob/662e44488b32ed7ba4ab97d293c42a69a29b2239/inc/ThirdParty/Hostings/LiteSpeed.php#L128 with https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/subscriber/third-party/Hostings/class-litespeed-subscriber.php#L114-L118 and it worked correctly.

I'll send you access to the LiteSpeed server on Slack, if you need to test the new approach with headers

2021-08-10 18:21 UTC, piotrbak requested changes
@mostafa-hisham Cleaning the posts' cache doesn't work. Could you recheck now on the website? Branch is uploaded there

2021-08-11 16:58 UTC, piotrbak commented
Tested and it seems to be working fine. Waiting for CR

2021-08-12 13:43 UTC, iCaspar approved these changes

2021-08-12 13:43 UTC, iCaspar commented on inc/ThirdParty/Hostings/LiteSpeed.php
> +		foreach ( $this->headers as $x ) {
```suggestion
		foreach ( $this->headers as $header ) {
```

2021-08-12 13:43 UTC, iCaspar commented on inc/ThirdParty/Hostings/LiteSpeed.php
> +			@header( "X-LiteSpeed-Purge: {$x}", false ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
```suggestion
			@header( "X-LiteSpeed-Purge: {$header}", false ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
```

2021-08-12 13:53 UTC, mostafa-hisham commented on inc/ThirdParty/Hostings/LiteSpeed.php
> +			@header( "X-LiteSpeed-Purge: {$x}", false ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
Fixed

2021-08-12 14:03 UTC, merged