Auto-exclusion for WooCommerce Product Gallery when Delay JS is enabled
wp-media/wp-rocket pull request #4142
Opened 2021-07-09 09:41 UTC by engahmeds3ed

## Description

As mentioned on the issue itself we need to show the gallery directly into the page once loaded.

Fixes #4077

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

I did some research on the issue itself but didn't groom.

## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-15 13:02 UTC, Tabrisrp requested changes
Can you also add the `@since 3.9.1` to the new methods in the WooCommerceSubscriber?

2021-07-15 13:02 UTC, remyperona commented on tests/Integration/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber/showEmptyProductGalleryWithDelayJS.php
> +use Brain\Monkey\Functions;
```suggestion
use WP_Rocket\Tests\Integration\TestCase;
```

The others are not used in this file

2021-07-15 13:02 UTC, remyperona commented on tests/Integration/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber/showEmptyProductGalleryWithDelayJS.php
> +			$this->assertContains( '.woocommerce-product-gallery{ opacity: 1 !important; }', $extra_after['after'] );
```suggestion
			$this->assertStringContainsString( '.woocommerce-product-gallery{ opacity: 1 !important; }', $extra_after['after'] );
```

You should be able to use this one since we use the polyfill for new versions of PHPUnit

2021-07-15 13:02 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber/showNotemptyProductGalleryWithDelayJS.php
> +		$this->assertEquals( $expected['excluded'], $actual );
```suggestion
		$this->assertSame( $expected['excluded'], $actual );
```

2021-07-15 13:02 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber/showNotemptyProductGalleryWithDelayJS.php
> +use Brain\Monkey\Functions;
```suggestion
use WP_Rocket\Tests\Integration\TestCase;
```

2021-07-15 13:06 UTC, engahmeds3ed commented on tests/Integration/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber/showEmptyProductGalleryWithDelayJS.php
> +			$this->assertContains( '.woocommerce-product-gallery{ opacity: 1 !important; }', $extra_after['after'] );
`assertStringContainsString` is used to assert that a string contains a string but after is an array so I need to assert that this `after` array has this string.

2021-07-15 13:28 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber/showEmptyProductGalleryWithDelayJS.php
> +			$this->assertContains( '.woocommerce-product-gallery{ opacity: 1 !important; }', $extra_after['after'] );
ah alright, I thought `after` was a string, all good then

2021-07-15 13:28 UTC, Tabrisrp approved these changes

2021-07-16 15:16 UTC, Mai-Saad approved these changes
Working as expected
[testrail-report-222.pdf](https://github.com/wp-media/wp-rocket/files/6831657/testrail-report-222.pdf)

2021-07-16 15:24 UTC, merged