Fix/4080 elementor pro animation
wp-media/wp-rocket pull request #4211
Opened 2021-07-30 06:57 UTC by mostafa-hisham

## Description

ِAdd js script to fix Elementor pro animations if delay js is enabled

Fixes #4080 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

- [x] create Unit and integration 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-08-02 19:41 UTC, Tabrisrp requested changes

2021-08-02 19:41 UTC, Tabrisrp commented on assets/js/elementor-animation.js
> +class RocketElementorAnimation {
We should minify this file

2021-08-02 19:41 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/PageBuilder/ElementorPro.php
> +	 *
```suggestion
	 *
	 * @since 3.9.2
	 *
```

2021-08-02 19:41 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/PageBuilder/ElementorPro.php
> +	 * @param html $html DelayJS HTML class.
```suggestion
	 * @param string $html HTML content.
```

2021-08-04 16:24 UTC, Tabrisrp approved these changes

2021-08-05 12:28 UTC, Mai-Saad commented
While exploring the fix found that:
1- Current fix only handle motion effect on text (which already exists in normal Elementor) while still not handling animated headline feature (open with Elementor Pro) i.e animated headline will only appear with user interaction, Do we need it to appear without user interaction?
2- If Elementor Pro is deactivated, we aren't handling the Motion effect which was already handled in 1 => I think if we kept the script while Elementor is activated
3- With the default exclusions, we still add the fixing script, Do we still need to add it?
4- Will the fixing script be added on all pages or only the page using Elementor animation? i.e this page https://new.rocketlabsqa.ovh/3279template/

Notes: 
- test page is  https://new.rocketlabsqa.ovh/elementor-pro-animation/
- Unhandled effects mean that it won't appear till user interaction occurs

2021-08-05 14:12 UTC, Tabrisrp commented
@GeekPress see Mai's questions above

2021-08-05 14:56 UTC, GeekPress commented
1- Animated headline feature is out of the scope of this enhancement.

2- Let's add our script with Elementor is detected instead of Elementor Pro.

3- We can keep adding our Elementor script, it shouldn't create a conflict. The inline script is very small, so it won't have a bad impact on performance if we keep it.

4- The script can be added on all pages for the same reason than 2.

2021-08-06 04:30 UTC, mostafa-hisham commented
@Mai-Saad 
Now the script will be added if `Elementor` is active, not `ElementorPRo`

2021-08-06 13:25 UTC, Mai-Saad reviewed
All test cases pass but we have a problem on the branch to display Desktop/ mobile at the bottom of the page while Delay js only is enabled (tested latest problem on both newlabs and rocketlabs)
![Screenshot from 2021-08-06 15-25-44](https://user-images.githubusercontent.com/76941962/128517277-ba7f7122-2650-430b-9b01-e30c43368d07.png)

2021-08-06 14:32 UTC, mostafa-hisham commented
@Mai-Saad  @GeekPress 
there is a problem with the script that is used to fix elementor animations

here the script appends this span to the end of the page
`<span id="elementor-device-mode"></span>`

and then after the js that was delayed by Delay js feature runs again when users interact with the page
it adds a new span with the same id and the class that should hide it
`<span id="elementor-device-mode" class="elementor-screen-only"></span>`

https://github.com/wp-media/delay-javascript-loading/blob/156b81eddf5a1d845b0f934ecea66dfcf24aad65/elementor-animation.js#L3-L9

I fixed the problem by removing this line but this needs to be checked by Gaël Métais

https://github.com/wp-media/delay-javascript-loading/blob/156b81eddf5a1d845b0f934ecea66dfcf24aad65/elementor-animation.js#L7

2021-08-06 14:41 UTC, Tabrisrp approved these changes

2021-08-06 14:48 UTC, GeekPress commented
@mostafa-hisham To fix the issue we also need to add the class `elementor-screen-only` to the span.

```
constructor() {
        // Injects a span, that will later provide the device type from some CSS media query rules
        this.deviceMode = document.createElement('span');
        this.deviceMode.id = 'elementor-device-mode';
        this.deviceMode.setAttribute('class', 'elementor-screen-only');
        document.body.appendChild(this.deviceMode);
}
```

2021-08-09 06:30 UTC, mostafa-hisham commented
@GeekPress 
I tried the code you send and it will fix the issue but also will append the span twice

![image](https://user-images.githubusercontent.com/29744252/128667571-6b7857cd-8b0d-415a-9df2-47049897b212.png)

2021-08-09 07:14 UTC, GeekPress commented
@mostafa-hisham Does it cause any issues to have it twice? If not, I think we can keep it.

You can try WP Meteor which has an option to do exactly the same, and check if the span is also added twice or not.

You can also have a look at WP Meteor code here:
- https://plugins.trac.wordpress.org/browser/wp-meteor/trunk/src/js/public/includes/elementor/device-mode.js
- https://plugins.trac.wordpress.org/browser/wp-meteor/trunk/src/js/public/includes/elementor/animations.js

2021-08-09 09:23 UTC, mostafa-hisham commented
@GeekPress 
I checked it with elementor it didn't cause any problems with animations
I updated the PR with the fix and I will send it to QA to check it

2021-08-09 11:33 UTC, Mai-Saad approved these changes
The latest problem is fixed now.
[testrail-report-235.pdf](https://github.com/wp-media/wp-rocket/files/6954134/testrail-report-235.pdf)

2021-08-09 11:46 UTC, merged