return false if it is not wc_product
wp-media/wp-rocket pull request #4302
Opened 2021-08-31 11:51 UTC by mostafa-hisham

## Description

return false if it is not wc_product

Fixes #4255 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

- [x] unit and integration tests

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-01 22:57 UTC, Tabrisrp requested changes

2021-09-01 22:57 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php
> +		if ( ! $product || empty( $product ) ) {
empty will check for both null and false, so we don't need the first part of the condition

2021-09-02 12:56 UTC, Tabrisrp approved these changes

2021-09-06 17:43 UTC, piotrbak approved these changes
Good to go!
[testrail-report-249.pdf](https://github.com/wp-media/wp-rocket/files/7117334/testrail-report-249.pdf)

2021-09-07 09:14 UTC, merged

2021-09-13 17:11 UTC, katielgc commented
Hi all, could you let me know when this will be merged into the master for deployment on our site?

2021-09-13 17:52 UTC, iCaspar commented
@katielgc We expect, pending final QA, to merge and release this week. 🤞