Closes WordFence background processes compatibility
wp-media/wp-rocket pull request #4355
Opened 2021-09-16 08:19 UTC by mostafa-hisham

## Description

Create a new compatibility class `Engine\ThirdParty\Plugins\Security\WordFence`
to add or IP to WordFence whitelist
Fixes #3916 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

- [x] locally by printing the WordFence whitelisted is in the footer
- [x] unit and integration tests

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-16 20:26 UTC, Tabrisrp requested changes

2021-09-16 20:26 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Security/WordFenceCompatibility.php
> +use Exception;
```suggestion
```

2021-09-16 20:26 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Security/WordFenceCompatibility.php
> +use WP_Rocket\Logger\Logger;
```suggestion
```

2021-09-16 20:26 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Security/WordFenceCompatibility.php
> +		$ips = apply_filters( 'rocket_wordfence_whitelisted_ips', self::WHITELISTED_IPS );
Can you add a docblock for the filter?

2021-09-16 20:26 UTC, Tabrisrp commented on tests/Fixtures/inc/ThirdParty/Plugins/Security/WordFence/wordfence.php
> + * Mocked WpeCommon for WP Engine to the minimum requirement for tests to run.
```suggestion
 * Mocked wordfence to the minimum requirement for tests to run.
```

2021-09-16 20:26 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Security/WordFence/whitelistIPs.php
> +use WP_Rocket\Tests\Unit\TestCase;
```suggestion
use WP_Rocket\Tests\Integration\TestCase;
```

2021-09-16 20:26 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Security/WordFence/whitelistIPs.php
> +use Brain\Monkey\Functions;
```suggestion
```

2021-09-17 15:40 UTC, Tabrisrp approved these changes

2021-09-20 15:27 UTC, piotrbak commented
@Tabrisrp @mostafa-hisham I'm not able to reproduce it. Even blocking the IP `135.125.83.227` in 3.9.4 version doesn't prevent RUCSS from working. Do we have any confirmation from support that whitelisting this IP in WordFence settings resolves the issue?

If so, then the IP is added to the whitelist correctly and that's what we could be testing further.

2021-10-05 12:39 UTC, piotrbak commented
@Tabrisrp Is this one ready for QA? Should we try this approach? I don't have any feedback from support 😢

2021-10-05 14:07 UTC, Tabrisrp commented
@piotrbak Code-wise it's ok, but if we are not able to replicate the issue during QA, and we're not sure that's the right solution for the problem, we should wait.

2021-10-25 13:48 UTC, piotrbak approved these changes
@Tabrisrp as per talks with @GeekPress 

We're going to release it and see if new tickets are still coming, as we're not able to reproduce it.
[testrail-report-285.pdf](https://github.com/wp-media/wp-rocket/files/7410507/testrail-report-285.pdf)

2021-10-25 20:03 UTC, merged