Closes combine CSS divi 4.10 compatibility
wp-media/wp-rocket pull request #4377
Opened 2021-09-23 12:12 UTC by mostafa-hisham

## Description

 exclude all Divi CSS files which are stored in /wp-content/et-cache/ From being Compiend

Fixes #4320 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-27 14:04 UTC, iCaspar approved these changes

2021-10-01 10:15 UTC, Mai-Saad commented
Well, I can't see a UI problem when the combine is enabled while Load Dynamic Stylesheet Inline is enabled at Divi, however, while checking that we keep Divi CSS order, here is the current state/questions:
1- When  Load Dynamic Stylesheet is enabled => All Divi related style sheets under the inline CSS are kept in the source (Is it expected that the sheet here is normally combined 
`<meta content="Divi v.4.10.7" name="generator"/><link rel='stylesheet' id='wp-block-library-css'  href='https://new.rocketlabsqa.ovh/wp-includes/css/dist/block-library/style.min.css?ver=5.8.1' type='text/css' media='all' /> ` also it was below an inline style  `<style id="et-divi-open-sans-inline-css">`?)
2- When Critical CSS is enabled while Load Dynamic Stylesheet is disabled => This file is combined  `<link rel='stylesheet' id='divi-style-css'  href='https://new.rocketlabsqa.ovh/wp-content/themes/Divi/style.min.css?ver=4.10.7' type='text/css' media='all' />` also it was below an inline style  `<style id="et-divi-open-sans-inline-css">` (order changed here, so shouldn't we keep this file uncombined?)
3- When both Critical CSS and Load Dynamic Stylesheet are disabled at Divi => We are not combining some Divi CSS files although no internal script in this case i.e no Divi CSS between style tags (shouldn't we combine Divi CSS files here?)

2021-10-01 19:09 UTC, Tabrisrp requested changes
Test & fixture should be updated based on the review's comments.

2021-10-01 19:09 UTC, Tabrisrp commented on inc/ThirdParty/Themes/Divi.php
> +		}
We don't need to check for the `remove_unused_css` value. If RUCSS is enabled, there won't be any minify/combine happening anyway.

What we need to check for is if `minify_concatenate_css` is enabled, and bail-out if it isn't.

2021-10-01 19:09 UTC, Tabrisrp commented on inc/ThirdParty/Themes/Divi.php
> +		$wp_content    = wp_parse_url( content_url( '/' ), PHP_URL_PATH );
`wp_parse_url()` can return `null` when using the second parameter. We should check if `$wp_content` is not null before using it on the line after.

2021-10-04 18:06 UTC, Tabrisrp requested changes
need to update the fixtures and test too

2021-10-04 18:06 UTC, Tabrisrp commented on inc/ThirdParty/Themes/Divi.php
> +		if ( (bool) $this->options->get( 'minify_concatenate_css', 0 ) ) {
```suggestion
		if ( ! (bool) $this->options->get( 'minify_concatenate_css', 0 ) ) {
```

We should bail-out if the option is not enabled

2021-10-05 14:54 UTC, Tabrisrp approved these changes

2021-10-05 15:58 UTC, Mai-Saad approved these changes
Working as expected
[testrail-report-265.pdf](https://github.com/wp-media/wp-rocket/files/7287343/testrail-report-265.pdf)

Notes:
We agreed that the following is fine
1- While Critical CSS is enabled at Divi , we will combine Divi style file although it's under divi inline fonts
2- If both Load CSS and critical CSS are disabled at Divi, there will be no inline for Divi styles and we will still exclude Divi files from Combine CSS

2021-10-05 17:49 UTC, merged