stop background processes before rollback and update
wp-media/wp-rocket pull request #4392
Opened 2021-09-28 13:19 UTC by mostafa-hisham

## Description

stop background processes before rollback and update to avoid fatal if the processes still running while the plugin changes

Fixes #4391 

## Type of change

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

there is no grooming
## How Has This Been Tested?

- [x] we should create an alpha release with this branch so we can test it in both rollback and upgrade

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2021-09-28 13:53 UTC, iCaspar reviewed
What's here looks good.
Can we add integration tests to cover this?

2021-09-30 09:09 UTC, mostafa-hisham commented
@iCaspar 
I successfully created Integration tests for 
stop CPCSS background Process
stop homepage preload background process

in both 
stop warmup background process
stop sitemap preload background process

i think the problem is I couldn't start them in the integration test 
to check if the upgrade or rollback action will stop them

you can have a look at the classes in the [previous commit](https://github.com/wp-media/wp-rocket/pull/4392/commits/c4d7f4c06b06bbbae7d3dcb2b0a699875285250c) if you want to give it a try

2021-09-30 13:16 UTC, iCaspar requested changes
Nice work.

2021-09-30 13:16 UTC, iCaspar commented on tests/Integration/inc/Engine/Preload/Homepage/stopPreload.php
> +		$this->assertSame(  false , $is_cron_exists );
```suggestion
		$this->assertFalse( $is_cron_exists );
```

2021-09-30 13:16 UTC, iCaspar commented on tests/Integration/inc/Engine/Preload/Homepage/stopPreload.php
> +		$this->assertSame(  false , $is_cron_exists );
```suggestion
		$this->assertFalse( $is_cron_exists );
```

2021-10-04 14:41 UTC, iCaspar approved these changes

2021-10-05 16:12 UTC, piotrbak commented
@mostafa-hisham 
When rolling back from the branch to 3.9, there's no fatal error, but the RUCSS process can be stuck on warming up with wrong data:
`"warmup_status":{"total":1,"warmed_count":0,"notwarmed_resources":[],"duration":70,"completed":false}`. 
While updating, it got stuck too, but the data was more accurate.

It seems not to be a problem with this branch, as it's only here to prevent fatal error from happening. There's no pattern to reproduce this though.

@Tabrisrp What do you think? Should we somehow make sure that RUCSS process will be continued and more reliable in this PR?

2021-10-05 16:22 UTC, remyperona commented
Since we cancel the process, we can't resume it easily after. I'd say it's ok for this PR, and we can follow up on another issue to handle this case.

2021-10-05 17:25 UTC, piotrbak commented
@mostafa-hisham @Tabrisrp After one of the tries, my log got blasted with that kind of notices:
```
[05-Oct-2021 15:40:59 UTC] PHP Notice:  Undefined index: external in /var/www/rocketlab.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php on line 123

[05-Oct-2021 15:40:59 UTC] PHP Notice:  Undefined index: path in /var/www/rocketlab.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php on line 123

[05-Oct-2021 15:40:59 UTC] PHP Notice:  Undefined index: path in /var/www/rocketlab.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php on line 135

```

Do you think we can do something about that?

2021-10-07 10:09 UTC, mostafa-hisham commented
@piotrbak @Tabrisrp 
i guarded the variables to avoid warnings

2021-10-08 13:26 UTC, piotrbak approved these changes
Good to go!
[testrail-report-269.pdf](https://github.com/wp-media/wp-rocket/files/7311611/testrail-report-269.pdf)

2021-10-08 15:29 UTC, merged