execlude ai-uncode.js from defer js
wp-media/wp-rocket pull request #4567
Opened 2021-12-07 06:27 UTC by mostafa-hisham

## Description

Add `/library/js/ai-uncode.js` , `/library/js/min/ai-uncode.min.js`, `/library/js/ai-uncode.min.js`  to the function rocket_exclude_defer_js_uncode()

Fixes #4506 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

- [x] Unit and integration test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2021-12-10 16:36 UTC, Tabrisrp approved these changes

2021-12-14 08:08 UTC, Mai-Saad commented
Fixed on Mega site for Defer JS.

Note: if Delay JS is enabled, header/BG image won't be displayed till user interaction. Do we need to handle anything in this case? @piotrbak 

Before interaction:
![Screenshot from 2021-12-14 09-20-01](https://user-images.githubusercontent.com/76941962/145957940-5f9f8ea3-3aa3-4fb3-8bcd-daa737de6885.png)

After interaction:
![Screenshot from 2021-12-14 09-20-08](https://user-images.githubusercontent.com/76941962/145958015-540acf9d-a514-4e25-9904-cd742766dc2e.png)

2021-12-14 11:23 UTC, piotrbak commented
@Mai-Saad To resolve the issue we need to exclude the following form the **Delay JS**:
```
/wp-content/themes/uncode/library/js/init.js
/wp-content/themes/uncode/library/js/ai-uncode.js
UNCODE\.
```

@mostafa-hisham Can we do that within this PR?

2021-12-15 14:10 UTC, Tabrisrp requested changes

2021-12-15 14:10 UTC, Tabrisrp commented on inc/3rd-party/themes/uncode.php
> +	function rocket_exclude_defer_js_uncode( $exclude_delay_js ) {
```suggestion
	function rocket_exclude_delay_js_uncode( $exclude_delay_js ) {
```

2021-12-15 20:30 UTC, Tabrisrp approved these changes

2021-12-16 09:14 UTC, Mai-Saad commented
For some reason exclusion isnot working for Delay Js 
`<script type='text/javascript' src='/uncode/wp-content/themes/uncode/library/js/ai-uncode.js' id='uncodeAI' data-async='true' data-home='/uncode/' data-path='/uncode/' data-breakpoints-images='258,516,720,1032,1440,2064,2880' id='ai-uncode-js'></script>`
is delayed and turned into
<script type="rocketlazyloadscript" data-rocket-type='text/javascript' src='/uncode/wp-content/themes/uncode/library/js/ai-uncode.js' id='uncodeAI' data-async='true' data-home='/uncode/' data-path='/uncode/' data-breakpoints-images='258,516,720,1032,1440,2064,2880' id='ai-uncode-js'></script>

I think we can have a separate issue for Delay JS for further investigations @piotrbak what do you think?

2021-12-16 09:37 UTC, Mai-Saad commented on inc/3rd-party/themes/uncode.php
> +	add_filter( 'exclude_delay_js', 'rocket_exclude_delay_js_uncode' );
I think` exclude_delay_js` shall be `rocket_exclude_delay_js`  to follow the same naming convention as the rest. what do you think @mostafa-hisham?

2021-12-17 05:46 UTC, Mai-Saad approved these changes
Working fine now for both Defer JS and Delay JS
[testrail-report-328.pdf](https://github.com/wp-media/wp-rocket/files/7732321/testrail-report-328.pdf)

2021-12-17 16:26 UTC, merged