Fixes #4728 Prevent PHP 8.1 deprecation notice related to FILTER_INPUT_STRING usage
wp-media/wp-rocket pull request #4732
Opened 2022-02-15 16:25 UTC by Tabrisrp

## Description

Replace the usage of `FILTER_INPUT_STRING` (deprecated in PHP 8.1) by using the WP function `sanitize_key()` instead.

Fixes #4728

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

2022-02-25 01:08 UTC, engahmeds3ed approved these changes

2022-04-01 03:26 UTC, engahmeds3ed requested changes

2022-04-01 03:26 UTC, engahmeds3ed commented on inc/ThirdParty/Plugins/SEO/Yoast.php
> +		$yoast_seo_xml = get_option( 'wpseo_xml', [] ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals
What do u think if we used here their options class instead? they handle there multisite in a good way:
https://github.com/Yoast/wordpress-seo/blob/trunk/inc/options/class-wpseo-options.php#L242-L263

2022-04-01 13:51 UTC, remyperona commented on inc/ThirdParty/Plugins/SEO/Yoast.php
> +		$yoast_seo_xml = get_option( 'wpseo_xml', [] ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals
A couple of reasons I prefer the current approach:
- less dependency on 3rd party code, if they ever change their code we won't have to change ours, since we use core functions
- using will re-introduce the deprecation notice on 8.1, because there is no guarantee it returns an array (even if the typehint says so), and we need this to be an array.

2022-04-11 10:12 UTC, engahmeds3ed approved these changes

2022-04-12 21:20 UTC, Mai-Saad commented
@Tabrisrp the main error is fixed but can see an error with the following steps in query monitor (it will be removed by clearing cache)
1- PHP 8.1
2- Install and activate 3.10.9 or 3.11.0.3 and refresh the plugins page while the query monitor is open => some errors exist for WPR
3- Deactivate plugin, switch to fix branch and `composer dumpautoload` then activate wpr and check query monitor

![Screenshot from 2022-04-12 23-10-11](https://user-images.githubusercontent.com/76941962/163056309-7d02176d-b21f-4e85-8c8f-3d026df4d199.png)
Do we need to do anything about this?

2022-04-13 13:38 UTC, Tabrisrp commented
@Mai-Saad Can you click on the ➕ icon to get the details of the location?

Right now I don't know which WPR code it's coming from

2022-04-13 14:11 UTC, Mai-Saad commented
@Tabrisrp HYG
![Screenshot from 2022-04-13 16-05-04](https://user-images.githubusercontent.com/76941962/163198817-edf1d018-509f-4af3-abec-bbc95e95c980.png)

2022-04-13 14:31 UTC, Tabrisrp commented
@Mai-Saad Thank you, the issue is coming from WP core itself, not from WP Rocket, so it's not something we can fix.

2022-04-13 15:26 UTC, Mai-Saad approved these changes
Working as expected

2022-04-13 15:28 UTC, merged