Display integers as width and height values for SVG (instead of decimals) to prevent errors
wp-media/wp-rocket pull request #4805
Opened 2022-03-10 15:28 UTC by Klemart3D

## Description

Display integers as width and height values for SVG (instead of decimals) to prevent errors.

Fixes #1804

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Load a SVG with decimals in viewBox and check DOM if width and height values are converted to integers (needs "Add Missing Image Dimensions" option enabled)

# Checklist:

Please delete the options that are not relevant.

2022-03-14 20:19 UTC, Tabrisrp requested changes

2022-03-14 20:19 UTC, Tabrisrp commented on inc/Engine/Media/ImageDimensions/ImageDimensions.php
> +			$size[3] = 'width="' . absint($width) . '" height="' . absint($height) . '"';
```suggestion
			$size[3] = 'width="' . absint( $width ) . '" height="' . absint( $height ) . '"';
```

2022-03-14 20:19 UTC, Tabrisrp commented on inc/Engine/Media/ImageDimensions/ImageDimensions.php
> +				$size[3] = 'width="' . absint($size[0]) . '" height="' . absint($size[1]) . '"';
```suggestion
				$size[3] = 'width="' . absint( $size[0] ) . '" height="' . absint( $size[1] ) . '"';
```

2022-03-17 20:26 UTC, Tabrisrp approved these changes

2022-03-17 20:27 UTC, remyperona commented
Thank you for the PR @Klemart3D,

After going through our QA process, it will be added in one of our next releases.

2022-04-07 10:49 UTC, Mai-Saad approved these changes
Working as expected with decimal/integer SVG dimensions/viewport internal/external and inside pic Elem.

2022-04-07 10:49 UTC, Mai-Saad approved these changes

2022-04-07 13:26 UTC, merged