Added amp-mobile-version-switcher to the HTML DelayJs exclusion array
wp-media/wp-rocket pull request #4827
Opened 2022-03-18 09:19 UTC by CrochetFeve0251

## Description

Fix the problem which prevent the page from redirecting automatically to the ?amp=1 page without any user interaction.
This has been implemented by excluding wprRemoveCPCSS from Delay JS.
Fixes #4757 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No the grooming was right

## How Has This Been Tested?

- [ ] Run tests locally
- [ ] Check the behavior on my own testing website

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-18 09:24 UTC, CrochetFeve0251 commented
@engahmeds3ed Should I change fixtures for this functionnality as it is external plugin: ``<script type="16b9331a55e54810d7a4cd33-text/javascript">
!function(){var e={};e.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||new Function("return this")()}catch(e){if("object"==typeof window)return window}}(),function(n){let{ampUrl:t,isCustomizePreview:r,isAmpDevMode:o,noampQueryVarName:s,noampQueryVarValue:i,disabledStorageKey:a,mobileUserAgents:c,regexRegex:u}=n;if("undefined"==typeof sessionStorage)return;const d=new RegExp(u);if(!c.some((e=>{const n=e.match(d);return!(!n||!new RegExp(n[1],n[2]).test(navigator.userAgent))||navigator.userAgent.includes(e)})))return;e.g.addEventListener("DOMContentLoaded",(()=>{const e=document.getElementById("amp-mobile-version-switcher");if(!e)return;e.hidden=!1;const n=e.querySelector("a[href]");n&&n.addEventListener("click",(()=>{sessionStorage.removeItem(a)}))}));const g=o&&["paired-browsing-non-amp","paired-browsing-amp"].includes(window.name);if(sessionStorage.getItem(a)||r||g)return;const m=new URL(location.href),h=new URL(t);h.hash=m.hash,m.searchParams.has(s)&&i===m.searchParams.get(s)?sessionStorage.setItem(a,"1"):h.href!==m.href&&(window.stop(),location.replace(h.href))}({"ampUrl":"https:\/\/rocket.mitango.app\/?amp=1","noampQueryVarName":"noamp","noampQueryVarValue":"mobile","disabledStorageKey":"amp_mobile_redirect_disabled","mobileUserAgents":["Mobile","Android","Silk\/","Kindle","BlackBerry","Opera Mini","Opera Mobi"],"regexRegex":"^\\/((?:.|\n)+)\\/([i]*)$","isCustomizePreview":false,"isAmpDevMode":false})}();
</script>``

2022-03-18 10:16 UTC, CrochetFeve0251 commented
@engahmeds3ed I added the script to the fixtures

2022-03-18 11:59 UTC, engahmeds3ed commented
@CrochetFeve0251 it looks good to me.

@Tabrisrp we already have third party compatibility for for AMP, do u think it'd be better if we used the filter there to add this exclusion?

2022-03-18 13:35 UTC, Tabrisrp commented
It could be cleaner that way indeed

2022-03-21 13:18 UTC, CrochetFeve0251 commented
@engahmeds3ed I added the integration test

2022-03-21 13:23 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/AMP.php
> +	 * @since 3.10.1
```suggestion
	 * @since 3.11.1
```

2022-03-21 13:26 UTC, Tabrisrp requested changes

2022-03-21 13:26 UTC, remyperona commented on tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php
> +	 */
```suggestion
	/**
	 * @dataProvider configTestData
	 */
```

You can use the configTestData method as the data provider, it will automatically match with the corresponding file in the fixtures directory

2022-03-21 13:26 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php
> +	}
```suggestion
```

2022-03-21 13:26 UTC, remyperona commented on tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php
> +	 */
```suggestion
	/**
	 * @dataProvider configTestData
	 */
```

2022-03-21 13:26 UTC, remyperona commented on tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php
> +	}
```suggestion
```

2022-03-28 12:58 UTC, Tabrisrp requested changes

2022-03-28 12:58 UTC, Tabrisrp commented on tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php
> +use WPMedia\PHPUnit\Unit\TestCase;
```suggestion
use WP_Rocket\Tests\Unit\TestCase;
```

2022-03-28 12:58 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php
> +use WPMedia\PHPUnit\Unit\TestCase;
```suggestion
use WP_Rocket\Tests\Integration\TestCase;
```

2022-03-28 12:58 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php
> +use WPMedia\PHPUnit\Unit\TestCase;
```suggestion
```

2022-03-28 12:58 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/AMP.php
> +	 * Adds the switching script from AMP to excluded files
```suggestion
	 * Adds the switching script from AMP to delay JS excluded files
```

2022-03-28 15:17 UTC, CrochetFeve0251 commented
@Tabrisrp I made changes

2022-03-28 21:27 UTC, Tabrisrp approved these changes

2022-03-29 09:38 UTC, Mai-Saad approved these changes
working as expected
[testrail-report-364.pdf](https://github.com/wp-media/wp-rocket/files/8370069/testrail-report-364.pdf)

2022-03-29 13:14 UTC, Tabrisrp commented
@CrochetFeve0251 You can merge the PR using "squash and merge" method. 👍🏼

2022-04-06 21:31 UTC, merged

2022-04-06 21:32 UTC, CrochetFeve0251 commented
@Tabrisrp just saw I forgot to merge that branch can I do the same with the others @Mai-Saad approuved?