Added a new Thirdparty class for Judge.me that excludes window.jdgmSettings from DelayJS
wp-media/wp-rocket pull request #4839
Opened 2022-03-22 12:48 UTC by CrochetFeve0251

## Description

Fix an issue with Judge.me that makes a JS script crash on load from a product page by excluding the script in question when Judge.me is loaded.

Fixes #4171

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?
No grooming was right

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

- [ ] Automated testing
- [ ] Test on my own web server

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-28 13:16 UTC, Tabrisrp commented
@wp-media/php I think we don't need a compatibility file here, we could directly add `window.jdgmSettings` to the exclusion array

2022-03-28 15:16 UTC, CrochetFeve0251 commented
@Tabrisrp should I wait someone confirm or should I refactor it now?

2022-03-28 21:25 UTC, Tabrisrp commented
You can refactor now

2022-03-29 13:15 UTC, Tabrisrp requested changes
Cleanup in the composer file, bootstrap and remove the integration test

2022-03-29 13:34 UTC, Tabrisrp commented on composer.json
> +		"test-integration": "\"vendor/bin/phpunit\" --testsuite integration --colors=always --configuration tests/Integration/phpunit.xml.dist --exclude-group AdminOnly,BeaverBuilder,Elementor,Hummingbird,
```suggestion
		"test-integration": "\"vendor/bin/phpunit\" --testsuite integration --colors=always --configuration tests/Integration/phpunit.xml.dist --exclude-group AdminOnly,BeaverBuilder,Elementor,Hummingbird,WithSmush,WithWoo,WithAmp,WithAmpAndCloudflare,WithSCCSS,Cloudways,Dreampress,DoCloudflare,Multisite,WPEngine,SpinUpWP,WordPressCom,O2Switch,PDFEmbedder,PDFEmbedderPremium,PDFEmbedderSecure,Godaddy,LiteSpeed,RevolutionSlider,WordFence",
```

2022-03-29 13:37 UTC, CrochetFeve0251 commented on composer.json
> +		"test-integration": "\"vendor/bin/phpunit\" --testsuite integration --colors=always --configuration tests/Integration/phpunit.xml.dist --exclude-group AdminOnly,BeaverBuilder,Elementor,Hummingbird,
@CrochetFeve0251 I pushed 2 commits on that topic in parallel

2022-03-29 13:37 UTC, Tabrisrp approved these changes

2022-04-06 12:15 UTC, Mai-Saad reviewed
Working fine now (note we will always exclude `window.jdgmSettings` even if the related plugin is not installed)

2022-04-06 12:29 UTC, Mai-Saad approved these changes

2022-04-11 17:12 UTC, merged