Enhancement/3929 remove revert uid for nonce actions in woocommerce compatiblity file
wp-media/wp-rocket pull request #4856
Opened 2022-03-25 08:21 UTC by jeawhanlee

## Description

Removed event `nonce_user_logged_out ` event and it's callback in `get_subscribed_events()` method.
Removed tests relating to `maybe_revert_uid_for_nonce_actions()`
Updated woocommerce dev dependency to 5.3

Fixes #3929 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

The Solution is in way different from the proposed one.

## How Has This Been Tested?

pending

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings

2022-03-25 16:11 UTC, Tabrisrp requested changes
This PR includes changes from another PR, it needs to be updated to remove those first

2022-03-29 16:07 UTC, Tabrisrp approved these changes

2022-05-25 05:30 UTC, vmanthos approved these changes
I checked if Ajax requests are working without the compatibility code using WooCommerce version >=5.3. This is working fine. 👍

As expected, the request will cause an error 403 with WP Rocket and WooCommerce <5.3.

2022-05-25 14:50 UTC, Tabrisrp commented
@jeawhanlee Can you fix the conflicts and merge the branch?

2022-05-25 16:25 UTC, merged