Fix missing AS missing DB tables issue
wp-media/wp-rocket pull request #4897
Opened 2022-04-06 08:22 UTC by engahmeds3ed

## Description

In some cases when client updates to our latest version 3.11.0.2, they face fatal error because one or more tables related to Action Scheduler isn't there, the error is like the following:-

```
[05-Apr-2022 12:36:29 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Table 'wordpress.wp_actionscheduler_actions' doesn't exist in /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php:86
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action()
#1 /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ActionFactory.php(105): ActionScheduler_ActionFactory->store()
#2 /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/functions.php(54): ActionScheduler_ActionFactory->recurring()
#3 /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php(51): as_schedule_recurring_action()
#4 /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/Queue.php(57): WP_Rocket\Eng in /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php on line 86
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Not groomed.

## How Has This Been Tested?

I need to test the queue runner by sending too much jobs from different groups and see if it'll handle our jobs with priority.

To test that you need to delete `wp_actionscheduler_actions` table from the DB and then check the site, with this PR you shouldn't see any fatal errors.

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-07 10:41 UTC, piotrbak commented
@engahmeds3ed If we detect this problem we should display not dismissable error (red) notice as follows:
**WP Rocket:** We detected missing database table related to Action Scheduler. Please visit the following URL(link) to recreate it, as it's needed for WP Rocket to work correctly.

2022-04-07 13:21 UTC, Tabrisrp commented
@piotrbak Action Scheduler automatically takes care of creating missing tables and displaying a notice for it https://github.com/wp-media/wp-rocket/blob/22b9aafffe55920aa40017007169fd3a3ab0849c/inc/Dependencies/ActionScheduler/classes/ActionScheduler_ListTable.php#L352-L371

2022-04-07 13:21 UTC, Tabrisrp approved these changes

2022-04-07 13:25 UTC, piotrbak commented
@Tabrisrp From what @engahmeds3ed told me, it's happening only on their admin page. That's why we need to have our own info notice there.

Let's talk about this on the standup

2022-04-08 09:00 UTC, engahmeds3ed commented
With this last change I did the following:-

- Show the admin notice in all pages except for the Action Scheduler tools page.
- Cache the number of AS tables for 24 hours.
- Remove this cache (transient) once any fatal error is detected.

2022-04-11 09:27 UTC, Mai-Saad approved these changes
Working as expected with the following notes:
- The error will be displayed on all pages except AS
- The error will be displayed even if RUCSS is not enabled 
- Fatal error will exist in debug.log while RUCSS is enabled till we click that link in the msg

2022-04-11 13:46 UTC, Tabrisrp requested changes

2022-04-11 13:46 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Settings.php
> +	 * @since 3.11.0.2
```suggestion
	 * @since 3.11.0.3
```

2022-04-11 13:46 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Settings.php
> +			__( '%1$s: We detected missing database table related to Action Scheduler. Please visit the following %2$sURL%3$s to recreate it, as it\'s needed for WP Rocket to work correctly.', 'rocket' ),
```suggestion
			__( '%1$s: We detected missing database table related to Action Scheduler. Please visit the following %2$sURL%3$s to recreate it, as it is needed for WP Rocket to work correctly.', 'rocket' ),
```

2022-04-11 13:46 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +	 * @since 3.11.0.2
```suggestion
	 * @since 3.11.0.3
```

2022-04-11 13:46 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +	 * @since 3.11.0.2
```suggestion
	 * @since 3.11.0.3
```

2022-04-11 13:47 UTC, Tabrisrp approved these changes

2022-04-11 13:56 UTC, merged

2022-04-17 16:37 UTC, umviajante commented
Hello guys. I am a WP Rocket user and subscriber. I can't find a link to open a support ticket.

I had to restore a backup of my blog and now even in the current version of WP Rocket I see an alert:

--------
WP Rocket: We detected missing database table related to Action Scheduler. Please visit the following URL to recreate it, as it is needed for WP Rocket to work correctly.

------

I don't know what to do... it looks like this table wasn't created or maybe it got lost when I restored my database. Now that WP Rocket is in the current version... I don't know what to do to solve the problem.

2022-04-17 16:39 UTC, umviajante commented
Ps.: after leaving the plugin active in the latest version, in addition to the alert in the control panel, the site starts showing 504 errors and seems to be related to the database problem.

2022-04-17 23:36 UTC, engahmeds3ed commented
> Hello guys. I am a WP Rocket user and subscriber. I can't find a link to open a support ticket.
> 
> I had to restore a backup of my blog and now even in the current version of WP Rocket I see an alert:
> 
> WP Rocket: We detected missing database table related to Action Scheduler. Please visit the following URL to recreate it, as it is needed for WP Rocket to work correctly.
> 
> I don't know what to do... it looks like this table wasn't created or maybe it got lost when I restored my database. Now that WP Rocket is in the current version... I don't know what to do to solve the problem.

You can reach support by sending an email to support@wp-rocket.me

What you want to do is to visit the url in this admin notice, which will redirect you to Action Scheduler page like the following:
```
https://example.org/wp-admin/tools.php?page=action-scheduler
```
**Note:** You need to replace example.org with your site domain.