Enhancement/2842 delete files in cache/min on theme switch
wp-media/wp-rocket pull request #4911
Opened 2022-04-11 11:48 UTC by jeawhanlee

## Description

Added a new AdminSubscriber class to to listen for `switch_theme `event and clean cache/min with `rocket_clean_minify()`

Fixes #2842 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Solution is in no way different from the proposed one.

## How Has This Been Tested?

- Enable Minify & Merge Options for both CSS & JS
- Activate a new theme
- Load new site in incognito with Ctrl+f5(windows) for force refresh
- check the wp-content/cache/min folder to see minified files generated
- Activate another theme
- check to see that previous minified files have been removed.

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2022-04-11 11:53 UTC, jeawhanlee commented
@Tabrisrp Do I need to write tests for this new class?

2022-04-11 13:20 UTC, Tabrisrp commented
@jeawhanlee Yes, we want to have automated tests as much as possible

2022-04-11 13:21 UTC, remyperona requested changes

2022-04-11 13:21 UTC, remyperona commented on inc/Engine/Optimization/Minify/AdminSubscriber.php
> +		rocket_clean_minify();
We should check here if at least minify CSS or minify JS is enabled, to avoid doing an unnecessary clean call if the options are not used. You can use the `Options_Data` class as a dependency to do that

2022-05-03 20:00 UTC, Tabrisrp requested changes

2022-05-03 20:00 UTC, remyperona commented on inc/Engine/Optimization/Minify/AdminSubscriber.php
> +		if ( ! (bool) $this->options->get( 'minify_js', 0 ) & ! (bool) $this->options->get( 'minify_css', 0 ) ) {
```suggestion
		if ( ! (bool) $this->options->get( 'minify_js', 0 ) && ! (bool) $this->options->get( 'minify_css', 0 ) ) {
```

2022-05-03 20:00 UTC, remyperona commented on tests/Integration/inc/Engine/Optimization/Minify/AdminSubscriber/cleanMinifyAll.php
> +	}
we're missing the call to the `switch_theme` action to validate the expectations

2022-05-31 14:38 UTC, piotrbak commented
@jeawhanlee this one is ready for review, right?

2022-05-31 15:07 UTC, jeawhanlee commented
@piotrbak Yes it is.

2022-05-31 19:30 UTC, remyperona approved these changes

2022-06-01 07:38 UTC, vmanthos commented
@piotrbak @jeawhanlee 

I tested this PR on:
* Single site
* Multisite

The files in `cache/min/` in both cases are removed. However, not all folders are.  For example, if there is a file:
`/wp-content/cache/min/1/wp-content/themes/twentytwenty/assets/js/something.js`

The file and the `/js/` folder will be removed but none of the parent folders will:
`/wp-content/cache/min/1/wp-content/themes/twentytwenty/assets/`

I'm guessing this is related to how `rocket_clean_minify()` works.

Is this something we need to handle as well?

I checked for an issue related to this but I didn't find one. Let me know if you want me to GitHub this.

2022-06-01 07:51 UTC, piotrbak commented
@vmanthos I think we're fine with directories, leaving them empty won't cause any issues. Do you see any bad sides of this?

2022-06-01 08:03 UTC, vmanthos commented
> Do you see any bad sides of this?

No, I don't other than increasing the number of inodes. But this shouldn't be a problem.

2022-06-01 08:03 UTC, vmanthos commented
> Do you see any bad sides of this?

No, I don't other than increasing the number of inodes. But this shouldn't be a problem.

2022-06-01 08:04 UTC, vmanthos approved these changes
Working as expected. 👍

2022-06-01 09:01 UTC, merged