Fix/4789 exclude is html on feed 2
wp-media/wp-rocket pull request #4922
Opened 2022-04-13 14:14 UTC by CrochetFeve0251

## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-13 14:57 UTC, CrochetFeve0251 commented
@Tabrisrp it looks good now

2022-04-14 14:58 UTC, Tabrisrp requested changes

2022-04-14 14:58 UTC, remyperona commented on tests/Fixtures/inc/classes/Buffer/Tests/canProcessBuffer.php
> +	'testShouldReturnTrueWhenIsFlux' => [
```suggestion
	'testShouldReturnTrueWhenIsFeed' => [
```

2022-04-14 14:58 UTC, remyperona commented on tests/Unit/inc/classes/Buffer/Tests/isFeedUri.php
> +		$GLOBALS['wp_rewrite'] = $wp_rewrite;
I would recommend to reset/unset the global in the `tearDown()` fixture, to make sure it's properly cleaned between each test.

2022-04-14 14:58 UTC, remyperona commented on tests/Unit/inc/classes/Buffer/Tests/isFeedUri.php
> +		$this->assertEquals($expected, $this->tests->is_feed_uri());
```suggestion
		$this->assertSame($expected, $this->tests->is_feed_uri());
```

2022-04-14 14:58 UTC, remyperona commented on tests/Unit/inc/classes/Buffer/Tests/canProcessBuffer.php
> +		$this->assertEquals($expected['buffer_results'], $this->tests->can_process_buffer($config['buffer']));
```suggestion
		$this->assertSame($expected['buffer_results'], $this->tests->can_process_buffer($config['buffer']));
```

2022-04-14 14:58 UTC, remyperona commented on tests/Unit/inc/classes/Buffer/Tests/canProcessBuffer.php
> +		$this->assertEquals($expected['error'], $this->tests->get_last_error());
```suggestion
		$this->assertSame($expected['error'], $this->tests->get_last_error());
```

2022-05-04 13:45 UTC, Tabrisrp commented on tests/Unit/inc/classes/Buffer/Tests/isFeedUri.php
> +		$GLOBALS['wp_rewrite'] = $wp_rewrite;
This is still missing

2022-05-04 13:46 UTC, Tabrisrp commented on tests/Unit/inc/classes/Buffer/Tests/canProcessBuffer.php
> +		$this->assertEquals($expected['error'], $this->tests->get_last_error());
☝🏼

2022-05-04 13:48 UTC, CrochetFeve0251 commented on tests/Unit/inc/classes/Buffer/Tests/canProcessBuffer.php
> +		$this->assertEquals($expected['error'], $this->tests->get_last_error());
@Tabrisrp ok changed it

2022-05-04 13:52 UTC, CrochetFeve0251 commented on tests/Unit/inc/classes/Buffer/Tests/isFeedUri.php
> +		$GLOBALS['wp_rewrite'] = $wp_rewrite;
@Tabrisrp changed

2022-05-05 16:02 UTC, remyperona approved these changes

2022-05-24 06:15 UTC, vmanthos commented
This is working as expected. 👍

Note: I also tested caching of REST API requests since the change in the code might have affected that as well.

2022-05-24 07:27 UTC, vmanthos approved these changes

2022-05-25 13:42 UTC, merged