Added constant in Avada subscriber to deactivate combined CSS and JS from Avada theme
wp-media/wp-rocket pull request #4928
Opened 2022-04-14 12:49 UTC by CrochetFeve0251

## Description

Fix an issue where Avada combined CSS file and prevent RUCSS to work sucessfully.
For that a constant `FUSION_DISABLE_COMPILERS` is set to prevent Avada from combining files.

Fixes #4881 
## Type of change 

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Yes

## How Has This Been Tested?

- [ ] Automated Test
- [ ] On my local env

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-02 16:24 UTC, Tabrisrp approved these changes

2022-05-02 16:25 UTC, Tabrisrp requested changes
Shouldn't we only set the constant if the RUCSS option is enabled?

2022-05-03 13:50 UTC, Tabrisrp approved these changes

2022-05-17 07:03 UTC, vmanthos approved these changes
Working as expected.

2022-05-17 11:27 UTC, piotrbak commented
@vmanthos Then it seems to be working as expected. I think we're fine here, you agree? 🆗

2022-05-17 11:30 UTC, vmanthos commented
> I think we're fine here, you agree? 

If what we mean to do is globally disable their combination when Remove Unused CSS is enabled, then yes.

Otherwise, if their combination should be active on pages where Remove Unused CSS is disabled, then we need to work on this.

2022-05-17 11:33 UTC, piotrbak commented
Ah! I got your point now, good catch! 

I believe that it's going to be an edge case and we should be fine here.

2022-05-19 13:45 UTC, merged