Enhancement/4905 minimalist blogger thirdparty class
wp-media/wp-rocket pull request #4951
Opened 2022-04-20 08:46 UTC by CrochetFeve0251

## Description

Fix a problem with jQuery in Minimalist Blogger when Delay JS is activated by excluding jQuery from delayed scripts when the theme is active.

Fixes #4905

## Type of change

Please delete options that are not relevant.

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [ ] Automated tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-03 18:28 UTC, Tabrisrp requested changes

2022-05-03 18:28 UTC, Tabrisrp commented on inc/ThirdParty/Themes/MinimalistBlogger.php
> +class MinimalistBlogger implements \WP_Rocket\Event_Management\Subscriber_Interface {
import the class here

2022-05-03 18:28 UTC, Tabrisrp commented on inc/ThirdParty/Themes/MinimalistBlogger.php
> +	 * @since 3.10.2
```suggestion
	 * @since 3.11.2
```

2022-05-03 18:28 UTC, Tabrisrp commented on inc/ThirdParty/Themes/MinimalistBlogger.php
> +	}
I'm thinking for this we should standardize the current theme check across all themes compatibility classes, using an interface and a parent abstract class implementing a method like `is_theme()`, and a class property that would be storing the theme name for each implementing class.

2022-05-05 18:16 UTC, remyperona requested changes

2022-05-05 18:16 UTC, Tabrisrp commented on inc/ThirdParty/Themes/ThirdpartyTheme.php
> +	}
```
protected static function is_theme( $theme = null ) {
		$theme = self::$theme instanceof WP_Theme ? self::$theme : wp_get_theme();

		return static::$theme_name === strtolower( $theme->get( 'Name' ) ) || static::$theme_name === strtolower( $theme->get_template() );
}
```

2022-05-05 18:38 UTC, CrochetFeve0251 commented on inc/ThirdParty/Themes/ThirdpartyTheme.php
> +	}
Remove all self

2022-05-12 13:21 UTC, engahmeds3ed requested changes

2022-05-12 13:21 UTC, engahmeds3ed commented on inc/ThirdParty/Themes/MinimalistBlogger.php
> +		return $events;
Applying returning early pattern to be something like that, what do u think?

```suggestion
		if ( ! self::is_theme() ) {
			return [];
		}
		
		return [
			'rocket_delay_js_exclusions' => 'exclude_jquery_from_delay_js',
		];
```

2022-05-12 13:21 UTC, engahmeds3ed commented on inc/ThirdParty/Themes/MinimalistBlogger.php
> +	 * @since 3.11.2
```suggestion
	 * @since 3.11.3
```

2022-05-12 13:21 UTC, engahmeds3ed commented on tests/Fixtures/inc/ThirdParty/Themes/MinimalistBlogger/excludeJqueryFromDelayJs.php
> +	'testShouldReturnExpected' => [
Can you add another test case for child themes that uses a parent of `minimalist-blogger` theme but with another name?

2022-05-12 14:38 UTC, Tabrisrp requested changes

2022-05-12 14:38 UTC, Tabrisrp commented on inc/ThirdParty/Themes/ThirdpartyTheme.php
> +		return ( str_contains( static::$theme_name, $theme->get_template() ) );
```suggestion
		return ( str_contains( static::$theme_name, strtolower( $theme->get_template() ) ) );
```
the template can have uppercase characters, so we need to make sure it's all lower case before using `str_contains()` as the function is case sensitive

2022-05-12 14:38 UTC, Tabrisrp commented on tests/Unit/inc/ThirdParty/Themes/MinimalistBlogger/excludeJqueryFromDelayJs.php
> +		$this->assertEquals($expected, $this->subscriber->exclude_jquery_from_delay_js($config['excluded']));
```suggestion
		$this->assertSame($expected, $this->subscriber->exclude_jquery_from_delay_js($config['excluded']));
```

2022-05-25 18:38 UTC, remyperona commented
You have a mix of different branches in here, a cleanup is needed

2022-06-06 09:33 UTC, piotrbak commented
@CrochetFeve0251 Per @Tabrisrp, seems we need a cleanup here, as there's a mix of branches.

2022-06-10 15:04 UTC, closed without merging