Fix/4231 remove params from url
wp-media/wp-rocket pull request #4978
Opened 2022-04-27 13:07 UTC by CrochetFeve0251

## Description
This fix an issue where some URL had in their params 

Fixes #4231

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated Tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-02 21:47 UTC, Tabrisrp requested changes

2022-05-02 21:47 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Optimization/AbstractOptimization/isExternalFile.php
> +	}
You can use the `get_reflective_method()` from the wp-media/phpunit `TestCaseTrait` to do this

2022-05-02 21:47 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Optimization/AbstractOptimization/isExternalFile.php
> +class Test_IsExternalFile extends \WP_Rocket\Tests\Unit\TestCase {
import the TestCase before using it

2022-05-03 14:55 UTC, Tabrisrp requested changes

2022-05-03 14:55 UTC, remyperona commented on tests/Unit/inc/Engine/Optimization/AbstractOptimization/isExternalFile.php
>  		$method->setAccessible(true);
`$method = $this->get_reflective_method($method, get_class($object));`

You don't need `$method->setAccessible(true);` anymore, it's already in `get_reflective_method()`

2022-05-03 14:55 UTC, remyperona commented on tests/Unit/inc/Engine/Optimization/AbstractOptimization/isExternalFile.php
> +		$this->assertEquals($expected, $this->callProtectedMethod($this->optimization, 'is_external_file', array
```suggestion
		$this->assertSame($expected, $this->callProtectedMethod($this->optimization, 'is_external_file', array
```

2022-05-03 15:13 UTC, CrochetFeve0251 commented on tests/Unit/inc/Engine/Optimization/AbstractOptimization/isExternalFile.php
>  		$method->setAccessible(true);
Oh ok

2022-05-03 18:55 UTC, Tabrisrp approved these changes

2022-05-19 14:14 UTC, Mai-Saad commented
@piotrbak the same problem occurs in CSS files with Minify CSS, Do we need to handle this in the current PR?
i.e 
`<link id='styles-aqua-bg' rel='stylesheet' href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css?test=123&test2=123&domain=https://new.rocketlabsqa.ovh">`

when we exclude `maxcdn.bootstrapcdn.com/font-awesome/`, it won't be excluded and will be minified.

2022-05-19 14:18 UTC, piotrbak commented
@Mai-Saad @CrochetFeve0251 Yes, let's do it in the same way for CSS Minification

2022-05-19 14:28 UTC, CrochetFeve0251 commented
@piotrbak @Mai-Saad the CSS minifer extends from the class I modified can you check if the change also worked for CSS urls?

2022-05-20 12:49 UTC, Mai-Saad approved these changes
As per discussion with @CrochetFeve0251 for external exclusion, we need either full URL or domain name and currently, both are working fine on the branch with JS/CSS while having/not having DN in the URL

2022-05-20 13:07 UTC, merged