Added filters to prevent the deletion from RUCSS
wp-media/wp-rocket pull request #4981
Opened 2022-04-28 08:11 UTC by CrochetFeve0251

## Description
Add two filters allowing control of the deletion from the RUCSS.

Fixes #4942

## Type of change

Please delete options that are not relevant.

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Test locally

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-20 15:02 UTC, Tabrisrp requested changes

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Database.php
>  	}
It's better to use the filter value directly in the method itself

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Database.php
>  	}
No need to b e updated as it's no longer used

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Database.php
>  	}
No need to b e updated as it's no longer used

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +		$delete_delay = apply_filters( 'rocket_rucss_css_delete_delay', 1 );
use the `is_rucss_deletion_activated()` here too instead

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +		$delete_delay = apply_filters( 'rocket_rucss_css_delete_delay', 1 );
use the `is_rucss_deletion_activated()` here too instead

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +		}
```suggestion
		$deletion_activated = $this->is_rucss_deletion_activated();

		if ( ! $deletion_activated ) {
			return;
		}
```
```suggestion
		if ( ! $this->is_rucss_deletion_activated() ) {
			return;
		}
```

Same for the other cases, it's not necessary to assign to a variable here

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +		}
```suggestion
		$deletion_activated = $this->is_rucss_deletion_activated();

		if ( ! $deletion_activated ) {
			return;
		}
```
```suggestion
		if ( ! $this->is_rucss_deletion_activated() ) {
			return;
		}
```

Same for the other cases, it's not necessary to assign to a variable here

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +	}
All of this is unnecessary, we already set the default values in the filter declaration

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +	}
All of this is unnecessary, we already set the default values in the filter declaration

2022-05-20 15:02 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +		return apply_filters( 'rocket_rucss_deletion_activated', true );
Add docblock for the filter https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters

And force a `bool` return

2022-05-20 15:02 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +		return apply_filters( 'rocket_rucss_deletion_activated', true );
Add docblock for the filter https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters

2022-05-20 15:02 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +	 * @return mixed|null
```suggestion
	 * @return bool
```

2022-05-20 15:02 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +	 * @return mixed|null
```suggestion
	 * @return bool
```

2022-05-20 15:02 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Database/Tables/Resources.php
> +	public function delete_old_items( $delete_delay = 1 ) {
No need to update this method, it's not used anymore

2022-05-20 15:02 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Database/Tables/Resources.php
> +	public function delete_old_items( $delete_delay = 1 ) {
No need to update this method, it's not used anymore

2022-05-20 15:02 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Database/Tables/UsedCSS.php
> +	public function delete_old_used_css( $delete_delay = 1 ) {
Use the filter value here, and make sure it's a positive int and not zero value before using it in the query

2022-05-20 15:02 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Database/Tables/UsedCSS.php
> +	public function delete_old_used_css( $delete_delay = 1 ) {
Use the filter value here, and make sure it's a positive int and not zero value before using it in the query

2022-06-14 12:57 UTC, CrochetFeve0251 commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
> +		$delete_delay = apply_filters( 'rocket_rucss_css_delete_delay', 1 );
@Tabrisrp the idea was to let the user control the period of time `is_rucss_deletion_activated` returns a boolean.

2022-07-18 17:29 UTC, Tabrisrp approved these changes

2022-09-05 12:33 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the PR.
Clear used CSS of this URL from page preview is not working in the following cases:
1- Old page whose used CSS > 1 month while the related filter `rocket_rucss_delete_interval` is set to 0
2- When the filter `rocket_rucss_deletion_enabled` is set to false then we try clear used CSS of this post
Can you please check?

2022-09-06 06:08 UTC, Mai-Saad commented
@CrochetFeve0251 Clear used CSS of this URL is working fine now. But if `rocket_rucss_deletion_enabled` is set to false, the edit/quick edit post will clear the used CSS of that post. Can you please check?

2022-09-07 03:26 UTC, mostafa-hisham approved these changes

2022-09-09 09:18 UTC, Mai-Saad approved these changes
Working as expected, failed test due to issue on the trunk.
Note:
Using invalid values for filter i.e Null, "" ,...etc,  the filter will prevent deletion of used CSS (not the default behavior which allows deletion)   => fine as is as per discussion with @piotrbak 
[testrail-report-409.pdf](https://github.com/wp-media/wp-rocket/files/9534095/testrail-report-409.pdf)

2022-09-12 09:44 UTC, merged