Fix problem with RUCSS and ConvertPlug
wp-media/wp-rocket pull request #5002
Opened 2022-05-03 15:38 UTC by CrochetFeve0251

## Description

Fix a conflit between  RUCSS and ConvertPlug.
This has been fixed by excluding the CSS in question in a thirdparty class.

Fixes #4984

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated Tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-03 16:03 UTC, Tabrisrp requested changes

2022-05-03 16:03 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/ConvertPlug/excludedFromRucss.php
> + * @covers  \WP_Rocket\ThirdParty\Plugins\Ecommerce\WooCommerceSubscriber::maybe_revert_uid_for_nonce_actions
This needs to refer to the correct method

2022-05-03 16:03 UTC, Tabrisrp commented on tests/Unit/inc/ThirdParty/Plugins/ConvertPlug/excludedFromRucss.php
> +
missing the cover and group annotations

2022-05-03 16:05 UTC, Tabrisrp requested changes

2022-05-03 16:05 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/ConvertPlug.php
> +		$excluded[] = '.content-';
Shouldn't the value be `cp-form-css` instead?

2022-05-04 13:43 UTC, Tabrisrp approved these changes

2022-05-04 17:16 UTC, piotrbak approved these changes

2022-05-04 17:17 UTC, piotrbak commented
@Tabrisrp This one too 🙏

2022-05-04 17:26 UTC, merged