Closes #4980 Refactor Kinsta thirdparty class
wp-media/wp-rocket pull request #5011
Opened 2022-05-05 11:56 UTC by CrochetFeve0251

## Description
This PR is here to fix two problems:
- Refactor Kinsta into new architecture
- Fix a problem where cache wasn't empty after RUCSS.

For the first issue we deleted old code and create a thirdparty class in the new architecture.
For the second issue we hooked `rocket_clean_kinsta_post_cache` method to two events:
-   `rocket_rucss_complete_job_status`
-   `rocket_rucss_after_clearing_usedcss` 

Fixes #4980 

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-05 11:57 UTC, CrochetFeve0251 commented
@Tabrisrp I would need you help to do integration tests on this one cause I got no idea how to do it and didn't found anything similar in others Thirdparty classes.

2022-05-05 20:32 UTC, Tabrisrp commented
@CrochetFeve0251 For the integration tests, you can do as it is done for other hostings, adding an entry in the `integration/bootstrap.php` file, and a new test in `composer.json`

2022-05-05 20:32 UTC, Tabrisrp commented
@CrochetFeve0251 For the integration tests, you can do as it is done for other hostings, adding an entry in the `integration/bootstrap.php` file, and a new test in `composer.json`

2022-05-06 13:26 UTC, Tabrisrp requested changes

2022-05-06 13:26 UTC, Tabrisrp commented on inc/ThirdParty/Hostings/Kinsta.php
> +<?php
In this file:
- You can use the `WP_Rocket\ThirdParty\ReturnTypesTrait` methods to return  `false` or an empty array where necessary without creating new methods
- You can remove all `@author` references
- You can remove all `rocket_` prefixes from the methods names

2022-05-06 13:26 UTC, remyperona commented on inc/ThirdParty/Hostings/Kinsta.php
> +		wp_remote_get(
```suggestion
		wp_safe_remote_get(
```

2022-05-06 13:26 UTC, Tabrisrp commented on inc/ThirdParty/Hostings/Kinsta.php
> +		wp_remote_get(
```suggestion
		wp_safe_remote_get(
```

2022-05-06 13:26 UTC, Tabrisrp commented on inc/ThirdParty/Hostings/Kinsta.php
> +	public function display_error_notice() {
This notice should be displayed only if the global `$kinsta_cache` is not set

2022-05-09 17:12 UTC, remyperona approved these changes

2022-05-12 12:58 UTC, engahmeds3ed requested changes
@Tabrisrp do we need to deprecate old functions in the deleted kinsta file?

2022-05-12 12:58 UTC, engahmeds3ed commented on composer.json
> +		  "@test-integration-wpengine",
plz adjust those spacings

2022-05-12 12:58 UTC, engahmeds3ed commented on composer.json
> +		  "@test-integration-convertplug"
here too

2022-05-12 13:24 UTC, Tabrisrp commented
Yes indeed we should

2022-05-31 12:25 UTC, vmanthos approved these changes
I tested:
* the original issue described in #4980
* the refactored class to make sure our compatibility works the way it used to before the latest changes.

Both are working as expected. 👍

2022-05-31 13:29 UTC, merged