Fixes #5005 Use WP cron for RUCSS pending jobs
wp-media/wp-rocket pull request #5014
Opened 2022-05-05 15:25 UTC by Tabrisrp

## Description

TBA

Fixes #5005

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [ ] TBA

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-09 04:27 UTC, engahmeds3ed requested changes
I think we need also to cancel the old pending Action Scheduler recurring action with update.

Also I believe we need to unschedule the CRONs with update also as maybe the CRON runs when we still upgrade the code and this may cause errors.

What do you think?

2022-05-09 04:27 UTC, engahmeds3ed commented on inc/Engine/Optimization/RUCSS/Admin/Subscriber.php
>  use WP_Rocket\Logger\Logger;
Not used anymore

2022-05-09 13:19 UTC, remyperona commented
> Also I believe we need to unschedule the CRONs with update also as maybe the CRON runs when we still upgrade the code and this may cause errors.

The WP cron events can't be triggered during update, as when you start an update there is the maintenance mode enabled, which prevents access to the website .

2022-05-09 14:58 UTC, engahmeds3ed commented
@Tabrisrp Good point.

What about:
> I think we need also to cancel the old pending Action Scheduler recurring action with update.
not to have one hook that is fired from two locations, what do u think?

2022-05-09 15:00 UTC, remyperona commented
my only worry about that would be to trigger the DB error by doing this, what do you think?

2022-05-10 17:30 UTC, engahmeds3ed commented
Here: https://github.com/wp-media/wp-rocket/blob/22b9aafffe55920aa40017007169fd3a3ab0849c/inc/Dependencies/ActionScheduler/classes/data-stores/ActionScheduler_DBStore.php#L449-L452

when the `wpdb` can't update the action to make its status `CANCELLED` it throws this error.

With update, we need to call [this method](https://github.com/wp-media/wp-rocket/blob/b1d16b7bd8ddfb0a998330fea09cd3fd687fb92f/inc/Engine/Optimization/RUCSS/Controller/Queue.php#L40-L47) but add it inside `try catch` so we can catch such this error, what do u think @Tabrisrp ?

2022-05-10 19:24 UTC, Tabrisrp commented
Looks good with the try/catch 👍🏼

2022-05-10 20:11 UTC, engahmeds3ed approved these changes

2022-05-17 20:27 UTC, Mai-Saad commented
@Tabrisrp Currently user may be stuck in in-progress status till entries are manually deleted from database in the following scenario:
1- On the PR, while preload is enabled, enable RUCSS => make sure to have some pending status in the used CSS table
2- Delete the Actions table of AS => make sure to have some in-progress items in the used CSS table
3- In the admin dashboard, refresh then click on the URL in AS error msg => Actions table is recreated but empty
4- refresh admin or access FE => the in-progress status in used CSS won't change
Can you please check this case?
![Screenshot from 2022-05-17 22-20-08](https://user-images.githubusercontent.com/76941962/168904117-175564a2-5f1d-486a-8c5e-ea8bba19ddd7.png)

2022-05-17 20:57 UTC, Tabrisrp commented
How do you delete the AS tables? Manually? This is an action that is not done by the plugin automatically in any case as far as I know

2022-05-17 20:58 UTC, piotrbak commented
Yes, if it's not done automatically, then we're fine and we can treat it as an edge case

2022-05-17 21:07 UTC, Mai-Saad commented
> How do you delete the AS tables? Manually? This is an action that is not done by the plugin automatically in any case as far as I know

@Tabrisrp Yes, it is deleted manually in the current scenario ( before there was a reported [issue](https://github.com/wp-media/wp-rocket/pull/4897), where AS was deleted for some reasons and caused an error => not sure how this can be reproduced automatically though)

2022-05-17 21:10 UTC, engahmeds3ed commented
The only case we found with real customers is that when installing wpr the AS tables are not created (whole tables).
We have transient that has AS tables count, we can check on it before changing the status to in-progress.
But yes, it's very edge case.

2022-05-18 09:41 UTC, Mai-Saad approved these changes
The main error was not reproducible, and as no further changes are needed for the edge case then we are good here.
[testrail-report-386.pdf](https://github.com/wp-media/wp-rocket/files/8715105/testrail-report-386.pdf)

2022-05-18 13:50 UTC, merged