Closes #5003 on respecting site trailing slash
wp-media/wp-rocket pull request #5061
Opened 2022-05-19 13:44 UTC by jeawhanlee

## Description

Closes issue on respect site trailing slash.

Fixes #5003 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

There are some differences from the proposed.

## How Has This Been Tested?

Tested locally.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2022-05-19 20:11 UTC, Tabrisrp requested changes
It is unnecessary to store the permalink structure into the WP Rocket options array. In `get_rocket_config_file()`, we can directly use `get_option( 'permalink_structure' )` to store the current permalink structure.

And we can use the `permalink_structure_changed` [hook](https://developer.wordpress.org/reference/hooks/permalink_structure_changed/) to update the config file when the structure is changed.

This hook and callback can be added in a new `Engine\Cache\Config\Subscriber` class, instead of adding it to the `Settings` class which is unrelated.

The function `rocket_generate_config_file()` can be used to re-generate the config file.

2022-05-19 20:11 UTC, Tabrisrp commented on inc/classes/Buffer/class-cache.php
> +		$url      = $protocol . $host . rtrim( $clean_request_uri, '/' ) . $permalink_last_char . $this->tests->get_query_string();
The clean request uri variable doesn't contain the full original URL requested

2022-05-20 21:43 UTC, Tabrisrp requested changes

2022-05-20 21:43 UTC, remyperona commented on inc/classes/Buffer/class-cache.php
> +		$request_uri = $this->tests->get_raw_request_uri();
```suggestion
		$request_uri = $this->tests->get_request_uri_base();
```

2022-05-24 13:30 UTC, Tabrisrp requested changes

2022-05-24 13:30 UTC, Tabrisrp commented on inc/classes/Buffer/class-cache.php
> +		$host                = $this->config->get_host() . ':10003';
```suggestion
		$host                = $this->config->get_host();
```

2022-05-24 13:45 UTC, Tabrisrp approved these changes

2022-05-25 10:25 UTC, vmanthos commented
@jeawhanlee This is working as expected for URLs with paths, e.g. `example.com/hello-world/` but for the homepage, it causes a redirect loop when the permalinks don't have a trailing `/`:
![](https://i.vgy.me/HBmOt9.jpg)

In the following check:
https://github.com/wp-media/wp-rocket/blob/af547d77ef69a773c62c6113f38757c4983bff96/inc/classes/Buffer/class-cache.php#L701-L704

the `$request_uri_last_char` will always be `/` and the `$permalink_last_char` will be empty.

The two characters that are compared are never equal and we don't bail out and the redirect takes place every time causing the loop.

Can you please look into this?

PS: Thanks to @Mai-Saad for bringing this to my attention.

2022-05-25 11:00 UTC, vmanthos commented
Also, the following scenarios are causing issues:

**Custom permalink without a trailing `/`**

1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
2. Visiting the homepage `https://example.com/?location=Paris` causes a redirect to `https://example.comlocation=Paris` and that request is canceled/failed.
3. Visiting a page with a path `https://example.com/?location=Paris` results in `error 404`: `https://example.com/hello-worldlocation=`

**Custom permalink with a trailing `/`**

1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
2. Visiting a page with a path `https://example.com/hello-world?location=Paris` causes a redirect to `https://example.com/hello-world/location=Paris` and this results in an `error 404`.

2022-05-25 11:24 UTC, CrochetFeve0251 commented
@jeawhanlee looks like the query 

> Also, the following scenarios are causing issues:
> 
> **Custom permalink without a trailing `/`**
> 
>     1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
> 
>     2. Visiting the homepage `https://example.com/?location=Paris` causes a redirect to `https://example.comlocation=Paris` and that request is canceled/failed.
> 
>     3. Visiting a page with a path `https://example.com/?location=Paris` results in `error 404`: `https://example.com/hello-worldlocation=`
> 
> 
> **Custom permalink with a trailing `/`**
> 
>     1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
> 
>     2. Visiting a page with a path `https://example.com/hello-world?location=Paris` causes a redirect to `https://example.com/hello-world/location=Paris` and this results in an `error 404`.

Look like the method `$this->tests->get_query_string()` doesn't returns the `?` I think adding it before the call of the function will solve the problem in this comment.

2022-05-25 12:04 UTC, jeawhanlee commented
> Also, the following scenarios are causing issues:
> 
> **Custom permalink without a trailing `/`**
> 
> 1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
> 2. Visiting the homepage `https://example.com/?location=Paris` causes a redirect to `https://example.comlocation=Paris` and that request is canceled/failed.
> 3. Visiting a page with a path `https://example.com/?location=Paris` results in `error 404`: `https://example.com/hello-worldlocation=`
> 
> **Custom permalink with a trailing `/`**
> 
> 1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
> 2. Visiting a page with a path `https://example.com/hello-world?location=Paris` causes a redirect to `https://example.com/hello-world/location=Paris` and this results in an `error 404`.

Thanks @vmanthos will work on these fixes.

2022-05-25 12:05 UTC, jeawhanlee commented
> @jeawhanlee looks like the query
> 
> > Also, the following scenarios are causing issues:
> > **Custom permalink without a trailing `/`**
> > ```
> > 1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
> > 
> > 2. Visiting the homepage `https://example.com/?location=Paris` causes a redirect to `https://example.comlocation=Paris` and that request is canceled/failed.
> > 
> > 3. Visiting a page with a path `https://example.com/?location=Paris` results in `error 404`: `https://example.com/hello-worldlocation=`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Custom permalink with a trailing `/`**
> > ```
> > 1. Usage of a query string for which we create cache, e.g. `location` added to the **Cache Query strings** text area in the Advanced Rules tab.
> > 
> > 2. Visiting a page with a path `https://example.com/hello-world?location=Paris` causes a redirect to `https://example.com/hello-world/location=Paris` and this results in an `error 404`.
> > ```
> 
> Look like the method `$this->tests->get_query_string()` doesn't returns the `?` I think adding it before the call of the function will solve the problem in this comment.

Correct @CrochetFeve0251

2022-05-26 15:51 UTC, Tabrisrp approved these changes

2022-06-01 06:06 UTC, vmanthos commented
@jeawhanlee I tested the branch after the latest changes and found that the query strings redirects are working and the redirect loop is fixed. 👏

However, when the permalinks don't have a trailing `/`, visiting a URL that has one, e.g. `https://vasilis.rocketlabsqa.ovh/hello-world/` doesn't redirect to `https://vasilis.rocketlabsqa.ovh/hello-world` which would be the expected outcome. (https://youtu.be/VdfwV1PdOq8)

@piotrbak Should we consider anchor links as well when respecting the trailing `/`?
Currently, we aren't: https://youtu.be/wDKHP8fQZ-E

2022-06-01 07:48 UTC, piotrbak commented
@vmanthos I think we can skip redirecting anchors. We need to make sure that redirect loop won't happen there though

2022-06-06 09:29 UTC, piotrbak commented
@jeawhanlee @vmanthos What's the state of this PR? From what you mentioned, it still need some love 🤔 Is that right?
```
However, when the permalinks don't have a trailing /, visiting a URL that has one, e.g. https://vasilis.rocketlabsqa.ovh/hello-world/ doesn't redirect to https://vasilis.rocketlabsqa.ovh/hello-world which would be the expected outcome. (https://youtu.be/VdfwV1PdOq8)
```

2022-06-06 09:35 UTC, jeawhanlee commented
@piotrbak I was with @vmanthos on this last week and I found out the branch on his test site was not updated. So I guess he'll check this and revert when he has some time.

2022-06-06 10:07 UTC, piotrbak commented
Thank you!

2022-06-07 06:49 UTC, vmanthos commented
@piotrbak @jeawhanlee 

This is working as expected. Please find my notes below.

When testing [ignored query strings](https://docs.wp-rocket.me/article/971-caching-query-strings#ignored-parameters), e.g. `utm_source` and the following conditions apply:
* Permalinks include a trailing `/`
* The visited URL doesn't have a trailing slash:
`https://domain.con/hello-world?utm_source=1&location=Paris`

the redirection URL doesn't include the ignored parameter `utm_source`:
`https://domain.con/hello-world/?location=Paris`

When visiting the URL with a trailing slash `utm_source`  is preserved:
https://vasilis.rocketlabsqa.ovh/hello-world/?utm_source=1&location=Thessaloniki

This is happening with `trunk` as well. We should preserve the ignored parameters in case these are handled by JavaScript after the page loads.

This is a new issue. Do you want it handled in the current PR or do you want me to create a new GitHub issue?

2022-06-07 08:51 UTC, piotrbak commented
@vmanthos If that's not a regression, we can create an issue and see the feedback. I think we're fine then.

2022-06-07 08:52 UTC, vmanthos approved these changes
Working as expected!

2022-06-08 14:54 UTC, merged