Feature/4932 create cron and scheduled actions
wp-media/wp-rocket pull request #5070
Opened 2022-05-23 07:35 UTC by CrochetFeve0251

## Description

Add the queue runner and the task to preload url.

Fixes #4932 

## Type of change

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Is the solution different from the one proposed during the grooming?

Yes.

## How Has This Been Tested?
- [ ] Automated Test

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-23 08:49 UTC, CrochetFeve0251 commented
@Tabrisrp waiting for the PR to fix the develop branch to be merge to fix bugs that are already fixed on develop

2022-06-08 15:20 UTC, Tabrisrp requested changes

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/LoadInitialSitemap.php
> +		$urls = apply_filters( 'rocket_preload_load_custom_urls', [] );
add the docblock for the filter

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +use WP_Rocket\Engine\Preload\Database\Queries\RocketCache;
```suggestion
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		wp_remote_get(
```suggestion
		wp_safe_remote_get(
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +			wp_remote_get(
```suggestion
			wp_safe_remote_get(
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +	public function get_mobile_user_agent_prefix() {
```suggestion
	private function get_mobile_user_agent_prefix() {
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +			$https = is_ssl() && get_rocket_option( 'cache_ssl' ) ? '-https' : '';
```suggestion
			$https = is_ssl() && $this->options->get( 'cache_ssl' ) ? '-https' : '';
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/Queue.php
> -use ActionScheduler_Store;
should this import be removed?

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		$file_cache_path = rocket_get_constant( 'WP_ROCKET_CACHE_PATH' ) . $url['host'] . strtolower( $url['path'] . $url['query'] ) . 'index' . $mobile . $https . '.html';
the `$mobile` variable seems useless here?

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Cron/Subscriber.php
> +use WP_Rocket\Engine\Preload\Database\Queries\RocketCache;
```suggestion
use WP_Rocket\Engine\Preload\Database\Queries\Cache;
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Frontend/Subscriber.php
>  	 * @param FetchSitemap $parse_sitemap controller parsing the sitemap.
```suggestion
	 * @param FetchSitemap $fetch_sitemap controller fetching the sitemap.
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Frontend/Subscriber.php
> +	public function __construct( FetchSitemap $parse_sitemap, PreloadUrl $preload_controller ) {
```suggestion
	public function __construct( FetchSitemap $fetch_sitemap, PreloadUrl $preload_controller ) {
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Frontend/Subscriber.php
>  	protected $parse_sitemap;
```suggestion
	protected $fetch_sitemap;
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Frontend/Subscriber.php
> +		$this->parse_sitemap      = $parse_sitemap;
```suggestion
		$this->fetch_sitemap      = $fetch_sitemap;
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Frontend/Subscriber.php
>  		$this->parse_sitemap->parse_sitemap( $url );
```suggestion
		$this->fetch_sitemap->parse_sitemap( $url );
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Cron/Subscriber.php
> +			'rocket_load_preload_url'              => 'load_preload_url',
```suggestion
			'rocket_preload_process_pending'              => 'process_pending_urls',
```

2022-06-08 15:20 UTC, Tabrisrp commented on inc/Engine/Preload/Cron/Subscriber.php
> +		}
We can remove this, so that the clean still occurs when the option is disabled to avoid stale data

2022-06-08 15:20 UTC, Tabrisrp commented on inc/Engine/Preload/Cron/Subscriber.php
> +	public function load_preload_url() {
```suggestion
	public function process_pending_urls() {
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Cron/Subscriber.php
> +			wp_next_scheduled( 'rocket_load_preload_url' )
```suggestion
			wp_next_scheduled( 'rocket_preload_process_pending' )
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Cron/Subscriber.php
> +			wp_clear_scheduled_hook( 'rocket_load_preload_url' );
```suggestion
			wp_clear_scheduled_hook( 'rocket_preload_process_pending' );
```

2022-06-08 15:20 UTC, remyperona commented on inc/Engine/Preload/Cron/Subscriber.php
> +		if ( wp_next_scheduled( 'rocket_load_preload_url' ) ) {
```suggestion
		if ( wp_next_scheduled( 'rocket_preload_process_pending' ) ) {
```

2022-06-08 15:20 UTC, Tabrisrp commented on inc/Engine/Preload/Cron/Subscriber.php
> +		$schedules['rocket_load_preload_url'] = [
```suggestion
		$schedules['rocket_preload_process_pending'] = [
```

2022-06-08 15:20 UTC, Tabrisrp commented on inc/Engine/Preload/Cron/Subscriber.php
> +		wp_schedule_event( time(), 'rocket_load_preload_url', 'rocket_load_preload_url' );
```suggestion
		wp_schedule_event( time(), 'rocket_preload_process_pending', 'rocket_preload_process_pending' );
```

2022-06-08 15:38 UTC, CrochetFeve0251 commented on inc/Engine/Preload/Controller/Queue.php
> -use ActionScheduler_Store;
It is used on the last function

2022-06-09 13:28 UTC, Tabrisrp requested changes

2022-06-09 13:28 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Preload/Cron/Subscriber/addInterval.php
> +		Functions\when('rocket_get_constant')->returnArg(2);
This function should already be mocked automatically

2022-06-09 13:28 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Preload/Cron/Subscriber/addInterval.php
> +		Functions\when('esc_html__')->returnArg(1);
Use the global stub translations function instead

2022-06-09 13:28 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Preload/Controller/PreloadUrl/processPendingJobs.php
> +		$this->options = \Mockery::mock(Options_Data::class);
```suggestion
		$this->options = Mockery::mock(Options_Data::class);
```

2022-06-09 13:28 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Preload/Controller/PreloadUrl/processPendingJobs.php
> +		$this->queue = \Mockery::mock(Queue::class);
```suggestion
		$this->queue = Mockery::mock(Queue::class);
```

2022-06-09 13:28 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Common/Queue/PreloadQueueRunner/addWpCronSchedule.php
> +		Functions\when('__')->returnArg();
use global stub translations function

2022-06-09 16:37 UTC, remyperona approved these changes

2022-06-09 16:38 UTC, merged