Enhancement/5041 rucss compatibility with inline related posts dynamic selectors
wp-media/wp-rocket pull request #5077
Opened 2022-05-25 10:08 UTC by jeawhanlee

## Description

Preserve dynamic inline styles for inline related posts plugin.

Fixes #5041 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

This solution is in no way different from the proposed.

## How Has This Been Tested?

- Install & Activate inline related posts.
- Activate RUCSS
- Created Identical Posts.
- Then inspect page to see that dynamic inline styles are preserved

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-25 18:58 UTC, Tabrisrp requested changes

2022-05-25 18:58 UTC, remyperona commented on inc/ThirdParty/Plugins/InlineRelatedPosts.php
> +		return $events;
```suggestion
		return [
		    'rocket_rucss_inline_content_exclusions' => 'exclude_inline_from_rucss',
		];
```

2022-05-25 18:58 UTC, remyperona commented on tests/Integration/inc/ThirdParty/Plugins/InlineRelatedPosts/excludeInlineFromRucss.php
> +	}
This is not necessary

2022-05-25 18:58 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Plugins/InlineRelatedPosts/excludeInlineFromRucss.php
> +		$this->assertSame( $expected, apply_filters( 'rocket_rucss_inline_content_exclusions', $inline_related_posts->exclude_inline_from_rucss($config['excluded'] ) ) );
You need to either use the filter, or the method call, but not both at the same time in the integration test.

2022-05-26 15:52 UTC, remyperona approved these changes

2022-05-30 10:57 UTC, Mai-Saad approved these changes
Working as expected

2022-05-30 16:33 UTC, merged