Added new fix for v1 google font
wp-media/wp-rocket pull request #5090
Opened 2022-05-27 08:38 UTC by CrochetFeve0251

## Description

Fix a problem with the loading from vv1  google fonts

Fixes #4967

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [ ] Automated Test

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-27 09:32 UTC, jeawhanlee approved these changes

2022-05-27 13:33 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +			'<link\s+([^>]+[\s"\'])?rel\s*=\s*[\'"]((preconnect)|(dns-prefetch)|(stylesheet)|(preload))[\'"]([^>]+)?\/?>',
shouldn't stylesheet and preload links be removed in `remove_used_css_from_html()`?

2022-05-30 14:50 UTC, CrochetFeve0251 commented
@vmanthos ok the problem came from the fact one of the testing tags didn't had any quotes: `<link href="https://fonts.googleapis.com/css?display=swap&family=Montserrat:400,600,700" rel=stylesheet>`.
I discussed with @piotrbak about it and we decided to handle that case too.
I changed the code so now we can accept missing quotes on `rel=stylesheet`, `rel=preload` and `as=style`

2022-05-30 14:54 UTC, Tabrisrp requested changes

2022-05-30 14:54 UTC, Tabrisrp commented on licence-data.php
> -}
This shouldn't be modified

2022-05-30 14:56 UTC, CrochetFeve0251 commented on licence-data.php
> -}
Oh I didn't saw I pushed that

2022-05-30 14:57 UTC, CrochetFeve0251 commented on licence-data.php
> -}
Ok it should be back there

2022-05-30 14:58 UTC, Tabrisrp approved these changes

2022-05-30 16:42 UTC, jeawhanlee approved these changes

2022-05-31 05:03 UTC, vmanthos approved these changes
This is working as expected now. 👍

2022-05-31 07:48 UTC, merged