Closes #5115 - New Preload: thirdpary classes
wp-media/wp-rocket pull request #5120
Opened 2022-06-08 12:35 UTC by CrochetFeve0251

## Description

Refactor all Thirdparties linked too the preload in the old architecture to the new one.
For that theses thirdparties got refactored:
- SEOPress.
- Jetpack.
- Rank Math SEO
- All in One SEO.

Fixes #5115

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested

- [ ] Automated tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-14 08:08 UTC, jeawhanlee reviewed
I think we should have all the SEO Related thirdparty classes in the SEO folder and also update namespaces.
- [AllInOneSEOPack](https://github.com/wp-media/wp-rocket/blob/task/preload-thirdpary-classes/inc/ThirdParty/Plugins/AllInOneSEOPack.php)
- [Jetpack.php](https://github.com/wp-media/wp-rocket/blob/task/preload-thirdpary-classes/inc/ThirdParty/Plugins/Jetpack.php)
- [RankMathSEO.php](https://github.com/wp-media/wp-rocket/blob/task/preload-thirdpary-classes/inc/ThirdParty/Plugins/RankMathSEO.php)

2022-06-14 08:08 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/AllInOneSEOPack.php
> +		if ( ! $aioseo_v3 && ! $aioseo_v4 ) {
Do we need to do this check here again, since we already have one on the subscribed events method.

2022-06-14 19:49 UTC, Tabrisrp requested changes
On the jetpack file, only keep the method that is adding the sitemap URL to the preload. All the rest is either not necessary anymore, or not working correctly. The previous compatibility file wasn't ever loaded because of this

2022-06-14 19:49 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		}
```suggestion
```
Option won't exist anymore with the new system

2022-06-14 19:49 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/SEO/RankMathSEO.php
> +	}
```suggestion
	public function add_sitemap_preload( $sitemaps ) { // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals
		$sitemaps[] = Router::get_base_url( 'sitemap_index.xml' );

		return $sitemaps;
	}
```

2022-06-14 19:49 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/SEO/SEOPress.php
> +		}
```suggestion
		$sitemaps[] = get_home_url() . '/sitemaps.xml';
```

2022-06-14 19:49 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/SEO/TheSEOFramework.php
> +		if ( $this->option->get( 'tsf_xml_sitemap', false ) ) {
```suggestion
```

2022-06-14 19:49 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/SEO/TheSEOFramework.php
> +		}
```suggestion
```

2022-06-15 10:30 UTC, jeawhanlee reviewed
What do you think about this?

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +
```suggestion
/**
     * All in one pack version
     *
     * @var bool
     */
    private $aioseo_v3;

    /**
     * All in one pack version
     *
     * @var bool
     */
    private $aioseo_v4;
```

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		$this->option = $option;
```suggestion
		$this->option = $option;
		$this->aioseo_v3 = defined( 'AIOSEOP_VERSION' );
        $this->aioseo_v4 = defined( 'AIOSEO_VERSION' ) && function_exists( 'aioseo' );
```

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		if ( ! $aioseo_v3 && ! $aioseo_v4 ) {
```suggestion
		if ( ! $this->aioseo_v3 && ! $this->aioseo_v4 ) {
```

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		$aioseo_v4 = defined( 'AIOSEO_VERSION' ) && function_exists( 'aioseo' );
```suggestion
```

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		if ( $aioseo_v3 && ! $aioseo_v4 ) {
```suggestion
		if ( $this->aioseo_v3 && ! $this->aioseo_v4 ) {
```

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		) {
```suggestion
		if (
            ( ! $this->aioseo_v4 && ! $sitemap_enabled ) ||
            ( $this->aioseo_v4 && ! aioseo()->options->sitemap->general->enable )
        ) {
```

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		if ( $aioseo_v3 ) {
```suggestion
		if ( $this->aioseo_v3 ) {
```

2022-06-15 10:30 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/SEO/AllInOneSEOPack.php
> +		} elseif ( $aioseo_v4 ) {
```suggestion
		} elseif ( $this->aioseo_v4 ) {
```

2022-06-15 12:35 UTC, CrochetFeve0251 commented
> What do you think about this?

From the state of the code and the architecture that would be nice. 
However there are two problems to that:
- I have no idea how to test it with integration tests if we move the check in the constructor as we need to tests both behaviors and they are depending on if the function is existing or not.
- The method to subscribe event is static so we cannot call $this inside it.

2022-06-15 12:45 UTC, jeawhanlee commented
True - the static method.

2022-06-15 15:25 UTC, Tabrisrp requested changes
Also remove the cookie law related code from jetpack

2022-06-15 15:34 UTC, CrochetFeve0251 commented
> Also remove the cookie law related code from jetpack

Oh ok left it as it had nothing to do with sitemap

2022-06-16 17:48 UTC, Tabrisrp approved these changes

2022-06-17 07:44 UTC, merged