Closes #4905 Minimalist blogger thirdparty class for delay JS compatibility
wp-media/wp-rocket pull request #5138
Opened 2022-06-10 14:50 UTC by CrochetFeve0251

## Description

Fix a problem with jQuery in Minimalist Blogger when Delay JS is activated by excluding jQuery from delayed scripts when the theme is active.

Fixes #4905

## Type of change

Please delete options that are not relevant.

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Automated tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-06-10 15:03 UTC, CrochetFeve0251 commented
@Tabrisrp @piotrbak the cleaned branche

2022-06-10 15:13 UTC, Tabrisrp requested changes
One change to make the method name more explicit

2022-06-10 15:13 UTC, Tabrisrp commented on inc/ThirdParty/Themes/ThirdpartyTheme.php
> +	protected static function is_theme( $theme = null ) {
```suggestion
	protected static function is_current_theme( $theme = null ) {
```

2022-06-10 15:13 UTC, Tabrisrp commented on inc/ThirdParty/Themes/MinimalistBlogger.php
> +		if ( ! self::is_theme() ) {
```suggestion
		if ( ! self::is_current_theme() ) {
```

2022-06-10 15:17 UTC, Tabrisrp approved these changes

2022-09-02 11:39 UTC, Mai-Saad commented
@CrochetFeve0251 can still see the error on newlabs using the plugin https://pcm.wordpress.org/themes/minimalistblogger/. can you please check?

2022-09-06 17:45 UTC, piotrbak commented
@Mai-Saad I'm not able to reproduce the problem. Excluding jQuery resolves the problem for me here:
https://rocketlabsqa.ovh

2022-09-09 15:51 UTC, Mai-Saad commented
Working fine now

2022-09-12 09:48 UTC, jeawhanlee reviewed
Small change

2022-09-12 09:48 UTC, jeawhanlee commented on inc/ThirdParty/Themes/ThirdpartyTheme.php
> +
```suggestion
use WP_Rocket\Event_Management\Subscriber_Interface;
```

2022-09-12 09:48 UTC, jeawhanlee commented on inc/ThirdParty/Themes/ThirdpartyTheme.php
> +abstract class ThirdpartyTheme implements \WP_Rocket\Event_Management\Subscriber_Interface {
```suggestion
abstract class ThirdpartyTheme implements Subscriber_Interface {
```

2022-09-12 10:04 UTC, jeawhanlee approved these changes

2022-09-12 11:25 UTC, vmanthos commented
@CrochetFeve0251 I retested this after the latest changes and it's working as expected.

Please merge it whenever you can.

2022-09-12 11:46 UTC, merged