Closes #5126 - Removing rocket lazyload attributes on native lazyload images
wp-media/wp-rocket pull request #5143
Opened 2022-06-14 15:05 UTC by jeawhanlee

## Description

This PR fixes the issue of adding rocket lazyload attributes on images that lazyloaded natively.

Fixes #5126

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

There is no grooming.

## How Has This Been Tested?

- Add the `loading="lazy"` attribute to an image.
- Activate LL on WPR, Our lazyload is not applied on images with native lazyload.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2022-06-15 09:27 UTC, CrochetFeve0251 approved these changes

2022-06-15 15:54 UTC, Tabrisrp requested changes
This is not the actual issue, and we don't want to prevent JS lazyload being applied when the loading attribute is present. I added a comment on the related issue to explain.

2022-06-21 07:04 UTC, CrochetFeve0251 approved these changes

2022-06-21 15:10 UTC, Tabrisrp requested changes

2022-06-21 15:10 UTC, Tabrisrp commented on inc/Dependencies/RocketLazyload/Assets.php
> +                }
it's not necessary for the background images

2022-06-21 15:10 UTC, Tabrisrp commented on inc/Dependencies/RocketLazyload/Assets.php
> +			elements_selector: ".rocket-lazyload",
The value for the selector should be the one passed to the method as part of the `$args` instead of being hardcoded

2022-06-22 14:47 UTC, Tabrisrp approved these changes

2022-06-22 14:48 UTC, Tabrisrp commented
@jeawhanlee can you also backport this change to https://github.com/wp-media/rocket-lazyload-common

2022-06-30 10:35 UTC, vmanthos approved these changes
Working as expected.

2022-06-30 11:09 UTC, merged