Closes #5075 Remove RUCSS resources table
wp-media/wp-rocket pull request #5145
Opened 2022-06-14 15:17 UTC by Tabrisrp

## Description

Remove the RUCSS resources table and all the related classes usage in the plugin

Fixes #5075

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-06-15 11:46 UTC, CrochetFeve0251 requested changes

2022-06-15 11:46 UTC, CrochetFeve0251 commented on tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Database/deleteOldUsedCss.php
>  		$this->usedCSS = $this->getMockBuilder('WP_Rocket\Engine\Optimization\RUCSS\Database\Tables\UsedCSS')
UsedCSS::class would be cleaner here?

2022-06-15 11:46 UTC, CrochetFeve0251 commented on tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Database/dropResourcesTable.php
> +		$this->usedCSS  = $this->getMockBuilder( 'WP_Rocket\Engine\Optimization\RUCSS\Database\Tables\UsedCSS' )
Same here

2022-06-15 11:46 UTC, CrochetFeve0251 commented on tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Database/dropRucssDatabaseTables.php
>  		$this->usedCSS = $this->getMockBuilder('WP_Rocket\Engine\Optimization\RUCSS\Database\Tables\UsedCSS')
Here too

2022-06-15 11:46 UTC, CrochetFeve0251 commented on tests/Unit/inc/Engine/Optimization/RUCSS/Admin/Database/truncateUsedCssTable.php
>  		$this->usedCSS = $this->getMockBuilder('WP_Rocket\Engine\Optimization\RUCSS\Database\Tables\UsedCSS')
Here too

2022-06-15 13:48 UTC, CrochetFeve0251 approved these changes

2022-08-09 05:52 UTC, vmanthos approved these changes
This is working as expected. 👍

2022-08-09 13:38 UTC, merged