Guard RUCSS filter returns against array of null
wp-media/wp-rocket pull request #5167
Opened 2022-06-21 10:20 UTC by engahmeds3ed

## Description

Guarding RUCSS `preg_quote` first argument in three places against being not string.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Not groomed, just got a warning from @Mai-Saad that this may return fatal errors.

## How Has This Been Tested?

```
add_filter( 'rocket_rucss_external_exclusions', function ( $exclusions ){
        $exclusions[] = null;
	return $exclusions;
} );
```

OR

```
add_filter( 'rocket_rucss_inline_atts_exclusions', function ( $exclusions ){
        $exclusions[] = null;
	return $exclusions;
} );
```

OR

```
add_filter( 'rocket_rucss_inline_content_exclusions', function ( $exclusions ){
        $exclusions[] = null;
	return $exclusions;
} );
```

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-21 15:25 UTC, Tabrisrp reviewed
Maybe we could remove items that are not string before passing it to array_map, using array_filter() with is_string?

With the current solution, values that are not string are still preserved in the array

2022-06-21 18:57 UTC, engahmeds3ed commented
> Maybe we could remove items that are not string before passing it to array_map, using array_filter() with is_string?
> 
> With the current solution, values that are not string are still preserved in the array

I was thinking of that, u r totally right, will adjust it to be like that.

2022-06-22 08:30 UTC, CrochetFeve0251 requested changes

2022-06-22 08:30 UTC, CrochetFeve0251 commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +			function ( $item ) {
You can consider using a static anonymous function as you don't need the context ^^'
```suggestion
			static function ( $item ) {
```

2022-06-22 09:09 UTC, engahmeds3ed commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +			function ( $item ) {
Good point, Yes this is [micro-optimization](https://www.designcise.com/web/tutorial/what-are-static-anonymous-functions-in-php#when-to-use-static-closures) so why not.
Thanks.

2022-06-22 13:33 UTC, remyperona approved these changes

2022-06-22 13:33 UTC, CrochetFeve0251 approved these changes

2022-06-23 17:02 UTC, Mai-Saad approved these changes
Working as expected

2022-06-23 17:24 UTC, merged