Closes #5169 - Hide related RUCSS notices on denied folder permission
wp-media/wp-rocket pull request #5171
Opened 2022-06-21 13:36 UTC by jeawhanlee

## Description

This PR removes the related RUCSS notices when we have a denied permission on the `cache` folder.

Fixes #5169 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2022-06-21 14:50 UTC, Tabrisrp requested changes

2022-06-21 14:50 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Settings.php
> +		if ( ! rocket_direct_filesystem()->is_writable( WP_ROCKET_CACHE_PATH ) ) {
```suggestion
		if ( ! rocket_direct_filesystem()->is_writable( rocket_get_constant( 'WP_ROCKET_USED_CSS_PATH', '' ) ) ) {
```

2022-06-21 14:50 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Admin/Settings.php
> +		if ( ! rocket_direct_filesystem()->is_writable( WP_ROCKET_CACHE_PATH ) ) {
```suggestion
		if ( ! rocket_direct_filesystem()->is_writable( rocket_get_constant( 'WP_ROCKET_USED_CSS_PATH', '' ) ) ) {
```

2022-06-21 15:06 UTC, Tabrisrp commented
The tests need to be updated too

2022-06-22 08:59 UTC, engahmeds3ed commented on inc/Engine/Optimization/RUCSS/Admin/Settings.php
> +		if ( ! rocket_direct_filesystem()->is_writable( WP_ROCKET_CACHE_PATH ) ) {
Also why not adding this logic inside the method `can_display_notice` after checking the screen? what do u think?

2022-06-22 10:45 UTC, jeawhanlee commented on inc/Engine/Optimization/RUCSS/Admin/Settings.php
> +		if ( ! rocket_direct_filesystem()->is_writable( WP_ROCKET_CACHE_PATH ) ) {
True Sir

2022-06-22 13:13 UTC, Tabrisrp approved these changes

2022-06-22 14:22 UTC, vmanthos approved these changes
This is working as expected.

The notices won't be displayed if we cannot create the `used-css` folder. 

After restoring the folder's permissions the "processing" notice gets displayed:
```
WP Rocket: Please wait 10 seconds. The Remove Unused CSS service is processing your pages.
```

If `rocket_rucss_pending_jobs` is executed before the issue is resolved, any preexisting jobs will have a `status` of `failed` and will require manually clearing of the used CSS or wait for anything that will trigger automatic clearing, for the used CSS to be generated for those URLs.

@piotrbak Maybe we can stop the creation of used CSS jobs _until_ we can write to the disk. Also, can we consider using a cron to clear and re-try `failed` jobs?

2022-06-22 14:39 UTC, piotrbak commented
@vmanthos I like the idea of `stopping creation of used CSS jobs until we can write to the disk.`

I believe it needs some discussion on how to implement this properly and when bail out. Could you create an issue?

2022-06-22 15:42 UTC, vmanthos commented
@piotrbak I'll create the issue tomorrow.

2022-06-23 07:41 UTC, vmanthos commented
@piotrbak @jeawhanlee When `cache` is writeable but `used-css` isn't we are still displaying the notices.
This is likely an edge case but could be resolved if, as @Tabrisrp suggested, we check if `WP_ROCKET_USED_CSS_PATH` is writeable instead of `WP_ROCKET_CACHE_PATH`.

2022-06-23 08:40 UTC, piotrbak commented
@vmanthos @jeawhanlee yes, we should check the Used CSS directory

2022-06-23 11:23 UTC, vmanthos commented
@jeawhanlee This is working as expected. 🙏

2022-06-23 13:29 UTC, vmanthos approved these changes

2022-06-23 17:24 UTC, merged