Enhancement/tests for flatsome 3rd party class
wp-media/wp-rocket pull request #5193
Opened 2022-06-28 14:11 UTC by jeawhanlee

This PR adds tests for the flatsome 3rd party class.

## Type of change

Please delete options that are not relevant.

- [x] Enhancement (non-breaking change which improves an existing functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2022-07-04 02:48 UTC, mostafa-hisham approved these changes

2022-07-04 14:59 UTC, Tabrisrp requested changes

2022-07-04 14:59 UTC, Tabrisrp commented on inc/ThirdParty/Themes/Flatsome.php
> +			return $patterns;
```suggestion
			return [];
```

2022-07-07 14:50 UTC, Tabrisrp approved these changes

2022-07-08 18:57 UTC, merged