Closes #5207 on redirect loop with WP on sub-dir
wp-media/wp-rocket pull request #5209
Opened 2022-07-01 15:36 UTC by jeawhanlee

## Description

This PR fixes the issue with a redirect loop on sub-dirs

Fixes #5207 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Tested on TLD and Sub-dir installation on Apache.
- Tested only on TLD and multilanguage on NGINX.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

2022-07-01 15:46 UTC, CrochetFeve0251 approved these changes

2022-07-03 19:11 UTC, piotrbak commented
I can see this solution failing for subdirectory multisite on the sites that are not main. Example:
https://subdir.rocketlabsqa.ovh/test2/

Moreover, we should take care of not redirecting 404 errors of static assets. Example:
https://domain.com/idontexist.txt

It should not be redirected to: https://domain.com/idontexist.txt/

2022-07-04 16:47 UTC, CrochetFeve0251 approved these changes

2022-07-04 17:52 UTC, Tabrisrp approved these changes

2022-07-05 10:51 UTC, vmanthos commented
@jeawhanlee 

While testing the PR I found and @Mai-Saad confirmed that there is a **redirect loop** for the homepage on a **Single site** installed in a **subfolder** when the URL includes:
* a cached `OR`
* an ignored query string `OR` 
* a combination of a cached and ignored query string

Can you please look into this?

2022-07-07 07:56 UTC, CrochetFeve0251 requested changes

2022-07-07 07:56 UTC, CrochetFeve0251 commented on inc/classes/Buffer/class-cache.php
> +		if ( defined( 'MULTISITE' ) && true === MULTISITE ) {
Based on @piotrbak on Slack we need also too check `SUBDOMAIN_INSTALL` is set to false

2022-07-07 08:02 UTC, piotrbak commented on inc/classes/Buffer/class-cache.php
> +		if ( defined( 'MULTISITE' ) && true === MULTISITE ) {
We seem to be fine on subdomains. We should let QA confirm thag

2022-07-08 12:57 UTC, CrochetFeve0251 approved these changes

2022-10-05 12:09 UTC, piotrbak commented
@jeawhanlee @CrochetFeve0251 this one can be closed in favour of https://github.com/wp-media/wp-rocket/pull/5215 right?

2022-11-18 13:19 UTC, closed without merging