Closes #5149 - remove wpr options from not public post types
wp-media/wp-rocket pull request #5224
Opened 2022-07-07 18:19 UTC by jeawhanlee

## Description

This PR removes WPR options on non public post types.

Fixes #5149 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2022-07-11 15:37 UTC, Tabrisrp requested changes

2022-07-11 15:37 UTC, Tabrisrp commented on inc/admin/admin.php
> +	$cpts = apply_filters( 'rocket_skip_post_row_actions', $cpts );
Add docblock for the filter

2022-07-11 15:37 UTC, Tabrisrp commented on inc/admin/ui/meta-boxes.php
> +		$cpts = apply_filters( 'rocket_submitbox_options_post_types', $cpts );
Add docblock here too

2022-07-12 13:22 UTC, Tabrisrp approved these changes

2022-09-02 06:29 UTC, Mai-Saad commented
@jeawhanlee Can see a Clear cache option for the draft post list, at the admin bar of the edit draft post, and, if the classic editor is used, can see a clear cache option inside the page edit view. Can you please check?

![2022-09-02 (2)](https://user-images.githubusercontent.com/76941962/188072620-f6adfafa-d7da-4ff5-9eed-ef78b6e2a7b4.png)
![2022-09-02 (3)](https://user-images.githubusercontent.com/76941962/188072627-4c3f7502-90fc-4880-9108-38f6d9fe86a9.png)
![2022-09-02 (4)](https://user-images.githubusercontent.com/76941962/188072634-c29a9f38-2179-409a-90e2-5a4d28bf60d5.png)

@piotrbak  shouldn't we remove the option from the trash post list?
![2022-09-02 (5)](https://user-images.githubusercontent.com/76941962/188072823-b49da53c-ec46-412c-9766-5b442d3d4c52.png)

2022-09-07 03:21 UTC, mostafa-hisham approved these changes

2022-09-07 17:50 UTC, Mai-Saad commented
@jeawhanlee Thanks for the update, I can see most of the cases working now. only the ADD new page now while using classic editor contains a clear cache option (page/post still not saved as draft nor published yet), can we handle this case?
![Screenshot from 2022-09-07 18-38-01](https://user-images.githubusercontent.com/76941962/188945016-07be4a46-8952-47aa-82dc-0709d557745c.png)

Note: there is a warning on the branch, still under investigation to get consistent reproducible steps (started discussion [here](https://wp-media.slack.com/archives/GUT7FLHF1/p1662572541730159)

2022-09-09 11:41 UTC, Mai-Saad commented
Working fine to clear the cache. Remain only, removing clear used CSS of this URL for the non-public post in preview or view page + checking the same case for Elementor template view
Note: update for test cases is needed
[testrail-report-410.pdf](https://github.com/wp-media/wp-rocket/files/9535050/testrail-report-410.pdf)

2022-09-09 11:51 UTC, Mai-Saad commented
@jeawhanlee can we handle Clear used of this URL not showing for private pages on the same PR?

2022-09-09 16:16 UTC, Mai-Saad commented
What's remaining to be handled:
scenario1:
1- create any post
2- from quick edit , check private
3- from posts list click view for this post
4- hover on admin bar

Scenario 2:
1- Create Elementor template (published one)
2- click preview from template list
3- hover admin bar

2022-10-03 10:00 UTC, Mai-Saad approved these changes
Working fine now for Elementor/ WC smart coupon templates, private, trashed/deleted, and draft posts

2022-10-05 09:27 UTC, merged