New Preload:  fix qa feedback
wp-media/wp-rocket pull request #5226
Opened 2022-07-08 09:59 UTC by CrochetFeve0251

## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-11 13:44 UTC, CrochetFeve0251 commented on inc/Engine/Preload/Subscriber.php
> +			do_action( 'rocket_preload_completed', $url );
@GeekPress here

2022-07-25 09:11 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the update.
Kindly find the notes/Qs below existing on commit `f4f67dfde`:

- [ ] 1- if we enable a separate mobile cache and while preload is in the background, if we visit the desktop of any page (that is not completed yet) then it will be completed while only the desktop version in cache (however, if we visited mobile version then it will be added in cache) => as per discussion, we need to trigger the other visit too. Is it doable?
- [ ] 2- Will we change URLs in the database while changing permalinks or just changing its status to pending? @piotr what do you think?
- [ ] 3- Currently, with a fresh install, we take some time to add the home page to caching table. can it be added instantly?
- [ ] 4- **Sometimes**, after a fresh install, preload adds nothing to cache with/without error in logs.. this needs further investigation and keeping an eye on it using different test sites
if there was an error it's probably
`22-Jul-2022 14:42:49 UTC] WordPress database error Table 'new_rocketlabsqa_ovh_AzP4U3TX.wpr_rocket_cache' doesn't exist for query SELECT id FROM `wpr_rocket_cache` WHERE `last_accessed` <= date_sub(now(), interval 1 month) made by do_action_ref_array('rocket_preload_clean_rows_time_event'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Cron\Subscriber->remove_old_rows, WP_Rocket\Engine\Preload\Database\Queries\Cache->remove_all_not_accessed_rows, WP_Rocket\Engine\Preload\Database\Queries\Cache->get_old_cache
`
and sometimes we have this as well (as per discussion, this error `this is the fix we did waiting for BerlinBD to create methods to modify cache`)
`[22-Jul-2022 18:28:12 UTC] WordPress database error Duplicate entry 'https://newer.rocketlabsqa.ovh/test' for key 'url' for query INSERT INTO `wp_wpr_rocket_cache` (`url`, `status`, `modified`, `last_accessed`) VALUES ('https://newer.rocketlabsqa.ovh/test', 'pending', '2022-07-22T18:28:12Z', '2022-07-22 18:28:12') made by do_action_ref_array('action_scheduler_run_queue_preload'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Common\Queue\PreloadQueueRunner->run, WP_Rocket\Engine\Common\Queue\PreloadQueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, ActionScheduler_Action->execute, do_action_ref_array('rocket_preload_job_parse_sitemap'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Frontend\Subscriber->parse_sitemap, WP_Rocket\Engine\Preload\Frontend\FetchSitemap->parse_sitemap, WP_Rocket\Engine\Preload\Database\Queries\Cache->create_or_nothing, WP_Rocket\Dependencies\Database\Query->add_item`

- [ ] 5- If we enabled Cookie Notice & Compliance for GDPR / CCPA plugin, click clear and preload then access any page with completed status => the cookie notice won't be displayed although it is displayed in nowprocket post. any ideas?

- [ ] 6- While transitional or reader AMP => created only normal files for all except home (for home no mobile at all), and no amp for all => shouldn't we have a mobile version for home? will we create the amp folder before a real visit (it is currently created with the manual visit)
- [ ] 7- Using this filter to control the number of rows to be deleted from the actions table seems not working, is it the correct filter or do we need to handle something there? (it shall remove 500 items that exist more than 1 min if we set the period filter to 60, however,  only 20 items are deleted now)
```
add_filter( 'rocket_action_scheduler_clean_batch_size', function( $entries ){
		return 500;
		} )
```
used filter for the duration was 
```
add_filter( 'rocket_action_scheduler_retention_period', function( $seconds ){
	return 60;
	} );
```
Note: tested on https://newer.rocketlabsqa.ovh/, while for point 4 tested with https://new.rocketlabsqa.ovh/ too

2022-07-25 14:13 UTC, CrochetFeve0251 commented
@Mai-Saad concerning point 2 when a permalink change it will create a new row in the database.
Some code executes on 404 error to drop the old permalink if it is accessed.

2022-07-29 16:34 UTC, piotrbak commented
@CrochetFeve0251 @Mai-Saad Regarding 2nd I believe that redirection to the correct version will happen (thanks Mai), not 404.

I think we have two options here:
1. Save in the db version with/without permalinks
2. Decide whether we need to add the `/` just before sending the request

2022-08-02 06:44 UTC, CrochetFeve0251 commented
> @CrochetFeve0251 @Mai-Saad Regarding 2nd I believe that redirection to the correct version will happen (thanks Mai), not 404.
> 
> I think we have two options here:
> 
>     1. Save in the db version with/without permalinks
> 
>     2. Decide whether we need to add the `/` just before sending the request

The option 2. is already implemented for trailing slashes.

2022-08-11 15:21 UTC, Tabrisrp requested changes

2022-08-11 15:21 UTC, remyperona commented on inc/Engine/Activation/Activation.php
> +use WP_Rocket\Engine\Preload\Subscriber;
Those don't seem to be used

2022-08-11 15:21 UTC, remyperona commented on inc/Engine/Activation/ServiceProvider.php
> +use WP_Rocket\Admin\Options;
not used in the class?

2022-08-11 15:21 UTC, remyperona commented on inc/Engine/Activation/ServiceProvider.php
> +use WP_Rocket\Engine\Preload\Activation;
not used in the class?

2022-08-11 15:21 UTC, remyperona commented on inc/Engine/Preload/Activation/Activation.php
> +		do_action( 'rocket_preload_activation' );
Add docblock for action

2022-08-11 15:21 UTC, remyperona commented on inc/Engine/Preload/Activation/Activation.php
> +	 */
That doesn't seem to match with what the method is doing

2022-08-11 15:21 UTC, remyperona commented on inc/Engine/Preload/Admin/Subscriber.php
> +		}
This could be directly in the method in the Settings class instead

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/Controller/LoadInitialSitemap.php
> +			$sitemaps = apply_filters( 'rocket_preload_sitemap_before_queue', $sitemaps );
add docblock for the filter

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/Controller/LoadInitialSitemap.php
> +		$sitemaps = apply_filters( 'rocket_preload_sitemap_before_queue', [ $sitemap ] );
add docblock for the filter

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +			if ( isset( $request['url'] ) && is_string( $request['url'] ) ) {
could change the conditional into an early bail-out if url is not set or not a string

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/Database/Queries/Cache.php
> +		$condition = apply_filters( 'rocket_preload_all_to_pending_condition', ' WHERE 1 = 1' );
add docblock for filter

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/Database/Queries/Cache.php
> +	 * Check if the page is preloaded.
```suggestion
	 * Check if the page is pending.
```

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/ServiceProvider.php
> +				$batch_size = (int) apply_filters( 'rocket_action_scheduler_clean_batch_size', 100, $group );
add docblock for filter

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/Subscriber.php
> +			do_action( 'rocket_preload_completed', $url, $detected );
add docblock for action

2022-08-11 15:21 UTC, Tabrisrp commented on inc/Engine/Preload/Subscriber.php
> +	 */
Shouldn't it be stop preload?

2022-08-11 15:21 UTC, Tabrisrp commented on inc/common/purge.php
> +			$purge_urls[] = $root_url . $page;
```suggestion
			$purge_urls[] = trailingslashit( $home_url ) . ltrim( $page, '/' );
```

2022-08-12 09:24 UTC, CrochetFeve0251 commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +			if ( isset( $request['url'] ) && is_string( $request['url'] ) ) {
@Tabrisrp in this case it won't work as I am checking that due to the filter just above that could potentially return invalid data.

2022-08-12 13:07 UTC, Tabrisrp commented on inc/Engine/Preload/Controller/LoadInitialSitemap.php
> +		if ( ! WP_Sitemaps::sitemaps_enabled() ) {
This method is not static

2022-08-12 13:07 UTC, Tabrisrp commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +			if ( isset( $request['url'] ) && is_string( $request['url'] ) ) {
Can't you do the following?

```
if ( ! isset( $request['url'] ) ||  ! is_string( $request['url'] ) ) {
    continue;
}
```

2022-08-12 14:16 UTC, CrochetFeve0251 commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +			if ( isset( $request['url'] ) && is_string( $request['url'] ) ) {
Ah when I got bail out I got go out of the method :')

2022-08-12 14:39 UTC, remyperona commented on inc/Engine/Preload/Admin/Settings.php
> +			'<a href="' . $as_tools_link . '">',
```suggestion
			'<a href="' . menu_page_url( 'action-scheduler', false ) . '">',
```

Can use the function directly there, as the variable is not used more than once

2022-08-12 14:39 UTC, remyperona commented on inc/Engine/Preload/Controller/LoadInitialSitemap.php
> +use WP_Sitemaps;
```suggestion
```

2022-08-16 14:25 UTC, Tabrisrp approved these changes

2022-08-16 16:39 UTC, merged