Closes #4357 on automate generating WPR css and js file
wp-media/wp-rocket pull request #5239
Opened 2022-07-12 20:44 UTC by jeawhanlee

## Description
This PR tries to close the initiative of automating the generation of WPR CSS and js files.

Fixes #435

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Slightly different from the proposed.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2022-07-13 15:59 UTC, Tabrisrp requested changes
That's a good start, but to avoid the issue with merge conflicts and still be able to review/test changes before deployement, we should modify the gulp tasks (or create new one), to generate unminified versions of the `wpr-admin.css`, `wpr-admin-rtl.css` and `wpr-admin.js`

2022-07-19 13:14 UTC, Tabrisrp reviewed
A couple of things:
- Can you run the tasks so that the unminified build are sync'ed to git
- Shouldn't the deploy build also use the `.min` suffix?
- Could you update the enqueue code to be compatible with both no suffix and suffix, depending on the value of `SCRIPT_DEBUG`

2022-07-20 15:06 UTC, Tabrisrp requested changes
The minified files are added to gitignore but still commited, you can use `git rm --cached <file>` to remove them

2022-07-20 15:06 UTC, remyperona commented on inc/admin/ui/enqueue.php
> +	$admin_style     = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? 'wpr-admin.css' : 'wpr-admin.min.css';
I'd suggest something like this instead:

```
$suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';
```

and then use `$suffix` in the enqueue URL like
```
WP_ROCKET_ASSETS_CSS_URL . 'wpr-admin' . $suffix . '.css'
```

2022-07-21 14:40 UTC, Tabrisrp requested changes
only the map file remaining to be removed

2022-07-21 18:41 UTC, Tabrisrp approved these changes

2022-07-22 09:44 UTC, engahmeds3ed commented
Do we need QA for this one?

2022-08-02 10:18 UTC, engahmeds3ed commented
@piotrbak 
@wp-media/qa 
do we need QA for this one?

2022-08-02 11:26 UTC, piotrbak commented
@engahmeds3ed How we could test this PR?

2022-08-02 13:36 UTC, engahmeds3ed commented
> @engahmeds3ed How we could test this PR?

I don't think we can test that!

@jeawhanlee @Tabrisrp what do u think?

2022-08-02 14:07 UTC, jeawhanlee commented
> > @engahmeds3ed How we could test this PR?
> 
> I don't think we can test that!
> 
> @jeawhanlee @Tabrisrp what do u think?

I don't think QA will be able to test this, we might have to run a fake deploy to test this, though I tested this using the **on:push and pull rquest** git action, so I think @Tabrisrp would know a better way to test this.

2022-08-02 14:47 UTC, Tabrisrp commented
Yeah we don't need QA, if it was tested using different triggers, it should be fine on the release tag too.

2022-08-03 19:10 UTC, merged

2022-09-05 06:14 UTC, mostafa-hisham commented
@jeawhanlee @Tabrisrp
do we need to update the GitHub action to run the gulp task to generate unminified files too?