Fixes/4988 update delay js script
wp-media/wp-rocket pull request #5256
Opened 2022-07-20 10:48 UTC by jeawhanlee

## Description

This PR updates the delay js script and set src to data-rocket-src for compatibility with update script.

Fixes #4988 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

This is solution is no way different from the proposed one.

## How Has This Been Tested?

Manually

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2022-07-20 15:00 UTC, Tabrisrp approved these changes

2022-07-26 12:20 UTC, piotrbak commented
As per https://github.com/wp-media/delay-javascript-loading/pull/32#issuecomment-1187002433, we need to make sure that only types mentioned Gael are rewritten to DelayJS markup.

2022-08-26 14:08 UTC, Mai-Saad commented
@piotrbak 
- We have the following regression:
If we used this markup `<script type='text/javascript' src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/print-helloworld.js'></script>`, it is not delayed. which resulted in a js error while using [Avada theme](https://mega.wp-rocket.me/avada/) (this was working before)

**Notes** 

1. if `type='text/javascript'` came after the script, it will be delayed i.e `<script  src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/print-helloworld.js' type='text/javascript'></script>`
2. if we used before script `Type='text/javascript'` or `TYPE='text/javascript'`, will be normally delayed

**Question**
we are dealing with this markup
```
<script type='' src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/print-helloworld-v2.js'></script>
<script type src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/print-helloworld-v2.js'></script>
```
as
```
<script type='' src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/print-helloworld-v2.js'></script>
<script type="rocketlazyloadscript" type data-rocket-src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/print-helloworld-v2.js'></script>
```
shouldn't we delay 1st script and not duplicate the type in the 2nd script?

2022-08-30 12:38 UTC, piotrbak commented
@Mai-Saad Regarding the **Question**, it seems to be an edge case. 

Could you confirm that:
1. This markup (not cached) is valid HTML markup
2. The first script `type=""` is executed normally

2022-08-30 15:11 UTC, Mai-Saad commented
As per discussion with @piotrbak and further investigations:
- The first script `type=""` is executed normally in the browser so probably we need to handle
- The 2nd script `type`, we shouldn't add another type as having 2 types will result in an error using validator [HTML](https://validator.w3.org/nu/?doc=https%3A%2F%2Fnew.rocketlabsqa.ovh%2Ftest-browser%2F%3Fnowprocket)

2022-08-30 15:57 UTC, jeawhanlee commented
> As per discussion with @piotrbak and further investigations:
> 
> * The first script `type=""` is executed normally in the browser so probably we need to handle
> * The 2nd script `type`, we shouldn't add another type as having 2 types will result in an error using validator [HTML](https://validator.w3.org/nu/?doc=https%3A%2F%2Fnew.rocketlabsqa.ovh%2Ftest-browser%2F%3Fnowprocket)

@Mai-Saad I was not able to reproduce the duplicate type using the markup:
`<script type src='https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/scripts/print-helloworld-v2.js'></script>`

2022-09-09 03:27 UTC, mostafa-hisham commented on inc/Engine/Preload/Admin/Settings.php
> +		$exp = "'^" . $wpdb->prefix . "actionscheduler_+(logs|actions|groups|claims)$'";
there is a conflict here with develop
`is_valid_as_tables` function are not in develop anymore

2022-09-09 06:39 UTC, jeawhanlee commented on inc/Engine/Preload/Admin/Settings.php
> +		$exp = "'^" . $wpdb->prefix . "actionscheduler_+(logs|actions|groups|claims)$'";
Thanks @mostafa-hisham

2022-09-09 06:39 UTC, jeawhanlee commented on inc/Engine/Preload/Admin/Settings.php
> +		$exp = "'^" . $wpdb->prefix . "actionscheduler_+(logs|actions|groups|claims)$'";
Thanks @mostafa-hisham

2022-09-09 13:40 UTC, mostafa-hisham approved these changes

2022-09-19 13:58 UTC, Mai-Saad commented
@jeawhanlee @piotrbak Seems we have regression on Firefox, so far while delay JS is enabled:
- Using the bridge theme, for some reason, the home page slider is not loaded after user interaction http://mega.wp-rocket.me/bridge
- Using Divi, the page keeps loading forever after user interaction http://mega.wp-rocket.me/divi/
can you please check?

2022-10-18 06:18 UTC, mostafa-hisham approved these changes

2022-10-25 05:03 UTC, mostafa-hisham approved these changes

2022-11-01 13:36 UTC, remyperona commented on inc/Engine/Optimization/DelayJS/HTML.php
> +				$delay_js = preg_replace( '/\s\s+/', ' ', preg_replace( '#' . preg_quote( $matches['attr'], '#' ) . '#i', $altered_attr, $matches[0], 1 ) );
that's a lot of regex usage, is there any way to simplify this part? @wp-media/php any ideas?

2022-11-10 09:57 UTC, piotrbak commented on inc/Engine/Optimization/DelayJS/HTML.php
> +				$delay_js = preg_replace( '/\s\s+/', ' ', preg_replace( '#' . preg_quote( $matches['attr'], '#' ) . '#i', $altered_attr, $matches[0], 1 ) );
@wp-media/php What do you think about @Tabrisrp comment here?

2022-11-18 12:03 UTC, piotrbak commented on inc/Engine/Optimization/DelayJS/HTML.php
> +				$delay_js = preg_replace( '/\s\s+/', ' ', preg_replace( '#' . preg_quote( $matches['attr'], '#' ) . '#i', $altered_attr, $matches[0], 1 ) );
@wp-media/php Could you check that comment? What do you think?

2022-11-30 16:17 UTC, Tabrisrp commented on inc/Engine/Optimization/DelayJS/HTML.php
> +				$delay_js = preg_replace( '/\s\s+/', ' ', preg_replace( '#' . preg_quote( $matches['attr'], '#' ) . '#i', $altered_attr, $matches[0], 1 ) );
also, what cases are we trying to handle with those?

2022-12-01 09:03 UTC, jeawhanlee commented on inc/Engine/Optimization/DelayJS/HTML.php
> +				$delay_js = preg_replace( '/\s\s+/', ' ', preg_replace( '#' . preg_quote( $matches['attr'], '#' ) . '#i', $altered_attr, $matches[0], 1 ) );
This [here](https://github.com/wp-media/wp-rocket/pull/5256#issuecomment-1228537288) and [here](https://github.com/wp-media/wp-rocket/pull/5256#issuecomment-1231804760)

2022-12-01 15:16 UTC, Tabrisrp approved these changes

2022-12-01 15:16 UTC, Tabrisrp commented
PR needs to be updated with develop branch, and conflict fixed

2022-12-02 12:13 UTC, engahmeds3ed commented
@Tabrisrp all good now, thanks for checking.

2022-12-02 14:30 UTC, Tabrisrp requested changes

2022-12-02 14:30 UTC, remyperona commented on inc/Engine/Optimization/DelayJS/HTML.php
> +		'application/jscript',
this is not a valid type

2022-12-05 14:39 UTC, Tabrisrp approved these changes

2022-12-06 04:25 UTC, Mai-Saad commented
As per the exploratory test, we have regression on FF mobile view => page keeps loading and has many warnings while a separate mobile cache is enabled/disabled and Delay JS has no exclusions. @engahmeds3ed @jeawhanlee can you please check :pray: 

https://user-images.githubusercontent.com/76941962/205810699-a8b1450d-7da8-448c-943e-b7c2720bdc01.mp4

Note: Same is happening on mega/divi (working fine on the trunk)

2022-12-07 12:21 UTC, piotrbak commented
For Avada example, excluding the following scripts makes slider appear right away. The root cause is most likely inside them:
```
/wp-content/themes/Avada/includes/lib/assets/min/js/library/jquery.flexslider.js
/avada/wp-includes/js/jquery/jquery.min.js
/wp-content/plugins/fusion-core/js/min/avada-fusion-slider.js
/wp-content/themes/Avada/includes/lib/assets/min/js/library/modernizr.js
/wp-content/themes/Avada/includes/lib/assets/min/js/general/fusion.js
/wp-content/themes/Avada/includes/lib/assets/min/js/library/cssua.js
/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.transition.js
/wp-content/themes/Avada/includes/lib/assets/min/js/library/bootstrap.tooltip.js
```

2022-12-12 08:26 UTC, gmetais commented
> As per the exploratory test, we have regression on FF mobile view

@Mai-Saad @piotrbak Actually, this is not really a bug.

We used to have an issue on Firefox, which led me to implement a Firefox browser detection in the code by checking the user agent. But when you switch Firefox to mobile view, it overwrites the user agent and replaces it with an Android or iOS user agent.

It should not reproduce on a real Firefox mobile browser. If you still want to test, Firefox allows you to edit the user agent. Adding "Firefox/107.0" to the end of the user agent field fixes the issue.

In case you still consider this issue as blocking (for example if some website creators use the Firefox mobile view to debug their website), we could try to find a different way to identify Firefox. For example, on Firefox, navigator.vendor === "" whereas other browsers have non-empty values. Kind of a hack and I prefer not to add it.

2022-12-14 20:33 UTC, Mai-Saad approved these changes
Working as expected.
[testrail-report-432.pdf](https://github.com/wp-media/wp-rocket/files/10231469/testrail-report-432.pdf)

2022-12-14 20:35 UTC, merged