Fix deploy dynamic list fall back workflow
wp-media/wp-rocket pull request #5287
Opened 2022-08-03 02:56 UTC by mostafa-hisham

## Description

Create a new git hu workflow to update dynamic list fallback JSON file when push to trunk

Fixes #5274 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

Tested on a separate GitHub repo to check if workflow is working

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2022-08-03 10:38 UTC, jeawhanlee reviewed
Isn't this supposed to be using the release trigger `on:release:` and if so, then we can append the concerned steps to the deploy workflow we already have.
What do you think @mostafa-hisham @Tabrisrp

2022-08-03 14:55 UTC, Tabrisrp requested changes

2022-08-03 14:55 UTC, Tabrisrp commented on .github/workflows/deploy_dynamic_lists_fallback.yml
> +name: CI
```suggestion
name: Dynamic lists fallback update
```

2022-08-03 14:57 UTC, Tabrisrp commented on .github/workflows/deploy_dynamic_lists_fallback.yml
> +          commit_message: update dynamic lits
```suggestion
          commit_message: update dynamic lists
```

2022-08-03 14:57 UTC, Tabrisrp commented on .github/workflows/deploy_dynamic_lists_fallback.yml
> +          commit_user_name: WP-media GitHub Actions Bot
```suggestion
          commit_user_name: WP Media GitHub Actions Bot
```

2022-08-03 14:59 UTC, Tabrisrp commented
Since we want the file to be committed to the trunk branch, it makes sense to do it on push to this branch I think

2022-08-04 13:12 UTC, Tabrisrp approved these changes

2022-08-04 13:48 UTC, merged