Fix preloading the sitemap with update from any version less than or equals 3.12.0.2
wp-media/wp-rocket pull request #5337
Opened 2022-08-24 08:30 UTC by engahmeds3ed

## Description

We had a problem with this condition
https://github.com/wp-media/wp-rocket/blob/a036f3c3949fb5ba10d5b651d9e80197bcfb4d1a/inc/Engine/Preload/Activation/Activation.php#L79

Which means that if the new version is less than `3.12` we will preload the sitemap and this will never happen.

So this PR to solve that.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Locally and fixed the fixtures

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-24 08:38 UTC, engahmeds3ed commented
Will update the fixtures and tests and be ready for review

2022-08-24 09:08 UTC, CrochetFeve0251 requested changes

2022-08-24 09:08 UTC, CrochetFeve0251 commented on tests/Fixtures/inc/Engine/Preload/Activation/refreshOnUpdate.php
>  	'versionInferiorShouldDoNothing' => [
@engahmeds3ed you should update names from fixtures to keep them coherent.

2022-08-24 09:08 UTC, CrochetFeve0251 commented on tests/Fixtures/inc/Engine/Preload/Activation/refreshOnUpdate.php
>  	'versionSuperiorShouldReload' => [
This one too
```suggestion
	'versionInferiorShouldReload' => [
```

2022-08-24 09:08 UTC, CrochetFeve0251 commented on tests/Fixtures/inc/Engine/Preload/Activation/refreshOnUpdate.php
>  	'versionInferiorShouldDoNothing' => [
@engahmeds3ed you should update names from fixtures to keep them coherent.
```suggestion
	'versionSuperiorShouldReload' => [
```

2022-08-24 09:25 UTC, CrochetFeve0251 approved these changes

2022-08-24 09:34 UTC, merged

2022-09-03 22:26 UTC, jasonb4u commented
Preload SITEMAPS has disappeared, this is where it used to be
![4-09-2022 8-21-41 AM](https://user-images.githubusercontent.com/20693414/188289399-a8fca781-50c2-4ac6-a4c7-97097be97471.jpg)

2022-09-05 08:27 UTC, jasonb4u commented
soooo where is it now ?

2022-09-05 09:59 UTC, piotrbak commented
@jasonb4u Since 3.12 release we changed how we deal with the preload. We save URLs and their statuses in the database, please check our documentation:
https://docs.wp-rocket.me/article/8-preload-cache

If you have any further questions, please reach our Support Team.

2022-09-05 10:54 UTC, jasonb4u commented
This is NOT allowing to select which sitemaps we want Cached.  Needs option to select what we want cached

2022-09-05 11:15 UTC, piotrbak commented
@jasonb4u From what I can see you were using autocompatibility with SEOPress + additional sitemap, this is how it's working now too. 
```
Needs option to select what we want cached
```
This is an enhancement we're discussing about and it's possible that it'll be implemented soon. Thank you.

2022-09-06 10:40 UTC, jasonb4u commented
how is it an extra enhancement when it was in v.3.11.5 and now removed, lol. I know most of my dev friends had to roll back to 3.11.5 because you remove something that needs to be there !

2022-09-06 11:03 UTC, piotrbak commented
For the initial load of the sitemap, you can use the following filter:
```
function add_my_sitemap() {
return ['https://domain.com/my_sitemap.xml'];
}
add_filter( 'rocket_sitemap_preload_list', 'add_my_sitemap', PHP_INT_MAX );
```
For the overall enhancement, please follow the following issue:
https://github.com/wp-media/wp-rocket/issues/5394

Please note that we use Github for development purposes only.