Fixes 5346: Fixed delete from url from preload on 404
wp-media/wp-rocket pull request #5350
Opened 2022-08-25 12:44 UTC by CrochetFeve0251

## Description

Fix an issue on preload where we don't remove the url from the preload when trashing or deleting it.
For that the `set_404` have been added back.

Fixes #5346

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

One test has been added to check this functionality is present.

- [ ] Automated Test
- [ ] Manual Testing

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-25 13:14 UTC, remyperona requested changes

2022-08-25 13:14 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Preload/Subscriber/deletePostPreloadCache.php
> +<?php
the test filename should be the same as the method being tested. `deleteUrlOnNotFound.php`

2022-08-25 13:14 UTC, remyperona commented on tests/Integration/inc/Engine/Preload/Subscriber/deletePostPreloadCache.php
> +class Test_DeletePostPreloadCache extends AdminTestCase
```suggestion
class Test_DeleteUrlOnNotFound extends AdminTestCase
```

2022-08-25 13:30 UTC, Tabrisrp approved these changes

2022-08-25 14:44 UTC, Mai-Saad commented
@CrochetFeve0251 just noticed that if we visited any URL as a logged-in user, the URL will be removed from the table. Can you please check that?

https://user-images.githubusercontent.com/76941962/186695994-1ce9d357-94b6-4f85-91d1-05ad8b5d9a9f.mp4

2022-08-29 13:31 UTC, Tabrisrp approved these changes
one minor change in the test

2022-08-29 13:31 UTC, Tabrisrp commented on tests/Integration/inc/Engine/Preload/Subscriber/deleteUrlOnNotFound.php
> +	}
```suggestion
	public function set_up()
	{
		parent::set_up();
		add_filter('pre_get_rocket_option_manual_preload', [$this, 'manual_preload']);
	}
```

2022-08-29 14:57 UTC, piotrbak approved these changes
Working as expected.

2022-08-29 15:54 UTC, merged