fix bandwidth typo in RocketCDN tab
wp-media/wp-rocket pull request #5392
Opened 2022-09-05 08:36 UTC by mostafa-hisham

## Description

fix bandwidth typo

Fixes #5353 

## Type of change 

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [x] Tested locally

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2022-09-05 16:57 UTC, jeawhanlee approved these changes

2022-09-06 08:52 UTC, Mai-Saad commented
The typo is fixed now but the translation is not displayed as it was on the trunk, @Tabrisrp do we need further changes on PR so translation works? 
![2022-09-06 (3)](https://user-images.githubusercontent.com/76941962/188591818-87e09c20-b58e-4d55-995e-e3495d8560a3.png)

2022-09-07 07:49 UTC, engahmeds3ed requested changes

2022-09-07 07:49 UTC, engahmeds3ed commented on tests/Fixtures/inc/Engine/CDN/RocketCDN/NoticesSubscriber/displayRocketcdnCta.php
> +				<li class="wpr-rocketcdn-feature wpr-rocketcdn-bandwidth">High performance Content Delivery Network (CDN) with <strong>unlimited bandwidth</strong></li>
Why those strings are not translatable?
@mostafa-hisham Do u think it's the time to change it to use the WordPress translation functions?

2022-09-07 14:19 UTC, engahmeds3ed commented on tests/Fixtures/inc/Engine/CDN/RocketCDN/NoticesSubscriber/displayRocketcdnCta.php
> +				<li class="wpr-rocketcdn-feature wpr-rocketcdn-bandwidth">High performance Content Delivery Network (CDN) with <strong>unlimited bandwidth</strong></li>
those are tests, sorry I didn't notice that :D

2022-09-08 08:31 UTC, Mai-Saad approved these changes
As per discussion with @engahmeds3ed nothing is needed on PR

2022-09-12 12:59 UTC, merged