Reduced UsedCss index key size
wp-media/wp-rocket pull request #5422
Opened 2022-09-13 20:03 UTC by CrochetFeve0251

## Description

Fix a bug at the creation from the RUCSS table due to the index key being too long.
For that we reduced to 191.

Fixes #5416

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Manually

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-14 13:11 UTC, remyperona reviewed
don't we also need to update the schema for existing installs?

2022-09-14 13:16 UTC, piotrbak commented
@Tabrisrp What do you think about reducing the size here:
https://github.com/wp-media/wp-rocket/blob/c6b74a8ad463158511a7d10352554379d4731099/inc/Engine/Optimization/RUCSS/Database/Tables/UsedCSS.php#L68

That's what @engahmeds3ed suggested at some point, not sure if that works and which option is better/cleaner.

2022-09-14 13:26 UTC, Tabrisrp commented
It really depends on the possible length of the queue_name values, do we know how long it can be?

2022-09-14 13:28 UTC, piotrbak commented
From what I can see, we should not expect this value to be long:
![image](https://user-images.githubusercontent.com/26767037/190167120-f37ff95a-4185-4212-868b-b3660d7ceec9.png)

2022-09-14 13:50 UTC, Tabrisrp commented
Makes me wonder why the queue name is indexed in the first place, we don't query based on it in the plugin. Looking at the code, I think there was a mistake at some point, making this an index instead of the status column.

2022-09-14 14:01 UTC, CrochetFeve0251 commented
> Makes me wonder why the queue name is indexed in the first place, we don't query based on it in the plugin. Looking at the code, I think there was a mistake at some point, making this an index instead of the status column.

Ok I think for that I will have to update the schema for all customers but I agree it is weird to index on that value.

2022-09-14 14:08 UTC, piotrbak commented
Since it's scheduled for 3.12.2 we have some time for discussion. 
```
making this an index instead of the status column.
```
Which queries would take advantage of this change? 🤔

2022-09-14 14:34 UTC, remyperona commented
We have some queries that are based on the current status, so if there is a lot of entries, they could be faster

2022-09-19 13:58 UTC, Tabrisrp requested changes
I think we need to add the method to update the existing schema on update

2022-09-20 13:30 UTC, remyperona requested changes
We should also drop the index for ` the queue_name` in the update method

2022-09-22 13:52 UTC, Tabrisrp requested changes

2022-09-22 13:52 UTC, Tabrisrp commented on inc/Dependencies/RocketLazyload/Iframe.php
> -				'google_ads_iframe_',
This shouldn't be modified

2022-09-22 18:25 UTC, Tabrisrp approved these changes

2022-09-22 19:31 UTC, Tabrisrp requested changes
getting the following error locally:  `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELETE INDEX `queue_name_index` (`status`)' at line 1`

2022-09-23 13:47 UTC, remyperona approved these changes

2022-10-10 11:58 UTC, vmanthos commented
@CrochetFeve0251 When installing WP Rocket from scratch indexes look fine.

However, updating WP Rocket from a previous version changes the `queue` index to `status` but it doesn't have the `191` length restriction.

I believe this is coming from here:

https://github.com/wp-media/wp-rocket/blob/29b14fd59332a8e7a61e09350f5f586e5bc92e35/inc/Engine/Optimization/RUCSS/Database/Tables/UsedCSS.php#L216

Can you please look into this? 🙏

2022-10-11 11:19 UTC, vmanthos approved these changes
Working as expected!
[testrail-report-416.pdf](https://github.com/wp-media/wp-rocket/files/9754572/testrail-report-416.pdf)

2022-10-11 11:20 UTC, merged