Closes 5382: Excluded url with extensions
wp-media/wp-rocket pull request #5427
Opened 2022-09-14 09:34 UTC by CrochetFeve0251

## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-14 10:02 UTC, jeawhanlee approved these changes

2022-09-14 13:12 UTC, Tabrisrp requested changes

2022-09-14 13:12 UTC, Tabrisrp commented on inc/Engine/Preload/Database/Queries/Cache.php
> +			'xsl' => 1,
I'd suggest to add kml extension too, as there was a comment in the issue about this type

2022-09-22 18:18 UTC, Tabrisrp approved these changes

2022-09-29 14:58 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the PR. Currently can see these types of URLs in the cache table while permalinks are set to `/%postname%.php/`, can you please check?
![Screenshot from 2022-09-29 16-52-19](https://user-images.githubusercontent.com/76941962/193066810-0963dbd9-0fdd-4451-bf16-7edf62cf6259.png)

2022-09-30 07:16 UTC, Mai-Saad approved these changes
Working as expected with the following notes:
- This kind of URL is cached and preloaded https://new.rocketlabsqa.ovh/open-book.xsl/project2 while https://new.rocketlabsqa.ovh/open-book.xsl is not cached nor preloaded
- If permalinks are set as `%post-name%.pdf` (another extension than pdf, XML, kml, xsl), Url domain/post.pdf will be cached and preloaded. @piotrbak  what do you think about this?
- If the user was using a trunk, having .PHP URLs in the database then update, those URLs won't automatically be removed nor with clear and preload nor re-enable preload but if permalinks were changed , .PHP URLs won't be added to the database anymore => @piotrbak  what do you think? shouldn't we remove them with the update?

These points are fine based on a discussion with @piotrbak to avoid complexity.

2022-10-05 09:38 UTC, merged