Enhancement/5394 excluding urls from preload
wp-media/wp-rocket pull request #5433
Opened 2022-09-15 11:12 UTC by CrochetFeve0251

## Description
Added a way to exclude uris from the preload.

For that we added a new check with a filter that check with the url to determine if it is excluded from the preload.
Then we used that filter where we update and add the urls to exclude them or delete them.

Fixes #5394

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated Test
- [ ] Manual Test

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-15 13:30 UTC, remyperona requested changes

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Admin/Settings/Page.php
> +			]
Why was this added back?

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Admin/Settings/Page.php
> +					'label'             => __( 'Sitemaps for preloading', 'rocket' ),
Label is not correct

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +		$regexes = apply_filters( 'rocket_preload_exclude_urls', [] );
Add docblock for filter

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +	protected function is_excluded_by_filter( string $url ) {
```suggestion
	protected function is_excluded_by_filter( string $url ): bool {
```

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +		if ( ! $regexes ) {
```suggestion
		if ( empty( $regexes ) ) {
```

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Subscriber.php
> +	public function add_preload_excluded_uri( array $regexes ) {
```suggestion
	public function add_preload_excluded_uri( $regexes ): array {
```

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Subscriber.php
> +		$preload_excluded_uri = $this->options->get( 'preload_excluded_uri', false );
```suggestion
		$preload_excluded_uri = $this->options->get( 'preload_excluded_uri', [] );
```

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Subscriber.php
> +		if ( ! $preload_excluded_uri ) {
```suggestion
		if ( empty( $preload_excluded_uri ) ) {
```

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Subscriber.php
> +			return false;
```suggestion
			return $regexes;
```

2022-09-15 13:30 UTC, remyperona commented on inc/Engine/Preload/Subscriber.php
> +		$preload_excluded_uri = explode( "\n", $preload_excluded_uri );
```suggestion
		$preload_excluded_uri = explode( "\n", $preload_excluded_uri );
```

The value of the option should be sanitized on saving to convert it to an array instead of a string, as we do for other textarea fields

2022-09-16 09:29 UTC, engahmeds3ed requested changes

2022-09-16 09:29 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +
U need casting here and make sure that this array contains strings only
```suggestion
		$regexes = (array) apply_filters( 'rocket_preload_exclude_urls', [] );

		if ( empty( $regexes ) ) {
			return false;
		}
		
		$regexes = array_filter( $items, 'is_string' );
```

2022-09-16 09:29 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +			if ( preg_match( '/' . $regex . '/', $url ) ) {
@piotrbak will we apply all regexes or only allow (.*) ?

2022-09-16 09:29 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/ClearCache.php
>  			if ( ! $this->is_excluded( $url ) ) {
multiple nested levels are not recommended, try bailout early

2022-09-19 09:05 UTC, piotrbak commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +			if ( preg_match( '/' . $regex . '/', $url ) ) {
Let's keep it with `(.*)` only for now.

2022-09-19 11:43 UTC, piotrbak commented
@CrochetFeve0251 Would it be possible to include the following issue directly in this PR?
https://github.com/wp-media/wp-rocket/issues/5445

It sounds like they're touching exactly the same part of the code and I believe we could solve it by just adding the `Never Cache URLs` values to the new filter.

2022-09-19 13:58 UTC, Tabrisrp requested changes

2022-09-19 13:58 UTC, Tabrisrp commented on inc/Engine/Preload/Admin/Subscriber.php
> +			$input['preload_excluded_uri'] = [];
```suggestion
			$input['preload_excluded_uri'] = [];

			return $input;
```

2022-09-19 13:58 UTC, Tabrisrp commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +	protected function is_excluded_by_filter( string $url ) {
This still needs to be updated

2022-09-21 15:08 UTC, remyperona approved these changes

2022-09-27 13:48 UTC, Mai-Saad commented
Moved to in-progress till we handle [slack](https://wp-media.slack.com/archives/GUT7FLHF1/p1664283914314709) discussion

2022-10-05 12:00 UTC, piotrbak commented
@CrochetFeve0251 Is this one ready to be reviewed again?

2022-10-05 12:01 UTC, CrochetFeve0251 commented
> @CrochetFeve0251 Is this one ready to be reviewed again?
 
@piotrbak it is

2022-10-07 07:38 UTC, vmanthos commented
@CrochetFeve0251 Currently, when any URL is added in the Preload exclusion text area the whole cache is cleared which is not something that should be happening.

This also affects QA testing, for example when trying to check if partial cache clearing will result in the removal of an excluded URL from the database.

Can you please look into this? 🙏 

PS: The PR is in "Ready for review". So whoever reviews it could also check this change as well.

2022-10-07 11:44 UTC, engahmeds3ed requested changes

2022-10-07 11:44 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/ClearCache.php
> +			}
No need to use this check as we already hooking to the filter here: 
https://github.com/wp-media/wp-rocket/pull/5433/files#diff-13bb6ae74d8bc004dd6fbdb9a3d705ceb0c263bb9ffa6e4df10ebc19190589afR116-R119
and add the callback `add_cache_reject_uri` which gets the option values and add to the filter return.

2022-10-07 11:44 UTC, engahmeds3ed commented on inc/Engine/Preload/Subscriber.php
> +		if ( ( isset( $_GET ) && is_array( $_GET ) ) && 0 < count( $_GET ) || ( $this->query->is_pending( $url ) && $this->options->get( 'do_caching_mobile_files', false ) ) ) { //phpcs:ignore WordPress.Se
Simplify it like:

```suggestion
		if ( ! empty( (array) $_GET ) || ( $this->query->is_pending( $url ) && $this->options->get( 'do_caching_mobile_files', false ) ) ) { //phpcs:ignore WordPress.Security.NonceVerification.Recommended
```

2022-10-07 11:44 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +
can we plz make this array unique, we are adding into this filter from two places so we need to make sure that it's unique  and no duplication.
something like
```
$regexes = array_flip( array_flip( $regexes ) );
```

2022-10-07 11:44 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +		$regexes = array_filter( $regexes, 'is_string' );
Here we are looping on the items and get only strings from inside and in the following line we are looping again, why not using the second loop and skip the iteration if it's not a string, that's good from performance wise, what do u think?

2022-10-11 10:15 UTC, engahmeds3ed approved these changes
Just a small minor change, Already approved but would be better to have it.

2022-10-11 10:15 UTC, engahmeds3ed commented on inc/Engine/Preload/Subscriber.php
> +		$preload_excluded_uri = $this->options->get( 'preload_excluded_uri', [] );
```suggestion
		$preload_excluded_uri = (array) $this->options->get( 'preload_excluded_uri', [] );
```

Guard against failure in array_merge if that's not an array.

2022-10-12 10:51 UTC, vmanthos reviewed
@wp-media/php Exclusions are not taken into consideration when they contain a `/`, e.g. `/path`.

This is because we are using `/` as the limiter of the `preg_match()` and we are not escaping the `$regex` here :
https://github.com/wp-media/wp-rocket/blob/13208ce736b2f51b9c26d798a0c10c7e30222f23/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L43

Using `@` as a delimiter fixes that. 

If a URL has a trailing `/` it will not be excluded from preloading because it is checked against the URL without it. This is at least when `update_cache_row()` is executed here:
https://github.com/wp-media/wp-rocket/blob/13208ce736b2f51b9c26d798a0c10c7e30222f23/inc/Engine/Preload/Subscriber.php#L101

`is_excluded_by_filter()` is used in several places. I'm not sure if in all places the `$url` will be without a `/`. These should be checked.

We should make sure that we cover cases like the following:
* `example.com/path?query_string`
*  `example.com/path#anchor`
*  `/path?query_string`
*  `/path#anchor`
* `/path/`
*  `example.com/path/`
* URIs with `http/https`
* the use of `(.*)` in all previous cases

Lastly, while running the `preg_match()` we should take into consideration that the `$regexes` except for what's added in the "Never Cache URL(s)" text area also includes:
```PHP
\/(?:.+\/)?feed(?:\/(?:.+\/?)?)?$|\/(?:.+\/)?embed\/|\/(index\.php\/)?wp\-json(\/.*|$)
```
when caching of the feeds isn't enabled.

2022-10-13 20:03 UTC, Tabrisrp commented
@vmanthos I updated the code a bit following your comment, can you test again?

2022-10-14 06:07 UTC, vmanthos commented
@Tabrisrp When permalinks have a trailing `/` the change works. 

When their structure doesn't have a trailing `/` excluded URLs with a trailing `/` are preloaded.

To wrap things up:
* Permalinks _with_ a trailing `/`: Excluded URLs with or without a trailing `/` will _not_ be preloaded. ✅
* Permalinks _without_ a trailing `/`: Excluded URLs without a trailing `/` will be excluded but those with one will be preloaded. ❌

2022-10-14 13:13 UTC, piotrbak commented
@vmanthos 
```
About URLs containing query strings (example 1), once we allow preloading them using custom sitemaps, we should consider if we'll offer the ability to exclude them using the UI. Of course, customers can edit the sitemaps to remove the ones they don't want to be preloaded.
```
Yes, I believe we should allow the exclusions there, but I think only when they're specified directly like:
`/pariatur-ipsam-reiciendis-aliquam-perferendis-eos-corporis?(.*)`
What do you think?

```
About 2, it may make sense to not preload the URL without the anchor link.
```
Not sure if I understood correctly. Do you think it makes sense to save URLs with the anchor to the DB at all? 🤔

2022-10-14 13:29 UTC, vmanthos commented
> I believe we should allow the exclusions there, but I think only when they're specified directly

This seems good.

> Do you think it makes sense to save URLs with the anchor to the DB at all?

If a URL having an anchor is added to the exclusion area, we should exclude it from preload, i.e. treat it as though it didn't have the anchor link.

2022-10-14 14:11 UTC, Tabrisrp commented
Can we summarize what needs to happen here to get the PR ready?

2022-10-14 14:15 UTC, piotrbak commented
@Tabrisrp The only question here is about how this PR will work together with https://github.com/wp-media/wp-rocket/pull/5491.
This type of exclusions should match, right? `/pariatur-ipsam-reiciendis-aliquam-perferendis-eos-corporis?(.*)` 

I'll send you the description + documentation URLs once confirmed with Lucy and we're 👌 here.

2022-10-14 15:26 UTC, piotrbak commented
@Tabrisrp Here's the detailed wording for this textarea:
**Title:** Exclude URLs (it should be URLs not URI, what do you think?)
**Description:** Specify URLs to be excluded from the preload feature (one per line). More info
**More info links:** 
```
https://docs.wp-rocket.me/article/1721-exclude-urls-from-being-preloaded
6349682bde258f5018eb456d
https://fr.docs.wp-rocket.me/article/1722-exclure-url-du-prechargement
63496d5b8a552811521e52d2
```
**Placeholder:** /author/(.*)
**Below the textarea:** Use (.*) wildcards to address multiple URLs under a given path.
![image](https://user-images.githubusercontent.com/26767037/195883646-01717dc8-1fa3-40ee-892f-0ef455a187ff.png)

2022-10-14 17:03 UTC, Tabrisrp commented
setting field is updated with all the info. For the query string, we can test that in the other PR once we have this merged

2022-10-17 06:24 UTC, vmanthos commented
@Tabrisrp Still, when permalinks don't have a trailing `/` and the exclusion has, the URL is preloaded.

Logging `$regex` and `$url` here:
https://github.com/wp-media/wp-rocket/blob/324bf97608d7dcd5aa92ea3374838256abca508e/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L45

I'm getting:
```PHP
Regex: /consectetur-bibendum-eu/
URL: https://vasilis.rocketlabsqa.ovh/consectetur-bibendum-eu
```

which is why the RegEx doesn't exclude the URL.

`untrailingslashit()` the `$regex` here:
https://github.com/wp-media/wp-rocket/blob/324bf97608d7dcd5aa92ea3374838256abca508e/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L40

works but then we'll have issues if, e.g. a `(.*)` is added after the path.

Can you please take a look into this? 🙏

2022-10-18 06:23 UTC, vmanthos commented
After the latest changes this is working as expected except for this scenario:
* Permalinks settings without a trailing `/`
* Never Cache URLs with a trailing `/` -> preloaded & cached as per #5509.

@piotrbak Is this something that should be handled now?

2022-10-18 08:45 UTC, piotrbak commented
@vmanthos I think we're okay here for now, it's a bit edgy and we already have an issue for that

2022-10-18 08:48 UTC, merged