Closes 2441: Fixed warning when temporary file can't be created
wp-media/wp-rocket pull request #5449
Opened 2022-09-20 08:48 UTC by CrochetFeve0251

## Description
Fixed a problem due to a warning happening when we are moving the temporary file to its final position.
For that we added a check to verify if the file was created before moving it.

Fixes #2441

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Manual Test

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-20 13:28 UTC, Tabrisrp requested changes

2022-09-20 13:28 UTC, Tabrisrp commented on inc/classes/Buffer/class-cache.php
> +		if ( rocket_put_content( $temp_filepath, $content ) ) {
```suggestion
		if ( ! rocket_put_content( $temp_filepath, $content ) ) {
```

2022-09-20 13:28 UTC, Tabrisrp commented on inc/classes/Buffer/class-cache.php
> +			if ( rocket_put_content( $temp_gzip_filepath, gzencode( $content, $compression_level ) ) ) {
```suggestion
			if ( ! rocket_put_content( $temp_gzip_filepath, gzencode( $content, $compression_level ) ) ) {
```

2022-09-21 15:06 UTC, Tabrisrp approved these changes

2022-09-28 12:03 UTC, Mai-Saad reviewed
Can't reproduce the problem here on the test site. However, smoke test for installation, update, and rollback using the terminal is working fine.
If it's working fine on any of the client's sites then we can merge this PR.

2022-10-07 11:31 UTC, merged