Closes 5401: Prevent useless requests when RUCSS and Preload activated
wp-media/wp-rocket pull request #5478
Opened 2022-09-27 15:45 UTC by CrochetFeve0251

## Description
Fix a problem where WP Rocket was preloading pages multiple times when RUCSS was activated.

For that we blocked preload from pages that are loading RUCSS.

Fixes #5401

## Type of change

Please delete options that are not relevant.

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated Tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-28 15:52 UTC, Tabrisrp requested changes

2022-09-28 15:52 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +			do_action( 'rocket_preload_lock_url', $url );
add docblock for action

2022-09-28 15:52 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +				do_action( 'rocket_preload_unlock_url', $row_details->url );
add docblock for action

2022-09-28 15:52 UTC, Tabrisrp commented on inc/Engine/Preload/Subscriber.php
> -			'pre_delete_term'                     => 'delete_term_preload_cache',
this callback should be preserved no?

2022-10-11 15:59 UTC, Tabrisrp approved these changes

2022-10-17 14:31 UTC, Mai-Saad commented
@CrochetFeve0251 @Tabrisrp @piotrbak Please find the exploratory test note below:
With the following scenario, Clear and preload will change the status for locked URLs (the completed URLs while RUCSS still not generated) as the same as it was on the trunk
1- Preload / RUCSS are disabled and nothing in the database
2- Enable Preload and RUCSS
3- Once URL is completed as preload, it is locked and started to be added and  processed in the RUCSS
4- Clear and preload cache => all locked URLS in cache table with status completed and RUCSS not completed yet, Will change to pending, I think that locked URLs status should remain completed till RUCSS is done then it shall change to pending. What do you think? 
https://jmp.sh/Stw5NBv

2022-10-17 15:50 UTC, piotrbak commented
@Mai-Saad I think that's okay.

2022-10-21 08:40 UTC, Mai-Saad commented
@CrochetFeve0251 Can you please check the following scenario? (preload is done on locked URLs)
1- Enable preload and RUCSS
2- Completed cache URL is locked while being processed in RUCSS
3- Clear and preload + run `rocket_preload_process_pending` multiple times
4- The locked URL status will change to pending -> inprogress -> completed although it wasn't completed on RUCSS yet

2022-10-21 12:09 UTC, CrochetFeve0251 commented
> @CrochetFeve0251 Can you please check the following scenario? (preload is done on locked URLs) 1- Enable preload and RUCSS 2- Completed cache URL is locked while being processed in RUCSS 3- Clear and preload + run `rocket_preload_process_pending` multiple times 4- The locked URL cache status will change to pending -> inprogress -> completed although it wasn't completed on RUCSS yet

@Mai-Saad after testing I found that only the homepage have this problem. Do you have this only on that page?

2022-10-24 08:17 UTC, CrochetFeve0251 commented
@Mai-Saad  I think I got what you are saying: At the first loading of the cache the page is still going to complete in the preload.
This is due to the fact we need to generate the cache to launch RUCSS process and that trigger the complete status on the preload.

However if you run others preload request on the URL it won't  preload it. 

Should we prevent the first request to preload too @piotrbak ?

2022-10-24 12:09 UTC, piotrbak commented
@CrochetFeve0251 The first request, when RUCSS is yet not triggered needs to happen. In this PR we cover the following scenario:
1. [domain.com/example](http://domain.com/example) is preloaded
2. It's added to the Used CSS table
3. It's locked until the Used CSS is there
4. We clear [domain.com/example](http://domain.com/example) cache
5. It'll not be preloaded till Used CSS it there
6. Used CSS appears in the database, the lock is set to 0
7. The URL will be preloaded

2022-11-04 13:32 UTC, Tabrisrp approved these changes
There is a conflict to fix in the test class

2022-11-08 11:34 UTC, Mai-Saad approved these changes
Working as expected

2022-11-08 11:35 UTC, merged