Closes #3717 compatibility with wpx hosting
wp-media/wp-rocket pull request #5515
Opened 2022-10-19 12:24 UTC by jeawhanlee

## Description

Adds compatibility with WPX Cloud hosting.

Fixes #3717 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?
Automated tests.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-20 15:28 UTC, CrochetFeve0251 approved these changes

2022-10-21 15:14 UTC, Tabrisrp requested changes

2022-10-21 15:14 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Hostings/WPXCloud/varnishIP.php
> +use WPMedia\PHPUnit\Integration\TestCase;
```suggestion
use WP_Rocket\Tests\Integration\TestCase;
```

2022-10-21 15:14 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Hostings/WPXCloud/varnishIP.php
> +	 * @dataProvider providerTestData
```suggestion
	 * @dataProvider configTestData
```

2022-10-21 15:14 UTC, Tabrisrp commented on tests/Integration/inc/ThirdParty/Hostings/WPXCloud/varnishIP.php
> +	}
```suggestion
```

2022-10-25 13:17 UTC, Tabrisrp approved these changes

2022-11-01 07:09 UTC, vmanthos commented
@jeawhanlee After discussing this with Piotr, the Varnish add-on should be automatically enabled when we detect the site is hosted on WPX. We are doing this already for Cloudways:
https://github.com/wp-media/wp-rocket/blob/develop/inc/ThirdParty/Hostings/Cloudways.php

Also, while purging the whole cache works fine, partial and homepage cache clearing isn't working.

I logged the `$url` and `$args` we use here:
https://github.com/wp-media/wp-rocket/blob/14eab568207523ee0207a0e09f07d48e99db4edf/inc/Addon/Varnish/Varnish.php#L94

```PHP
[ 2022-11-01 05:45:20 ] Purge URL: http://127.0.0.1:6081/hello-world/.*
Array
(
    [method] => PURGE
    [blocking] => false
    [redirection] => 0
    [headers] => Array
        (
            [host] => wpxnew.rocketlabsqa.ovh
            [X-Purge-Method] => regex
        )

)

[ 2022-11-01 05:45:20 ] Purge URL: http://127.0.0.1:6081/
Array
(
    [method] => PURGE
    [blocking] => false
    [redirection] => 0
    [headers] => Array
        (
            [host] => wpxnew.rocketlabsqa.ovh
            [X-Purge-Method] => default
        )

)
```

I tried different combinations of scheme and regex but the Varnish cache wasn't purged. 
@piotrbak you may need to reach out to WPX and check if there is anything wrong with the requests we sent.

2022-11-01 08:22 UTC, alxtv commented
Alex from WPX here:

@vmanthos The issue with purging homepage and partial cache has been resolved. 

Can you please try again ?

2022-11-01 09:06 UTC, vmanthos commented
Thank you @alxtv!

Indeed, both partial cache clearing and homepage cache clearing is working as expected. 🎉

2022-11-01 11:50 UTC, vmanthos commented
@alxtv WP Rocket's preload feature isn't working on our test site on wpx.net. 

We are using `WP Rocket/Preload` as the user agent and requests from that have an `error 403`:
```
45.77.227.117 5.254.55.39 - [01/Nov/2022:11:37:19 +0000] "GET /hello-world/ HTTP/1.1" 403 1074 "https://wpxnew.rocketlabsqa.ovh/hello-world/" "WP Rocket/Preload" "-" 0 
45.77.227.117 5.254.55.39 - [01/Nov/2022:11:37:19 +0000] "GET /will-it-purge/ HTTP/1.1" 403 1074 "https://wpxnew.rocketlabsqa.ovh/will-it-purge/" "WP Rocket/Preload" "-" 0 
45.77.227.117 5.254.55.39 - [01/Nov/2022:11:37:20 +0000] "GET /sample-page/ HTTP/1.1" 403 1074 "https://wpxnew.rocketlabsqa.ovh/sample-page/" "WP Rocket/Preload" "-" 0 
45.77.227.117 5.254.55.39 - [01/Nov/2022:11:37:20 +0000] "GET /category/uncategorized/ HTTP/1.1" 403 1074 "https://wpxnew.rocketlabsqa.ovh/category/uncategorized/" "WP Rocket/Preload" "-" 0 
```

Would you mind taking a looking? If I have to reach out to someone else about this, please let me know who that is. 🙏

2022-11-01 12:22 UTC, alxtv commented
@vmanthos We have "disabled" the preload feature by default a long time ago as it caused high CPU usage for many websites (websites with thousands auto-generated posts/pages, sites using some unoptimized/bad-coded plugins/themes, sites with many products or big databases and etc).
We are enabling it on request via support ticket or livechat.

I've enabled it for your website so you can check if everything works fine.

I see that the description in error_log is not accurate so I've updated it too.

2022-11-01 12:34 UTC, vmanthos commented
Thank you very much for the quick response and for the explanation, @alxtv!

Preloading works now.

Maybe we can work together (pinging @piotrbak) to investigate cases like the one you described so you don't have to disable preload for our common customers.

2022-11-01 12:43 UTC, alxtv commented
Sure, we can discuss this via email.

We're open to work on this and find a better solution for the cache preload feature.

We are planning to do new round of performance/speed tests and comparisons once these changes are included in the plugin so additionally I will include the Preload feature in tests and see how it works now with different setups.
Will provide you with feedback once we have some results.

2022-11-01 13:29 UTC, Tabrisrp approved these changes

2022-11-02 06:51 UTC, vmanthos approved these changes
This is working as expected. 👍

2022-11-02 06:52 UTC, merged