This line is not needed since #3483
wp-media/wp-rocket pull request #5575
Opened 2022-11-16 17:33 UTC by dgwatkins

This PR is specifically for 'WooCommerce Multilingual' compatibility, the WPML add-on for WooCommerce. 

## Description

Since #3483, where we added multicurrency support, we no longer need to add the currency URL argument.

- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- Setup WooCommerce, WooCommerce Multilingual & wp-rocket
- Use a theme like storefront that has a mini-cart
- Setup Multicurrency with at least one more currency
- Create a product
- In an incognito window, visit the product page
- add to the cart
- Switch to secondary currency
- There shouldn't be an argument in the URL - e.g. ?wcmlc=USD
- Both the product price and the minicart should have switched currency
- Switch back to the default currency
- Both the produce price and the minicart should have switched currency

2022-12-05 16:36 UTC, piotrbak commented
Hello @dgwatkins and thanks for creating the PR and for the testing steps. We'll do QA based on the provided scenario.

2022-12-05 18:35 UTC, Tabrisrp approved these changes

2022-12-08 10:10 UTC, Mai-Saad commented
Working as expected with the following notes.
- Since the PR branch is not synced with the dev branch, We added the change on the dev branch locally and used that zip
- On [https://vasilis.rocketlabsqa.ovh/](https://vasilis.rocketlabsqa.ovh/) test site, for some reason, when we change the currency at WCML, We aren't rewriting cookies at our config file (same while using WPR 3.10.8 )   => Same scenario is working fine on new labs (recommend further investigation at Vasilis test site)
- Sometimes, with certain setups for WCML, the mini cart currency is not matching product currency (same on the trunk) => using this plugin will fix the problem [WP Rocket | Deactivate WooCommerce Refresh Cart Fragments Cache](https://docs.wp-rocket.me/article/1100-optimize-woocommerce-get-refreshed-fragments)
[testrail-report-430.pdf](https://github.com/wp-media/wp-rocket/files/10184327/testrail-report-430.pdf)

2022-12-08 11:13 UTC, vmanthos commented
> On https://vasilis.rocketlabsqa.ovh/ test site, for some reason, when we change the currency at WCML, We aren't rewriting cookies at our config file

This isn't related to WP Rocket. The `wcml_currency_mode` option doesn't change in the database when changing the respective setting in the WCML's UI.

2022-12-08 14:32 UTC, Tabrisrp requested changes

2022-12-08 14:32 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/I18n/WPML.php
>  			'rocket_preload_sitemap_before_queue'          => 'add_languages_sitemaps',
```suggestion
			'rocket_rucss_is_home_url'                          => [ 'is_secondary_home', 10, 2 ],
			'rocket_preload_all_to_pending_condition' => 'clean_only_right_domain',
			'rocket_preload_sitemap_before_queue'     => 'add_languages_sitemaps',
```

2022-12-08 14:35 UTC, remyperona requested changes

2022-12-08 14:35 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/I18n/WPML.php
> +			'rocket_rucss_is_home_url'                          => [ 'is_secondary_home', 10, 2 ],
```suggestion
			'rocket_rucss_is_home_url'                => [ 'is_secondary_home', 10, 2 ],
```

2022-12-08 20:13 UTC, merged