Closes #4773 Clear cache partially for never cache urls
wp-media/wp-rocket pull request #5581
Opened 2022-11-18 12:01 UTC by jeawhanlee

## Description
Closes issue of global cache clearing for Never Cache URL(s)

Fixes #4773 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
Slightly

We also needed to consider patterns and also get the full url using the path.

## How Has This Been Tested?

Automated & Manual Test

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-11-22 15:45 UTC, Tabrisrp requested changes
I think that's a good start, but I would recommend 2 things to improve:
- Add this to a class instead of creating a new function (could be on the settings class and subscriber for example)
- Use BerlinDB (our DB dependency) to do the request to the cache table

2022-11-28 15:37 UTC, Tabrisrp requested changes

2022-11-28 15:37 UTC, Tabrisrp commented on inc/Engine/Preload/Database/Queries/Cache.php
> +
@engahmeds3ed Do you think it's the best way to do this query using BerlinDB? You have more experience with it than me

2022-11-28 15:37 UTC, Tabrisrp commented on inc/Engine/Cache/Purge.php
> +	public function purge_cache_reject_uri_partially( $old_value, $value ): void {
In the subscriber you typecast the parameters, and here you don't, both should be the same for consistency

2022-11-28 15:37 UTC, Tabrisrp commented on inc/Engine/Cache/Purge.php
> +		}
if you typecast the parameters to array, this is not needed

2022-12-05 15:32 UTC, Tabrisrp approved these changes

2022-12-09 14:24 UTC, vmanthos commented
@jeawhanlee Doing exploratory testing I found that when in the **Never Cache URLs** text area I added `/hello(.*)`, although the correct URL was found here:
https://github.com/wp-media/wp-rocket/blob/e50db622d4b53767d2620a5d510018acfc4bea16/inc/Engine/Cache/Purge.php#L303

the whole cache was cleared.

Can you please look into this? 🙏

2023-01-10 12:58 UTC, Tabrisrp approved these changes

2023-01-12 10:39 UTC, vmanthos commented
This is working as expected in terms of not clearing the whole cache when adding URL(s) in the Never Cache URL(s) text area.

Because of [this issue](https://github.com/wp-media/wp-rocket/issues/491#issuecomment-1162916459) when:
1. Permalinks don't have a trailing `/`.
2. There are query strings, e.g. `location`, in the "Cache Query String(s)" text area.
3. `/hello-world?location=Paris` is cached (in `/cache/wp-rocket/example.com/hello-world#location=Paris`).

Excluding, e.g. `/hello-world` will not clear the cache file from step 3.

Regardless of this, visiting `/hello-world?location=Paris` will fetch the non-cached page. 

Unless the whole cache is cleared, removing `/hello-world` from the exclusion text area will result in serving the old cache file when visiting `/hello-world?location=Paris`.

@piotrbak Should we fix #491 before releasing this one?

2023-01-12 11:03 UTC, piotrbak commented
@vmanthos I think this is a bit edgy, we can move forward without that fix. For the query strings and clearing cache we already more issues, we should probably tackle all of them at once.

2023-01-12 11:16 UTC, vmanthos approved these changes
Following Piotr's comment, this PR is :+1: .

2023-01-20 14:29 UTC, merged