Closes #5599 The /feed/ url is cached and optimized by default on 3.12.3.2
wp-media/wp-rocket pull request #5604
Opened 2022-12-01 10:18 UTC by jeawhanlee

## Description
Fixes the issue where trailing slash is appended to non user defined patterns for cache_reject_uri.

Fixes #5599 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?
Automated and Manual Tests.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-12-01 16:16 UTC, Tabrisrp requested changes
The value in the option should be updated before saving it to the DB, not when serving it from the DB.

We want the change to be reflected in the UI for this field

2022-12-05 15:28 UTC, Tabrisrp requested changes

2022-12-05 15:28 UTC, Tabrisrp commented on inc/Engine/Cache/Config/ConfigSubscriber.php
> +		update_rocket_option( 'cache_reject_uri', $cache_reject_uri );
We could use our Options and Options_Data classes instead of the helper functions

2022-12-05 15:28 UTC, Tabrisrp commented on inc/Engine/Cache/Config/ConfigSubscriber.php
> +	 * @param array|mixed $old_value Old values.
```suggestion
	 * @param mixed $value The new, unserialized option value.
	 * @param mixed $old_value The old option value.
```

2022-12-05 18:34 UTC, remyperona approved these changes

2022-12-06 08:35 UTC, vmanthos commented
@jeawhanlee I run tests and found that when:
1. the permalinks don't have a `/` and
2. in the **Never Cache URLs** text area `/` was added to prevent caching of the homepage

the `/` is removed so caching of the homepage takes place. This isn't happening with `trunk` or when the permalinks include a trailing `/`.

Can you please look into this?

**Note**

This is to have a reference of the [the index.php issue](https://github.com/wp-media/wp-rocket/issues/678) reported [here](https://github.com/wp-media/wp-rocket/issues/5599#issuecomment-1335678072).

When permalinks:
1. have a trailing `/`and 
2. the `/cache/wp-rocket/example.com/index.php/` folder  is created manually, the non-cached pages are redirected to the homepage.

**Slack discussion:** https://wp-media.slack.com/archives/GUT7FLHF1/p1670251431739879

2022-12-08 11:21 UTC, mostafa-hisham approved these changes

2022-12-08 12:00 UTC, engahmeds3ed requested changes

2022-12-08 12:00 UTC, engahmeds3ed commented on inc/Engine/Cache/Config/ConfigSubscriber.php
> +	public function match_pattern_with_permalink_structure( array $patterns ): array {
```suggestion
	private function match_pattern_with_permalink_structure( array $patterns ): array {
```

2022-12-08 12:00 UTC, engahmeds3ed commented on inc/Engine/Cache/Config/ConfigSubscriber.php
> +			'pre_update_option_' . WP_ROCKET_SLUG => [ 'change_cache_reject_uri_with_permalink', 10, 2 ],
```suggestion
			'pre_update_option_' . rocket_get_constant( 'WP_ROCKET_SLUG', 'wp_rocket_settings' ) => [ 'change_cache_reject_uri_with_permalink', 10, 2 ],
```
what do u think

2022-12-08 12:00 UTC, engahmeds3ed commented on tests/Fixtures/inc/Engine/Cache/Config/ConfigSubscriber/changeCacheRejectUriWithPermalink.php
> +<?php
(That's a dev matter so it won't affect the PR itself and not a blocker)
I know that you need to write less code and not to duplicate ourselves but this fixture isn't readable for me, I believe you need to make it simpler by writing the pattern manually for each case below, so it'd be easier for anyone to add cases whenever u want

2022-12-08 13:20 UTC, vmanthos approved these changes
This is working as expected now.

**Note**
[The exclusion](https://github.com/wp-media/wp-rocket/issues/5599#issuecomment-1335678072) of `index.php` will not work in [some cases](https://github.com/wp-media/wp-rocket/issues/5599#issuecomment-1335678072).

After internal discussion, we decided that that's fine since we recommend excluding `/index.php` in our docs.

2022-12-08 13:21 UTC, merged