Added new logic for the preload queue
wp-media/wp-rocket pull request #5628
Opened 2022-12-14 16:48 UTC by CrochetFeve0251

## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-15 10:30 UTC, jeawhanlee approved these changes

2022-12-15 15:18 UTC, Tabrisrp requested changes

2022-12-15 15:18 UTC, remyperona commented on inc/Engine/Preload/Database/Queries/Cache.php
> +	public function revert_old_failed() {
Maybe update the method name and description to `set_failed()` or something like that

2022-12-19 13:47 UTC, CrochetFeve0251 commented on inc/Engine/Preload/Database/Queries/Cache.php
> +	public function revert_old_failed() {
I updated the doc that wasn't up to date.

2022-12-20 13:02 UTC, jeawhanlee approved these changes

2023-01-04 06:40 UTC, Mai-Saad commented
We need to increase the 2mins and get feedback [here](https://wp-media.slack.com/archives/GUT7FLHF1/p1672757821546629).

2023-01-04 17:01 UTC, piotrbak commented
I'm thinking, maybe we could make the [value](https://github.com/wp-media/wp-rocket/pull/5628/files#diff-30a46cf1cdbb73aeb3f9cc7171e0088ad71307d47bd27d32e548e2aab0f1d540R650) of `2 minutes` auto-adjustable and also introduce the filter there. Let's say the value could be:

`rocket_preload_cache_pending_jobs_cron_rows_count` / `15` = [value](https://github.com/wp-media/wp-rocket/pull/5628/files#diff-30a46cf1cdbb73aeb3f9cc7171e0088ad71307d47bd27d32e548e2aab0f1d540R650) 

And the `value` could be filtered for advanced cases, it'd need to return the `int`, always. We could also probably use the same `value` as a schedule for this cron.

With the above example:
1. With default `rocket_preload_cache_pending_jobs_cron_rows_count`, we'd catch URLs that are in `in-progress` state for 3 minutes. Cron schedule would run each 3 minutes too.
2. With `rocket_preload_cache_pending_jobs_cron_rows_count` set to 450, we'd catch URLs that are in `in-progress` state for 30 minutes. Cron schedule would run each 30 minutes too.

Not sure what would be the best value, 15 sounds reasonable, but we might think about the different one. What do you think @CrochetFeve0251 @wp-media/php ?

2023-01-09 10:25 UTC, CrochetFeve0251 commented
> I'm thinking, maybe we could make the [value](https://github.com/wp-media/wp-rocket/pull/5628/files#diff-30a46cf1cdbb73aeb3f9cc7171e0088ad71307d47bd27d32e548e2aab0f1d540R650) of `2 minutes` auto-adjustable and also introduce the filter there. Let's say the value could be:
> 
> `rocket_preload_cache_pending_jobs_cron_rows_count` / `15` = [value](https://github.com/wp-media/wp-rocket/pull/5628/files#diff-30a46cf1cdbb73aeb3f9cc7171e0088ad71307d47bd27d32e548e2aab0f1d540R650)
> 
> And the `value` could be filtered for advanced cases, it'd need to return the `int`, always. We could also probably use the same `value` as a schedule for this cron.
> 
> With the above example:
> 
>     1. With default `rocket_preload_cache_pending_jobs_cron_rows_count` (45) value, we'd catch URLs that are in `in-progress` state for 3 minutes. Cron schedule would run each 3 minutes too.
> 
>     2. With `rocket_preload_cache_pending_jobs_cron_rows_count` set to 450, we'd catch URLs that are in `in-progress` state for 30 minutes. Cron schedule would run each 30 minutes too.
> 
> 
> Not sure what would be the best value, 15 sounds reasonable, but we might think about the different one. What do you think @CrochetFeve0251 @wp-media/php ?

The filter and calculating the delay is a good idea.
However there is no CRON for this task as we run it with the preload.

2023-01-09 12:04 UTC, piotrbak commented
@CrochetFeve0251 Is it ready for QA?

2023-01-09 14:40 UTC, remyperona approved these changes

2023-01-10 15:01 UTC, Mai-Saad commented
For CR and further test:
The last change [e3523dd](https://github.com/wp-media/wp-rocket/pull/5628/commits/e3523ddf08e3d26da1f682fb36470e80e0f82d13) was mainly to fix the following problem/scenario:
Brief description=> changing status is not changing modified nor last accessed then when we process URL, mostly the modified/last accessed > 3min (default time to switch in progress to failed if not succeeded) => This will cause many URLs to be switched to failed although we didn't send the request for the URL then will be completed
Steps:
1- we did clear and preload so the time of each entry now not changed => mostly > 3mins
2- We change the status to inprogress => time still not changed => why not change last modified in this case?
3- After 3min we do our check and send all inprogress things to failed even if no request is sent
4- After a while request is sent and the status change to completed => time change here
![Screenshot from 2023-01-10 06-27-27](https://user-images.githubusercontent.com/76941962/211584957-a991d2ef-bc54-476a-ab2d-d8911cee4f58.png)
![Screenshot from 2023-01-10 06-26-06](https://user-images.githubusercontent.com/76941962/211584967-16e91c34-c7ca-4da1-b50e-3350ec2dd225.png)
![Screenshot from 2023-01-10 06-17-42](https://user-images.githubusercontent.com/76941962/211584972-70d4bdbd-10dd-4813-9231-b59e9756cc72.png)
![Screenshot from 2023-01-10 06-18-35](https://user-images.githubusercontent.com/76941962/211584974-31a45fa4-54d2-452e-8e7c-4a7ba1c9bce8.png)

**Notes:** 
- The change above fixed this problem but currently we change the last accessed when changing the status from pending to inprogress or from inprogress to failed/completed
- As per team discussion => modified shall change whenever we change item(s) in the row while last accessed whenever we receive a response for URL (page got cached) => @engahmeds3ed can you please confirm?

2023-01-11 11:34 UTC, engahmeds3ed requested changes

2023-01-11 11:34 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		if ( ! $rows || count( $rows ) === 0 ) {
No Need to check the count here because we return false from `get_rows_by_url` method if there is no available rows.

2023-01-11 11:34 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		$row = array_pop( $rows );
Are we using `array_pop` to get only mobile row or what?
from what I know, `get_rows_by_url` returns two rows, one for desktop version and the other for mobile version, right?
So Which one do we need to update last accessed?

2023-01-11 11:34 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		$this->query->update_last_access( $row->id );
Why not letting the cache creation process handle this last accessed column?
did u do that Because of hosts with their own cache or what?

2023-01-11 11:34 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		}
I believe having a dedicated method hooked to CRON hook `rocket_preload_process_pending` would be better to reflect the proper method name like what we do now here:
https://github.com/wp-media/wp-rocket/blob/b1857bdb42d48b7c1aed2aaeec413bfdc3e5a3b0/inc/Engine/Preload/Cron/Subscriber.php#L56-L57

what do u think?

2023-01-11 11:34 UTC, engahmeds3ed commented on inc/Engine/Preload/Database/Queries/Cache.php
> +				'last_accessed' => current_time( 'mysql', true ),
I believe `last_accessed` should be set when we try to access this page but now it's set every time we change the status and this isn't reflecting its name so why do we need to set the last_accessed here?

2023-01-11 11:34 UTC, engahmeds3ed commented on inc/Engine/Preload/Database/Queries/Cache.php
> +		);
this is the query class so I don't like having WP hooks here, try sending this value as a method argument.
If you moved this code here:
https://github.com/wp-media/wp-rocket/blob/f20d0c189ca6ce6c099ae5bbde0ade2b9a420a7f/inc/Engine/Preload/Controller/PreloadUrl.php#L191

You will take benefit of having the filter `rocket_preload_cache_pending_jobs_cron_rows_count` not used twice:
https://github.com/wp-media/wp-rocket/blob/f20d0c189ca6ce6c099ae5bbde0ade2b9a420a7f/inc/Engine/Preload/Controller/PreloadUrl.php#L196

2023-01-11 11:34 UTC, engahmeds3ed commented on inc/Engine/Preload/Database/Queries/Cache.php
> +						'column' => 'last_accessed',
why not dealing here with the modified column?

2023-01-11 13:34 UTC, CrochetFeve0251 commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		}
The idea there was to run it before processing pending jobs to make sure it sure we won't make `in-progress` stucked longer than expected.

2023-01-12 15:06 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/PreloadUrl.php
> +		}
Yes, this can be achieved by hooks priorities as well.
Thanks Cyrille.

2023-01-12 15:18 UTC, engahmeds3ed requested changes
Looks amazing, just small enhancements.

2023-01-12 15:18 UTC, engahmeds3ed commented on inc/admin/upgrader.php
> +
Why not moving this code to the subscriber with the hook `wp_rocket_upgrade` ?
Also before clearing this schedule, we need to check if it's scheduled or not.

2023-01-12 15:18 UTC, engahmeds3ed commented on inc/Engine/Preload/Database/Queries/Cache.php
> +				'modified' => current_time( 'mysql', true ),
if we are using berlinDB update_item method, no need to set the modified column, berlinDB will do that for us.

2023-01-13 11:00 UTC, mostafa-hisham approved these changes

2023-01-13 13:19 UTC, Mai-Saad commented
This cron is not deleted after deleting WPR `rocket_preload_revert_old_failed_rows` and modified only changes when the completed status is the same as last accessed.

2023-01-13 13:42 UTC, CrochetFeve0251 commented on inc/Engine/Preload/Database/Queries/Cache.php
> +				'modified' => current_time( 'mysql', true ),
@engahmeds3ed look like this is not working so I reverted back changes

2023-01-16 14:59 UTC, Tabrisrp approved these changes

2023-02-01 13:26 UTC, Mai-Saad commented
Working fine now

2023-02-01 13:27 UTC, Mai-Saad approved these changes

2023-02-01 13:41 UTC, merged