Closes #5654 Update WebP detection for browsers missing Accept headers data
wp-media/wp-rocket pull request #5664
Opened 2023-01-05 16:12 UTC by Tabrisrp

## Description

This PR refactors the WebP class to split it in multiple classes to reduce complexity and bring it in the new architecture.

It also add new detection for browsers missing Accept headers data, most notably Apple devices on newer versions of Safari.

Fixes #5654

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-12 08:52 UTC, CrochetFeve0251 commented on inc/Addon/WebP/AbstractWebp.php
> +			if ( ! is_a( $plugin, '\WP_Rocket\Subscriber\Third_Party\Plugins\Images\Webp\Webp_Interface' ) ) {
@Tabrisrp maybe we can use the ::class attribute here?

2023-01-20 14:28 UTC, CrochetFeve0251 approved these changes

2023-01-26 12:57 UTC, vmanthos commented
@Tabrisrp I merged `develop` to this PR locally and then I tested it.

We are not rewriting images to their WebP counterparts. This is because the path here is wrong:
https://github.com/wp-media/wp-rocket/blob/3c2bd70b49c1331b1ca1a535064ac937f321ea53/inc/Addon/WebP/Subscriber.php#L426

Instead of being `/var/www/example.com/wp-content/uploads/2022/12/01/image.jpg` that's `/var/www/example.com/wp-contentuploads/2022/12/01/image.jpg`, i.e. there is a missing `/` after `wp-content`.

This is coming from here:
https://github.com/wp-media/wp-rocket/blob/3c2bd70b49c1331b1ca1a535064ac937f321ea53/inc/Addon/WebP/Subscriber.php#L408

Can you please take a look into this?

You can see this happening here:
https://mega.wp-rocket.me/divi/webp-testing/

2023-01-26 15:00 UTC, Tabrisrp commented
@vmanthos Thanks, it's fixed with the latest commit

2023-01-27 07:17 UTC, vmanthos commented
@Tabrisrp Thank you for the fix. WebP-containing cached pages are correctly generated now.
However, on Safari `jpg` images are still served. 

I saw that you created methods to detect if `is_browser_webp_compatible()` in `WP_Rocket\Addon\WebP`, but I didn't see any change related to how we are serving the `webp` file. Shouldn't that method be used here?
https://github.com/wp-media/wp-rocket/blob/eb7de8265f190f1efd4d14865b0da15f68c5303d/inc/classes/Buffer/class-cache.php#L589-L625

I'm surely missing something here. Can you please look into this?

2023-01-29 21:33 UTC, piotrbak commented
@Tabrisrp Is it ready for the next CR or should it go to QA directly?

2023-02-07 13:44 UTC, engahmeds3ed requested changes
Minor discussion points

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AbstractWebp.php
> +	 * @since 3.4
```suggestion
	 * @since 3.12.6
```

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AbstractWebp.php
> +		foreach ( $webp_plugins as $i => $plugin ) {
```suggestion
		foreach ( $webp_plugins as $plugin_key => $plugin ) {
```

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AbstractWebp.php
> +				continue;
We don't need to use continue here as it's already the end of the loop iteration, what do u think?

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AbstractWebp.php
> +	 * @since 3.4
```suggestion
	 * @since 3.12.6
```

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AbstractWebp.php
> +		return \rocket_is_plugin_active( $plugin_basename );
```suggestion
		if ( doing_action( 'deactivate_' . $plugin_basename ) ) {
			return false;
		}

		if ( doing_action( 'activate_' . $plugin_basename ) ) {
			return true;
		}

		return rocket_is_plugin_active( $plugin_basename );
```

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AbstractWebp.php
> +	 * @since 3.4
```suggestion
	 * @since 3.12.6
```

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AdminSubscriber.php
> +	public function webp_section_description( $cache_webp_field ) {
very complex method, I don't know if moving each block to its own private method is in the scope of this PR or not but I think this will help us understanding this part more and change it when needed, what do u think?

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/AdminSubscriber.php
> +	 * @since 3.4
```suggestion
	 * @since 3.12.6
```

2023-02-07 13:44 UTC, engahmeds3ed commented on inc/Addon/WebP/Subscriber.php
> +		$has_webp = apply_filters( 'rocket_page_has_hebp_files', $has_webp, $html );
I know that this filter was there before this refactoring but I believe there is a typo on the filter name and u solved it for variable name, I'm not sure we can change that and deprecate the old name, what do u think?
```suggestion
		$has_webp = apply_filters( 'rocket_page_has_webp_files', $has_webp, $html );
```

2023-02-08 19:07 UTC, Tabrisrp commented on inc/Addon/WebP/AdminSubscriber.php
> +	public function webp_section_description( $cache_webp_field ) {
I don't like it but it's also out of scope

2023-02-09 14:01 UTC, engahmeds3ed approved these changes

2023-02-10 11:11 UTC, vmanthos commented
@Tabrisrp I tested the PR using browserstack.com and found that WebP images are served to the latest Safari version but they are not served to:
1. Previous Safari versions that support WebP images, i.e.  Safari 14-15.6 on MacOS 11 Big Sur or later.
2. Mobile Safari versions that support WebP Images, i.e. versions 14 onward.

For the 1, we don't have RegEx's to find their user agents. Here are some of them:
**Big Sur/Safari 14.1**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15`

**Monterey/Safari 15.6**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15`

For number 2, we do detect the user agent here:
https://github.com/wp-media/wp-rocket/blob/1d6e3dc00e6b91b0be65cc03da603bb5a8bfdd3c/inc/classes/Buffer/class-cache.php#L665-L669

but when we check this:
https://github.com/wp-media/wp-rocket/blob/1d6e3dc00e6b91b0be65cc03da603bb5a8bfdd3c/inc/classes/Buffer/class-cache.php#L671-L674

that matches the mobile user agent as well and bails out:
https://regex101.com/r/Dv7yqC/1

Can you please look into these? :pray:

2023-02-10 16:30 UTC, Tabrisrp commented
Don't those versions have the WebP hint in their Accept header?

2023-02-10 16:39 UTC, vmanthos commented
It seems they don't, at least not on browser stack.com where I checked. By the way, this wasn't working with trunk either.

2023-02-10 17:39 UTC, Tabrisrp commented
I fixed case 2.

For case 1 we don't have a way to detect the OS, the user agent doesn't give the correct information (it's outdated).

2023-02-13 12:13 UTC, piotrbak commented
@vmanthos Sounds like we don't have a way there. We should be fine with it

2023-02-13 14:30 UTC, vmanthos commented
@Tabrisrp I believe we need to change the `Cache::is_user_agent_compatible()` method as well. 

Currently, if a Safari that supports WebP images accesses a non-cached URL, we are creating a cached file that includes `webp` images but doesn't have `-webp` in its filename.

2023-02-13 16:22 UTC, Tabrisrp commented
Thank you, updated that too

2023-02-14 08:01 UTC, vmanthos commented
@Tabrisrp Thank you for the update.

With the latest changes the only thing preventing serving WebP images to `13 < Safari < 16` is this conditional:
https://github.com/wp-media/wp-rocket/blob/3c6a68b8e747021c1c1a74ea409db7e824fa46a9/inc/classes/Buffer/class-cache.php#L674

Setting that to `14` allowed WP Rocket to serve the `-webp` cache file to Safari both on MacOS and iPads which share the same user agents:
```
iPad 8th / Safari 14.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

iPad / Safari 15.3
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15

Monterey / Safari 15.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15

Bigsur / Safari 14.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15

Catalina / Safari 13.1.2 (not supporting WebP)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
```
By the way, Safari 15.6.1 is available for [Catalina](https://www.macrumors.com/2022/08/18/safari-security-update-macos-big-sur-catalina/). This isn't available on browserstack.com to test, but that should work fine with the WebP cache.

Of course, this should be changed as well:
https://github.com/wp-media/wp-rocket/blob/562dd77c3b0af0d17ede87308213d91f586e751c/inc/Addon/WebP/Subscriber.php#L278

2023-02-14 14:23 UTC, Tabrisrp commented
Isn't Safari compatible with WebP only from Safari 16 on macOS?

2023-02-14 14:28 UTC, vmanthos commented
> Isn't Safari compatible with WebP only from Safari 16 on macOS?

No. Safari started supporting WebP images in v14:
https://caniuse.com/webp

2023-02-14 14:31 UTC, Tabrisrp commented
I'm failing to see what pattern we can use to detect Safari 14 or higher, only on Big Sur or higher

2023-02-14 15:28 UTC, vmanthos commented
@Tabrisrp I tested Safari 15.6.1 on Catalina which preceded Big Sur and WebP images are loaded there:
![image](https://user-images.githubusercontent.com/193660/218781616-2c1b580c-f05f-4f73-a842-dc5d171ef31e.png)

From this, it's safe to assume that regardless of the MacOS version if Safari >= 14 is used WebP images are supported.

@piotrbak Should we apply the changes I mentioned here?
https://github.com/wp-media/wp-rocket/pull/5664#issuecomment-1429290574

2023-02-14 15:47 UTC, piotrbak commented
@vmanthos Was this image loaded and displayed correctly? If so, we can proceed.

2023-02-14 15:56 UTC, vmanthos commented
> Was this image loaded and displayed correctly?

It was the first time I checked. I double-checked to make sure I didn't miss anything and it's not displayed. :disappointed: 
I'm not sure what happened the first time around. ¯\_(ツ)_/¯

So, unfortunately, this is a no-go as it seems that Big Sur is indeed a requirement.

2023-02-14 17:19 UTC, vmanthos approved these changes
This is working as expected. :+1: 

**NOTES**

The `-webp` cached files will _NOT_ be served to:
* Desktop Safari versions `< 16`
* iPad Safari versions `< 16`
* iPhone Safari versions `< 14`

2023-02-14 17:20 UTC, merged