Closes 5533 & 5424 Detect use of Perfmatters and RapidLoad used css
wp-media/wp-rocket pull request #5669
Opened 2023-01-10 12:44 UTC by jeawhanlee

## Description
This PR detects the use of Perfmatters and RapidLoad used css and disable the rucss option.

Fixes #5533
Fixes #5424 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?
Automated Tests

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-10 17:46 UTC, CrochetFeve0251 approved these changes

2023-01-11 10:14 UTC, vmanthos reviewed
This PR is working as expected, i.e. Remove Unused CSS is disabled and a notice is displayed when Perfmatters' Remove Unused CSS or RapidLoad Power-Up for Autoptimize is enabled.

**Notes**

1. In the Perfmatters notice, instead of using `Removing Unused CSS is currently activated in` we should use `Remove Unused CSS is currently activated in` to match the name of their feature.

2. For `RapidLoad Power-Up for Autoptimize` we display this:
> Removing Unused CSS is currently activated in Autoptimize's RapidLoad. If you want to use WP Rocket's Remove Unused CSS feature, disable this option in Autoptimize's RapidLoad.

Taking account the description on RapidLoad Power-Up for Autoptimize [plugin's page](RapidLoad Power-Up for Autoptimize), I suggest we change the notice to:

> Automated unused CSS removal is currently activated in RapidLoad Power-Up for Autoptimize. If you want to use WP Rocket's Remove Unused CSS feature, disable this option in RapidLoad Power-Up for Autoptimize.

3. In the case of RapidLoad Power-Up for Autoptimize, WP Rocket's Remove Unused CSS will be disabled even if someone hasn't actually connected their rapidload.io account, in which case unused CSS still exists.

Ideally, we should disable our feature only when theirs is applied.

2023-01-11 12:06 UTC, piotrbak commented
@vmanthos @jeawhanlee Agreed with the wording.

For the 3rd point, @jeawhanlee do we have an easy option to see if their option is **really** activated?

2023-01-11 12:39 UTC, jeawhanlee commented
> @vmanthos @jeawhanlee Agreed with the wording.
> 
> For the 3rd point, @jeawhanlee do we have an easy option to see if their option is **really** activated?

@piotrbak I'll check this...

2023-01-16 15:12 UTC, Tabrisrp requested changes

2023-01-16 15:12 UTC, Tabrisrp commented on inc/Engine/Admin/Settings/Page.php
> +			'rocket_maybe_disable_rucss',
```suggestion
			'rocket_disable_rucss_setting',
```

2023-01-16 15:12 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/Perfmatters.php
> +			'rocket_maybe_disable_rucss'              => 'disable_rucss_option',
```suggestion
			'rocket_disable_rucss_setting'              => 'disable_rucss_setting',
```

2023-01-16 15:12 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/Perfmatters.php
> +	public function disable_rucss_option( array $status ): array {
```suggestion
	public function disable_rucss_setting( array $status ): array {
```

2023-01-16 15:12 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/Perfmatters.php
> +	 * Disable RUCSS option.
```suggestion
	 * Disable RUCSS setting.
```

2023-01-16 15:12 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/Perfmatters.php
> +	 * @return boolean
```suggestion
	 * @return bool
```

2023-01-16 15:12 UTC, remyperona commented on inc/ThirdParty/Plugins/Optimization/Perfmatters.php
> +		return false;
```suggestion
		return empty( $perfmatters_options['assets']['remove_unused_css'] ) );
```

2023-01-16 15:12 UTC, remyperona commented on inc/ThirdParty/Plugins/Optimization/RapidLoad.php
> +			'rocket_maybe_disable_rucss'              => 'disable_rucss_option',
```suggestion
			'rocket_disable_rucss_setting'              => 'disable_rucss_setting',
```

2023-01-16 15:12 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/RapidLoad.php
> +	 * Disable RUCSS option.
```suggestion
	 * Disable RUCSS setting.
```

2023-01-16 15:12 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/Optimization/RapidLoad.php
> +	public function disable_rucss_option( array $status ): array {
```suggestion
	public function disable_rucss_setting( array $status ): array {
```

2023-01-16 18:21 UTC, remyperona approved these changes

2023-01-17 10:29 UTC, vmanthos commented
With the latest changes, we are displaying the Rapidload notice when that's actually activated. Disabling the plugin enables our Remove Unused CSS back, however, that's not applied until the cache is cleared.

@piotrbak Do you think we should clear WP Rocket's cache when:
1. Rapidload's used CSS was enabled `AND`
2. The plugin was deactivated?

2023-01-18 12:31 UTC, piotrbak commented
@jeawhanlee Vasilis is right there about the cache clearing. We should handle that in this PR to improve UX. Here is the scenario (thanks @vmanthos):

1. Our Remove Unused CSS is enabled.
2. They install Rapidload and enable their RUCSS.
3. We display the notice and disable ours.
4. **They either disable RUCSS or deactivate their plugin.**
5. Our RUCSS is automatically enabled.
6. We clear the cache for that to be applied to the front-end.

2023-01-25 15:26 UTC, CrochetFeve0251 approved these changes

2023-01-27 09:12 UTC, vmanthos commented
@jeawhanlee  The trial of Rapidload has ended on my [test site](https://vasilis.rocketlabsqa.ovh/), and I'm getting this in "Settings > Rapidload":
![image](https://user-images.githubusercontent.com/193660/215047856-28310e42-f18c-42fe-93d0-321260e00f69.png)

Although the license information is "NOT VALID" our Remove Unused CSS is still disabled, the notice is displayed, and I cannot manually enable it.

Can you please look into this?

2023-01-31 15:05 UTC, Tabrisrp approved these changes

2023-02-01 13:16 UTC, vmanthos approved these changes
Working as expected! :+1:

2023-02-01 13:18 UTC, merged