Closes #5682 RocketCDN CTA banner displayed in cdn tab on one dot com hosting
wp-media/wp-rocket pull request #5694
Opened 2023-01-18 11:29 UTC by jeawhanlee

## Description
This PR removes the RocketCDN CTA banner when ONE.com cdn is enabled.

Fixes #5682 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

NO

## How Has This Been Tested?

Automated Tests.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-18 16:33 UTC, Tabrisrp approved these changes

2023-01-19 06:57 UTC, vmanthos commented
@jeawhanlee The CTA in the CDN tab is hidden. :+1: 

There are two more places we need to hide RocketCDN info:
1. 
![image](https://user-images.githubusercontent.com/193660/213374233-215e7448-4505-4918-9c53-64774530d5f9.png)

coming from:
https://github.com/wp-media/wp-rocket/blob/55ac46292a05931c202d31881f7fdcf5467a5200/inc/Engine/CDN/RocketCDN/views/promote-notice.php#L10-L14

and the following in WP Rocket's dashboard:
2. 
![image](https://user-images.githubusercontent.com/193660/213375254-11d7aa9a-5137-4dca-8fd3-cde0bd3d8378.png)

coming from:
https://github.com/wp-media/wp-rocket/blob/55ac46292a05931c202d31881f7fdcf5467a5200/inc/Engine/CDN/RocketCDN/views/dashboard-status.php#L18-L37

Can you please look into this? :pray:

2023-01-19 19:58 UTC, Tabrisrp requested changes

2023-01-19 19:58 UTC, Tabrisrp commented on inc/ThirdParty/Hostings/OneCom.php
> +	}
I think we could re-use one method as a callback for the 3 filters instead

2023-01-23 14:27 UTC, Tabrisrp approved these changes

2023-01-26 07:19 UTC, vmanthos reviewed
With the recent [change](https://github.com/wp-media/wp-rocket/pull/5712) in the way we detect if  ONE's CDN is enabled, all RocketCDN CTA/info will be displayed if
* the Performance Cache is deactivated `OR`
* it's activated but the CDN option is disabled

In these scenarios, ONE customers will be able to purchase a RocketCDN subscription.

@piotrbak I'm guessing this isn't what we want. Can you please confirm?

@jeawhanlee Depending on Piotr's reply you may need to create a new method to detect if the site is hosted on ONE and hook that to the UI hooks you are using to hide RocketCDN CTA/info.

Also, some tests are[ failing](https://github.com/wp-media/wp-rocket/actions/runs/4012993264). Can you please look into this? :pray:

2023-01-31 15:00 UTC, Tabrisrp approved these changes

2023-02-01 14:00 UTC, vmanthos approved these changes
Working as expected. :+1:

2023-02-01 14:01 UTC, merged