disable preload for pagination URLs
wp-media/wp-rocket pull request #5696
Opened 2023-01-18 12:30 UTC by mostafa-hisham

## Description

disable add pagination URLs in `wpr_rocket_cache` table
Fixes #5544 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?
- [x] local envoinment
- [x] unit and integration tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-18 13:11 UTC, CrochetFeve0251 approved these changes

2023-01-18 16:27 UTC, Tabrisrp requested changes

2023-01-18 16:27 UTC, remyperona commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +		$regexes          = (array) apply_filters( 'rocket_preload_exclude_urls', [ $pagination_regex ] );
The docblock for the filter should be placed correctly next to the filter function usage

2023-01-19 15:02 UTC, Tabrisrp approved these changes

2023-01-25 12:13 UTC, vmanthos reviewed
This is working as expected. :+1: 

In the following cases:
1. There is a post or page whose slug is matching the pagination base, e.g. `https://example.com/page/`.
2. The user has changed the default category/tag base and that matches the pagination base.

we are going to prevent the preloading of all the URLs that include `/page/`.

@piotrbak These are edge cases.  Should we address them in this PR or monitor them, and if any come up act on this?

2023-01-25 12:35 UTC, piotrbak commented
@vmanthos Let's monitor them and make decision based on that. It'll be possible to redo this change with filter for edge cases and specifc use cases

2023-01-25 12:39 UTC, vmanthos approved these changes

2023-02-01 16:26 UTC, merged