Closes #5675 improve wpx hosting compatibility
wp-media/wp-rocket pull request #5701
Opened 2023-01-19 11:04 UTC by jeawhanlee

## Description
Improve wpx hosting compatibility

Fixes #5675 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Yes, We need to append the cache control header for only mime type text/html content and previous grooming would only work with a matching html file.

## How Has This Been Tested?

Automatic & Manual Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-19 14:45 UTC, CrochetFeve0251 requested changes

2023-01-19 14:45 UTC, CrochetFeve0251 commented on composer.json
> +			"@test-integration-wpxcloud"
@jeawhanlee is it possible to correct indentation?

2023-01-26 11:02 UTC, CrochetFeve0251 approved these changes

2023-02-07 15:08 UTC, Mai-Saad commented
@jeawhanlee thanks for the PR, Partial Cache clear is not working there, can you please check? (was working fine on trunk 3.12.5.3)

As per @vmanthos 

> It's standard Varnish functionality and that should be working. :thinking_face:
There was an issue with clearing the homepage and partial cache clearing:
https://github.com/wp-media/wp-rocket/pull/5515#issuecomment-1298202478
But supposedly WPX resolved that. Maybe it's the same.

2023-02-08 06:53 UTC, vmanthos commented
I've logged the purge request to WPX's Varnish:
```PHP
URL:https://wpxnew.rocketlabsqa.ovh/hello-world/?regex
Purge URL:http://127.0.0.1:6081/hello-world/.*
Array
(
    [method] => PURGE
    [blocking] => 
    [redirection] => 0
    [headers] => Array
        (
            [host] => wpxnew.rocketlabsqa.ovh
            [X-Purge-Method] => regex
        )

)
```

Nothing has changed on our side compared to the [previous time](https://github.com/wp-media/wp-rocket/pull/5515#issuecomment-1298112131) I did the same.

@alxtv Can you possibly look into this and check if it's something on your side? :pray:

2023-02-08 07:32 UTC, alxtv commented
According to our logs, it's working fine.

I will double check it.

![PURGE](https://user-images.githubusercontent.com/44799811/217463267-b0f920d9-40f3-4f3d-8d72-99508b0be670.png)

2023-02-08 14:24 UTC, jeawhanlee commented
Thanks @piotrbak, we found out that partial cache clearing will only happen when permalink has a trailing slash as we are only matching urls with a trailing slash [here](https://github.com/wp-media/wp-rocket/blob/60b76bc8bc9a366bf5b9644894df8203bba103fd/inc/Addon/Varnish/Subscriber.php#L84) and [here](https://github.com/wp-media/wp-rocket/blob/60b76bc8bc9a366bf5b9644894df8203bba103fd/inc/Addon/Varnish/Subscriber.php#L98)
@Mai could you please confirm this?

2023-02-08 14:26 UTC, piotrbak commented
@Mai-Saad @jeawhanlee It should be the same on the trunk though.

2023-02-08 15:14 UTC, alxtv commented
We can fix that and handle http://127.0.0.1:6081/hello-world.* or http://127.0.0.1:6081/hello-world(.*) PURGE like requests.
Just let me know how it will be better for you.

Meanwhile I've tested the new "cache-control" header and it works as expected -> no browser cache for text/html, but cached on the CDN.

2023-02-09 12:38 UTC, piotrbak commented
@alxtv Great about the browser caching! 🙌 

From our perspective it would be the best if `http://127.0.0.1:6081/hello-world/.*` would clear both:
-  http://127.0.0.1:6081/hello-world/
-  http://127.0.0.1:6081/hello-world
(in that case, our PR is ready-to-go)

Most likely it should not be possible to have both of them accessible though. If it's not doable, then sending that kind of request ` http://127.0.0.1:6081/hello-world.*` would be the best. We'd need to make sure it also clears both URLs.

2023-02-09 14:27 UTC, alxtv commented
@piotrbak we will clear both http://127.0.0.1:6081/hello-world and http://127.0.0.1:6081/hello-world/ if we receive PURGE request for http://127.0.0.1:6081/hello-world/.*
Will confirm once it's deployed on the whole CDN.

2023-02-09 15:51 UTC, piotrbak commented
@alxtv That's perfect, thank you 🙏 

@Mai-Saad Partial cache clearing case will be handled on the WPX side.

2023-02-13 12:05 UTC, Mai-Saad approved these changes
Working as expected in terms of adding headers and partial cache clear while permalinks with `/`.
notes:
- after deactivating WPR, headers can still exist for a while in the browser (probably due to browser cache, however, WPR rules were removed from htaccess)
- Partial cache clearing while permalinks without `/` will be handled on WPX's side

2023-02-14 14:42 UTC, alxtv commented
> @piotrbak we will clear both http://127.0.0.1:6081/hello-world and http://127.0.0.1:6081/hello-world/ if we receive PURGE request for http://127.0.0.1:6081/hello-world/.* Will confirm once it's deployed on the whole CDN.

This is done.

2023-03-15 14:49 UTC, merged