Closes #5687 Remove multiple config files on deactivation
wp-media/wp-rocket pull request #5730
Opened 2023-01-31 11:45 UTC by jeawhanlee

## Description
This PR solves the issue where we do not clear out irrelevant config files when WP Rocket is deactivated.

Fixes #5687 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
Slightly different with a helpful addition from @engahmeds3ed 

## How Has This Been Tested?
Manual Tests

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-01-31 15:08 UTC, Tabrisrp requested changes

2023-01-31 15:08 UTC, Tabrisrp commented on inc/functions/files.php
> +	if ( is_multisite() && ! is_plugin_active_for_network( plugin_basename( WP_ROCKET_FILE ) ) ) {
WP Rocket is never network active, it's not compatible with it

2023-02-03 13:45 UTC, engahmeds3ed commented on inc/functions/files.php
> +		}
Bailout early
```suggestion
		if ( ! $file->isFile() || 'php' !== $file->getExtension() ) {
			continue;
		}
		rocket_direct_filesystem()->delete( $file->getPathname() );
```

2023-02-03 14:16 UTC, engahmeds3ed approved these changes

2023-02-09 06:50 UTC, Mai-Saad commented
Working fine for the single site, however, on a multisite, deactivating WPR from the site won't remove the wrong .php and thus won't remove WPR from the htaccess. 

Steps:
1- install WPR on multisite (using Apache)
2- Activate WPR on the main site or subsite
3- Duplicate the config file from the /wp-rocket-config/ folder and give it a filename different from the site’s domain.
4- Deactivate WP Rocket.
5- Check the .htaccess and see that our rules are still there.

=> expected after step 4 is removing the wrong config file and removing our rules from htaccess. @piotrbak  @jeawhanlee  what do you think?

Note: if we cached a page after step 2 and then visited the same page after step 5, it will be served from the nocache which is correct

2023-02-09 11:15 UTC, Mai-Saad approved these changes

2023-03-15 14:49 UTC, merged