Update delayJS script and stop handling scripts inside svg
wp-media/wp-rocket pull request #5731
Opened 2023-01-31 12:40 UTC by CrochetFeve0251

## Description
Updated lazyload JS script.

Fixes #5725

## Type of change

Please delete options that are not relevant.

- [ ] Bug

## How Has This Been Tested?

- [ ] Automated test 

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-31 18:35 UTC, piotrbak commented
@wp-media/php For the 3.12.5.2 we'll also need to make sure that `<script>` inside <svg> is not rewritten to Delay JS.

Related convo:
https://wp-media.slack.com/archives/GUT7FLHF1/p1675189916149859

2023-02-02 09:47 UTC, jeawhanlee requested changes

2023-02-02 09:47 UTC, jeawhanlee commented on inc/Engine/Optimization/RegexTrait.php
> +	 * Replace <xmp> tags in the HTML with comment
```suggestion
	 * Replace <svg> tags in the HTML with comment
```

2023-02-02 09:47 UTC, jeawhanlee commented on inc/Engine/Optimization/RegexTrait.php
> +	 * @since 3.12.3
```suggestion
	 * @since 3.12.5.3
```

2023-02-02 09:47 UTC, jeawhanlee commented on inc/Engine/Optimization/RegexTrait.php
> +	 * @since 3.12.3
```suggestion
	 * @since 3.12.5.3
```

2023-02-02 13:06 UTC, jeawhanlee approved these changes

2023-02-02 16:12 UTC, merged

2023-03-09 10:45 UTC, charls637 commented
On firefox, when delayJS script  is enabled.. links are not working A links and Nav links.. Using elementor.. btw chrome and other browser works fine.

2023-03-09 10:49 UTC, piotrbak commented
@charls637 Hello and thanks for your comment. Are you using the latest, 3.12.6.1 version of WP Rocket?

If so, and you still experience this problem, please reach our Support.

2023-03-09 10:54 UTC, charls637 commented
![image](https://user-images.githubusercontent.com/8040085/224002652-7f9f1369-2cf4-47c7-9b80-cd20d2a0b69b.png)
Hello @piotrbak  thank you for the fast response. I already submitted the ticket  5-6 hours ago.
Latest I can use is wp-rocket_3.12.5.3.zip.. I tried to download it from the account page.