Closes #5724 Clean up failed RUCSS after a short period of time
wp-media/wp-rocket pull request #5739
Opened 2023-02-03 12:14 UTC by jeawhanlee

## Description
This PR schedules a cron to clear RUCSS failed jobs every 3 days.

Fixes #5724 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
Yes.

## How Has This Been Tested?
Automated Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-02-06 15:30 UTC, Tabrisrp approved these changes

2023-02-07 12:17 UTC, piotrbak commented
@jeawhanlee After talking with @Mai-Saad .

In this PR it'd be much better to set the row to `pending` and reset the `retries` column. Not sure if we have that kind of function in the codebase 🤔

2023-02-08 19:29 UTC, Tabrisrp approved these changes

2023-02-09 10:11 UTC, Mai-Saad commented
@jeawhanlee @piotrbak Thanks for the update. Please find my notes/qs below:
1- Now whenever the cron runs, we will revert all failed URLs to pending. Shouldn't we only revert the ones which failed since >= 3days?
2- Reverted URLs still have the error msg in the database. I think it shall be cleared while reverting to pending as same as retries. can you please check?

2023-02-09 12:12 UTC, piotrbak commented
@Mai-Saad @jeawhanlee Agree with both QA points 🙏

2023-02-09 19:37 UTC, Tabrisrp approved these changes

2023-02-10 11:44 UTC, Mai-Saad commented
@jeawhanlee Thanks for the update. Currently, the msg is cleared and we revert only if failed since >= 3d. 
One more thing we need to handle here, When reverting the status, we need to update the modified date. Can you please check that?

2023-02-13 16:24 UTC, Tabrisrp approved these changes

2023-03-20 10:47 UTC, Mai-Saad commented
@jeawhanlee the last modified date is updated, however, if the filter was set to `null `or `' '`, we will have error in logs. Can we guard this?
`add_filter( 'rocket_remove_rucss_failed_jobs_cron_interval', function( $interval ){
return null;
} );`

`[20-Mar-2023 10:15:22 UTC] Cron reschedule event error for hook: rocket_remove_rucss_failed_jobs, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"rocket_remove_rucss_failed_jobs","args":[],"interval":null}`

2023-03-21 14:23 UTC, remyperona requested changes

2023-03-21 14:23 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Cron/Subscriber.php
> +		$interval         = apply_filters( 'rocket_remove_rucss_failed_jobs_cron_interval', $default_interval );
the filter comment needs to be next to the filter use

2023-03-22 14:11 UTC, Tabrisrp approved these changes

2023-03-24 07:32 UTC, Mai-Saad commented
@jeawhanlee Thanks for the update, no error now with null , ''. However, can see error with -ve  value. Do you think we need to handle this? cc @piotrbak 
`[24-Mar-2023 07:09:13 UTC] Cron reschedule event error for hook: rocket_remove_rucss_failed_jobs, Error code: could_not_set, Error message: The cron event list could not be saved., Data: {"schedule":"rocket_remove_rucss_failed_jobs","args":[],"interval":-1}`

2023-03-24 11:20 UTC, piotrbak commented
Thank you @Mai-Saad 

I believe we're good here, it's a bit edgy and not causing fatal errors. That's acceptable.

2023-03-27 07:56 UTC, Mai-Saad approved these changes
Working fine then, failed test due to other known issue.
[testrail-report-465.pdf](https://github.com/wp-media/wp-rocket/files/11076087/testrail-report-465.pdf)

2023-03-29 19:33 UTC, merged

2023-05-26 06:26 UTC, DahmaniAdame commented
@piotrbak currently, only the cron interval is controllable using the `rocket_remove_rucss_failed_jobs_cron_interval` filter: 

https://github.com/wp-media/wp-rocket/blob/3b6300ec350c3fa60bdae03c32bc8d5c4b9cb7f9/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#LL169C31-L169C76

While failed jobs we are looking for on the database have a static 3 days age: 

https://github.com/wp-media/wp-rocket/blob/3b6300ec350c3fa60bdae03c32bc8d5c4b9cb7f9/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php#L423

Which nullifies the effect of `rocket_remove_rucss_failed_jobs_cron_interval`. Regardless of its value, it will still be a static 3 days minimum of unavailable Used CSS without manual interaction.

Both need to be controllable using a filter for cases where the 3 days interval failed lifetime are not tolerable. At least, until we have more accurate errors reporting from SaaS To know what is causing `40x` errors.