Added referrer by default to actions
wp-media/wp-rocket pull request #5749
Opened 2023-02-09 14:07 UTC by CrochetFeve0251

## Description
Fixed an error where the clear cache button create an error while being used with no-referrer policy.
To fix this I forced the header on button actions.

Fixes #5747 

## Type of change

Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Tested on local env

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-09 15:25 UTC, Tabrisrp requested changes

2023-02-09 15:25 UTC, Tabrisrp commented on inc/classes/class-abstract-render.php
> +				}
```suggestion
                               $referer = '';

				if ( ! empty( $_SERVER['REQUEST_URI'] ) ) {
					$referer = filter_var( wp_unslash( $_SERVER['REQUEST_URI'] ), FILTER_SANITIZE_URL );
					$referer = '&_wp_http_referer=' . rawurlencode( remove_query_arg( 'fl_builder', $referer ) );
				}
```

2023-02-10 14:41 UTC, Tabrisrp approved these changes

2023-03-02 07:44 UTC, Mai-Saad approved these changes
Working as expected for Cache clear and Used CSS clear on Apache (even with no referrer header) and Nginx

2023-03-15 14:48 UTC, merged