Closes #4215 Add preload fonts before cpcss and rucss
wp-media/wp-rocket pull request #5767
Opened 2023-02-16 20:20 UTC by jeawhanlee

## Description
Move fonts after title.

Fixes #4215

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

Automated tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-02-17 02:17 UTC, mostafa-hisham approved these changes

2023-02-17 14:58 UTC, Tabrisrp requested changes

2023-02-17 14:58 UTC, Tabrisrp commented on inc/Engine/Preload/Fonts.php
> +		return str_replace( '</title>', $preloads, $html );
it's better to use `preg_replace()` with a replacement limit of 1 in this case, to prevent inserting in unexpected cases (seen it happen before)

2023-02-20 16:29 UTC, Tabrisrp approved these changes

2023-03-13 11:49 UTC, vmanthos commented
@jeawhanlee The preload fonts are added after the `<style id="rocket-critical-css"></style>`. This is because the respective method is run with a priority of `10` while the `CriticalCSSSubscriber::insert_critical_css_buffer` has a priority of `19`.

Can you look into this, please?

@piotrbak Are we going to cover the case where there isn't a `</tilte>`? We aren't doing this currently.

2023-03-15 14:35 UTC, remyperona approved these changes

2023-03-20 08:24 UTC, vmanthos approved these changes
Working as expected! :+1:

2023-03-29 19:33 UTC, merged