Closes #5764: Sanitize rocket_clean_user path the same way as we create the path when caching
wp-media/wp-rocket pull request #5819
Opened 2023-03-15 17:33 UTC by jeawhanlee

## Description
Sanitizes user cache path before deleting.

Fixes #5764 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

Manual Test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2023-03-15 19:56 UTC, Tabrisrp approved these changes

2023-03-17 19:38 UTC, Tabrisrp approved these changes

2023-03-30 07:03 UTC, vmanthos commented
@jeawhanlee Thank you for the PR!

The user's cache isn't cleared and this is happening because of the following line:
https://github.com/wp-media/wp-rocket/blob/48e6c4a4195ceaed57901a7436cd825f762e6340/inc/functions/files.php#L917

This removes the `.` from the site's TLD. So, instead of having:
```
/shared/httpd/wprocketest/htdocs/wp-content/cache/wp-rocket/wprocketest.test-vasilis-642284781a455276847402
```
you have this:
```
shared/httpd/wprocketest/htdocs/wp-content/cache/wp-rocket/wprocketesttest-vasilis-642284781a455276847402
```

Note the absence of the `.` between `wprocketest` and `test` which is the TLD suffix.

I believe the `preg_replace() ` should be applied to the `$user_key` only.

To test if the user's cache is cleared you can do one of the following:
1. Delete a user.
2. Update a user's profile.
3. Use the "Clear this cache" URL under a user in WordPress's Users page.

Can you please look into this? :pray:

2023-04-03 13:04 UTC, Tabrisrp approved these changes

2023-04-04 08:06 UTC, vmanthos commented
@jeawhanlee Thank you for the fixes!

@piotrbak I found an edge case that can cause issues. By default, WordPress sanitizes usernames and won't allow using non-Latin characters, e.g. Cyrillic (`Анастасия`, `Борис`, `Виктор`, ), Greek (`Βασίλης`, `Ελένη`), etc.
The same stands when using `wp-cli` to add users.

However, it's possible to add such usernames directly in the database or use WordPress filters to achieve the same.

 In that scenario, we completely remove the usernames and the cache folder's name will be like this for every user with such a username:
`example.com--642284781a455276847402` 

So, it will be a common cache folder for all logged-in users. 

Is this something we need to consider or is it too edgy?
By the way, I didn't find any such issue reported so far.

2023-04-13 13:17 UTC, piotrbak commented
@jeawhanlee Do you think it'd be possible to tackle the edge case described by @vmanthos by changing the structure of the user cache directory to: wprocketest.test-vasilis-`hashedUsername`-642284781a455276847402

So if this edge cache happen, we'll still be able to differentiate cache directories using `hashedUsername`? We'd need to make sure that the directories are:
1. Correctly created
2. Correctly read
3. Correctly cleared

2023-04-14 12:18 UTC, jeawhanlee commented
> @jeawhanlee Do you think it'd be possible to tackle the edge case described by @vmanthos by changing the structure of the user cache directory to: wprocketest.test-vasilis-`hashedUsername`-642284781a455276847402
> 
> So if this edge cache happen, we'll still be able to differentiate cache directories using `hashedUsername`? We'd need to make sure that the directories are:
> 
> 1. Correctly created
> 2. Correctly read
> 3. Correctly cleared

@piotrbak I think we should be able to.
I'm looking into this.

2023-04-17 13:33 UTC, Tabrisrp requested changes

2023-04-17 13:33 UTC, Tabrisrp commented on inc/classes/Buffer/class-cache.php
> +		$sanitized_user = rawurlencode( $user );
```suggestion
	private function sanitize_user( string $user = '' ): string {
		return strtolower( rawurlencode( $user ) );
```

2023-04-17 13:33 UTC, Tabrisrp commented on inc/classes/Buffer/class-cache.php
> +		return strtolower( $sanitized_user );
```suggestion
```

2023-04-18 05:53 UTC, mostafa-hisham approved these changes

2023-04-18 13:18 UTC, Tabrisrp approved these changes

2023-04-19 07:26 UTC, vmanthos commented
Thank you for the PR @jeawhanlee! :pray: 
This is working as expected. 

@piotrbak Before approving this, a matter to discuss. 

The new approach which `rawurlencode`s the username increases the length of the cache folder's name when the username is in a non-Latin alphabet. 
For example, using `Βασίλης`, my name in Greek, as the username the length was 22 characters longer compared to `base64_encode`ing it. This can be even large if a longer username of that kind is used.

As a result, the path length to the cached file will be increased, even more, if URLs are written in non-Latin, e.g. Greek. 
That could potentially cause issues if the path's length is greater than PHP's `PATH_MAX` value. That was set to `4096` in my test environment and I didn't actually see an issue. But the value could be lower in other systems.

Not having data about this value "in the wild" is it something we want to move forward with and treat as an edge case or should we follow a different approach?

By the way, keeping the current approach compared to e.g. adding a hash of the username, has the advantage of having readable usernames in the cache folder for all logged-in users, but the ones whose username is in non-Latin.

2023-04-19 13:45 UTC, vmanthos approved these changes

2023-04-19 13:45 UTC, merged