Closes #5815 Correctly clear cache for URLs whose permalink contains uppercase letters in non-latin alphabets
wp-media/wp-rocket pull request #5852
Opened 2023-04-03 11:39 UTC by jeawhanlee

## Description
Transforms url character to lower case before deleting cache.

Fixes #5815 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

Manual Test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2023-04-03 13:05 UTC, Tabrisrp approved these changes

2023-04-03 20:43 UTC, Mai-Saad commented
@jeawhanlee Thanks or the PR. Currently , on branch, can see the cache isnot cleared to the post in the following case (can you please check):
1- Disable preload 
2- Set permalinks to `/%postname%/роизвод`
3- cache a post
4- edit post and check cache => the cache of the post isnot cleared

2023-04-07 03:25 UTC, mostafa-hisham approved these changes

2023-04-13 11:28 UTC, Mai-Saad commented
@jeawhanlee While exploratory test can see that we have a regression in the following scenario (was working fine on 3.13.0.1)
1- post URL with slug `γυναικείο` 
2- permalinks `/%postname%`
3- Preload is disabled
4- cache the post url
5- edit the post and check cache => cache isnot cleared
can you please check that?

2023-04-14 12:54 UTC, Tabrisrp approved these changes

2023-04-18 13:08 UTC, Mai-Saad commented
@jeawhanlee Thanks for the update. the slug case is working fine now. However, if permalinks contains capital Latin letter, cache won't be cleared when edit the post. can you please check that?
steps:
1- while preload is disabled, set permalinks `/%postname%/Test/`
2- cache a post i.e `https://newer.rocketlabsqa.ovh/new-test/Test/`
3- edit post and check cache
Expected:
Cache is cleared as same as with Capital non-Latin letters

2023-04-20 13:49 UTC, Tabrisrp requested changes
small naming change to make it more clear the variable is a callback function

2023-04-20 13:49 UTC, Tabrisrp commented on inc/functions/files.php
> +					$encode_non_latin = function( $non_latin ) {
```suggestion
					$cb_encode_non_latin = function( $non_latin ) {
```

2023-04-20 13:49 UTC, Tabrisrp commented on inc/functions/files.php
> +					$parsed_url['path'] = str_replace( $matches['non_latin'], array_map( $encode_non_latin, $matches['non_latin'] ), $parsed_url['path'] );
```suggestion
					$parsed_url['path'] = str_replace( $matches['non_latin'], array_map( $cb_encode_non_latin, $matches['non_latin'] ), $parsed_url['path'] );
```

2023-04-24 11:32 UTC, Tabrisrp approved these changes

2023-05-11 10:15 UTC, Mai-Saad commented
@jeawhanlee The capital Latin char issue is fixed now. However, if permalinks contains non-latin char then we cache post then click purge this URL from post view, the post cache won't be cleared (as same as on trunk). can you please check?

2023-05-11 10:19 UTC, piotrbak commented
@jeawhanlee Could you check the effort of what @Mai-Saad mentioned? Do you feel it can introduce any bigger risk?

2023-05-15 10:12 UTC, jeawhanlee commented
> @jeawhanlee Could you check the effort of what @Mai-Saad mentioned? Do you feel it can introduce any bigger risk?

I'm checking this...

2023-05-15 12:01 UTC, jeawhanlee commented
@piotrbak @Mai-Saad To fix this we have to revert the previous commit on this [PR](https://github.com/wp-media/wp-rocket/pull/5852/commits/340995d67195bab4e996cdc392a39e9ddeca246f) that tries to fix @Mai-Saad comment [here](https://github.com/wp-media/wp-rocket/pull/5852#issuecomment-1513104271) as I feel that `purge this url` from post view is something that will be used more often.
what do you think?

2023-05-15 12:24 UTC, piotrbak commented
@jeawhanlee The comment you mentioned is about the Latin char while the question [here](https://github.com/wp-media/wp-rocket/pull/5852#issuecomment-1543724893) is about the non-Latin one, right?

We should be able to clear the cache for the following scenarios:
1) non-Latin uppercase character present in the permalink or post title
2) non-Latin permalink or post title contains only lowercase characters
3) Latin uppercase character present in the permalink or post title
4) Latin permalink or post title contains only lowercase characters

Would be great if all those scenarios worked with the trailing slash at the end or without it in the permalinks settings. It's important not to introduce any regression in this PR though, as we're fixing a problem that's not touching majority of our customers.

We can brainstorm the problem here to find a solution that would cover everything.

2023-05-15 13:42 UTC, piotrbak commented
@vmanthos Agreed!

2023-05-19 15:20 UTC, Tabrisrp approved these changes

2023-05-22 10:29 UTC, Mai-Saad commented
@jeawhanlee Can you please check this case?
1- Preload is off then Permalinks set to /%postname%/дÆÈÜ
2- We visit post URL [https://new.rocketlabsqa.ovh/test-post2/дÆÈÜ`](https://new.rocketlabsqa.ovh/test-post2/%D0%B4%C3%86%C3%88%C3%9C%60) incognito => the following entry added to cache table as completed https://new.rocketlabsqa.ovh/test-post2/%D0%B4%C3%86%C3%88%C3%9C
3- edit the post => another entry [https://new.rocketlabsqa.ovh/test-post2/дÆÈÜ`](https://new.rocketlabsqa.ovh/test-post2/%D0%B4%C3%86%C3%88%C3%9C%60) added to the database that will remain pending, and if we visit the post URL, the link in step 2 will update the last accessed

Note: same on the trunk, also on trunk purge this URL won't work for the link in step 2, however, it's working on the branch.
@piotrbak what do you think?

2023-05-22 13:30 UTC, piotrbak commented
Thanks @Mai-Saad, @jeawhanlee could you check the second case? How complex is this one?

2023-05-24 10:21 UTC, CrochetFeve0251 approved these changes

2023-05-25 11:13 UTC, Mai-Saad commented
@jeawhanlee Thanks for the update, now the cache is cleared with permalinks containing Latin/non-Latin char when edit the post, clear this cache, purge this URL and clear the whole cache.
However, When we enable RUCSS, once used CSS is created, we aren't clearing the cache folder of related post although the cache table status changed to pending (while preload is off) while permalinks contain non-latin char i.e `/%postname%/ПÇŞĞIİÖÜ` @piotrbak what do you think?

2023-05-29 11:31 UTC, piotrbak commented
@Mai-Saad Is it only about the `cache folder` or the cache files itselves?

2023-05-30 10:02 UTC, Mai-Saad commented
@piotrbak the cache files.
1- Disable preload
2- Use permalinks` /%postname%/ПÇŞĞIİÖÜ`
3- Cache a post i.e https://new.rocketlabsqa.ovh/test-post-2/ПÇŞĞIİÖÜ/
4- Enable RUCSS 
5- Once Used CSS is completed at the used CSS table => check the cache table and cache folder, files are still in the cache folder while the status switched to pending at the cache table

2023-05-30 10:54 UTC, piotrbak commented
@Mai-Saad That sounds like an edge case, I think we're okay here.

2023-06-01 07:50 UTC, Mai-Saad commented
ok, another note:
- when permalinks contain non-latin char, then we switch post to draft => cache is cleared but status at cache table remains completed
- For case 1, is occurring too when trash a post or switch a post to draft
- Already on the trunk (while preload off), when we delete the post, we are not removing it from the cache table

2023-06-01 07:52 UTC, Mai-Saad approved these changes
As agreed, mentioned points will remain as is. Working fine then

2023-06-01 07:55 UTC, merged