use preload exclusions from the backend
wp-media/wp-rocket pull request #5865
Opened 2023-04-12 04:10 UTC by mostafa-hisham

## Description

Use the newly added preload_excluison in the backend on the plugin side

Fixes #5810 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking change which improves an existing functionality)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-13 13:12 UTC, Tabrisrp requested changes

2023-04-13 13:12 UTC, remyperona commented on tests/Integration/inc/Engine/Optimization/DynamicLists/Subscriber/addPreloadExcluisons.php
> +class Test_AddPreloadExcluisons extends TestCase {
```suggestion
class Test_AddPreloadExclusions extends TestCase {
```

+ same typo in the filename

2023-04-13 13:12 UTC, Tabrisrp commented on tests/Fixtures/inc/Engine/Optimization/DynamicLists/Subscriber/addPreloadExcluisons.php
> +<?php
fix typo in the filename

2023-04-19 13:21 UTC, Tabrisrp approved these changes

2023-04-24 10:40 UTC, vmanthos approved these changes

2023-04-24 10:42 UTC, vmanthos commented
This is working as expected. :+1: 

PS: The exclusion I've added to the staging SaaS back end is `void\(.*;`. 
This should be added to the production SaaS once the PR that adds the preload exclusions is merged there.

2023-04-24 10:43 UTC, merged

2023-05-08 06:36 UTC, vmanthos commented
@mostafa-hisham Can you push to the SaaS production the related branch? :pray:

2023-05-08 07:55 UTC, mostafa-hisham commented
Done