create rocket_min_rucss_size filter to fail on small css result
wp-media/wp-rocket pull request #5875
Opened 2023-04-17 10:38 UTC by mostafa-hisham

## Description
create `rocket_min_rucss_size` filter so we can see it to set the min accepted CSS result size from RUCSS servers
and make the Job status failed if the CSS size is lower than `rocket_min_rucss_size`

Fixes #5809 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [ ] Unit test

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-04-17 13:16 UTC, jeawhanlee approved these changes

2023-04-17 13:23 UTC, Tabrisrp requested changes

2023-04-17 13:23 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +		 * @since 3.12.3
```suggestion
		 * @since 3.13.3
```

2023-04-18 13:15 UTC, remyperona approved these changes

2023-05-10 13:30 UTC, vmanthos commented
@mostafa-hisham We should make sure that only integers are passed to the `rocket_min_rucss_size` filter and safeguard it from values like `null`, `false`, and from strings and arrays.

Also, maybe mention the unit, e.g. bytes, in the filter's docblock.

2023-05-11 07:01 UTC, vmanthos commented
@mostafa-hisham Typecasting values like `null`, `[]`, `"string"` as `int` will return a `0`. In such a case, if the `$job_details['contents']['shakedCSS_size']` is anything larger than `0` but still lower, e.g. than 150 bytes, we'll still add the incomplete/incorrect used CSS to the table.

I guess we wouldn't want to hardcode a fallback value, e.g. `150`, if the filter returns a `0`. 

Is there possibly a better way to safeguard the filter?

2023-05-11 13:49 UTC, Tabrisrp commented
We can check if the value of the filter with `is_numeric()`, and if not, use the default value as a fallback. That way it will work with a numeric value even if its type is string

2023-05-11 13:49 UTC, Tabrisrp commented
We can check if the value of the filter with `is_numeric()`, and if not, use the default value as a fallback. That way it will work with a numeric value even if its type is string.

2023-05-11 13:55 UTC, Tabrisrp commented
We can check if the value of the filter with `is_numeric()`, and if not, use the default value as a fallback. That way it will work with a numeric value even if its type is string.

2023-05-15 12:54 UTC, Tabrisrp approved these changes

2023-05-16 06:00 UTC, vmanthos approved these changes
This is working as expected! :+1:

2023-05-16 06:01 UTC, merged