Fix: Allow caching WP Rest API when helper plugin is activated.
wp-media/wp-rocket pull request #5906
Opened 2023-05-08 10:41 UTC by jeawhanlee

## Description

Return early when when WP Rest API is accessed and helper plugin is activated.

Fixes #5900 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?
Manual

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-05-08 15:21 UTC, remyperona approved these changes

2023-05-09 21:15 UTC, engahmeds3ed requested changes

2023-05-09 21:15 UTC, engahmeds3ed commented on inc/classes/Buffer/class-cache.php
> +		if ( ! preg_match( '#wp\\-json#', $this->config->get_config( 'cache_reject_uri' ) )
why do we need that check?
[Here](https://github.com/wp-media/wp-rocket/blob/5b9b3f30b3aefa615d2d005f5b5b94ffc3424965/inc/classes/Buffer/class-tests.php#L210-L214) we are check if the current url is excluded from cache or not so once we reach this method `maybe_allow_wp_redirect` we are sure that the current url is not excluded from cache, right?

2023-05-09 21:15 UTC, engahmeds3ed commented on inc/classes/Buffer/class-cache.php
> +			preg_match( '#wp-json/wp/v[0-9]+(/|)$#', $this->tests->get_request_uri_base() )
this will work only with wordpress out-of-the-box rest api endpoints `wp-json/wp/v2`
I believe we need to make it more generic.

what do u think?

2023-05-11 11:24 UTC, engahmeds3ed approved these changes

2023-05-12 07:25 UTC, vmanthos commented
@jeawhanlee @piotrbak  This is working as expected. :+1: 

A possible implication of the current PR is that redirects to add or remove the trailing `/` won't take place when `wp-json` is included in the URI. For example, for a post titled "What is /wp-json?" the URI will be https://example.com/what-is-wp-json. 

Is there something we can/should do about this?

2023-05-12 09:24 UTC, piotrbak commented
@vmanthos We're good here, thanks!

2023-05-12 11:33 UTC, vmanthos approved these changes

2023-05-12 11:33 UTC, merged