Closes #5909 Remove combine CSS option
wp-media/wp-rocket pull request #5911
Opened 2023-05-09 08:20 UTC by CrochetFeve0251

## Description
Remove the combine CSS feature.
For that we remove the main logic, removed the setting from the page and inside 3rdparties.

Fixes #5909 

## Type of change

Please delete options that are not relevant.

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Automated Tests

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-10 15:07 UTC, Tabrisrp requested changes

2023-05-10 15:07 UTC, Tabrisrp commented on inc/Engine/Admin/Settings/Page.php
> -				'minify_concatenate_css'       => [
We need to move the `minify_concatenate_css` value to the hidden fields array to preserve the value in case of revert

2023-05-10 15:07 UTC, remyperona commented on inc/Engine/Optimization/Minify/CSS/Subscriber.php
> +		rocket_clean_domain();
We can also call `rocket_clean_minify()` to clean the old combined files

2023-05-11 13:59 UTC, Tabrisrp requested changes

2023-05-11 13:59 UTC, Tabrisrp commented on inc/Engine/Admin/Settings/Page.php
> +					'minify_concatenate_css',
spacing seems strange no?

2023-05-11 13:59 UTC, Tabrisrp commented on inc/Engine/Optimization/Minify/CSS/Subscriber.php
> +		rocket_clean_minify();
You can do both clean domain and clean minify

2023-05-12 15:45 UTC, Tabrisrp commented
There is some conflicts to fix

2023-05-16 12:05 UTC, vmanthos commented
@CrochetFeve0251 A minor change. 

In the following meta-box, the `/combine` part should be removed:
![image](https://github.com/wp-media/wp-rocket/assets/193660/db100f4f-8892-41c8-aa42-ce87569814aa)
https://github.com/wp-media/wp-rocket/blob/9822ca221e2070d39ecd1a8e74fec20b4351f3d5/inc/admin/ui/meta-boxes.php#L105

2023-05-16 12:51 UTC, remyperona approved these changes

2023-05-17 13:12 UTC, vmanthos commented
@CrochetFeve0251 When updating to `3.15` (I changed the `WP_ROCKET_VERSION` of this PR for testing purposes), the cache is cleared but the `/cache/min/1/` folder isn't.

`wp_rocket_upgrade` fired but the `on_update()` method didn't run.

Can you please look into this?

**Steps to reproduce this**

1. Install WP Rocket 3.13.2.
2. Enable the "Combine CSS files" feature.
3. Update to `3.15` (that can be done from a custom URL -> [doc - internal link](https://www.notion.so/wpmedia/Update-WP-Rocket-from-a-custom-URL-404154e66cc147c395d44aeb87c9b4ce) ).
4. Check the `/cache/min/1/` folder.

2023-05-19 15:00 UTC, Tabrisrp approved these changes

2023-05-23 09:32 UTC, vmanthos commented
@CrochetFeve0251 Thank you for the PR.

The issue from the [previous comment](https://github.com/wp-media/wp-rocket/pull/5911#issuecomment-1551369327) is still there. Can you please take another look?

2023-05-23 13:29 UTC, remyperona approved these changes

2023-05-30 08:51 UTC, vmanthos commented
@piotrbak @CrochetFeve0251 Currently, the cache, and minified/combined CSS files will be deleted when updating to 3.15 even if the "Combine CSS files" feature was disabled.

Is this something we'd like to address?

2023-05-30 11:16 UTC, piotrbak commented
@vmanthos @CrochetFeve0251 Yes, we need to be sure that we'll be able to remove the leftovers later though:
1. Combine CSS enabled some combined files generated
2. Turn off Combine CSS
3. Update the plugin, Combined CSS files are not removed
4. Clear /min/ directory to remove combined/minified [CSS files ](https://docs.wp-rocket.me/article/1135-when-does-wp-rocket-delete-which-files)

If 4 point works okay for the leftovers in this PR, we should handle this. If not, we'll need to leave it like it's.

2023-05-30 12:24 UTC, vmanthos commented
Taking the opportunity from @piotrbak previous comment, I commented out the following line:
https://github.com/wp-media/wp-rocket/blob/5e19edb2212fdcf701137e7d426e363f3d61c52d/inc/Engine/Optimization/Minify/CSS/Subscriber.php#L26

in the `3.15` update file to prevent the cache clearing actions after updating WP Rocket. 

Both when Combine CSS files was enabled and when it was disabled before the update the following took place:
* The cache was cleared `/cache/wp-rocket/`
* The minified folder `/cache/min/` and its content wasn't cleared

After the update, using "Clear and preload" from the admin bar cleared any leftovers, e.g. previously combined CSS files.

According to Piotr, given this will be a major update,  "it will be good to save the resources".

2023-06-01 11:40 UTC, vmanthos commented
@CrochetFeve0251 A minor change as far as wording goes.

When Autoptimize's CSS minification is enabled we prevent enabling WP Rocket's CSS minification and we display the following message:
> CSS Minification is currently activated in Autoptimize. If you want to use WP Rocket’s minification, disable those options in Autoptimize.

https://github.com/wp-media/wp-rocket/blob/50dcab488d8594a6bbeea3bbd11ccb4a8df6d537/inc/Engine/Admin/Settings/Page.php#L611

We should change this to:
> CSS Minification is currently activated in Autoptimize. If you want to use WP Rocket’s minification, disable the option in Autoptimize.

2023-06-20 19:09 UTC, merged