Closes #5885: Preload: Don't try to preload private pages
wp-media/wp-rocket pull request #5920
Opened 2023-05-12 16:28 UTC by jeawhanlee

## Description

Checks for posts with private status and exclude from preload.

Fixes #5885 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?
Automated tests

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-05-15 08:41 UTC, CrochetFeve0251 approved these changes

2023-05-16 10:05 UTC, engahmeds3ed requested changes

2023-05-16 10:05 UTC, engahmeds3ed commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +		$post_id = url_to_postid( $url );
we can early bailout here if $post_id = 0, url_to_postid returns zero when it's not a post

2023-05-16 15:16 UTC, engahmeds3ed approved these changes

2023-05-16 17:26 UTC, Mai-Saad commented
@jeawhanlee Thanks for the PR. Now adding new private post / editing content of existing private post won't add any entry in the cache table.

However, @piotrbak do you think we need to do change for any of the following?

1. if we edited public cached post to private, we won't remove the entry from the cache table till manual cache clear or change settings. can we delete the URL in this case? 
2. if custom sitemap contains private URL, it will be added to the table then removed once processed. 
3. if we edited private post, home, author  (prev/next if not private) will be preloaded

2023-05-16 20:03 UTC, piotrbak commented
@Mai-Saad 2 and 3 are okay.

For the first one, it's acceptable, but it would be better if we could remove that kind of post from the cache table directly. @jeawhanlee Is it doable without much complexity?

2023-05-18 09:04 UTC, jeawhanlee commented
> @Mai-Saad 2 and 3 are okay.
> 
> For the first one, it's acceptable, but it would be better if we could remove that kind of post from the cache table directly. @jeawhanlee Is it doable without much complexity?

@piotrbak  We should be able to do that.

2023-05-18 10:20 UTC, piotrbak commented
@jeawhanlee Please try to do that. If you have any troubles or feel it can introduce side effects, please ping me

2023-05-22 10:17 UTC, Mai-Saad commented
@jeawhanlee Can you please check this case?
1- Preload is off then Permalinks set to `/%postname%/дÆÈÜ`
2- We visit post URL https://new.rocketlabsqa.ovh/test-post2/дÆÈÜ` incognito => the following entry added to cache table as completed https://new.rocketlabsqa.ovh/test-post2/%D0%B4%C3%86%C3%88%C3%9C
3- edit the post => another entry  https://new.rocketlabsqa.ovh/test-post2/дÆÈÜ` added to the database that will remain pending, and if we visit the post URL, the link in step 2 will update the last accessed

Note: same on the trunk, also on trunk purge this URL won't work for the link in step 2, however, it's working on the branch.
@piotrbak what do you think?

2023-05-24 15:08 UTC, remyperona approved these changes

2023-05-26 09:13 UTC, Mai-Saad commented
@jeawhanlee Thanks for the updates. editing public post to private, is not sending any requests now.
However, we are sending requests to the URL in the following cases:
1- Update while having pending private post => When we remove the private URL from the cache table, we send a request (404)
2- While using a custom sitemap, containing private URLs => when we remove the private URL, we are sending a request (404)
can you please check?

2023-06-07 15:38 UTC, Tabrisrp approved these changes

2023-06-12 12:57 UTC, Mai-Saad commented
@jeawhanlee Thanks for the update. Can still see the requests mentioned [here](https://github.com/wp-media/wp-rocket/pull/5920#issuecomment-1564075521). Can you please check?

2023-06-20 13:33 UTC, Tabrisrp approved these changes

2023-06-22 13:26 UTC, engahmeds3ed requested changes
After a discussion with @jeawhanlee we agreed to make it more performant and use static variable to have the list of private urls not to get the list again with each url and instead of adding a new condition/login we will use the filter `rocket_preload_exclude_urls` to exclude all of those private posts urls.

2023-06-26 11:50 UTC, engahmeds3ed approved these changes

2023-06-27 11:09 UTC, vmanthos approved these changes
Working as expected. :+1: 

TestRail report will be added when ready.

2023-06-27 11:09 UTC, merged