Added CPCSS notice
wp-media/wp-rocket pull request #5935
Opened 2023-05-19 12:03 UTC by CrochetFeve0251

## Description

Add a notice to switch from CPCSS to RUCSS.

Fixes #5905 

## Type of change

Please delete options that are not relevant.

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Locally

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-19 15:19 UTC, Tabrisrp requested changes

2023-05-19 15:19 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +		if ( isset( $screen->id ) && 'settings_page_wprocket' !== $screen->id ) {
Missing the function to set the `$screen` variable

2023-05-19 15:19 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +					__( 'We highly recommend the %1$s updated Remove Unused CSS %2$s for a better CSS optimization. Load CSS Asynchronously is always available as a back-up.', 'rocket' ),
```suggestion
					__( 'We highly recommend the %1$supdated Remove Unused CSS%2$s for a better CSS optimization. Load CSS Asynchronously is always available as a back-up.', 'rocket' ),
```

2023-05-19 15:19 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +		if ( ! current_user_can( 'administrator' ) ) {
```suggestion
		if ( ! current_user_can( 'rocket_manage_options' ) ) {
```

2023-05-19 15:19 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +		}
You can use https://developer.wordpress.org/reference/functions/check_admin_referer/ instead

2023-05-19 15:19 UTC, Tabrisrp commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +		if ( 'true' === $_GET['value'] ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotValidated
I think it would be better to:
- check the existence of the 'value' key with isset()
- validate that the value is a boolean with is_bool()

2023-05-19 15:19 UTC, remyperona commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +			$this->options->set( 'remove_unused_css', true );
I don't think that's enough to update the settings in the database, you would need the Options API class too

2023-05-22 09:57 UTC, engahmeds3ed requested changes

2023-05-22 09:57 UTC, engahmeds3ed commented on assets/css/wpr-admin.css
> +}
So why not using the above CSS and only remove the .open, I believe this will be applied on opened and not opened div.

2023-05-22 09:57 UTC, engahmeds3ed commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +					// translators: %s = opening bold tag, %s = closing bold tag.
```suggestion
					// translators: %1$ = opening bold tag, %2$ = closing bold tag.
```

2023-05-22 09:57 UTC, engahmeds3ed commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +		if ( is_array( $_GET ) && key_exists( 'value', $_GET ) && $_GET['value'] ) { // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized,WordPress.Security.ValidatedSanitizedInput.
Can we change this value to be more meaningful and not interfering name?

2023-05-22 09:57 UTC, engahmeds3ed commented on inc/Engine/CriticalPath/CriticalCSSSubscriber.php
> +			do_action( 'rocket_clear_usedcss' );
I'm just wondering (not totally sure) do we really need this action here to delete the used CSS?
I believe the previous line which sets the settings in the options table is firing the action `update_option_wp_rocket_settings` and we have a callback here:
https://github.com/wp-media/wp-rocket/blob/9d8dbd0f069e54036a8ed7ecc16babc5d450f02f/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L69

that clears cache and used CSS, am I correct?

2023-05-22 14:54 UTC, engahmeds3ed approved these changes
Good job

2023-05-22 14:54 UTC, CrochetFeve0251 commented
> Good job

@engahmeds3ed you too

2023-05-23 07:51 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the PR.

Exploratory test notes so far that we need to fix:

1. The banner is displayed in other admins after being dismissed
2. The CPCSS is displayed at the admin bar and enabled at the page edit 
3. The CPCSS `id="rocket-critical-css"` exists at page source although we clicked `turn on RUCSS`
4. The notice is displayed even if 3rd party disabled our RUCSS i.e when RUCSS is on at perfmatters (we need to check if another 3rd party can block or RUCSS)=> @piotrbak What do you think?

2023-05-23 08:55 UTC, piotrbak commented
@Mai-Saad about the 4th point, Perfmatters disables our RUCSS, right? 

If that's the thing, I think that's okay, we'll be able to improve it later if we have complaints

2023-05-23 09:55 UTC, engahmeds3ed commented
@piotrbak we did that here: https://github.com/wp-media/wp-rocket/pull/5669

2023-05-23 10:08 UTC, piotrbak commented
@engahmeds3ed @CrochetFeve0251 Do you think it'll be easy to block the notice in those conditions, or it'll require major work?
https://github.com/wp-media/wp-rocket/blob/b533e6c14d8b1bc6835c02289aa1af76bd3aaf28/inc/ThirdParty/Plugins/Optimization/Perfmatters.php#L20
https://github.com/wp-media/wp-rocket/blob/b533e6c14d8b1bc6835c02289aa1af76bd3aaf28/inc/ThirdParty/Plugins/Optimization/RapidLoad.php#L20

2023-05-23 10:14 UTC, engahmeds3ed commented
@piotrbak 
I think we can apply the same filter from here:

https://github.com/wp-media/wp-rocket/blob/ff90b7d271541b58bdd927434ccb138fa0a12c70/inc/Engine/Admin/Settings/Page.php#L589-L595

to be here also:

https://github.com/wp-media/wp-rocket/pull/5935/files#diff-535a87e3b5fde41fbdf9a1c973c438fa47eab64b24a4616d46418c3784a136c5R796

I hope we can have only one apply_filters in one place and called twice.

What do u think @CrochetFeve0251 ?

2023-05-23 16:05 UTC, Mai-Saad approved these changes
The latest comments were fixed with the following notes:
- If we dismiss the notice with the stay on old option, the notice will still be displayed to other admins => Fine as per discussion with @piotrbak 
- rerun of updated tests that are not on cypress will be considered during prerelease

2023-05-23 16:06 UTC, merged