Closes #5951 Add compatibility with Cloudflare plugin & APO
wp-media/wp-rocket pull request #5953
Opened 2023-05-26 20:21 UTC by Tabrisrp

## Description

WIP

Fixes #5951

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

WIP

## How Has This Been Tested?

WIP

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-06-06 05:50 UTC, vmanthos commented
I did exploratory testing and so far I found that when:

1. The Cloudflare plugin is installed/activated.
2. Credentials are set correctly.
3. APO is enabled in the plugin's settings.

we are still displaying the "Modify Options" button but we shouldn't:
![image](https://github.com/wp-media/wp-rocket/assets/193660/ce798a1d-ee91-44ce-9463-2d3740df9955)

@CrochetFeve0251 Can you please look into this? pray

2023-06-07 08:40 UTC, Mai-Saad commented
- [ ] Better add **WP Rocket:** at the start of the notice as we used to.
example
![Screenshot from 2023-06-07 11-28-23](https://github.com/wp-media/wp-rocket/assets/76941962/c2947456-1e41-4ab0-a484-50aa9ab19e48)

- [ ] The text of the button in the notice displayed when cache by device type is enabled on Cloudflare and not on our side shall be `Enable “Separate Cache Files for Mobile Devices” now`
![Screenshot from 2023-06-07 10-51-52](https://github.com/wp-media/wp-rocket/assets/76941962/62d5899b-3860-4beb-9b3d-90f6dc4645c1)

2023-06-12 08:17 UTC, piotrbak commented
@Tabrisrp Could you take a look at this comment? https://github.com/wp-media/wp-rocket/pull/5953#issuecomment-1577955528

It would be great to resolve the `wording` points + `Purge Everything` case before releasing alpha version today. Do you think it'll be possible?

2023-06-12 09:14 UTC, engahmeds3ed requested changes
code review still in progress.

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/Engine/Admin/Beacon/Beacon.php
> +			],
We need to add the FR version ( https://fr.docs.wp-rocket.me/article/1757-utiliser-cloudflare-apo-avec-wp-rocket )

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/Engine/Admin/Settings/Page.php
> +					'url'    => WP_ROCKET_ASSETS_IMG_URL . 'logo-cloudflare2.svg',
it'd be better to have the constant inside `rocket_get_constant` function, what do u think?

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/Engine/Admin/Settings/Page.php
> +				// translators: %1$s = opening em tag, %2$l = list of add-on name(s), %3$s = closing em tag.
```suggestion
				// translators: %1$s = opening span tag, %2$s = closing span tag.
```

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/Engine/Admin/Settings/Page.php
> +		}
this way we will not make sure that the return of the filter will have all needed fields so I'd suggest something like:-

```suggestion
		$cf_settings = (array) apply_filters( 'rocket_cloudflare_field_settings', $default_cf_settings );

		$cf_settings = wp_parse_args( $cf_settings, $default_cf_settings );
```

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/ThirdParty/Plugins/CDN/Cloudflare.php
> +		}
what do u think about moving this empty check to be after checking if plugin active and apo enabled? it's a small performance enhancement because those functions has a filter inside to it'll take some time to process them and this time is not really needed if the plugin is not active or APO is not enabled.

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/ThirdParty/Plugins/CDN/Cloudflare.php
> +		}
this is a duplicate code I believe it'd be better to have a private method here with the name `can_show_notice` with this code to be called in every notice method, what do u think?

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/ThirdParty/Plugins/CDN/Cloudflare.php
> +		$cf_device_type = get_option( 'automatic_platform_optimization_cache_by_device_type', [] );
only a small comment here, their plugin has the option key in this constant `\CF\API\Plugin::SETTING_AUTOMATIC_PLATFORM_OPTIMIZATION_CACHE_BY_DEVICE_TYPE` also the value attribute is coming from here `\CF\API\Plugin::SETTING_VALUE_KEY`

I believe it'll be a rare case that they change the option name, so we are OK here.

2023-06-12 09:14 UTC, engahmeds3ed commented on inc/ThirdParty/Plugins/CDN/Cloudflare.php
> +			'cloudflare_purge_everything_actions' => 'add_clean_domain_on_purge',
does this filter's callback works if cloudflare is activated before activating WPR?

from what I see in their code here:
https://plugins.trac.wordpress.org/browser/cloudflare/trunk/cloudflare.loader.php#L71

they are using `apply_filters` without enclosing it in any WP Hook so it fires directly when enabling it so I think if their code is loaded before ours, this callback will not be added, worth testing, what do u think?

2023-06-12 13:55 UTC, remyperona commented on inc/ThirdParty/Plugins/CDN/Cloudflare.php
> +			'cloudflare_purge_everything_actions' => 'add_clean_domain_on_purge',
This is something that the QA team can check

2023-06-12 13:55 UTC, Tabrisrp commented on inc/ThirdParty/Plugins/CDN/Cloudflare.php
> +		$cf_device_type = get_option( 'automatic_platform_optimization_cache_by_device_type', [] );
it's unlikely to change once they started to use it

2023-06-12 17:04 UTC, merged

2023-06-13 08:41 UTC, vmanthos commented
@engahmeds3ed I checked your comment [here](https://github.com/wp-media/wp-rocket/pull/5953#discussion_r1226343949). 

Cloudflare APO's cache isn't cleared when our settings are saved. Their `\CF\WordPress\Hooks::purgeCacheEverything` method doesn't run when `after_rocket_clean_domain` fires.

This is the same both when WP Rocket was installed before and after Cloudflare. 

As far as I can tell, WordPress will load the plugins alphabetically but this wouldn't be a problem if they had the filter hooked to a WordPress filter.

@Tabrisrp Can you please look into this?

2023-06-13 12:00 UTC, Tabrisrp commented
Testing the output of the filters, there is nothing added to the original values. Looking into their GH, the issue was reported before: https://github.com/cloudflare/Cloudflare-WordPress/issues/345 and no fixed happened at all since.

We will have to find another way to call the CF purge.