Fixed disappearing notice
wp-media/wp-rocket pull request #5979
Opened 2023-06-15 11:44 UTC by CrochetFeve0251

## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-15 13:05 UTC, Tabrisrp requested changes

2023-06-15 13:05 UTC, Tabrisrp commented on inc/Addon/Cloudflare/Subscriber.php
> +	 * @return array
`update_option_` is an action, callback method doesn't need any returned value, why this change?

2023-06-15 13:05 UTC, Tabrisrp commented on inc/Addon/Cloudflare/Subscriber.php
> +	 * @return array
same question

2023-06-15 19:25 UTC, Tabrisrp approved these changes

2023-06-19 08:08 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the update. Saving the settings while the error is displayed won't hide the error. However,  please find exploratory test notes below:
- Refreshing the page while the error is displayed, will hide the error.  => Shouldn't the error still be displayed here?
- If we have 3.14, where the error was hidden due to the bug there, then we update to the PR, shouldn't the error be displayed? (currently, it is not)

2023-06-19 08:42 UTC, CrochetFeve0251 commented
> @CrochetFeve0251 Thanks for the update. Saving the settings while the error is displayed won't hide the error. However,  please find exploratory test notes below:
> - Refreshing the page while the error is displayed, will hide the error.  => Shouldn't the error still be displayed here?
> - If we have 3.14, where the error was hidden due to the bug there, then we update to the PR, shouldn't the error be displayed? (currently, it is not)

@Mai-Saad the error is displayed when we save so it is normal if we don't save anything.
Are we supposed to display an error even nothing is currently saved?

2023-06-19 09:27 UTC, Mai-Saad commented
@CrochetFeve0251 As per discussion with @piotrbak nothing is needed here and fine as is.

2023-06-19 13:12 UTC, Mai-Saad approved these changes
[testrail-report-494.pdf](https://github.com/wp-media/wp-rocket/files/11788479/testrail-report-494.pdf)
Working as expected with the following note (agreed to remain as is)
The 1st time we save settings while having wrong CF addon data + CF plugin is on and authenticated => validation error is displayed and any other save settings after that won't show the error

2023-06-19 13:45 UTC, merged