Enhancement/5984 woocommerce product sorting not woring with wpr
wp-media/wp-rocket pull request #5993
Opened 2023-06-19 17:59 UTC by jeawhanlee

## Description

Disable WP Rocket from clearing post cache when WC product is sorted.

Fixes #5984 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?
Manual

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-06-20 08:37 UTC, CrochetFeve0251 requested changes

2023-06-20 08:37 UTC, CrochetFeve0251 commented on inc/common/purge.php
> +	 * @param array $allow_clean_post Allow cleaning post cache if true; otherwise false.
@jeawhanlee filter docblock have a return type if you could add it.

2023-06-20 08:55 UTC, CrochetFeve0251 approved these changes

2023-06-21 19:05 UTC, Tabrisrp requested changes
I don't really like the idea of having a filter that is preventing the function from doing what it is expected to do. It could cause issues down the line, if someone uses it and the support has to dig to understand why cleaning doesn't happen for example.

I'd suggest instead to remove the action on the hook causing the issue (clean_post_cache) with this priority 9, and add it back once the WC call has finished running, on priority 11.

2023-06-22 14:41 UTC, engahmeds3ed requested changes
but this means that we will not clean those changed posts cache so their ordering will not reflect in category page or at any place, right?

2023-06-22 14:41 UTC, engahmeds3ed commented on inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php
> +	use ReturnTypesTrait;
do we really need this trait here?

2023-06-27 07:27 UTC, CrochetFeve0251 approved these changes

2023-06-29 13:50 UTC, vmanthos commented
I haven't been able to reproduce the issue on my test site but I logged cache clearing during sorting of products.
With the PR, cache clearing - which caused the issue, doesn't take place during sorting. So, this part is handled.

However, there is a regression as far as cache clearing goes.

Typically, we clear the `/shop` cache as well as that of all the categories pages the sorted products belong to.
This isn't happening with the current PR which only clears one of the category pages the product belongs to.

To reproduce this:
1. Add two products to the two same categories. Visit their URLs on the front end to make sure they are cached.
2. Change the product order in the sorting tab.
3. Check the URLs of both categories and the `/shop` page.

The latter will remain the same, and only one of the two category URLs will have been cleared.

2023-07-04 20:57 UTC, Tabrisrp approved these changes

2023-07-06 07:47 UTC, vmanthos approved these changes
This is working as expected! :+1: 

**TestRail Report:** [testrail-report-500.pdf](https://github.com/wp-media/wp-rocket/files/11966298/testrail-report-500.pdf)

2023-07-06 07:47 UTC, merged