add wp-optimize in plugins to deactivate
wp-media/wp-rocket pull request #6023
Opened 2023-07-04 06:16 UTC by mostafa-hisham

## Description
add wp-optimize in plugins to deactivate

Fixes #6005

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [ ] locally

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-04 06:16 UTC, mostafa-hisham commented
https://github.com/wp-media/wp-rocket/assets/29744252/f3a04580-d919-43db-878a-bc7a8bfc949e

2023-07-04 20:57 UTC, Tabrisrp requested changes

2023-07-04 20:57 UTC, Tabrisrp commented on inc/admin/ui/notices.php
> +		'psn-pagespeed-ninja'                        => 'psn-pagespeed-ninja/pagespeedninja.php',
this line is duplicated

2023-07-05 12:20 UTC, engahmeds3ed approved these changes

2023-07-05 20:39 UTC, merged