Enhancement/6041 add incompatible plugins backend
wp-media/wp-rocket pull request #6065
Opened 2023-07-25 13:34 UTC by mostafa-hisham

## Description
Plugin part for add incompatible plugins in backend

Fixes #6041 

## Type of change
- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?

- [ ] Locally
- [ ] Unit test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-07-26 12:15 UTC, Mai-Saad commented
@mostafa-hisham Thanks for the PR. During the exploratory test can see that the transient `wpr_dynamic_lists_incompatible_plugins` is not deleted after deleting WPR as same as the similar transients. Can you please check that?

Notes:
- As per discussion, we need to add data to the live backend before the release so it grabs the correct list.
- Currently the `wpr_dynamic_lists_incompatible_plugins.json` , is not in the WPR folder with installation. As per discussion, the new list file will be created after on creating a new release on GitHub

2023-07-26 12:31 UTC, mostafa-hisham commented
> @mostafa-hisham Thanks for the PR. During the exploratory test can see that the transient wpr_dynamic_lists_incompatible_plugins is not deleted after deleting WPR. Can you please check that?

@Mai-Saad 
should be fixed now

2023-07-26 14:39 UTC, engahmeds3ed requested changes
Good job, minor changes.

2023-07-26 14:39 UTC, engahmeds3ed commented on inc/Engine/Optimization/DynamicLists/Subscriber.php
> +		return array_merge( $plugins, $this->dynamic_lists->get_incompatible_plugins() );
```suggestion
		return array_merge( (array) $plugins, $this->dynamic_lists->get_incompatible_plugins() );
```

2023-07-26 14:39 UTC, engahmeds3ed commented on inc/Engine/Optimization/DynamicLists/IncompatiblePluginsLists/DataManager.php
> +	public function get_lists() {
why do we override here the get_lists method?
I believe it'd be better to change it to a new method so if we needed to use both method in the future, this will be easier.
what do u think?

2023-07-26 14:39 UTC, engahmeds3ed commented on inc/Engine/Optimization/DynamicLists/IncompatiblePluginsLists/DataManager.php
> +				$lists = array_merge( $lists, $list );
```suggestion
				$lists[$list['slug']] = $list['file'];
```
is this a valid suggestion?

2023-07-26 14:52 UTC, Tabrisrp requested changes

2023-07-26 14:52 UTC, remyperona commented on inc/Engine/Optimization/DynamicLists/IncompatiblePluginsLists/DataManager.php
> +			if ( get_rocket_option( trim( $condition ), false ) ) {
We could use the Options_Data class here by passing it to the constructor of the class

2023-07-27 04:08 UTC, mostafa-hisham commented on inc/Engine/Optimization/DynamicLists/Subscriber.php
> +		return array_merge( $plugins, $this->dynamic_lists->get_incompatible_plugins() );
@engahmeds3ed do we have to cast it again?
we have this condition before
```
if ( ! is_array( $plugins ) ) {
      $plugins = (array) $plugins;
}
```

2023-07-27 04:12 UTC, mostafa-hisham commented on inc/Engine/Optimization/DynamicLists/IncompatiblePluginsLists/DataManager.php
> +				$lists = array_merge( $lists, $list );
@engahmeds3ed It didn't work, `$list` is an array of objects

2023-07-27 07:10 UTC, engahmeds3ed approved these changes

2023-07-28 07:47 UTC, Mai-Saad approved these changes
Working as expected
Note:
- failed tests need to be checked at the 1st alpha
- translations for dynamic list update while valid /invalid license shall be checked in the prerelease
[testrail-report-508.pdf](https://github.com/wp-media/wp-rocket/files/12191777/testrail-report-508.pdf)

2023-07-28 07:48 UTC, merged