Fixes #6040 Preload mobile homepage on activation & RUCSS clean
wp-media/wp-rocket pull request #6067
Opened 2023-07-26 11:29 UTC by Tabrisrp

## Description

Preload mobile homepage on activation, and fix bug where preload happened before cache clean when doing a RUCSS clean.

Fixes #6040

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [ ] Automated tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-07-27 05:25 UTC, mostafa-hisham approved these changes
Looks good to me 
@wp-media/php 
but better have another quick look at it  
I didn't work a lot in the preload part

2023-07-27 07:23 UTC, engahmeds3ed requested changes

2023-07-27 07:23 UTC, engahmeds3ed commented on inc/Engine/Preload/ServiceProvider.php
> +		$options = $this->getLeagueContainer()->get( 'options' );
really I don't know the exact difference betwee both methods to get the container but as in here:
https://container.thephpleague.com/4.x/upgrade-guide/

> The distinction between AbstractServiceProvider::getContainer and AbstractServiceProvider::getLeagueContainer has been removed. Always just use AbstractServiceProvider::getContainer

2023-07-29 07:21 UTC, engahmeds3ed approved these changes

2023-07-31 13:40 UTC, Mai-Saad commented
@Tabrisrp thanks for the PR. please note that currently, after a fresh install of wpr , the cache of the home page is not added to the cache folder also it is completed in the cache table.

2023-07-31 14:54 UTC, CrochetFeve0251 commented on inc/Engine/Preload/ServiceProvider.php
> +		$options = $this->getLeagueContainer()->get( 'options' );
@engahmeds3ed the difference is that `getContainer` returns the `ContainerInterface` interface from the PSR and `getLeagueContainer` returns the `Container` from League library

2023-07-31 15:45 UTC, Tabrisrp commented
From my local testing:

It seems there is a timing issue at play here, when running the activation process, we create or modify multiple files (wp-config, advanced-cache, cache config), and WP Rocket itself is not fully loaded (confirmed by using the debug log on the cache process), so the preload requests to the homepage are not doing anything.

We would have to find a different solution for this point, as I expect it was not working correctly before either anyway.

2023-07-31 18:20 UTC, piotrbak commented
It's not a regression than, right @Mai-Saad ?

2023-08-01 04:39 UTC, Mai-Saad commented
Yes @piotrbak. The following is happening already on 3.14.2.1
- on trunk randomly (often), after fresh activation, the home URL is completed at the cache table but not in the cache folder (with custom sitemap or WordPress sitemap)
- on trunk randomly (rarely), after fresh install and activation of wpr then we enable separate mobile cache => only desktop is at cache folder although status is completed
**Note:** 
when using 3.12.0.5, usually it works fine regarding the home page added to the cache folder once completed, rarely after fresh activation of WPR, the home page is added as completed in the database (without adding a file in the cache folder yet) then the sitemap is fetched and the URL  status change to pending so the next processing URL is added at cache folder.

2023-08-01 13:23 UTC, Mai-Saad approved these changes
Now both mobile/desktop is added to the used CSS after clearing the used CSS and activating WPR while a separate mobile cache is on will add both mobile and desktop
 **note:**
- fresh activation won't add a cache file in the cache folder although the status is completed as same as with 3.14.2.1
- failed tests are also failing on 3.14.2.1
- if RUCSS and separate mobile cache are enabled at the same instant, we create the used CSS for the desktop of the home then preload the home then create the used CSS for mobile then preload home (same on 3.14.2.1)
- clear and preload cache while separate + rucss on, visit url while home and that URL are still pending=> sometimes loads only desktop (same on 3.14.2.1)
- randomly on the branch when disabling separate mobile cache if RUCSS was on and completed  => still have a mobile version in the cache folder (if after that we enabled separate mobile cache => only desktop added, for this part, it happened on trunk sometimes)
- activate while
1- cache is completed at the table but the folder is empty => adds the files for home (often, mainly when with activation or refresh admin after activation, other URLs added to the table and we here add home)
2- cache folder empty, cache table completed => adds files for home (other URLs added to cache table)
[testrail-report-509.pdf](https://github.com/wp-media/wp-rocket/files/12229425/testrail-report-509.pdf)

2023-08-01 14:02 UTC, merged