Fixes 5994: Added check for indexes on RUCSS response
wp-media/wp-rocket pull request #6080
Opened 2023-08-01 14:28 UTC by CrochetFeve0251

## Description

Check indexes on RUCSS response to prevent fatal error when they are not present.

Fixes #5994

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Unit Test

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-01 14:49 UTC, Tabrisrp requested changes

2023-08-01 14:49 UTC, Tabrisrp commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +			if ( false === $add_to_queue_response || ! isset( $add_to_queue_response['contents'] ) || ! isset( $add_to_queue_response['contents']['jobId'] ) || ! isset( $add_to_queue_response['contents']['que
You can pass multiple variables to the same `isset()` call, that will make it more readable

2023-08-02 13:21 UTC, remyperona approved these changes

2023-08-08 08:11 UTC, vmanthos approved these changes
Working as expected! :+1:

2023-08-08 08:12 UTC, merged