add filter rocket_delay_remove_rucss_failed_jobs to delete faild rucss jobs instead of 3 days hardcoded
wp-media/wp-rocket pull request #6087
Opened 2023-08-03 02:40 UTC by mostafa-hisham

## Description

add new filter `rocket_delay_remove_rucss_failed_jobs` and use its value in `get_failed_rows` function

Fixes #6066 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [ ] Locally

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2023-08-03 13:17 UTC, CrochetFeve0251 approved these changes

2023-08-04 13:03 UTC, vmanthos commented
Thank you @mostafa-hisham for the PR. 
It's working fine when the value-unit pair is correct, i.e. if it follows these:
https://dev.mysql.com/doc/refman/8.0/en/expressions.html#temporal-intervals

If `rocket_delay_remove_rucss_failed_jobs` returns any of the following:
`null`, float, boolean, `[]`, or an incorrect value-unit pair, e.g. `1 day`, 

then the failed jobs will stay there until the used CSS is manually or automatically truncated.

Maybe instead of retuning if the `$delay` is not valid (all cases), we could set the default values here:
https://github.com/wp-media/wp-rocket/blob/874c2ccfda5f63e9fbdd26abd8d70a7652cff268/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L836-L838

@piotrbak Should we check if the units are correct according to [this](https://dev.mysql.com/doc/refman/8.0/en/expressions.html#temporal-intervals) - this can complicate things on our part, or should this better be covered in our documentation?

2023-08-04 13:54 UTC, CrochetFeve0251 commented
> Thank you @mostafa-hisham for the PR. It's working fine when the value-unit pair is correct, i.e. if it follows these: https://dev.mysql.com/doc/refman/8.0/en/expressions.html#temporal-intervals
> 
> If `rocket_delay_remove_rucss_failed_jobs` returns any of the following: `null`, float, boolean, `[]`, or an incorrect value-unit pair, e.g. `1 day`,
> 
> then the failed jobs will stay there until the used CSS is manually or automatically truncated.
> 
> Maybe instead of retuning if the `$delay` is not valid (all cases), we could set the default values here:
> 
> https://github.com/wp-media/wp-rocket/blob/874c2ccfda5f63e9fbdd26abd8d70a7652cff268/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L836-L838
> 
> @piotrbak Should we check if the units are correct according to [this](https://dev.mysql.com/doc/refman/8.0/en/expressions.html#temporal-intervals) - this can complicate things on our part, or should this better be covered in our documentation?

I agree it is more logic to clean failed tasks as otherwise it will flood the table.

2023-08-07 06:29 UTC, mostafa-hisham commented
@piotrbak After checking this with @vmanthos 
We found out that changing failed jobs status to pending will not give them a new Job ID which means it is going to try to fetch the same failed data in this case `400 bad json ` 3 more times

Should we delete the records so it trie to create new jobs on Saas side?

thanks @vmanthos for checking this with me

2023-08-07 09:46 UTC, piotrbak commented
@mostafa-hisham When we receive the `400 bad json`, it means taht the job was already processed by the saas, right? There's no option that this job is in the saas queue?

2023-08-08 03:17 UTC, mostafa-hisham commented
@piotrbak, when we receive 400 bad json, means that the job is processed by saas and was deleted before the plugin gets its data.

2023-08-09 12:37 UTC, MathieuLamiot commented
See proposed solution [here](https://wp-media.slack.com/archives/C015FT0RBKQ/p1691578008322849?thread_ts=1691564901.977129&cid=C015FT0RBKQ). Moving back to In progress.

2023-08-10 08:16 UTC, CrochetFeve0251 approved these changes

2023-08-10 08:29 UTC, MathieuLamiot commented
Following [this](https://wp-media.slack.com/archives/C015FT0RBKQ/p1691654055694549?thread_ts=1691564901.977129&cid=C015FT0RBKQ), let's move forward with the PR and tackle the discovered new issues in a dedicated enhancement story.
Moved the task to Ready for PR, and now ready for QA.

2023-08-10 11:53 UTC, MathieuLamiot commented
Following [this](https://wp-media.slack.com/archives/C015FT0RBKQ/p1691666126183749?thread_ts=1691564901.977129&cid=C015FT0RBKQ):
Let's keep the PR here and wait for a proper handling of failed status and related JobID in the plugin so that we can actually retry a new job.

2023-08-16 12:11 UTC, CrochetFeve0251 requested changes

2023-08-16 12:11 UTC, CrochetFeve0251 commented on inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php
> +	 * Reset th job and add new job_id pending.
```suggestion
	 * Reset the job and add new job_id pending.
```

2023-08-16 12:11 UTC, CrochetFeve0251 commented on tests/Unit/inc/Engine/Optimization/RUCSS/Controller/UsedCSS/clearFailedUrls.php
> +				//var_dump($config['is_int']);
```suggestion

```

2023-08-16 12:11 UTC, CrochetFeve0251 commented on tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/cronRemoveFailedJobs.php
> +			}'
```suggestion
			'body'=> json_encode([
			"code" => 200,
			"message" => "Added to Queue successfully.",
			"contents" => [
				"jobId" => "OVH_EU--496540278",
				"queueName" => "EU",
				"isHome" => false,
				"queueFullName" => "rucssJob_EU"
				]
			]),
```

2023-08-16 12:11 UTC, CrochetFeve0251 commented on tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/cronRemoveFailedJobs.php
> +		add_filter('pre_http_request', [$this, 'edit_http_request'], 10, 3);
@mostafa-hisham is there an issue adding it to the `set_up` method that would be more clean as it is what we usually do for filters.

2023-08-16 12:25 UTC, CrochetFeve0251 approved these changes

2023-08-17 10:37 UTC, Mai-Saad commented
@mostafa-hisham Thanks for the PR. Notes from the exploratory test:
-  When using the filter with [] `add_filter( 'rocket_delay_remove_rucss_failed_jobs', function( $interval ){
return [];
} );` ,we will have a warning `[17-Aug-2023 09:08:03 UTC] PHP Warning:  Array to string conversion in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 833` => Will remain as is as per discussion
- (fixed) When we switch failed to pending, the last modified time stamp is not changed
- If we executed the Cron `rocket_remove_rucss_failed_jobs` while external requests are blocked, we won't switch failed to pending till requests are not blocked => As per discussion, this is the new behavior as we request job id before switching to pending. 
- Probably not related to PR and further investigation is needed => when change retries and status change to failed while external requests are blocked, we are not changing last modified. @piotrbak what do you think?

2023-08-17 12:26 UTC, CrochetFeve0251 approved these changes

2023-08-18 09:43 UTC, Mai-Saad approved these changes
Working as expected with the following notes:
1- Filter won't apply decimal values i.e 1.5 days will be ignored and the default is applied
2- Empty array if used will generate warning
3- We may have a corner case where URLs at cache are locked while URLs are failed in used CSS while external requests are blocked => further investigation is needed
[testrail-report-518.pdf](https://github.com/wp-media/wp-rocket/files/12377910/testrail-report-518.pdf)

2023-09-15 08:37 UTC, merged