Stop clearing cache when incompatible plugins list is updated
wp-media/wp-rocket pull request #6166
Opened 2023-09-15 06:49 UTC by engahmeds3ed

## Description

As groomed.

Fixes #6077

## Type of change

*Please delete options that are not relevant.*

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No, exactly the same.

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-09-20 12:58 UTC, engahmeds3ed commented
For the tests, I invested some time trying to add them quickly but I found that we now only test the default lists so we need to refactor those tests to be able to test the cache clear functionality with incompatible plugins only in a better way.

For that I created this issue not to forget about it: https://github.com/wp-media/wp-rocket/issues/6180

2023-09-20 13:27 UTC, Tabrisrp requested changes

2023-09-20 13:27 UTC, Tabrisrp commented on inc/Engine/Optimization/DynamicLists/DynamicLists.php
> +			do_action( 'rocket_after_save_dynamic_lists', $should_purge );
Add the new param description to the docblock

2023-09-20 13:40 UTC, engahmeds3ed commented on inc/Engine/Optimization/DynamicLists/DynamicLists.php
> +			do_action( 'rocket_after_save_dynamic_lists', $should_purge );
Good catch, Many thanks.
Fixed

2023-09-20 13:42 UTC, Tabrisrp approved these changes

2023-09-21 06:54 UTC, vmanthos approved these changes
Working as expected! 🙏 :tophat:

2023-09-21 06:54 UTC, merged