Closes #6152: Add license type to what is reported to Mixpanel
wp-media/wp-rocket pull request #6189
Opened 2023-09-26 13:02 UTC by Miraeld

## Description

This will help see how representative is the current sample from opted-in users vs our current users and how reliable data collected from them to help with product decisions.

A new function has been created that returns the type of license. As this functionality is used in different files, it has been modified to use the newly created function.

Fixes #6152 

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

Yes

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-09-26 13:13 UTC, engahmeds3ed requested changes
Good job @Miraeld in ur first PR.

I didn't fully review it yet but I noticed this important point.

Also plz run the command
```
composer phpcs:fix
```

to automatically fix most of those reported coding standard issues.

2023-09-26 13:13 UTC, engahmeds3ed commented on inc/functions/admin.php
> +function get_license_type($customer_data) {
You are in the global namespace, you need to add a prefix here to be `rocket_get_license_key`

2023-09-26 13:16 UTC, Miraeld commented on inc/functions/admin.php
> +function get_license_type($customer_data) {
Oh alright, didn't know about that, I'm going to add it :)

2023-09-26 13:19 UTC, Miraeld commented on inc/functions/admin.php
> +function get_license_type($customer_data) {
Alright, I've changed it :)

2023-09-26 13:30 UTC, remyperona requested changes
The code needs to be updated to follow our coding standards (errors are available in the CS GH action)

2023-09-27 07:05 UTC, engahmeds3ed requested changes
Minor adjustments

2023-09-27 07:05 UTC, engahmeds3ed commented on inc/functions/admin.php
> +		$type = 'Single';
```suggestion
		return 'Single';
```

You can return directly and get rid of any else.

2023-09-27 07:05 UTC, engahmeds3ed commented on inc/functions/admin.php
> +	) {
Let's make it more readable.

```suggestion
	if (
		false === $customer_data
		||
		! isset( $customer_data->licence_account )
	) {
```

2023-09-27 07:05 UTC, engahmeds3ed commented on inc/functions/admin.php
> +	) {
```suggestion
	if (
		1 <= $customer_data->licence_account
		&&
		3 > $customer_data->licence_account
	) {
```

2023-09-27 07:58 UTC, Miraeld commented on inc/functions/admin.php
> +		$type = 'Single';
I've corrected it.

2023-09-27 07:58 UTC, Miraeld commented on inc/functions/admin.php
> +	) {
I've corrected it.

2023-09-27 07:58 UTC, Miraeld commented on inc/functions/admin.php
> +	) {
I've corrected it.

2023-10-03 06:39 UTC, CrochetFeve0251 approved these changes

2023-10-03 07:48 UTC, vmanthos commented
@Miraeld Thank you for the PR! 
I see the `license_type` is added to the data sent to Mixpanel. :+1: 

@wp-media/productrocket The new info that will be collected is not listed here:
![image](https://github.com/wp-media/wp-rocket/assets/193660/070aab57-22bd-41a6-b12d-0072bc77d240)

Also, the CTA (Activate Rocket Analytics) is displayed even when Rocket Analytics is enabled.

Please confirm (or not) that:
1. The license type info should be included in the data collection table.
2. The CTA should not be displayed if Rocket Analytics is already enabled.

2023-10-04 05:54 UTC, DahmaniAdame commented
> The license type info should be included in the data collection table.
Yes, it should show. 

> The CTA should not be displayed if Rocket Analytics is already enabled.
No, there is no need to redisplay it if the consent is already given.

2023-10-05 13:52 UTC, Tabrisrp approved these changes

2023-10-06 07:01 UTC, vmanthos commented
@Miraeld Thank you for the fixes.

The CTA button is not displayed but with that, the following text is hidden as well:
![image](https://github.com/wp-media/wp-rocket/assets/193660/91034cd6-ad4f-4778-a2cf-8e33a80c4a7d)

Since that's a disclaimer notice it should stay in place.

Also, and this is a late notice on my part, there is inconsistency in how various info is displayed as far as the used fonts go:
![image](https://github.com/wp-media/wp-rocket/assets/193660/07b49693-0a59-41ac-a0c4-389b37568f5e)

This has to do with some of it being wrapped in `<code></code>` and that results in the use of a monospace font.

Unless there is a specific reason to have some part in `<code>`, maybe we can go with a uniform look there.

@DahmaniAdame What's your take on this?

2023-10-06 07:27 UTC, DahmaniAdame commented
@vmanthos yes, uniformizing it is the way to go. 
`code` looks nicer, but not consistent and practical (doesn't look good when lines are wrapped). 
Uniformizing it without the `code` would make sense.

2023-10-06 09:13 UTC, Miraeld commented
@vmanthos I've corrected the cta, now only the button is not displayed once rocket analytics is enabled. 

@vmanthos @DahmaniAdame I've taken off the `<code></code>` tags to standardize the formatting.

2023-10-06 10:20 UTC, vmanthos approved these changes
Thank you for the fixes, @Miraeld ! 

This is working as expected. :+1:

2023-10-06 10:21 UTC, merged