Closes #6175 Fatal error related to Logger
wp-media/wp-rocket pull request #6212
Opened 2023-10-10 05:33 UTC by Miraeld

## Description

When enabling the debug mode of WP Rocket, we get a fatal error related to Monolog.
As explained in the grooming this is due to Mozart. 

Fixes #6175

## Type of change

*Please delete options that are not relevant.*

- Bug fix (non-breaking change which fixes an issue).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-10-10 07:35 UTC, CrochetFeve0251 approved these changes

2023-10-10 07:35 UTC, CrochetFeve0251 commented on inc/Engine/Cache/PurgeActionsSubscriber.php
> +		if ( version_compare( $old_version, '3.15', '>=' ) ) {
@Miraeld are we sure we gonna deploy it in 3.15? Maybe you can ask @piotrbak for that

2023-10-10 10:05 UTC, wordpressfan requested changes
Totally agree with @CrochetFeve0251 we need to know the exact version this fix will be shipped in.

Pinging @piotrbak

2023-10-10 10:16 UTC, piotrbak commented
@wordpressfan It's a change touching the `advanced-cache.php` which is important part, but it's a regression related to 3.15 release. I'd say we should release it asap, which would be 3.15.3 version, if we'll be able to test it properly.

2023-10-10 23:07 UTC, Miraeld commented
I have modified the version to make it `3.15.3`.

2023-10-12 10:56 UTC, Mai-Saad approved these changes
Working as expected
[testrail-report-533.pdf](https://github.com/wp-media/wp-rocket/files/12880607/testrail-report-533.pdf)

2023-10-17 09:14 UTC, merged