Closes #6204: Refine RUCSS error reporting
wp-media/wp-rocket pull request #6216
Opened 2023-10-11 12:26 UTC by Miraeld

## Description

The goal here is to give more info about the error message from the RUCSS process, and also, add a new column in the DB called `submitted_at`. Also, we do update the `error_message` column in order to get more details when the request fails.

Fixes #6204

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-10-12 07:22 UTC, CrochetFeve0251 requested changes

2023-10-12 07:22 UTC, CrochetFeve0251 commented on tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/checkJobStatus.php
> +	}
@Miraeld there is an issue with indentation here

2023-10-12 07:36 UTC, Miraeld commented on tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/checkJobStatus.php
> +	}
It's been fixed :)

2023-10-12 13:29 UTC, Tabrisrp approved these changes

2023-10-17 09:11 UTC, Mai-Saad commented
Working as expected.
- Submitted at added to the table
- detailed error + timestamp in message (some char then truncate)
- bad json msg is replaced
- submitted_at = modified due to https://github.com/wp-media/wp-rocket/issues/6229

2023-10-19 11:33 UTC, merged