Closes #6181: DB Query can cause timeout
wp-media/wp-rocket pull request #6218
Opened 2023-10-11 22:45 UTC by Miraeld

## Description

On a site with many many private posts, any action that involves post cache clearing will result in a timeout error.
DB Queries have been optimised to make it more responsive and quicl.

Fixes #6181

## Type of change

*Please delete options that are not relevant.*

- Bug fix (non-breaking change which fixes an issue).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-10-12 07:54 UTC, CrochetFeve0251 approved these changes

2023-10-12 13:29 UTC, Tabrisrp requested changes

2023-10-12 13:29 UTC, Tabrisrp commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +		$is_excluded = apply_filters( 'rocket_preload_exclude', false, $url );
add docblock for filter

2023-10-13 00:41 UTC, Miraeld commented on inc/Engine/Preload/Controller/CheckExcludedTrait.php
> +		$is_excluded = apply_filters( 'rocket_preload_exclude', false, $url );
The docblock has been added.

2023-10-13 13:02 UTC, Tabrisrp approved these changes

2023-10-30 11:50 UTC, vmanthos approved these changes
This is working as expected as far as the feature goes.

**NOTE**

I haven't been able to reproduce the original issue although I tried to do so in different environments. Testing was mainly about preventing regressions.

**TestRail report:** Will be added when ready.

2023-10-30 12:44 UTC, merged