Fixes 6271:  Prevent saas looping
wp-media/wp-rocket pull request #6272
Opened 2023-11-16 13:11 UTC by CrochetFeve0251

## Description
Guard the `process_on_submit_jobs` method against RUCSS disabled.
Pass failed registration to `fail` status.

Fixes #6271 

## Type of change

- Bug fix (non-breaking change which fixes an issue).

## Is the solution different from the one proposed during the grooming?

No.

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

2023-11-16 13:48 UTC, mostafa-hisham commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +use function _PHPStan_c6b09fbdf\RingCentral\Psr7\str;
do we use this?

2023-11-16 13:50 UTC, CrochetFeve0251 commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +use function _PHPStan_c6b09fbdf\RingCentral\Psr7\str;
PHPStorm :') I didn't saw that one thx

2023-11-16 13:50 UTC, MathieuLamiot requested changes

2023-11-16 13:50 UTC, MathieuLamiot commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +				$this->used_css_query->make_status_failed( (int) $row->id, '',  '' );
Please store response['code'] and response['message'] if available in the DB.

2023-11-16 13:55 UTC, CrochetFeve0251 commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +				$this->used_css_query->make_status_failed( (int) $row->id, '',  '' );
@MathieuLamiot I did it at the beginning but the answer we get from the `send_api` is in fact a boolean `false` due to here: https://github.com/wp-media/wp-rocket/blob/78371cb401c22b32d213f748960bbdf9783263b9/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L1068

Should I keep it like that or do we need more in depth changes?

2023-11-16 14:13 UTC, MathieuLamiot commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +				$this->used_css_query->make_status_failed( (int) $row->id, '',  '' );
Ah right... OK, let's keep it like this for now and open an issue for later to store the response in case of failure when adding to the queue. OK.

2023-11-16 14:13 UTC, MathieuLamiot approved these changes

2023-11-20 06:49 UTC, vmanthos commented
This is working as expected!

**NOTE**

[Known issue](https://github.com/wp-media/wp-rocket/pull/6272#discussion_r1395722173).

2023-11-20 06:49 UTC, vmanthos approved these changes

2023-11-20 07:08 UTC, merged