Closes #4226: Importing data should not clear cache
wp-media/wp-rocket pull request #6274
Opened 2023-11-17 08:10 UTC by Miraeld

## Description
When a user is importing data to Wordpress or WooCommerce, WP Rocket is clearing cache for each new content which make the process very slow. 
Here we are offering our user a new filter `rocket_importing_mode` which will disable cache clearing. 

Fixes #4226 
## Type of change

- New feature (non-breaking change which adds functionality).

## Is the solution different from the one proposed during the grooming?

Yes, we have created a new filter `rocket_importing_mode` to let our user or thirdparties enable it to avoid cache clearing. 

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-11-20 10:00 UTC, mostafa-hisham approved these changes
looks good

2023-11-20 10:41 UTC, wordpressfan commented
Ongoing discussion: https://wp-media.slack.com/archives/CUT7FLHF1/p1700228302413559

2023-11-20 10:46 UTC, mostafa-hisham requested changes
after checking this slack [convo](https://wp-media.slack.com/archives/CUT7FLHF1/p1700228302413559) we need to handle the `WP_IMPORTING` too

2023-11-20 13:32 UTC, Tabrisrp reviewed
Could be good to add it in PurgeActionsSubscriber for the method cleaning terms too

2023-11-20 15:20 UTC, wordpressfan requested changes
@mostafa-hisham what if we added the default value for the filter with the value of the constant?

2023-11-20 15:20 UTC, wordpressfan commented on inc/Engine/Cache/Purge.php
> +		if ( (bool) apply_filters( 'rocket_importing_mode', false ) || defined( 'WP_IMPORTING' ) ) {
```suggestion
		if ( (bool) apply_filters( 'rocket_importing_mode', defined( 'WP_IMPORTING' ) && WP_IMPORTING ) ) {
```

2023-11-20 15:24 UTC, Tabrisrp commented on inc/Engine/Cache/Purge.php
> +		if ( (bool) apply_filters( 'rocket_importing_mode', false ) || defined( 'WP_IMPORTING' ) ) {
it could be a good idea

2023-11-20 15:31 UTC, wordpressfan requested changes

2023-11-20 15:31 UTC, wordpressfan commented on inc/Engine/Cache/PurgeActionsSubscriber.php
> +		}
The filter is defined 6 times, do u think it'd be better having a dedicated function for it so it can be maintained easily?

2023-11-20 19:35 UTC, wordpressfan approved these changes

2023-11-22 06:12 UTC, thinkjarvisdesignandmarketing commented
Can you confirm that this fix covers WPALLIMPORT and WP_IMPORTING?
Also can you confirm that WP-Rocket intends to provide usaging instructions? Or does this automatically apply to all WP ALL IMPORT scheduled imports?

2023-11-22 10:07 UTC, Mai-Saad commented
With WP-> tools->import(post/page), the cache isn't cleared now by default (nothing is needed from the user side). However, not reproducible on the test site with WP All Import so if anyone else can confirm it's fixed with WP All import would be great

2023-11-22 10:33 UTC, thinkjarvisdesignandmarketing commented
> With WP-> tools->import, the cache isn't cleared now by default (nothing is needed from the user side). However, not reproducible on the test site with WP All Import so if anyone else can confirm it's fixed with WP All import would be great

@Mai-Saad @piotrbak @wordpressfan @Tabrisrp This MUST cover WPALLIMPORT Imports to close off this issue. wp_importing. I will raise a support request with WPALLIMPORT and direct them to this Git.

2023-11-22 10:33 UTC, wordpressfan commented
> Can you confirm that this fix covers WPALLIMPORT and WP_IMPORTING? Also can you confirm that WP-Rocket intends to provide usaging instructions? Or does this automatically apply to all WP ALL IMPORT scheduled imports? @Miraeld @Tabrisrp @wordpressfan @mostafa-hisham

This PR added a new filter that can be used with other third-party or custom code to check on any constant they want.
By default we handle the case of the constant `WP_IMPORTING`, you can use the following snippet:

```
add_filter( 'rocket_is_importing', function( $importing ) {
    return $importing || ( defined( 'ANY_CONSTANT_NEEDED' ) && ANY_CONSTANT_NEEDED )
} );
```

2023-11-22 12:13 UTC, Mai-Saad commented
Using the following steps confirms it is fixed with WP All Import by default.
1- In the 576th line of the code in inc/functions/files.php add the following error_log:
`error_log( "\n[" . date('Y-m-d H:i:s', $_SERVER['REQUEST_TIME']) . "] URLs: " . print_r($urls, true), 3, ABSPATH . "wpr.log" ); `
2. Run import using WPAI, choosing the import of new products + select to udpate even if they exist
3. Check if something is written to the log
4. Expected is that on develop it'll be written, on PR not.

Note: 
Manual cache clear will be needed in this case after import so changes are reflected on updated products.

Thanks to @piotrbak for the steps

2023-11-22 13:16 UTC, Mai-Saad approved these changes

2023-11-22 13:16 UTC, merged