Closes #6282: Stop Firing WP Cron when disabled
wp-media/wp-rocket pull request #6295
Opened 2023-11-28 07:38 UTC by Miraeld

## Description

Add a check if CRON are disabled before firing one. 

Fixes #6282 

## Type of change
- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?
No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-11-28 08:12 UTC, CrochetFeve0251 approved these changes

2023-11-28 11:20 UTC, MathieuLamiot commented
To keep track of our discussion @Miraeld, this could benefit from one or two test cases to make sure we don't create regressions later on on the use of DISABLE_WP_CRON

2023-11-29 08:57 UTC, Mai-Saad reviewed
@Miraeld Thanks for the PR. Shouldn't the condition here be `typeof rocket_ajax_data.notice_end_time !== 'undefined' && ! rocket_ajax_data.cron_disabled` ?

2023-11-29 10:21 UTC, Miraeld commented
> @Miraeld Thanks for the PR. Shouldn't the condition [here](https://github.com/wp-media/wp-rocket/pull/6295/files#diff-9b19f89766a63e11ef01f00fc66257f99485141dd91781916529b2f14bb6bf56R354) be `typeof rocket_ajax_data.notice_end_time !== 'undefined' && ! rocket_ajax_data.cron_disabled` ?
You are right, I'm going to correct it.

2023-11-30 07:23 UTC, mostafa-hisham approved these changes

2023-12-01 07:55 UTC, wordpressfan requested changes

2023-12-01 07:55 UTC, wordpressfan commented on assets/js/wpr-admin.js
> +if (typeof rocket_ajax_data.notice_end_time !== 'undefined' && ! rocket_ajax_data.cron_disabled) {
@Miraeld I believe we need to build the minified file.

2023-12-01 08:44 UTC, wordpressfan commented on assets/js/wpr-admin.js
> +if (typeof rocket_ajax_data.notice_end_time !== 'undefined' && ! rocket_ajax_data.cron_disabled) {
@mostafa-hisham or it's built automatically using a github action?

2023-12-01 12:07 UTC, wordpressfan commented on assets/js/wpr-admin.js
> +if (typeof rocket_ajax_data.notice_end_time !== 'undefined' && ! rocket_ajax_data.cron_disabled) {
I generated it after changing the logic a bit.

2023-12-04 12:08 UTC, CrochetFeve0251 approved these changes

2023-12-05 06:59 UTC, Mai-Saad approved these changes
Working as expected.
Note: if cron is disabled, the success msg will mention home is processed while it isnot (will be handled in separate GH)
[testrail-report-549.pdf](https://github.com/wp-media/wp-rocket/files/13556304/testrail-report-549.pdf)

2023-12-05 06:59 UTC, merged