Closes #6281: Task/lcp refactor rucss api cron queue
wp-media/wp-rocket pull request #6307
Opened 2023-12-05 08:29 UTC by jeawhanlee

## Description

Refactor RUCSS, cron, queue and API module.

Fixes #6281 

## Type of change

sub-task

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2023-12-12 17:57 UTC, CrochetFeve0251 requested changes
i think we should make a clear split between what is abstract and concrete logic aka atf and rucss. 

The issue here is that we mixed namespaces but also concerns.
For me the queue should have no idea from what it processes thanks to abstraction so it will be only in charge of handling the queue. It will also prevent to have to change that logic if we need in the future to add a new set of actions to that queue.

Also you can insert families of classes using factories or using tags on the container which will prevent you from having to handle it inside the subscriber.

For the hooks you can use a variable like `"rocket{$this->my_prefix}_pending_jobs"` or find an abstract name so it won't be heavily linked to the RUCSS or ATF.

Also I don't see any tests is this something wanted? 

PS: It can seem like a lot of comments but as it is architectural things it impacts a bit everywhere. So I tried to keep only comments which illustrated each cases.

PS 2: I don't see any deprecated code when most hooks linked to RUCSS seems to have disappeared leading to potential breaks inside the configs from users. I think that would be beneficial for our support to make a bridge between the old hooks and the new ones.

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Context/RUCSSContext.php
> +class RUCSSContext extends AbstractContext {
@jeawhanlee This context shouldn't be inside the RUCSS part?

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +			'rocket_rucss_atf_clean_rows_time_event' => 'cron_clean_rows',
@jeawhanlee why theses hooks are related to rucss? Shouldn't they be abstract? (we are in common)

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +		wp_schedule_event( time(), 'weekly', 'rocket_rucss_atf_clean_rows_time_event' );
@jeawhanlee same here

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +		$interval = apply_filters( 'rocket_rucss_atf_pending_jobs_cron_interval', 1 * rocket_get_constant( 'MINUTE_IN_SECONDS', 60 ) );
@jeawhanlee here too

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +		$schedules['rocket_rucss_atf_pending_jobs'] = [
@jeawhanlee here too

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +		$this->rucss_context = $rucss_context;
@jeawhanlee why are we using the rucss context?

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Managers/AtfManager.php
> +class AtfManager extends AbstractManager implements ManagerInterface, LoggerAwareInterface {
@jeawhanlee same with the Atf why it is inside the common namespace? Shouldn't be that logic inside the Above the fold namespace?

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Managers/RUCSSManager.php
> +class RUCSSManager extends AbstractManager implements ManagerInterface, LoggerAwareInterface {
@jeawhanlee same here

2023-12-12 17:57 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/ServiceProvider.php
> +class ServiceProvider extends AbstractServiceProvider {
I think we need to make a clear split between what is inside the abstract logic and RUCSS and ATF ones.
Using factories here could be the way

2023-12-12 18:07 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/APIHandler/AbstractAPIClient.php
> +	const API_URL = 'https://rucss-director-staging.public-default.live2-k8s-cph3.one.com/';
@jeawhanlee I think you forgot that

2023-12-12 18:51 UTC, Tabrisrp requested changes

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/Database/Queries/AbstractQuery.php
> -				],
I don't think those should be removed

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/Database/Queries/AbstractQuery.php
> +	 * @return int/boolean
```suggestion
	 * @return bool|int
```

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/Database/Queries/AbstractQuery.php
> +	 * @return int/boolean
```suggestion
	 * @return bool|int
```

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/JobManager/APIHandler/AbstractAPIClient.php
> +	const API_URL = 'https://rucss-director-staging.public-default.live2-k8s-cph3.one.com/';
we will need to remember to update this later

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/JobManager/Context/RUCSSContext.php
> +namespace WP_Rocket\Engine\Common\JobManager\Context;
I think this should be in the RUCSS namespace, even if we use it here. We could use it later in the RUCSS classes too.

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +		if ( wp_next_scheduled( 'rocket_rucss_atf_clean_rows_time_event' ) ) {
I think we should make the SaaS related events a more generic name, like `rocket_sass_clean_rows_time_event`.

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +	 * Adds new interval for RUCSS pending jobs cron
```suggestion
	 * Adds new interval for SaaS pending jobs cron
```

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/JobManager/Cron/Subscriber.php
> +	 * Clear schedule of RUCSS CRONs on deactivation.
```suggestion
	 * Clear schedule of SaaS CRONs on deactivation.
```

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/JobManager/Queue/Queue.php
> +	private $pending_job_cron = 'rocket_rucss_atf_pending_jobs_cron';
```suggestion
	private $pending_job_cron = 'rocket_saas_pending_jobs_cron';
```

2023-12-12 18:51 UTC, remyperona commented on inc/Engine/Common/JobManager/Queue/Queue.php
> +			'rocket_rucss_atf_job_check_status',
```suggestion
			'rocket_saas_job_check_status',
```

2023-12-13 06:21 UTC, vmanthos commented on inc/Engine/Common/JobManager/APIHandler/AbstractAPIClient.php
> +	const API_URL = 'https://rucss-director-staging.public-default.live2-k8s-cph3.one.com/';
Why don't we do it like here?
https://github.com/wp-media/wp-rocket/blob/fb65f675bf69ba50e40918c57312e20dec0ddc87/inc/Engine/Optimization/RUCSS/AbstractAPIClient.php#L69-L71

That way, for testing we'll be able to use the constant, and we will not risk shipping the staging site URL.

2023-12-14 10:45 UTC, jeawhanlee commented on inc/Engine/Common/Database/Queries/AbstractQuery.php
> -				],
I'm doing this to return all the columns then use this to check which job is unique to lcp or rucss for example, row for atf will return a column with lcp and row of rucss will return a column with css.

2023-12-14 12:49 UTC, CrochetFeve0251 approved these changes
As per discussion with @jeawhanlee the routing from old hooks to new hooks will be done later on.
Same for testing.

2023-12-14 12:49 UTC, CrochetFeve0251 commented on inc/Engine/Common/JobManager/Managers/AbstractManager.php
> +class AbstractManager {
As we have an interface here I am thinking that using a trait could be beneficial for later evolution as with traits we are not limited to one parent

2023-12-14 12:49 UTC, CrochetFeve0251 commented on inc/Engine/Common/Database/Tables/AbstractTable.php
> +class AbstractTable extends Table implements TableInterface {
Same thing as for the manager here as we got the interface we could use a trait at that level

2023-12-14 19:14 UTC, Tabrisrp requested changes

2023-12-14 19:14 UTC, remyperona commented on inc/Engine/Common/Database/Table.php
> +interface Table {
```suggestion
interface TableInterface {
```

2023-12-14 19:14 UTC, remyperona commented on inc/Engine/Common/JobManager/AbstractFactory/SaasFactory.php
> +use WP_Rocket\Engine\Common\Database\Table;
```suggestion
use WP_Rocket\Engine\Common\Database\TableInterface;
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Common/JobManager/AbstractFactory/SaasFactory.php
> +	 * @return Table
```suggestion
	 * @return TableInterface
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Common/JobManager/AbstractFactory/SaasFactory.php
> +	public function table(): Table;
```suggestion
	public function table(): TableInterface;
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/Jobs/Factory.php
> +use WP_Rocket\Engine\Common\Database\Table;
```suggestion
use WP_Rocket\Engine\Common\Database\TableInterface;
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/Jobs/Factory.php
> +	 * @var Table
```suggestion
	 * @var TableInterface
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/Jobs/Factory.php
> +	 * @param Table            $table ATF Table.
```suggestion
	 * @param TableInterface   $table ATF Table.
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/Jobs/Factory.php
> +	public function __construct( ManagerInterface $manager, Table $table ) {
```suggestion
	public function __construct( ManagerInterface $manager, TableInterface $table ) {
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/Jobs/Factory.php
> +	 * @return Table
```suggestion
	 * @return TableInterface
```

2023-12-14 19:14 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/Jobs/Factory.php
> +	public function table(): Table {
```suggestion
	public function table(): TableInterface {
```

2023-12-14 20:29 UTC, Tabrisrp approved these changes

2023-12-15 12:18 UTC, merged