Closes #6354: Tests for RUCSS API & CRON Refactor
wp-media/wp-rocket pull request #6356
Opened 2024-01-02 16:10 UTC by jeawhanlee

## Description
Adds tests for RUCSS API & CRON Refactor

Fixes #6354

2024-01-09 15:06 UTC, Khadreal commented on tests/Fixtures/inc/Engine/Common/JobManager/APIHandler/.DS_Store
I think this should be in gitignore file

2024-01-09 15:57 UTC, jeawhanlee commented on tests/Fixtures/inc/Engine/Common/JobManager/APIHandler/.DS_Store
it shouldn't even be there in the first place, Thanks @Khadreal

2024-01-10 11:45 UTC, Khadreal approved these changes
Looks good to me

2024-01-12 11:25 UTC, wordpressfan requested changes
We have failed tests, mainly because this method:
```
WP_Rocket\Engine\Optimization\RUCSS\Admin\Settings::add_localize_script_data
```

seems like it is moved to

https://github.com/wp-media/wp-rocket/blob/0b20b4047605be6f190d5ba9aa9b18f8bf20222d/inc/Engine/Saas/Admin/Subscriber.php#L160-L162

2024-01-12 11:39 UTC, jeawhanlee commented
> We have failed tests, mainly because this method:
> 
> ```
> WP_Rocket\Engine\Optimization\RUCSS\Admin\Settings::add_localize_script_data
> ```
> 
> seems like it is moved to
> 
> https://github.com/wp-media/wp-rocket/blob/0b20b4047605be6f190d5ba9aa9b18f8bf20222d/inc/Engine/Saas/Admin/Subscriber.php#L160-L162

I saw it but did not touch this yet as it's not related to the refactored RUCSS CRON & API Module plus I think they are related to a sub-task of 3.16 that @Tabrisrp worked on, so I don't have enough context on how they will be implemented.

2024-03-22 19:24 UTC, Tabrisrp approved these changes

2024-03-22 19:24 UTC, merged