Fixes #6392 Optimize WP Query in `rocket_url_to_postid()`
wp-media/wp-rocket pull request #6403
Opened 2024-01-22 20:16 UTC by Tabrisrp

## Description

Optimize the query by passing the args to prevent caching and found rows calculation.

Fixes #6392

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No grooming, small change.

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2024-01-23 03:18 UTC, Miraeld approved these changes

2024-02-14 12:40 UTC, Mai-Saad commented
Related initial test plan https://wpmediaqa.testrail.io/index.php?/runs/view/816&group_by=cases:section_id&group_order=asc

2024-02-14 15:44 UTC, wordpressfan requested changes

2024-02-14 15:44 UTC, wordpressfan commented on inc/functions/posts.php
> +				$query = new WP_Query(
As far as I know, WP_Query constructor has only one argument, what I'm missing here?

2024-02-15 14:52 UTC, wordpressfan commented on inc/functions/posts.php
> +				$query = new WP_Query(
@Tabrisrp I think we are fine now, just wanted to mention that those items will be outside the filter, and I think that's fine or u think to consider them into the filter so anyone can play with it if he faced a problem?

2024-02-15 20:38 UTC, Tabrisrp commented on inc/functions/posts.php
> +				$query = new WP_Query(
I think we don't want those to be overridden by the filter, as that would reduce optimization of the query.

2024-02-16 14:04 UTC, wordpressfan approved these changes

2024-02-28 16:37 UTC, hanna-meda commented
Moved this to QA done for now without merging it till we check the 2 blocked tests in [here](https://wpmediaqa.testrail.io/index.php?/runs/view/816).

2024-02-29 13:15 UTC, hanna-meda approved these changes
[testrail-report-577.pdf](https://github.com/wp-media/wp-rocket/files/14448468/testrail-report-577.pdf)

2024-02-29 13:15 UTC, merged