Closes #6372: Log on submit status last entry
wp-media/wp-rocket pull request #6411
Opened 2024-01-25 10:40 UTC by jeawhanlee

## Description

This PR logs the last entry for new rucss job added.

Fixes #6372 

## Type of change

- New feature (non-breaking change which adds functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

2024-01-25 20:00 UTC, Tabrisrp requested changes

2024-01-25 20:00 UTC, Tabrisrp commented on inc/Engine/Debug/RUCSS/Subscriber.php
> +use WP_Rocket\Admin\Options_Data;
```suggestion
use WP_Rocket\Admin\{Options, Options_Data};
```

2024-01-25 20:00 UTC, Tabrisrp commented on inc/Engine/Debug/Resolver.php
> +			if ( ! (bool) get_rocket_option( $option ) ) {
We could use the Options_Data instance instead

2024-01-25 20:00 UTC, Tabrisrp commented on inc/classes/ServiceProvider/class-options.php
> +		'options_debug',
I would register this class in the Debug service provider too instead

2024-01-29 20:46 UTC, Tabrisrp requested changes

2024-01-29 20:46 UTC, Tabrisrp commented on wp-rocket.php
> +define( 'WP_ROCKET_DEBUG_SLUG',            'wp_rocket_debug' );
I think we should move away from using global constants like this. We can use the option name directly, with our architecture now it's more centralized.

2024-01-29 20:46 UTC, Tabrisrp commented on inc/admin/upgrader.php
> +	);
Couple of things here:
- We should do this in a separate method in a debug subscriber
- We need to check that it's only done once when upgrading, by using the plugin version check

2024-01-29 20:46 UTC, Tabrisrp commented on inc/Engine/Debug/ServiceProvider.php
> +				->addArgument( $this->getContainer()->get( 'options_api' ) );
this only works if all services have the same construct signature forever, are we sure about it?

2024-01-29 20:46 UTC, Tabrisrp commented on inc/Engine/Debug/Resolver.php
> +			'service' => 'rucss_subscriber',
```suggestion
			'service' => 'rucss_debug_subscriber',
```

2024-02-14 20:21 UTC, jeawhanlee commented on inc/Engine/Debug/ServiceProvider.php
> +				->addArgument( $this->getContainer()->get( 'options_api' ) );
From what I see, we'll mostly be updating the debug options based on triggered hooks. Do you see something else?

2024-02-15 15:39 UTC, CrochetFeve0251 commented on inc/Engine/Debug/Resolver.php
> +	}
@jeawhanlee why everything is static?

2024-02-15 15:39 UTC, CrochetFeve0251 commented on inc/Engine/Debug/RUCSS/Subscriber.php
> +		$this->options_api->set( 'debug', $this->options->get_options() );
@jeawhanlee by default options contains the wpr settings.

2024-02-16 20:16 UTC, Tabrisrp approved these changes

2024-02-20 08:08 UTC, merged