Closes #6373 #6374: Add logs to rucss
wp-media/wp-rocket pull request #6412
Opened 2024-01-26 08:08 UTC by Miraeld

## Description

The goal here is to add some logs in the DB for debugging purpose. 

Fixes #6373 #6374

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2024-01-26 11:17 UTC, Khadreal reviewed
Looks good to me

2024-02-14 14:11 UTC, mostafa-hisham commented
Hi @Miraeld :vulcan_salute: from plugin team :grin:
I think we are missing call back saving the time of `rocket_rucss_process_on_submit_jobs_end` action in the [plugin PR](https://github.com/wp-media/wp-rocket/pull/6412/files)

and I don't know what are the options names for `RUCSS-related Async action started and ended` [issue-6374](https://github.com/wp-media/wp-rocket/issues/6374) I don't see them in the PR

We need those options to use them in the [RUCSS debug tool](https://github.com/orgs/wp-media/projects/112/views/2?pane=issue&itemId=53138212)

2024-02-15 04:47 UTC, Miraeld commented
Hey @mostafa-hisham from service team :D

I've added the missing callback, and also added the check if debug is enabled as I forgot it. 

👍

2024-02-15 07:11 UTC, mostafa-hisham commented
@Miraeld which options I should use to know
RUCSS-related Async action started
RUCSS-related Async action ended
to know if Action Scheduler is running as expected?

2024-02-15 15:08 UTC, CrochetFeve0251 requested changes

2024-02-15 15:08 UTC, CrochetFeve0251 commented on inc/Engine/Debug/RUCSS/Subscriber.php
> +			$this->options_api->set( 'debug', $this->options->get_options() );
@Miraeld I am not sure what you wanted to save but here you are saving the whole wpr configurations inside the debug configuration

2024-02-15 15:08 UTC, CrochetFeve0251 commented on inc/Engine/Debug/RUCSS/Subscriber.php
> +			$this->options_api->set( 'debug', $this->options->get_options() );
This is due to the fact we are loading the wrong data into the options instance: https://github.com/wp-media/wp-rocket/blob/704f03428f286a9a84e32378626848444986534a/inc/classes/ServiceProvider/class-options.php#L36

2024-02-16 06:51 UTC, mostafa-hisham commented on inc/Engine/Debug/RUCSS/Subscriber.php
> +			$this->options->set( 'log_process_on_submit_end', $timestamp );
@Miraeld 
Is this option name `log_process_on_submit_end` correct?

2024-02-20 04:13 UTC, mostafa-hisham requested changes

2024-02-20 04:13 UTC, mostafa-hisham commented on inc/Engine/Debug/RUCSS/Subscriber.php
> +			$this->options->set( 'log_process_on_submit_end', $timestamp );
@Miraeld I think we can change it to `rucss_process_on_submit_jobs_end`

2024-02-20 07:22 UTC, Miraeld commented on inc/Engine/Debug/RUCSS/Subscriber.php
> +			$this->options->set( 'log_process_on_submit_end', $timestamp );
It's been modified

2024-02-21 13:36 UTC, merged