Sub-task: #6429 preload links with actions
wp-media/wp-rocket pull request #6465
Opened 2024-03-06 11:08 UTC by jeawhanlee

# Description
Sub task of #6429 that fetches links from homepage.

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
*Delete options that are not relevant.*

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-03-06 11:12 UTC, jeawhanlee commented
This will hold the base branch for the next 2 task mentioned here: https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-1969454194

2024-03-06 11:16 UTC, jeawhanlee commented
Tests will be added in this last task of this PR.

2024-03-06 11:56 UTC, Miraeld approved these changes

2024-03-06 15:14 UTC, Tabrisrp requested changes

2024-03-06 15:14 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
> +		}
This is already done in `wp_remote_retrieve_body()`.

One thing to check though would be the response code, to make sure we receive a 200 response, with `wp_remote_retrieve_response_code()`.

2024-03-06 20:29 UTC, Tabrisrp requested changes
I think we should already have tests for what is built in this PR. It will help validate the fetch links part and the possible cases.

2024-03-06 20:29 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
> +			}
We should also support relative URLs case

2024-03-07 12:33 UTC, MathieuLamiot commented
@jeawhanlee I am not sure to see how this PR handles triggering fetch_link when clearing the ATF/LCP data? (see [this discussion](https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-1969936207)).
Is it handled?

Thanks 🙏

2024-03-07 12:38 UTC, jeawhanlee commented
> @jeawhanlee I am not sure to see how this PR handles triggering fetch_link when clearing the ATF/LCP data? (see [this discussion](https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-1969936207)). Is it handled?
> 
> Thanks 🙏

@MathieuLamiot Thanks for this, I must have skipped this.

2024-03-07 20:37 UTC, Tabrisrp reviewed
Aren't we missing the fetch links on activation part?

2024-03-14 04:53 UTC, Miraeld requested changes
There are some references to the `AboveTheFold Manager` but it's been deleted as part of https://github.com/wp-media/wp-rocket/issues/6461, I was wondering if it would impacts here. 

Also there are some lint errors that could be fixed with `phpcs`.

2024-03-14 04:53 UTC, Miraeld commented on inc/Engine/Media/AboveTheFold/Activation/Activation.php
> +	public function __construct( Controller $controller, ManagerInterface $manager ) {
Above the fold manager doesn't exist anymore as part of https://github.com/wp-media/wp-rocket/issues/6461, does it impact here ?

2024-03-14 04:53 UTC, Miraeld commented on inc/Engine/Media/AboveTheFold/Activation/ServiceProvider.php
> +		'atf_manager',
`atf_manager` doesn't exist anymore as part of https://github.com/wp-media/wp-rocket/issues/6461

2024-03-14 11:53 UTC, Tabrisrp approved these changes

2024-03-20 21:15 UTC, merged

2024-04-22 11:42 UTC, hanna-meda reviewed
Test Run Results >
[testrail-report-595.pdf](https://github.com/wp-media/wp-rocket/files/15062257/testrail-report-595.pdf)
The failing tests, each have their own GH logged.