Feature/bail out#6428
wp-media/wp-rocket pull request #6504
Opened 2024-03-21 11:54 UTC by Khadreal

# Description

Fixes #6428

## Documentation

### User documentation

This won't allow user that their licence has expired past 15 days to use the pre-warmup feature

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] New feature (non-breaking change which adds functionality).

## New dependencies
N/A

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-03-21 13:07 UTC, Tabrisrp requested changes

2024-03-21 13:07 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
> + * @group ATF
```suggestion
 * @group AboveTheFold
```

2024-03-21 13:07 UTC, Tabrisrp commented on tests/Unit/inc/Engine/Media/AboveTheFold/WarmUp/Controller/fetchLinks.php
> +            } );
```suggestion
            $this->stubWpParseUrl();
```

2024-03-21 13:07 UTC, Tabrisrp commented on tests/Unit/inc/Engine/License/API/User/hasLicenseExpiredPast15Days.php
> +namespace WP_Rocket\tests\Unit\inc\Engine\License\API\User;
```suggestion
namespace WP_Rocket\Tests\Unit\Inc\Engine\License\API\User;
```

2024-03-21 13:07 UTC, Tabrisrp commented on tests/Unit/inc/Engine/License/API/User/hasLicenseExpiredPast15Days.php
> +class hasLicenseExpiredPast15Days extends TestCase {
```suggestion
class Test_hasLicenseExpiredPast15Days extends TestCase {
```

2024-03-21 20:28 UTC, Tabrisrp approved these changes

2024-03-22 20:35 UTC, merged

2024-04-19 08:59 UTC, Mai-Saad commented
related test case https://wpmediaqa.testrail.io/index.php?/cases/view/15319 is already on [test Run](https://wpmediaqa.testrail.io/index.php?/runs/view/834&group_by=cases:section_id&group_order=asc) used at this PR https://github.com/wp-media/wp-rocket/pull/6465 (so if it passed there, we can move this PR too to done)

2024-04-19 11:35 UTC, MathieuLamiot commented
Let's move it to Done then. If there is an issue during test execution, we'd open a dedicated GH issue anyway