Enhancement/6432 bail out from beacon conditions
wp-media/wp-rocket pull request #6555
Opened 2024-04-10 12:11 UTC by Miraeld

# Description

Fixes #6432 

This PR modifies the beacon script to add a check for existing image data related to the URL in the database. If such data exists or the status is failed, the script process should be stopped. Additionally, a screen-size check should be added to the script to bail out under certain conditions.

## Documentation

### User documentation

This change does not directly impact users as it is related to the test setup and the beacon script.

### Technical documentation

The `add_lcp_data` and `check_lcp_data` methods in the `Controller.php` file are used to add and check LCP data respectively. The `main` function in the `lcp-beacon.js` file has been modified to make an AJAX call to check if there are any records for the current URL and to check the screen size. If the screen size is not within the acceptable range, the function bails out.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
N/A

## Risks
N/A

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitly.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] I listed the introduced external dependencies explicitly on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

2024-04-11 20:05 UTC, remyperona commented
Is this ready for review?

2024-04-12 08:11 UTC, Miraeld commented
@Tabrisrp, yes it is ready. 
We keep it like this at the moment. The documentation related to these changes can be found [here](https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-66f9411b46b9414082ac985b5cb83fb1?pvs=4#ec7f67b35eab4ee4956876042c855671).

2024-04-12 17:07 UTC, Tabrisrp requested changes

2024-04-12 17:07 UTC, Tabrisrp commented on assets/js/lcp-beacon.js
> +			rocket_lcp_nonce: rocket_lcp_data.nonce
isn't it missing the is_mobile value?

2024-04-12 17:07 UTC, Tabrisrp commented on assets/js/lcp-beacon.js
> +		body: new URLSearchParams({
We use this here, and FormData on the other AJAX request, possibly we need to choose one and use the same for both?

2024-04-12 17:07 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/AJAX/Controller.php
> +		$is_mobile = isset( $_POST['is_mobile'] ) ? filter_var( wp_unslash( $_POST['is_mobile'] ), FILTER_VALIDATE_BOOL ) : false;
```suggestion
		$is_mobile = isset( $_POST['is_mobile'] ) ? filter_var( wp_unslash( $_POST['is_mobile'] ), FILTER_VALIDATE_BOOLEAN ) : false;
```

2024-04-16 21:23 UTC, Tabrisrp approved these changes

2024-04-16 21:23 UTC, Tabrisrp commented
You have some conflicts to fix in the JS

2024-04-17 12:35 UTC, Khadreal approved these changes

2024-04-19 13:24 UTC, MathieuLamiot approved these changes

2024-04-24 16:22 UTC, MathieuLamiot commented
@Miraeld There are conflicts to be resolved. Then it should be merged ASAP to avoid further conflicts with upcoming changes on the beacon.

2024-04-25 03:44 UTC, merged

2024-04-25 08:45 UTC, Miraeld commented
@Mai-Saad, there is no test plan available for this yet, 
However, I've tested this PR. 
The way I've tested => Open a page with different dimensions while checking the devconsole for results. 

Please find screenshots of the result as follow:
## Desktop
### Case 1
Opening a page in desktop mode while not meeting the size resolution requirements, we bail out. 
![beacon-not-ok-desktop-size](https://github.com/wp-media/wp-rocket/assets/14993267/ed0f39ee-381b-4909-a034-460f7873922d)

### Case 2
Opening a page in desktop while meeting the size resolution, we process and get results.
![beacon-ok-desktop-size](https://github.com/wp-media/wp-rocket/assets/14993267/580deb57-138d-41b5-8f9d-a7f4035fc502)

### Case 3
Opening a page in desktop while we already have saved data within the database.
![becaon-data-already-exists](https://github.com/wp-media/wp-rocket/assets/14993267/3f865e78-7c44-4ca8-970c-eaee68b56750)

## Mobile
### Case 1
Opening a page in mobile mode while not meeting the size resolution requirements, we bail out. 
![beacon-not-ok-mobile-size](https://github.com/wp-media/wp-rocket/assets/14993267/057c8688-9ebf-401a-a714-e8775611f942)

### Case 2
Opening a page in mobile while meeting the size resolution, we process and get results.
![beacon-ok-mobile-size](https://github.com/wp-media/wp-rocket/assets/14993267/88b35827-91ab-4d45-9713-ddf4b313858d)

### Case 3
Opening a page in mobile while we already have saved data within the database.
![beacon-data-already-exists-mobile](https://github.com/wp-media/wp-rocket/assets/14993267/1df77549-6dac-4d47-8cb6-d0bcc199a8f4)


Please review this results for now and if everything's okay, we can move it to QA Done. 
Thank you

2024-04-25 11:03 UTC, MathieuLamiot commented
@Miraeld Maybe we need to test the new filters and also that they are guarded against bad values? (null, [], string, etc.). If wrong value, then the default value should be applied.

2024-04-25 14:08 UTC, Miraeld commented
True that, Here is the following tests: 

## Changing values of the filter 
### Settings new threshold: 
``` php
// Change the width threshold for the LCP beacon.
add_filter( 'rocket_lcp_width_threshold', function( $width_threshold, $is_mobile, $url ) {
	return $is_mobile ? 500 : 2500;
}, 10, 3 );

// Change the height threshold for the LCP beacon.
add_filter( 'rocket_lcp_height_threshold', function( $height_threshold, $is_mobile, $url ) {
	return $is_mobile ? 900 : 1200;
}, 10, 3 );
```
![Screenshot 2024-04-25 at 15 52 08](https://github.com/wp-media/wp-rocket/assets/14993267/3dee3b18-d96a-437e-bcaf-77dab969d0d2)
![Screenshot 2024-04-25 at 15 52 39](https://github.com/wp-media/wp-rocket/assets/14993267/74f5fde2-3942-40d8-a566-826b317729ca)

Thresholds are working perfectly. 

## Passing `null` & `[]` to filters
``` php
// Change the width threshold for the LCP beacon.
add_filter( 'rocket_lcp_width_threshold', function( $width_threshold, $is_mobile, $url ) {
	return [];
}, 10, 3 );

// Change the height threshold for the LCP beacon.
add_filter( 'rocket_lcp_height_threshold', function( $height_threshold, $is_mobile, $url ) {
	return null;
}, 10, 3 );
```
Result: 
![Screenshot 2024-04-25 at 16 02 02](https://github.com/wp-media/wp-rocket/assets/14993267/6bad67bf-fc70-465e-8ca7-06d927029d2d)
As values from the filter were not valid, we set back the default value.


Also please see https://github.com/wp-media/wp-rocket/pull/6593 for new threshold values modification

2024-04-25 16:17 UTC, MathieuLamiot commented
Ok on my side 👍