Bug/saas results db#6521
wp-media/wp-rocket pull request #6557
Opened 2024-04-12 15:11 UTC by Khadreal

# Description
Add data-attribute and header to beacon script and ajax request.

Fixes #6521
## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-04-12 17:23 UTC, MathieuLamiot reviewed
LGTM.
Just a question, shouldn't the PR also change the minified version of the script?

2024-04-12 17:25 UTC, MathieuLamiot requested changes
The code change is OK ✅ 
Just a question, shouldn't the PR also change the minified version of the script?
Also, tests are failing.

2024-04-15 13:35 UTC, remyperona approved these changes

2024-04-15 14:24 UTC, MathieuLamiot approved these changes

2024-04-24 19:31 UTC, MathieuLamiot commented
Tests are failing. Bringing back to In Progress.

2024-04-25 09:11 UTC, merged