Closes #6530 #6531 #6532 #6534 #6535 #6552: Preload images markup
wp-media/wp-rocket pull request #6559
Opened 2024-04-16 05:33 UTC by Miraeld

# Description

Fixes #6530 #6531 #6532 #6534 #6535 #6552 

This PR addresses several issues related to image preloading, specifically for images detected as Largest Contentful Paint (LCP) and Above The Fold (ATF) images. The changes ensure that various types of images are correctly preloaded and excluded from lazy loading to improve page load performance. Additionally, it fixes an issue where background images identified as the LCP were incorrectly labeled as 'img' in the database, they are now correctly labeled dynamically.

## Documentation

### User documentation

This update improves the page load performance by correctly preloading various types of images and excluding them from lazy loading when they are detected as Largest Contentful Paint (LCP) and Above The Fold (ATF) images. This means faster loading times for your website visitors.

### Technical documentation

The code works by identifying images that are LCP and ATF, and then preloading these images to improve page load performance. It also correctly labels background images identified as LCP with the corrected type in the database. The changes are implemented across several files, including JavaScript for front-end changes and PHP for back-end changes.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
n/a

## Risks
n/a

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style

- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitly.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] I listed the introduced external dependencies explicitly on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

2024-04-16 08:43 UTC, MathieuLamiot commented
@Miraeld Independently of the review, can you provide some info about test & validation of the content of this PR? I am thinking mostly: what templates has this been tested against to validate the new markups? Is there new tests passing on Rocket-E2e, or tests/templates that should be covered by this that are not passing?
Thanks

2024-04-16 08:50 UTC, Miraeld commented
@MathieuLamiot ,
Integrations tests are here to make sure that if we get the right value within the database, the frontend will be correct. 

In terms of detection and saving the data itself (role of the `beacon-lcp.js`), I've only tested manually, as we can't run JS in integrstion tests, sadly. I don't think there are e2e tests even tho some templates are there.

How I've been testing it: 
Simply by using templates available in `rocket-test-data` repo. 

Some are not available yet, so I've built my own on the same structure as we would do for e2e. 
Then do the process manually to make sure everything is detected and saved properly.

2024-04-16 08:53 UTC, MathieuLamiot commented
> In terms of detection and saving the data itself (role of the beacon-lcp.js), I've only tested manually, as we can't run JS in integrstion tests, sadly. I don't think there are e2e tests even tho some templates are there.

There should be E2E checking what is saved in DB after a visit on the page, and running on many templates from the QA team. @jeawhanlee should be able to show you, that's what he implemented last cooldown sprint.

2024-04-16 08:53 UTC, jeawhanlee requested changes

2024-04-16 08:53 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/AJAX/Controller.php
> +		if ( 'img-srcset' === $image->type ) {
Any reason we don't use a switch statement here?

2024-04-16 08:53 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/Frontend/Controller.php
> +					$media = $source->media;
I think we should Isolate these logic in a new method to modularize things for future enhancement for example, when we intend to handle min-width or disordered source tag, this present method can quickly become long and complex.  We can have this logic in a new method that only handles max-width.

2024-04-16 10:46 UTC, Miraeld commented on inc/Engine/Media/AboveTheFold/AJAX/Controller.php
> +		if ( 'img-srcset' === $image->type ) {
There was a `if` before, so I continued with that logic, 
I will change it in the next commit if it makes it easier ;)

2024-04-16 10:48 UTC, Miraeld commented
@MathieuLamiot totally agreed, 
I was planning to look at e2e, as in the same time it's part of the testing we need to do for 3.16. 
It's just I did not want to hold this PR while doing the e2e as e2e is on another repo.

2024-04-17 10:28 UTC, jeawhanlee approved these changes

2024-04-17 14:26 UTC, MathieuLamiot commented
As discussed [here](https://github.com/wp-media/wp-rocket/issues/6537#issuecomment-2061387690), this PR is likely to miss the AC about ATF exclusion of Lazyload for elements that are not "img" (so video, picture, p, main, div)

2024-04-18 06:14 UTC, Miraeld commented
Well I can add them here. I may have a solution but need some optimization :)

2024-04-24 15:46 UTC, merged