Fix/update default fetched links to 10 and parse unappended url to is home
wp-media/wp-rocket pull request #6563
Opened 2024-04-16 17:05 UTC by jeawhanlee

# Description
Fetches 10 links from home plus home(11) and also fixes the is_home not detecting the homepage.

Fixes: Addresses @hanna-meda comment [here](https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-2056995658) and [here](https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-2058331751)

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation
https://github.com/wp-media/wp-rocket/blob/38775e5e095d57a01aa9a1255f290db9197c5d66/inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php#L17
We now save the original url before appending the query strings then reuse the version in `is_home` method
Also we now filter out the home url from the links if it exists and append in the end just before returning the urls, reason for this is to always return the home url for templates that might not contain the home url.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## New dependencies
None

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-04-16 21:34 UTC, Tabrisrp requested changes

2024-04-16 21:34 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
> +				return wp_http_validate_url( $link ) && $link_host['host'] === $site_host['host'] && ! Utils::is_home( $link );
triple conditions is hard to read, maybe we could split that?

2024-04-16 21:34 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
> +			'is_home'           => $is_home,
Is this change necessary?

2024-04-17 07:57 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
> +			'is_home'           => $is_home,
Yes I believe it is, in reference to @hanna-meda comment [here](https://github.com/wp-media/wp-rocket/issues/6429#issuecomment-2058331751)

2024-04-17 12:46 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
> +			'is_home'           => $is_home,
I'm failing to understand the difference it makes, it's the same code assigned to a variable?

2024-04-17 13:00 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
> +			'is_home'           => $is_home,
Yes but we are now preserving the original state of the `url` param which was not the case before as we alter the state [here](https://github.com/wp-media/wp-rocket/blob/38775e5e095d57a01aa9a1255f290db9197c5d66/inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php#L18) first then we use it [here](https://github.com/wp-media/wp-rocket/blob/38775e5e095d57a01aa9a1255f290db9197c5d66/inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php#L27) which in the `is_home` method [here](https://github.com/wp-media/wp-rocket/blob/132a9f0d69483020ba41f290a624d10168ac014a/inc/Engine/Common/Utils.php#L24) we will always return false even if it's the home page because it's now appended with a query string i.e `example.org?wpr_imagedimensions=1`

2024-04-17 13:46 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/APIClient.php
> +			'is_home'           => $is_home,
ah yes right, I see now, all good

2024-04-17 13:46 UTC, Tabrisrp approved these changes

2024-04-18 09:56 UTC, merged