Enhancement/rucss lcp enabled#6569
wp-media/wp-rocket pull request #6588
Opened 2024-04-24 13:13 UTC by Khadreal

# Description

Fixes #(issue number)

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
*Delete options that are not relevant.*

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-04-24 18:25 UTC, Tabrisrp requested changes

2024-04-24 18:25 UTC, Tabrisrp commented on inc/Engine/Common/JobManager/APIHandler/APIClient.php
> +		$url = apply_filters( 'rocket_saas_api_queued_url', $url );
Add filter docblock

2024-04-24 18:25 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
> +	public function add_wpr_imagedimensions_query_arg(): string {
this is missing the `$url` parameter

2024-04-24 18:25 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/Controller.php
> +			return '';
should return the default `$url` instead

2024-04-24 18:25 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/Subscriber.php
> +		return $this->controller->add_wpr_imagedimensions_query_arg();
missing the `$url` parameter

2024-04-25 20:35 UTC, Tabrisrp approved these changes

2024-04-26 11:38 UTC, merged

2024-04-26 11:39 UTC, MathieuLamiot commented
I manually validated the AC.
With RUCSS + LCPA/ATF, I can see both table filling too which means LCP/ATF is processed along side RUCSS.