Closes #6571: Reduce the processing on not-cached page when checking the LCP/ATF data
wp-media/wp-rocket pull request #6610
Opened 2024-05-03 11:02 UTC by Miraeld

# Description

Fixes #6571 

## Documentation

### User documentation

It won't try to check if LCP data are already existing for non-cached URLs.

### Technical documentation

We check if the page is a cached version, if it isn't we will bailout before sending an AJAX call to check if LCP datas are already existing for the URL.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
N/a
## Risks
N/a

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

2024-05-03 11:30 UTC, jeawhanlee requested changes

2024-05-03 11:30 UTC, jeawhanlee commented on assets/js/lcp-beacon.js
> +		if ( signature && signature.includes( 'Debug: cached' ) ) {
I think we should check for something more reliable maybe like the whole sentence as there are some cases where we do not generate timestamp in the footprint.

2024-05-03 11:30 UTC, jeawhanlee commented on assets/js/lcp-beacon.js
> +		let status = false;
```suggestion
		let signature = '', status = false;
```

2024-05-03 11:30 UTC, jeawhanlee commented on assets/js/lcp-beacon.js
> +		// }
Why do we have this commented out, we should remove the lines if they are not useful.

2024-05-03 11:30 UTC, jeawhanlee commented on assets/js/lcp-beacon.js
> +			}
```suggestion
		if ( this._isPageCached() && this._isGeneratedBefore() ) {
			this._logMessage('Bailing out because data is already available');
			return false;
```

2024-05-03 12:00 UTC, wordpressfan requested changes
We need to bear in mind that in some hosts our cache is disabled by default also the signature can be removed in cases like when having the whitelabel constant or so.

I need to understand more how do u detect the cached page in depth.

2024-05-03 12:00 UTC, wordpressfan commented on assets/js/lcp-beacon.js
>  		return lcp_data_response.success;
```suggestion
		const lcp_data_response = await fetch(this.config.ajax_url, {
			method: "POST",
			credentials: 'same-origin',
			body: data_check
		})
		.then(data => data.json());

		return lcp_data_response.success;
```

2024-05-03 12:39 UTC, Miraeld commented on assets/js/lcp-beacon.js
> +		if ( signature && signature.includes( 'Debug: cached' ) ) {
I used the same condition as on WPR Inspector (https://github.com/wp-media/wpr-inspector/blob/bd71796388de3c9cc0cff45488de23ce920df6d1/wpr-inspector/inspector.js#L25)

2024-05-03 12:45 UTC, Miraeld commented
@wordpressfan for these cases, I guess we won't have the choice to do the DB request we want to avoid which is the one checking if LCP data does exists for the page while it isn't even cached yet. 

We can't check through the DB as it would add another DB Request, which is the opposite of what we want, and there are no other way to determine if a page is cached or not. Except if there is something else I'm missing. 

The way the current detection work is through the signature, where if the page is cached, we get the following text: `Debug: cached@1714733510` 
Where `1714733510` is a timestamp.

2024-05-10 20:36 UTC, Miraeld commented
@jeawhanlee & @wordpressfan  Are you okay with the latest changes ?

2024-05-11 20:05 UTC, jeawhanlee commented
For me I have issues with how reliable it can be detecting a cached page with our footprint signature, what if we tried checking the directory if the cache file exists and pass the result (boolean) to the script.

2024-05-11 20:19 UTC, jeawhanlee commented
> For me I have issues with how reliable it can be detecting a cached page with our footprint signature, what if we tried checking the directory if the cache file exists and pass the result (boolean) to the script.

The above won't work, when the page is cached, it would bail out and render the cache. 

In my opinion, If we would use the signature, we should use parts that must always be present instead of just `Debug: cached`
Here is an example of a page without the timestamp:
<img width="815" alt="Screenshot 2024-05-11 at 21 18 08" src="https://github.com/wp-media/wp-rocket/assets/38788055/7e19f5d2-983c-49bb-a64b-930cfb9d338c">

2024-05-13 14:58 UTC, MathieuLamiot commented
@Miraeld Looking at wp-rocket's code, there are versions of the code that don't have the timestamp in the signature I think. Typically in case of 3rd party hosting, white label and if time is empty.
In that case, it would make sense indeed to look for:
- '<!-- Optimized for great performance'
OR
- '<!-- This website is like a Rocket, isn\'t it? Performance optimized by  '

Then, of course, it is not perfect because sometimes, comments are removed from cached files. But better done than perfect.

WDYT of matching on those two rather than Debug + timestamp?
Can we just change the matching to those 2 strings, move forward with this PR and eventually open a follow-up GH issue if there are edge cases you still foresee?

2024-05-14 06:55 UTC, Miraeld commented
So based on our conversation yesterday, I guess we have to merge this PR and prepare another issue to enhance it, 
@wordpressfan as you had the idea for the enhancement, can you create the new issue, and when it's done can you merge this PR ?

2024-05-14 15:31 UTC, MathieuLamiot commented
@wordpressfan @jeawhanlee Since @Miraeld will be off end of this week, can you make sure to close this? Thanks 🙏

2024-05-15 07:34 UTC, wordpressfan approved these changes
Approved with very minor enhancement

2024-05-15 07:34 UTC, wordpressfan commented on assets/js/lcp-beacon.js
> +		return false;
```suggestion
		const signature = document.documentElement.nextSibling.data ? document.documentElement.nextSibling.data : '';

		return signature && signature.includes( 'Debug: cached' );
```

2024-05-21 15:38 UTC, MathieuLamiot commented
Expected behavior and observation from QA team discussed here: https://wp-media.slack.com/archives/CUT7FLHF1/p1716202320587489

2024-05-23 08:40 UTC, Mai-Saad commented
The issue mentioned here https://github.com/wp-media/wp-rocket/pull/6610#issuecomment-2122910431 is fixed, but on PR, nothing is added to the database with warmup (neither after a fresh install, nor after clear critical images)

Note: related test plan https://wpmediaqa.testrail.io/index.php?/runs/view/856&group_by=cases:section_id&group_order=asc

2024-05-23 10:44 UTC, wordpressfan commented
All jobs from that site in SaaS are returning timeout error, I'm checking with Mostafa now what is going on there.

2024-05-23 10:57 UTC, wordpressfan commented
This was because in SaaS we load the not cached page which doesn't include the signature and this means that the following line returns js error in the console:

https://github.com/wp-media/wp-rocket/blob/a6b762284692de00b1ef67a1ae24d52a67551c42/assets/js/lcp-beacon.js#L51

because `document.documentElement.nextSibling` is null in this case, pushing a fix now.

2024-05-23 12:20 UTC, Mai-Saad approved these changes
Working as expected

2024-05-23 12:39 UTC, merged