Closes #6632: Image Optimization Tab Update
wp-media/wp-rocket pull request #6675
Opened 2024-05-28 11:46 UTC by jeawhanlee

# Description
Updates the UI of the Image Optimization tab.

Fixes #6632 

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
`wp-admin/includes/plugin-install.php`

## Risks
None

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-05-28 17:41 UTC, jeawhanlee commented
### State without Imagify installed.
<img width="1204" alt="Screenshot 2024-05-28 at 18 40 10" src="https://github.com/wp-media/wp-rocket/assets/38788055/5c2a875f-f42c-461d-8015-589909887377">

2024-05-28 17:42 UTC, jeawhanlee commented
### State with Imagify Installed but not activated.
<img width="1202" alt="Screenshot 2024-05-28 at 18 42 16" src="https://github.com/wp-media/wp-rocket/assets/38788055/bbd6599e-28f7-4813-a10c-94ffabc16489">

2024-05-28 17:45 UTC, jeawhanlee commented
### State with Imagify Installed & Activated.
<img width="1203" alt="Screenshot 2024-05-28 at 18 44 19" src="https://github.com/wp-media/wp-rocket/assets/38788055/0fced8db-93cd-48ad-889a-c704c4675d52">

2024-05-28 17:57 UTC, Miraeld approved these changes

2024-05-29 05:21 UTC, marija-nikolic commented
> ### State with Imagify Installed & Activated.
> <img alt="Screenshot 2024-05-28 at 18 44 19" width="1203" src="https://private-user-images.githubusercontent.com/38788055/334517812-0fced8db-93cd-48ad-889a-c704c4675d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjAwOTQsIm5iZiI6MTcxNjk1OTc5NCwicGF0aCI6Ii8zODc4ODA1NS8zMzQ1MTc4MTItMGZjZWQ4ZGItOTNjZC00OGFkLTg4OWEtYzcwNGM0Njc1ZDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA1MTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTY1NWQ1MzM4MTNiOTJmODUxOTczNGYxZmQ0ZDJmYjk5MjczZTAyYjFjZmJmMjc5OTU3Y2ZlZDJhMWVkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JCHTXMCriWi3NlFUMubTB4JxVeasxe7kJhDuvQq5q3g">

We don't have an Image Optimization tab at all when Imagify is Installed and Activated. That is currently the case.

2024-05-29 13:16 UTC, Tabrisrp requested changes

2024-05-29 13:16 UTC, Tabrisrp commented on inc/Engine/Admin/Settings/Render.php
> +			set_transient( 'imagify_plugin_data', $plugin_data, WEEK_IN_SECONDS );
```suggestion
			set_transient( 'rocket_imagify_plugin_data', $plugin_data, WEEK_IN_SECONDS );
```

2024-05-29 13:16 UTC, Tabrisrp commented on views/settings/page-sections/imagify.php
> + * @since 3.2ƒ
is this a typo?

2024-05-29 13:27 UTC, jeawhanlee commented on views/settings/page-sections/imagify.php
> + * @since 3.2ƒ
Definitely a typo.

2024-05-29 13:33 UTC, Tabrisrp approved these changes

2024-05-29 13:38 UTC, Tabrisrp commented
Display is good 👍🏼

2024-05-29 13:38 UTC, merged