Closes #5549 Clear cache table on domain change
wp-media/wp-rocket pull request #6696
Opened 2024-06-04 18:51 UTC by Tabrisrp

# Description

Fixes #5549

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
*Delete options that are not relevant.*

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-06-07 16:22 UTC, jeawhanlee requested changes

2024-06-07 16:22 UTC, jeawhanlee commented on inc/Engine/Preload/Admin/Settings.php
> +	public function __construct( Options_Data $options, PreloadUrl $preload_url, $load_initial_sitemap, $cache_table ) {
```suggestion
	public function __construct( Options_Data $options, PreloadUrl $preload_url, LoadInitialSitemap $load_initial_sitemap, CacheTable $cache_table ) {
```

2024-06-07 16:22 UTC, jeawhanlee commented on inc/Engine/Preload/Database/Tables/Cache.php
> +	public function truncate_cache_table(): bool {
I don't see this method used anywhere in this PR, is it useful?

2024-06-10 13:56 UTC, remyperona commented on inc/Engine/Preload/Database/Tables/Cache.php
> +	public function truncate_cache_table(): bool {
Good catch, I updated the function call

2024-06-10 15:53 UTC, jeawhanlee approved these changes

2024-06-18 10:30 UTC, jeawhanlee requested changes

2024-06-18 10:30 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/WarmUp/Subscriber.php
> +			'rocket_domain_options_changed' => 'warm_up_home',
Something skipped during code review, This event here: `rocket_domain_options_changed` doesn't seem relevant.
We already clear atf [here](https://github.com/wp-media/wp-rocket/blob/e67e7697e368bc5e8bc5d2aeb0c59ffad322c505/inc/Engine/Media/AboveTheFold/Admin/Subscriber.php#L34) during domain and we do this action [here](https://github.com/wp-media/wp-rocket/blob/e67e7697e368bc5e8bc5d2aeb0c59ffad322c505/inc/Engine/Media/AboveTheFold/Admin/Controller.php#L74) when clearing atf which fires the warm up [here](https://github.com/wp-media/wp-rocket/blob/e67e7697e368bc5e8bc5d2aeb0c59ffad322c505/inc/Engine/Media/AboveTheFold/WarmUp/Subscriber.php#L33)

2024-06-18 11:10 UTC, jeawhanlee commented
Aside the comment above, On develop, I can see that we clear the cache table during domain change but it's not truncated, with this PR we truncate the cache table.

I also proactively ran smoke tests on e2e and it passes. @MathieuLamiot do we wait for a test plan from @wp-media/qa-team  on this one.

2024-06-18 11:59 UTC, MathieuLamiot commented
@jeawhanlee @Tabrisrp Unless you see something risky in the changes, let's not wait for a specific test plan. Instead we should:
- Perform the "How to reproduce" steps from the original GH issue and ensure the expected behavior is now happening, that there are no errors/warnings and that the preload feature seems to work appropriately on basic use-cases.
- QA team would then be able to perform overall preload Non-regression tests on develop once they are back.

2024-06-18 11:59 UTC, MathieuLamiot commented
Following @jeawhanlee comments on the review, I am moving this back to In Progress so that you can discuss them.

2024-06-18 13:24 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/WarmUp/Subscriber.php
> +			'rocket_domain_options_changed' => 'warm_up_home',
Good catch

2024-06-18 13:39 UTC, Miraeld approved these changes

2024-06-19 09:54 UTC, jeawhanlee approved these changes

2024-06-20 08:57 UTC, jeawhanlee commented
Working as expected according to AC [here](https://github.com/wp-media/wp-rocket/issues/5549#issuecomment-2145981360)

2024-06-20 09:04 UTC, merged