Enhancement/6621 increase phpstan level
wp-media/wp-rocket pull request #6754
Opened 2024-07-02 03:10 UTC by Miraeld

# Description

Fixes #6621 

## Documentation

### User documentation

It won't impact users. 

### Technical documentation

This PR simply changes some things on how the code is structured to comply with php-stan. 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies

## Risks

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [x] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [x] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [x] I explicitely mentioned performance risks in the PR.
- [x] I explicitely mentioned security risks in the PR.

2024-07-03 14:01 UTC, Tabrisrp requested changes

2024-07-03 14:01 UTC, remyperona commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +				// @phpstan-ignore-next-line .
`Variable $exclude_fonts_preload_pattern in empty() always exists and is not falsy.  `

We could handle that without ignoring no? Maybe using `array_filter()` before the `implode()`

2024-07-03 14:01 UTC, remyperona commented on inc/ThirdParty/Hostings/LiteSpeed.php
> +			@header( "X-LiteSpeed-Purge: {$header}" ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
this should not be modified, it's a bug caused by a fixture overridding the default header function for tests. The fixture should be updated instead to accept the second optional parameter and match the original (override_header_functions.php)

2024-07-03 14:01 UTC, remyperona commented on inc/ThirdParty/Plugins/SEO/SEOPress.php
> +		if ( ! function_exists( 'seopress_get_toggle_option' ) || 1 !== (int) seopress_get_toggle_option() ) {
same thing here, the report is caused by the fixture not correctly matching the original

2024-07-04 01:22 UTC, Miraeld commented on inc/ThirdParty/Hostings/LiteSpeed.php
> +			@header( "X-LiteSpeed-Purge: {$header}" ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
Modified

2024-07-04 01:25 UTC, Miraeld commented on inc/ThirdParty/Plugins/SEO/SEOPress.php
> +		if ( ! function_exists( 'seopress_get_toggle_option' ) || 1 !== (int) seopress_get_toggle_option() ) {
Modified.

2024-07-04 01:30 UTC, Miraeld commented on inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php
> +				// @phpstan-ignore-next-line .
Done

2024-07-04 12:15 UTC, Tabrisrp commented on phpstan-bootstrap.php
We could move this in the `tests/phpstan` directory instead

2024-07-08 13:40 UTC, Miraeld commented on phpstan-bootstrap.php
It's been moved :)

2024-07-08 13:47 UTC, Tabrisrp approved these changes

2024-07-08 19:32 UTC, MathieuLamiot commented
@Miraeld can this be merged and moved to Done?

2024-07-08 20:13 UTC, merged