Closes #6764: Refactor lcp beacon script
wp-media/wp-rocket pull request #6789
Opened 2024-07-17 02:14 UTC by Miraeld

Change the structure of the beacon script to include a new class `RocketBeacon` which will contains more generic functions that could be shared with other features.

# Description

Fixes #6764

## Documentation

### User documentation

This shouldn't impact users.

### Technical documentation

The beacon script has been renamed to `wpr-beacon.js` & has been refactored. 
This refactor includes the addition of a new class named `RocketBeacon` which contains generic functions used later on by `RocketLcpBeacon` class. 
It will allow us to add more feature easily to avoid duplication. 
In order to test this PR, https://github.com/wp-media/wp-rocket-e2e/issues/124 needs to be merged into e2e. 

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I listed the introduced external dependencies explicitely on the PR.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [x] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [x] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [x] I explicitely mentioned performance risks in the PR.
- [x] I explicitely mentioned security risks in the PR.

2024-07-18 12:17 UTC, Tabrisrp approved these changes

2024-07-18 12:17 UTC, jeawhanlee commented on assets/js/wpr-beacon.js
>  		data_check.append('action', 'rocket_check_lcp');
Should `rocket_check_lcp` not be changing to something more generic since its single ajax request?

2024-07-18 12:17 UTC, jeawhanlee commented on assets/js/wpr-beacon.js
> +		data.append('action', 'rocket_lcp');
This also, `rocket_lcp` should it not be changed to something more generic?

2024-07-18 14:58 UTC, Tabrisrp commented
Should this PR be done against `develop`? Shouldn't it be against the refactor branch?

2024-07-19 00:58 UTC, Miraeld commented
@jeawhanlee I've updated action names and everything related to that. 

@Tabrisrp I've changed the based branch.

2024-07-19 12:58 UTC, Tabrisrp requested changes

2024-07-19 12:58 UTC, Tabrisrp commented on inc/Engine/Media/AboveTheFold/Frontend/Controller.php
> -		$delay = apply_filters( 'rocket_lcp_delay', $default_delay );
if we change the filter name, we should add an apply_filters_deprecated call too for backward compatibility

2024-07-23 15:15 UTC, Tabrisrp requested changes

2024-07-23 15:15 UTC, Tabrisrp commented on README.md
> +| `gulp build:js:lcp`             |      Builds lcp beacon script, the minified version (lcp-beacon.min.js, source file, and map file)      |
I think this line should be removed?

2024-07-24 11:20 UTC, wordpressfan commented on README.md
> +| `gulp build:js:lcp`             |      Builds lcp beacon script, the minified version (lcp-beacon.min.js, source file, and map file)      |
Good catch, Done

2024-07-24 12:01 UTC, Tabrisrp approved these changes

2024-07-25 10:46 UTC, merged