Closes #6779: AboveTheFold Database Refactor
wp-media/wp-rocket pull request #6794
Opened 2024-07-18 02:08 UTC by Miraeld

# Description
Adds a `Queries` and `Table` interface to `PerformanceHints` + Respective `AboveTheFold` implementing them. 
Fixes #6779 

## Documentation

### User documentation

It shouldn't impact users

### Technical documentation

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [x] I validated the repo-specific guidelines from CONTRIBUTING.md.

2024-07-18 10:29 UTC, jeawhanlee requested changes

2024-07-18 10:29 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Database/Queries.php
> +interface Queries {
```suggestion
interface QueriesInterface {
```

2024-07-18 10:29 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Database/Table.php
> +interface Table {
```suggestion
interface TableInterface {
```

2024-07-18 10:29 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Database/Queries.php
We can change this filename to `QueriesInterface` for clarity as when we just use Queries, it feels more like a class and a real queries class rather than an abstract factory or interface.

2024-07-18 10:29 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Database/Table.php
We can change this as well to `TableInterface`

2024-07-18 10:29 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/FactoryInterface.php
> +use WP_Rocket\Engine\Common\PerformanceHints\Database\Table;
```suggestion
use WP_Rocket\Engine\Common\PerformanceHints\Database\QueriesInterface;
use WP_Rocket\Engine\Common\PerformanceHints\Database\TableInterface;
```

2024-07-18 10:29 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/FactoryInterface.php
> +	public function table(): Table;
```suggestion
	public function table(): TableInterface;
```

2024-07-18 10:29 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/FactoryInterface.php
> +	public function queries(): Queries;
```suggestion
	public function queries(): QueriesInterface;
```

2024-07-19 12:55 UTC, Tabrisrp approved these changes
There is a conflict to fix

2024-07-29 17:09 UTC, Tabrisrp approved these changes

2024-07-30 10:41 UTC, merged