Closes #6781: 3.17 - Refactor Cron
wp-media/wp-rocket pull request #6797
Opened 2024-07-18 08:28 UTC by Khadreal

# Description

Fixes #6781

## Documentation

### User documentation
Nothing changed on user side.

*Explain how this code impacts users.*

### Technical documentation
Move cron controller and subscriber from ATF to PerformanceHints.

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation
- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-07-24 09:38 UTC, Miraeld approved these changes

2024-07-24 09:58 UTC, jeawhanlee commented
Moving this back to in progress.
Cron tests were not refactored..

2024-07-24 09:59 UTC, jeawhanlee requested changes

2024-07-24 09:59 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
Why did  we change this from `Controller` to `CronProcessor`

2024-07-24 12:24 UTC, Khadreal commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
No reason per se 😄

2024-07-24 12:24 UTC, Khadreal commented
> Moving this back to in progress. Cron tests were not refactored..

Will add test for it, don't think we have one before now

2024-07-24 19:31 UTC, jeawhanlee requested changes

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
It would be good to rename that back to `Controller` for consistency sake.

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
> + * The Class is responsible for scheduling, executing, and unscheduling the 'above the fold' cleanup.
```suggestion
 * The Class is responsible for scheduling, executing, and unschedulin performance hints optimization cleanup.
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
>   * It has private properties for ATFTable, ATFQuery, and Context instances.
```suggestion

```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
> +class CronProcessor {
```suggestion
class Controller {
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
>  			wp_schedule_event( time(), 'daily', 'rocket_atf_cleanup' );
```suggestion
		if ( ! wp_next_scheduled( 'rocket_performance_hints_cleanup' ) ) {
			wp_schedule_event( time(), 'daily', 'rocket_performance_hints_cleanup' );
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/CronProcessor.php
>  			wp_unschedule_event( $timestamp, 'rocket_atf_cleanup' );
```suggestion
		$timestamp = wp_next_scheduled( 'rocket_performance_hints_cleanup' );
		if ( $timestamp ) {
			wp_unschedule_event( $timestamp, 'rocket_performance_hints_cleanup' );
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +		$this->cron_processor = $cron_processor;
```suggestion
	 * Cron Controller Instance.
	 *
	 * @var Controller
	 */
	private $controller;


	/**
	 * Instantiate the cron controller class
	 *
	 * @param Controller $controller Cron controller instance.
	 */
	public function __construct( Crontroller $controller ) {
		$this->controller = $controller;
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +			'rocket_atf_cleanup'  => 'cleanup',
```suggestion
			'rocket_performance_hints_cleanup'  => 'cleanup',
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +	 * Executes the 'above the fold' cleanup.
```suggestion
	 * Executes the performance hints optimization cleanup.
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +		$this->cron_processor->cleanup();
```suggestion
		$this->controller->cleanup();
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +	 * Schedules the 'above the fold' cleanup to run at a later time.
```suggestion
	 * Schedules performance hints optimization cleanup to run at a later time.
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +	public function schedule_atf_cleanup() {
```suggestion
	public function schedule_cleanup() {
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +		$this->cron_processor->schedule_cleanup();
```suggestion
		$this->controller->schedule_cleanup();
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +	 * Unscheduled the 'above the fold' cleanup, preventing it from running at the previously scheduled time.
```suggestion
	 * Unscheduled the performance hints optimization cleanup, preventing it from running at the previously scheduled time.
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Cron/Subscriber.php
> +		$this->cron_processor->unscheduled_cleanup();
```suggestion
		$this->controller->unscheduled_cleanup();
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +use WP_Rocket\Engine\Common\PerformanceHints\Cron\Subscriber as CronSubscriber;
```suggestion
use WP_Rocket\Engine\Common\PerformanceHints\Cron\{Controller as CronController, Subscriber as CronSubscriber};
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +		'performance_hints_cron_subscriber',
You need to add this to the common subscribers [here](https://github.com/wp-media/wp-rocket/blob/b4da82fd9e697ea13bc7683002cf5d0252b155ef/inc/Plugin.php#L310)

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +		'cron_processor',
```suggestion
		'cron_controller',
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +		$this->getContainer()->add( 'cron_processor', CronProcessor::class )
```suggestion
		$this->getContainer()->add( 'cron_controller', CronController::class )
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +					$this->getContainer()->get( 'cron_processor' ),
```suggestion
					$this->getContainer()->get( 'cron_controller' ),
```

2024-07-24 19:31 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/ServiceProvider.php
> -		'atf_cron_subscriber',
You also need to remove this from the common subscriber [here](https://github.com/wp-media/wp-rocket/blob/b4da82fd9e697ea13bc7683002cf5d0252b155ef/inc/Plugin.php#L395)

2024-07-25 09:25 UTC, jeawhanlee commented
> > Moving this back to in progress. Cron tests were not refactored..
> 
> Will add test for it, don't think we have one before now

I can see one here: https://github.com/wp-media/wp-rocket/tree/subtask/6781-3.17-refactor-cron/tests/Integration/inc/Engine/Media/AboveTheFold/Cron/Subscriber

2024-07-25 09:26 UTC, jeawhanlee commented
I have temporarily changed the base branch to develop so git actions and automated tests can be triggered when you push.

2024-07-25 14:28 UTC, jeawhanlee requested changes

2024-07-25 14:28 UTC, jeawhanlee commented on tests/Integration/inc/Engine/Common/PerformanceHints/Cron/Subscriber/cleanup.php
>  	protected $path_to_test_data = '/inc/Engine/Media/AboveTheFold/Cron/Subscriber/atfCleanup.php';
```suggestion
	protected $path_to_test_data = '/inc/Engine/Common/PerformanceHints/Cron/Subscriber/atfCleanup.php';
```
You need to update the fixture location as well.

2024-07-25 14:28 UTC, jeawhanlee commented on tests/Integration/inc/Engine/Common/PerformanceHints/Cron/Controller/scheduleCleanup.php
> +class scheduleCleanup extends TestCase {
```suggestion
class Test_scheduleCleanup extends TestCase {
```

2024-07-25 16:33 UTC, jeawhanlee commented
Merge [3.17-atf-refactor](https://github.com/wp-media/wp-rocket/tree/3.17-atf-refactor) branch and fix the conflicts

2024-07-26 12:45 UTC, jeawhanlee approved these changes

2024-07-26 13:07 UTC, merged