Closes: #6773 Refactor admin
wp-media/wp-rocket pull request #6802
Opened 2024-07-19 11:26 UTC by Khadreal

# Description

Fixes #6773 

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-07-19 13:00 UTC, remyperona requested changes

2024-07-19 13:00 UTC, remyperona commented on inc/Engine/Common/PerformanceHints/Admin/ServiceProvider.php
that change doesn't make sense, why are we moving this service provider?

2024-07-19 16:24 UTC, Khadreal commented on inc/Engine/Common/PerformanceHints/Admin/ServiceProvider.php
I misunderstood this part `Move the Admin folder from AboveTheFold to PerformanceHints within Common.` of the  grooming, @Miraeld explained this, I'll modify and push the changes

2024-07-25 14:03 UTC, jeawhanlee requested changes

2024-07-25 14:03 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Admin/AdminContext.php
We should change this back to `Controller`
Also for the sake of keeping this review short and precise, the contents of the previous Admin\Controller class should not change much, we only need to take out the context interface and the dependency as we would have those in the factory, the method names also needs to change, all occurrence of `atf` should become `performance_hints` and hooks should be updated with backward compatibility using rocket_apply_filter_and_deprecated for filters or rocket_do_action_and_deprecated for actions.

2024-07-25 14:03 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Admin/ControllerInterface.php
I don't think we need this interface.

2024-07-25 14:03 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/FactoryInterface.php
I also don't think we need the changes here.

2024-07-25 14:03 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/Admin/Controller.php
> +	public function clean_url(): void {
We shouldn't retain this method in the AboveTheFold Namespace.

2024-07-25 14:03 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/Admin/Subscriber.php
> +			'rocket_saas_clean_url' => 'clean_url',
This would also not need to be here anymore.

2024-07-25 14:03 UTC, jeawhanlee commented on inc/Engine/Media/AboveTheFold/Factory.php
We don't need an admin controller here.

2024-07-30 11:34 UTC, Miraeld approved these changes

2024-07-30 13:46 UTC, merged