3.17 Pilot - ATF Refactor
wp-media/wp-rocket pull request #6831
Opened 2024-07-30 17:18 UTC by jeawhanlee

# Description

Closes https://github.com/wp-media/wp-rocket/issues/6777 https://github.com/wp-media/wp-rocket/issues/6775 https://github.com/wp-media/wp-rocket/issues/6781 https://github.com/wp-media/wp-rocket/issues/6778 https://github.com/wp-media/wp-rocket/issues/6776 https://github.com/wp-media/wp-rocket/issues/6764 https://github.com/wp-media/wp-rocket/issues/6772 https://github.com/wp-media/wp-rocket/issues/6774 https://github.com/wp-media/wp-rocket/issues/6779 https://github.com/wp-media/wp-rocket/issues/6773

## Documentation

### Technical documentation

Refactor OCI to share Performance hints modules also updated hooks to be generic and deprecated old ones
```
rocket_lcp_width_threshold -> rocket_performance_hints_optimization_width_threshold
rocket_lcp_height_threshold -> rocket_performance_hints_optimization_height_threshold
rocket_lcp_delay -> rocket_performance_hints_optimization_delay
rocket_after_clear_atf -> rocket_after_clear_performance_hints_data
rocket_atf_warmup_links_number ->  rocket_performance_hints_warmup_links_number,
```

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
None

## Risks
None

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-07-30 17:37 UTC, jeawhanlee commented
Blocking till [this](https://github.com/wp-media/wp-rocket/pull/6830) is ready.

2024-07-31 08:42 UTC, Miraeld commented on package.json
> +	"wp-rocket-scripts": "github:wp-media/rocket-scripts#enhancement/beacon-script-refactoring-phase-2",
Will it still be this branch or it will be a dedicated version ?

2024-07-31 08:44 UTC, Miraeld approved these changes

2024-07-31 11:06 UTC, Mai-Saad commented
Can't delete 3.17 zip, it will result in a fatal error. @wp-media/engineering-plugin-team can you please check
[debug.log](https://github.com/user-attachments/files/16440349/debug.log)

2024-08-01 21:12 UTC, MathieuLamiot commented
Can someone check this before moving forward?
https://wp-media.slack.com/archives/CUT7FLHF1/p1722546721389749?thread_ts=1722433782.954279&cid=CUT7FLHF1

2024-08-02 11:15 UTC, MathieuLamiot requested changes
Blocked by: https://github.com/wp-media/wp-rocket/issues/6838
See https://wp-media.slack.com/archives/CUT7FLHF1/p1722596982917919?thread_ts=1722433782.954279&cid=CUT7FLHF1

2024-08-03 11:57 UTC, MathieuLamiot approved these changes

2024-08-03 21:10 UTC, Miraeld approved these changes

2024-08-05 07:16 UTC, MathieuLamiot commented
Not blocked anymore.

2024-08-07 12:56 UTC, Mai-Saad approved these changes
Failed tests are either accepted for now or have GH issue.
- Accepted issues as per @piotrbak 
1- Fetch the home page (added to logs but not DB) when fresh install or trigger clear critical images. Thanks @hanna-meda 
2- Fetched Urls from home  (added to log)  are double when update from version < 3.16  (DB has no duplication)

[testrail-report-626.pdf](https://github.com/user-attachments/files/16526821/testrail-report-626.pdf)

2024-08-09 06:32 UTC, merged