Closes #6845 Rework UI for data clearing and notices for OCI and LRC
wp-media/wp-rocket pull request #6858
Opened 2024-08-08 14:04 UTC by Khadreal

# Description

Fixes #6845 

## Documentation
Rework UI for data clearing and notices. Add menu class and traits.

### Technical documentation
Add traits for classes with similar code for admin menu

## Type of change
- [x] Sub-task of epic

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.

2024-08-13 16:01 UTC, Tabrisrp requested changes
Could we see if we can improve the test coverage a bit to pass at least 50%?

2024-08-13 16:01 UTC, remyperona commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +		'atf_context',
This service provider is not the one providing the atf_context instance, it doesn't need to be added here.

2024-08-13 16:01 UTC, remyperona commented on inc/Engine/Common/PerformanceHints/Admin/Clean.php
> +
we're missing capability check in addition to the nonce check. It was possibly an oversight from the previous implementation, but it's necessary for security hardening.

We can use `rocket_manage_options` capability check.

2024-08-13 16:01 UTC, remyperona commented on inc/Engine/Common/PerformanceHints/Admin/Clean.php
> +
Same here

2024-08-13 16:03 UTC, Tabrisrp commented
Also you can update with the base branch, which will give you access to the LRC context class, to use in addition to the ATF context where needed.

2024-08-14 13:11 UTC, MathieuLamiot commented
@Khadreal Have you taken into account @Tabrisrp's comment about test coverage? I can still see the coverage being below 50%. Maybe there is a blocker?

2024-08-14 13:13 UTC, MathieuLamiot requested changes
Could you use the apply-filters-typed library instead of apply_filters?
I can see 3 added apply_filters.

2024-08-14 13:32 UTC, Khadreal commented
> @Khadreal Have you taken into account @Tabrisrp's comment about test coverage? I can still see the coverage being below 50%. Maybe there is a blocker?

Yes, will add more test

2024-08-15 13:18 UTC, jeawhanlee requested changes

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Admin/AdminBar.php
> +	private $lrc_context;
We don't need these contexts properties, instead just the factories property.

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Admin/AdminBar.php
> +	public function __construct( ContextInterface $atf_context, ContextInterface $lrc_context, $template_path ) {
We need only to pass the pass the factories here and use their context products.
```suggestion
	public function __construct( array $factories, $template_path ) {
```

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Admin/AdminBar.php
> +		$this->lrc_context = $lrc_context;
```suggestion
		$this->factories = $factories;
```

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Admin/Controller.php
> +				__( '%1$s: WP Rocket: Critical images and Lazy Render data was cleared!', 'rocket' ),
We are already passing the formatted string in the first parameter in `sprintf`
```suggestion
				__( '%1$s: Critical images and Lazy Render data was cleared!', 'rocket' ),
```

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/Admin/Notices.php
Pass the factories as dependency instead.

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +			->addArgument( $this->getContainer()->get( 'lrc_context' ) );
Pass the factories as dependency.

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/ServiceProvider.php
> +			->addArgument( $this->getContainer()->get( 'lrc_context' ) )
Pass the factories as dependency

2024-08-15 13:18 UTC, jeawhanlee commented on inc/Engine/Saas/Admin/Clean.php
>  		$clean = apply_filters( 'rocket_saas_clean_all', [] );
```suggestion
		$clean = wpm_apply_filters_typed( 'array', 'rocket_saas_clean_all', [] )
```

2024-08-16 13:52 UTC, jeawhanlee approved these changes

2024-08-16 13:56 UTC, MathieuLamiot approved these changes

2024-08-19 10:14 UTC, hanna-meda commented
Thank you all for the work on this one. Have a couple of minor changes on UI:
1. Under WPR Dashboard > Quick Actions > Performance Hints: Spacing on the `Clear` button should be consistent with the ones above
![Screenshot 2024-08-19 at 12 52 39](https://github.com/user-attachments/assets/6282ca1a-520c-4d0a-96a4-18d55c1a0184)
2. On View page of any published URL, the `Performance Hints` text should start in upper case
<img width="762" alt="Screenshot 2024-08-19 at 12 41 24" src="https://github.com/user-attachments/assets/18070328-c82d-4fe5-9a5f-3722822f5786">

2024-08-19 12:12 UTC, Khadreal commented
@hanna-meda the modified UI
![Screenshot 2024-08-19 at 13 11 32](https://github.com/user-attachments/assets/3effb172-0f20-4526-8257-bfbb5e0af6b9)
![Screenshot 2024-08-19 at 13 11 42](https://github.com/user-attachments/assets/1a7ca210-0ef9-471b-a626-7f69a1972929)

2024-08-19 13:02 UTC, hanna-meda commented
@Khadreal, "Clear" button still looks the same to me. Checked on Chrome & FF (Mac) with cleared site cache & cookies:
![Screenshot 2024-08-19 at 16 02 06](https://github.com/user-attachments/assets/d0993393-e241-4a27-bac8-2d114a96bc8c)

2024-08-19 13:28 UTC, hanna-meda commented
@Khadreal, using filters
`add_filter( 'rocket_above_the_fold_optimization', function( $flag ){ return false; } );`
`add_filter( 'rocket_lazy_render_content_optimization', function( $flag ){ return false; } );`
 to disable LRC & ATF does not seem to work. We will still see `Clear Performance Hints Data` in Admin bar and `Clear` button under the Quick Actions from Dashboard > Performance Hints section. Is this dependent on #6828 or do we have an issue on PR? If you can have a look. Thank you.

2024-08-19 15:58 UTC, Khadreal commented
@hanna-meda buttons look good from my end using diff browser, could you confirm you're using latest branch.
FF
<img width="377" alt="Screenshot 2024-08-19 at 16 56 13" src="https://github.com/user-attachments/assets/04a14090-d4d7-447c-bc8a-9f89a4ac3fc4">
Safari
<img width="377" alt="Screenshot 2024-08-19 at 16 56 13" src="https://github.com/user-attachments/assets/f355f232-9a9b-4fec-a5e4-d634f2a74b60">
Chrome
![Screenshot 2024-08-19 at 16 57 43](https://github.com/user-attachments/assets/12ed3f83-2f53-4366-b9a3-beb75d8ca959)


Filter

2024-08-20 07:26 UTC, jeawhanlee approved these changes

2024-08-20 07:54 UTC, jeawhanlee commented
Taking this back to in progress in respect to @benorfaz comment [here](https://github.com/wp-media/wp-rocket/issues/6845#issuecomment-2298143530)

2024-08-20 11:02 UTC, jeawhanlee commented on inc/Engine/Admin/Settings/Page.php
> +					__( '%1$sWP Rocket:%2$s the plugin has been updated to the 3.17 version. New feature: %3$sLazy Render Content%4$s. Check out our documentation to learn more about it.', 'rocket' ),
Did product influence the change of this text?

2024-08-20 11:07 UTC, Khadreal commented on inc/Engine/Admin/Settings/Page.php
> +					__( '%1$sWP Rocket:%2$s the plugin has been updated to the 3.17 version. New feature: %3$sLazy Render Content%4$s. Check out our documentation to learn more about it.', 'rocket' ),
Yes

2024-08-20 11:14 UTC, hanna-meda commented on inc/Engine/Admin/Settings/Page.php
> +					__( '%1$sWP Rocket:%2$s the plugin has been updated to the 3.17 version. New feature: %3$sLazy Render Content%4$s. Check out our documentation to learn more about it.', 'rocket' ),
@jeawhanlee It was I who pointed out given text from [Notion](https://www.notion.so/wpmedia/Lazy-render-content-bf707b5f731a426cb5d1294beb770540?pvs=4#b5d069b2e8d147119a15c5f7408b22b8)

2024-08-20 11:24 UTC, jeawhanlee commented on inc/Engine/Admin/Settings/Page.php
> +					__( '%1$sWP Rocket:%2$s the plugin has been updated to the 3.17 version. New feature: %3$sLazy Render Content%4$s. Check out our documentation to learn more about it.', 'rocket' ),
Thanks @hanna-meda I asked @wp-media/product a question [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1724152527252139) though

2024-08-20 12:02 UTC, jeawhanlee commented on inc/Engine/Admin/Settings/Page.php
> +					__( '%1$sWP Rocket:%2$s the plugin has been updated to the 3.17 version. New feature: %3$sLazy Render Content%4$s. Check out our documentation to learn more about it.', 'rocket' ),
Ok by product.

2024-08-20 12:02 UTC, jeawhanlee approved these changes

2024-08-21 13:27 UTC, hanna-meda approved these changes
Related Test Report below:
[testrail-report-632.pdf](https://github.com/user-attachments/files/16692187/testrail-report-632.pdf)
with 3 tests failing:

- 1 regression, new ticket #6883
- 1 existing ticket #6704
- 1 failing also on trunk, ~still investigating~ new ticket #6885 

Blocked TCs will be retested when we'll be able to check the new LRC table from DB.

2024-08-22 18:56 UTC, merged

2024-08-22 18:57 UTC, MathieuLamiot commented
Merged as per QA request at the daily.