#6828 Add Database for LRC
wp-media/wp-rocket pull request #6872
Opened 2024-08-16 12:58 UTC by Khadreal

# Description
Decouple #6828, created a standalone branch for database.

Fixes #6887

## Documentation

### Technical documentation
Add database table, queries and rows class.

## Type of change
- [x] Sub-task

## New dependencies
n/a

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [x] I handled errors when needed.
- [x] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [x] I prepared ways to observe the implemented system (logs, data, etc.).

2024-08-16 13:34 UTC, Tabrisrp requested changes

2024-08-16 13:34 UTC, Tabrisrp commented on inc/Engine/Optimization/LazyRenderContent/Database/Queries/LazyRenderContent.php
> +	protected $table_alias = 'wpr_lcr';
```suggestion
	protected $table_alias = 'wpr_lrc';
```

2024-08-16 13:34 UTC, Tabrisrp commented on inc/Engine/Optimization/LazyRenderContent/Database/Table/LazyRenderContent.php
> +		20240812 => '',
We don't need any value in the array if there was no upgrade yet

2024-08-16 14:48 UTC, jeawhanlee commented
We will need to update the Factory with the queries and table products

2024-08-19 18:28 UTC, jeawhanlee approved these changes

2024-08-19 18:28 UTC, merged