Closes #6828 Add Ajax for LRC
wp-media/wp-rocket pull request #6873
Opened 2024-08-16 17:12 UTC by Khadreal

# Description
Decouple #6828, second part of the part. This PR #6872 should be merged first.

Fixes #6828 

## Documentation

### User documentation

Add the controller class to insert the **LCR** data into the database.

### Technical documentation
The implementation is done with a controller using an interface and the methods
- `add_data`
- `check_data`

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Sub-task.

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.

2024-08-20 07:19 UTC, jeawhanlee requested changes

2024-08-20 07:19 UTC, jeawhanlee commented on inc/Engine/Common/PerformanceHints/AJAX/AbstractAJAXController.php
Why did we abstract this?

2024-08-20 07:19 UTC, jeawhanlee commented on inc/Engine/Optimization/LazyRenderContent/AJAX/Controller.php
We changed the return for the add_data and check_data [here](https://github.com/wp-media/wp-rocket/pull/6861). I already merged the PR

2024-08-20 07:19 UTC, jeawhanlee commented
Some conflicts to resolve

2024-08-20 10:25 UTC, Khadreal commented on inc/Engine/Common/PerformanceHints/AJAX/AbstractAJAXController.php
forgot to use this for above the fold class, the same method is used there too, better to abstract it and use than duplicate it

2024-08-20 10:25 UTC, Khadreal commented on inc/Engine/Optimization/LazyRenderContent/AJAX/Controller.php
Got it, will update the branch

2024-08-20 13:02 UTC, Tabrisrp requested changes

2024-08-20 13:02 UTC, remyperona commented on inc/Engine/Optimization/LazyRenderContent/ServiceProvider.php
> +		$this->getContainer()->add( 'atf_ajax_controller', AJAXController::class )
```suggestion
		$this->getContainer()->add( 'lrc_ajax_controller', AJAXController::class )
```

2024-08-20 13:02 UTC, remyperona commented on inc/Engine/Optimization/LazyRenderContent/ServiceProvider.php
> +		'lrc_controller',
```suggestion
		'lrc_ajax_controller',
```

2024-08-20 13:02 UTC, remyperona commented on inc/Engine/Optimization/LazyRenderContent/Database/Table/LazyRenderContent.php
> +
```suggestion
```

2024-08-21 11:00 UTC, jeawhanlee commented on inc/Engine/Optimization/LazyRenderContent/AJAX/Controller.php
> +		$max_lrc_hashes_number = (int) apply_filters( 'rocket_lrc_hashes_number', 20, $url, $hashes );
I think we should introduce our new filter function here

2024-08-21 13:05 UTC, jeawhanlee approved these changes

2024-08-21 13:54 UTC, merged