Fixes #6883 Clear performance hints data of current URL
wp-media/wp-rocket pull request #6886
Opened 2024-08-21 14:41 UTC by Khadreal

# Description
This should be merge after this is merge https://github.com/wp-media/wp-rocket/pull/6858
Fixes #6883

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation
- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.

2024-08-21 17:53 UTC, MathieuLamiot commented
@Khadreal PHPCS is failing.
Since this issue was not groomed, a little description of the root cause could be beneficial. For instance, I read quickly the issue, I don't understand why the issue is specifically about homepage and we add a filter that seems applied for every pages.

2024-08-21 17:54 UTC, MathieuLamiot requested changes
PHPCS failing

2024-08-22 10:43 UTC, Khadreal commented
> @Khadreal PHPCS is failing. Since this issue was not groomed, a little description of the root cause could be beneficial. For instance, I read quickly the issue, I don't understand why the issue is specifically about homepage and we add a filter that seems applied for every pages.

Yes, the issue is for the homepage but the `Clear Performance Hints data of this URL` is not working for other pages too. The filter is added to run every time url is cleared not specific to only homepage. It's similar to `Clear Used CSS for this url`

2024-08-22 21:44 UTC, Tabrisrp approved these changes

2024-08-23 09:25 UTC, hanna-meda approved these changes
Confirmed as fixed on PR.

2024-08-23 09:31 UTC, merged