Closes #6877 Create a new tab in WP Rocket
wp-media/wp-rocket pull request #7047
Opened 2024-10-21 15:27 UTC by Khadreal

# Description

Fixes #6877
Add a new tab to WP Rocket settings page

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario
There should be a new tab on the settings page

## Technical description

### Documentation
Added a new tab on settings page to view plugin.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

2024-10-21 16:48 UTC, Khadreal commented
We have different state for the plugins and in this screenshot, we have install, activate and activated plugins.

![Screenshot 2024-10-21 at 17 46 48](https://github.com/user-attachments/assets/71d08257-1384-46cf-8cfc-fa687fb6fec9)

2024-10-22 08:32 UTC, jeawhanlee requested changes

2024-10-22 08:32 UTC, jeawhanlee commented on assets/js/lazyload-css.min.js
Why was this file modified in this PR?

2024-10-22 08:32 UTC, jeawhanlee commented on assets/js/wpr-beacon.js
Why was this file modified in this PR?

2024-10-22 08:32 UTC, jeawhanlee commented on assets/js/wpr-beacon.min.js
Why was this file modified in this PR?

2024-10-22 08:32 UTC, jeawhanlee commented on assets/js/wpr-beacon.min.js.map
Why was this file modified in this PR?

2024-10-22 08:32 UTC, jeawhanlee commented on inc/Engine/Admin/Settings/Render.php
> +		}
We don't need to reorder, we already do that from the package, but we also order based on activated status following the AC [here](https://docs.google.com/document/d/1lNfOB2dUg4FtDeW8OInwKP5GIExBNGgHXenqdJ8hFa8/edit#heading=h.5s7nn046slkw)

2024-10-22 10:05 UTC, Khadreal commented on inc/Engine/Admin/Settings/Render.php
> +		}
I reordered it based on the design

2024-10-22 10:21 UTC, Khadreal commented on assets/js/lazyload-css.min.js
ran gulp for js and commits all. will remove them

2024-10-22 13:16 UTC, jeawhanlee approved these changes

2024-10-22 16:52 UTC, remyperona approved these changes

2024-10-23 01:28 UTC, Miraeld approved these changes

2024-10-23 12:40 UTC, remyperona commented on views/settings/page-sections/plugins.php
> +								style="width: <?php echo esc_attr( $wpm_plugin['logo']['width'] ); ?>" />
add `loading="lazy"` attribute to the images

2024-10-28 16:37 UTC, hanna-meda approved these changes
Everything looks and works as it should now. Thank you, @Khadreal.
Test Run Results below:
[testrail-report-653.pdf](https://github.com/user-attachments/files/17546066/testrail-report-653.pdf)

2024-10-29 07:43 UTC, merged