Fixes #7049: Performance issue with table existence query
wp-media/wp-rocket pull request #7050
Opened 2024-10-22 11:19 UTC by jeawhanlee

# Description
This PR fixes the issue with user servers being impacted due to unoptimized query.

Fixes #7049 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

Not able to reproduce on local at the moment.

## Technical description

### Documentation

The query that checks if table exists is now optimized to specifically target the current DB instead of recurrently checking tables in all the Databases on the server.

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I did not introduce unnecessary complexity.

2024-10-22 13:43 UTC, Miraeld commented
There is this one to change as well https://github.com/wp-media/wp-rocket/blob/d99bce0f0270963b82d6112276fc29dd97363d4b/inc/Engine/Common/Database/Queries/AbstractQuery.php#L509-L535

2024-10-22 13:44 UTC, Miraeld requested changes
There is this one to change as well https://github.com/wp-media/wp-rocket/blob/d99bce0f0270963b82d6112276fc29dd97363d4b/inc/Engine/Common/Database/Queries/AbstractQuery.php#L509-L535

2024-10-22 15:10 UTC, remyperona approved these changes
For later: we should see how to avoid having duplicated code for this

2024-10-23 01:24 UTC, Miraeld approved these changes

2024-10-24 11:30 UTC, Mai-Saad commented
Test plan:
- Reproduce the issue and confirm that PR fixed that
- NRT https://wpmediaqa.testrail.io/index.php?/runs/view/917&group_by=cases:section_id&group_order=asc

2024-10-28 09:16 UTC, Miraeld commented
Hello, 
NRT is green :) 
[testrail-report-652.pdf](https://github.com/user-attachments/files/17540150/testrail-report-652.pdf)

2024-10-29 07:44 UTC, Miraeld commented
Hello hello, 

I've been trying to reproduce the issue in a local environment. 
To do this, I made a Docker environment with 2 main containers: 1 Wordpress, and 1 DB server. 

On this DB server, I've created 10 000 databases where each one of them has their own user and these aren't SUPER user and of course, there is a single SUPER User that has access to everything. 

So to make it short.

10 000 databases, they all have the same named tables. So in my example I'll use `table_1`.

There is 1 SUPER User, otherwise, each database have a different user which isn't SUPER.


From the SUPER User:
The query: `SELECT table_name FROM information_schema.tables;` given by @Ahmed returns all tables in every database, which means if I do
`SELECT table_name FROM information_schema.tables WHERE table_name = 'table_1';` I'll get 10k rows results.



Now, from a normal user from 1 db,
If I run `SELECT table_name FROM information_schema.tables` I only get the table of its own database.

and `SELECT table_name FROM information_schema.tables WHERE table_name = 'table_1' LIMIT 1;` (similar to what we had in WP Rocket) runs within 0.017s

While the new query introduced by [#7049](https://github.com/wp-media/wp-rocket/issues/7049)
is `SELECT table_name FROM information_schema.tables WHERE table_schema = 'wordpress' AND table_name = 'table_1' LIMIT 1`  runs within 0.002s.

So we can see an improvement, as we are reducing the execution time of the query by almost 10.

2024-10-29 07:45 UTC, merged