Add method to update lists from JSON files and clear cache
wp-media/wp-rocket pull request #7054
Opened 2024-10-23 03:38 UTC by Miraeld

* **DynamicLists.php**
  - Add `update_lists_from_files` method to clear transient cache and update lists from JSON files
  - Call `remove_lists_cache` and `get_lists` methods from each provider's data manager in `update_lists_from_files`

* **AbstractDataManager.php**
  - Add `remove_lists_cache` method to delete transient cache

* **Subscriber.php**
  - Modify `wp_rocket_upgrade` callback to call `update_lists_from_files` method
  - Add `update_lists_from_files` method to call `$this->dynamic_lists->update_lists_from_files()`

# Description

Fixes #6920 
This update modifies the dynamic lists handling, improving the performance and reliability of the feature as the customer won't have to wait a week before getting the new exclusions updated.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

Update WP Rocket

## Technical description

### Documentation

We simply delete the transient cache before fetching the dynamic list from the file within the ZIP archive. 

### New dependencies

### Risks

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

2024-10-23 10:35 UTC, jeawhanlee commented on inc/Engine/Optimization/DynamicLists/DynamicLists.php
> +		}
Just a question, why do we need this check when we are only getting list that is already updated in the json file and not from our servers?

2024-10-23 13:34 UTC, Miraeld commented on inc/Engine/Optimization/DynamicLists/DynamicLists.php
> +		}
Honestly ? I don't have any reason, I just thought that would be a +. 
We can remove it

2024-10-23 13:40 UTC, Miraeld commented on inc/Engine/Optimization/DynamicLists/DynamicLists.php
> +		}
It's been removed.

2024-10-23 14:30 UTC, jeawhanlee commented on inc/Engine/Optimization/DynamicLists/DynamicLists.php
> +		];
Also do we need to return anything for this method as it's hooked to an action and not a filter?

2024-10-24 03:10 UTC, Miraeld commented on inc/Engine/Optimization/DynamicLists/DynamicLists.php
> +		];
Removed it.

2024-10-24 06:11 UTC, jeawhanlee approved these changes

2024-10-30 08:51 UTC, Mai-Saad commented
Related test plan https://wpmediaqa.testrail.io/index.php?/runs/view/921&group_by=cases:section_id&group_order=asc

2024-11-06 07:36 UTC, wordpressfan requested changes

2024-11-06 07:36 UTC, wordpressfan commented on inc/Engine/Optimization/DynamicLists/AbstractDataManager.php
> +		delete_transient( $this->get_cache_transient_name() );
```suggestion
		delete_transient( $this->get_cache_transient_name() );
		$lists_filepath = $this->get_json_filepath();

		if ( ! $this->filesystem->exists( $lists_filepath ) ) {
			return;
		}

		$this->filesystem->delete( $lists_filepath );
```

Seems like we need to remove the json file from the config also, to go and get the data from the json in the plugin file.
I tested that and it works.

2024-11-06 11:34 UTC, wordpressfan commented on inc/Engine/Optimization/DynamicLists/AbstractDataManager.php
> +		delete_transient( $this->get_cache_transient_name() );
I pushed the code to let @hanna-meda validate from her side not to delay the process, feel free to adjust the code if needed.

2024-11-06 16:18 UTC, hanna-meda approved these changes
@Miraeld, @wordpressfan, thank you.
All looks good on test env with this PR.
Related Test Plan Report here:

2024-11-06 16:20 UTC, merged