Fixes #7042
wp-media/wp-rocket pull request #7059
Opened 2024-10-25 09:56 UTC by Khadreal

# Description

Fixes #7042
Fixed error for some users when updating from one version to another.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario
Check #7042 

## Technical description
Revert the phpstan update on the method.

### Documentation

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

2024-10-25 12:14 UTC, Miraeld requested changes

2024-10-25 12:14 UTC, Miraeld commented on inc/Engine/Plugin/UpdaterSubscriber.php
> +		if ( ! is_string( $url ) ) {
You should add a php-stan ignore on this line. 

``` php
// @phpstan-ignore-line GH #7042 - $url variable may be change by other plugins to something else than string.

2024-10-25 12:17 UTC, Miraeld approved these changes

2024-10-29 11:55 UTC, Mai-Saad commented
For test: reproduce the issue and confirm it's fixed is enough. Please check this for reproducing it https://wp-media.slack.com/archives/CUT7FLHF1/p1730103718060409?thread_ts=1730101320.378249&cid=CUT7FLHF1

2024-11-01 16:18 UTC, remyperona approved these changes

2024-11-04 08:39 UTC, hanna-meda approved these changes
Thank you, @Khadreal, for this PR.
Reproduced error outside the PR by using snippet from [thread](https://wp-media.slack.com/archives/CUT7FLHF1/p1730103718060409?thread_ts=1730101320.378249&cid=CUT7FLHF1). On PR this error no longer happens (just some deprecation notices because of snippet but confirmed with devs that those are expected in this situation, and a very edgy one).
Confirming this as fixed on test env.

2024-11-05 15:56 UTC, merged