Closes #7065: 3.18 - Filter changing output
wp-media/wp-rocket pull request #7107
Opened 2024-11-14 05:37 UTC by Miraeld

# Description

Fixes #7065 
It allows the user to use the new added filter `rocket_internal_fonts_styling` in order to change the way we are including the local hosted fonts. 

If `rocket_host_fonts_locally_inline_css ` returns true => We get the css within a `<style></style>` tag
if `rocket_host_fonts_locally_inline_css ` returns false => We get the css within a `<link rel="stylesheet" [...]>` tag

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).
- [x] Sub-task of #7063 

## Detailed scenario
Just set the filter mentioned in the description above to `true` and see the change on the front-end.

## Technical description

### Documentation

Refer to the description, pretty simple. 

### New dependencies

### Risks

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

2024-11-14 13:15 UTC, remyperona requested changes

2024-11-14 13:15 UTC, remyperona commented on inc/Engine/Media/Fonts/Frontend/Controller.php
> +		if ( $internal_styling ) {
```suggestion
		$inline_fonts_css = wpm_apply_filters_typed( 'boolean', 'rocket_host_fonts_locally_inline_css', false );
		if ( $inline_fonts_css ) {
```

Need the docblock too

2024-11-14 13:15 UTC, remyperona commented on inc/Engine/Media/Fonts/Frontend/Controller.php
> +			}
```suggestion
			$inline_css = $this->get_font_inline_css( $gf_parameters, $raw_path );
			if ( $inline_css ) {
				return $inline_css;
			}
```

2024-11-14 13:15 UTC, remyperona commented on inc/Engine/Media/Fonts/Frontend/Controller.php
> +	 * Sets the font internal style.
```suggestion
	 * Gets the font inline css.
```

2024-11-14 13:15 UTC, remyperona commented on inc/Engine/Media/Fonts/Frontend/Controller.php
> +	private function set_font_internal_style( string $gf_parameters, string $css_path ) {
```suggestion
	private function get_font_inline_css( string $gf_parameters, string $css_path ) {
```

2024-11-15 17:02 UTC, remyperona commented on inc/Engine/Media/Fonts/ServiceProvider.php
> +					wpm_apply_filters_typed( 'string', 'rocket_host_font_cache_root', 'fonts/' . get_current_blog_id() ),
Is this path needed to be filterable from the AC?

2024-11-18 10:39 UTC, Khadreal approved these changes

2024-11-19 03:38 UTC, merged