Closes #7123: Rules about get_subscribed_events
wp-media/wp-rocket pull request #7124
Opened 2024-11-21 07:13 UTC by Miraeld

# Description

Fixes #7123 
*Explain how this code impacts users.*

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Release

## Detailed scenario

*Explain how to reproduce the issue (for bugs) or how to trigger the new code. You can refer to the GitHub issue or grooming if it is still applicable.*

## Technical description

### Documentation

*Explain how this code works. Diagrams & drawings are welcome.*

### New dependencies

*List any new dependencies that are required for this change.*

### Risks

*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Mandatory Checklist

## Code validation

- [ ] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style
- [ ] I wrote a self-explanatory code about what it does.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unnecessary complexity.
- [ ] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

2024-11-21 13:16 UTC, CrochetFeve0251 requested changes

2024-11-21 13:16 UTC, CrochetFeve0251 commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +			if ('get_subscribed_events' === $functionName) {
@Miraeld two things:
- It would be better to bail out here to keep the logic simple.
- We also need to check that we extend from the interface `Subscriber_Interface` to prevent side effects

2024-11-21 13:16 UTC, CrochetFeve0251 commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +				if ($node->expr instanceof Node\Expr\Array_) {
We need to bail out here too

2024-11-21 13:16 UTC, CrochetFeve0251 commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +						if ($item instanceof Node\Expr\ArrayItem) {
Same here with a `continue`

2024-11-21 13:16 UTC, CrochetFeve0251 commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +			$errors = $this->checkIfMethodExistsInClass($methodValue->value, $scope, $methodValue);
We can bail out here

2024-11-21 13:16 UTC, CrochetFeve0251 commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +				if ($subItem instanceof Node\Expr\ArrayItem) {
Same here, we can bail out

2024-11-21 13:16 UTC, CrochetFeve0251 commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +					if ($subItem->value instanceof Node\Scalar\String_) {
and same here with `continue`

2024-11-25 01:55 UTC, Miraeld commented
I've treated your feedback @CrochetFeve0251 , 
Also, modified the way it was working a bit to comply with your tests. 

Also, you'll notice I've added some `// @php-stan-ignore-[next]-line` 
That's because when phpstan run within this class, it kinda gets messed up with some type, even tho it's explicit, and due to this it thinks some part of the code are unreachable while in real they are. 

I add a screenshot of your test passing as it isn't part of the CI in here. 

![Screenshot 2024-11-25 at 02 44 29](https://github.com/user-attachments/assets/4226ccb1-69d7-4f39-a241-1b244298840b)

2024-11-27 18:17 UTC, CrochetFeve0251 requested changes

2024-11-27 18:17 UTC, CrochetFeve0251 commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +				->line( $node->getLine() ) // Add the line number.
@Miraeld can you add an identifier?

2024-11-28 09:56 UTC, Miraeld commented on tests/phpstan/Rules/EnsureCallbackMethodsExistsInSubscribedEvents.php
> +				->line( $node->getLine() ) // Add the line number.
Done `callbackMethodNotFound` has been added

2024-11-28 16:37 UTC, remyperona approved these changes

2024-11-28 17:58 UTC, merged