Closes #7126: PHPStan ~ Discourage wp option function
wp-media/wp-rocket pull request #7155
Opened 2024-11-29 07:24 UTC by Miraeld

# Description

Fixes #7126
Nothing impacts uers.

## Type of change

- [x] Chore

## Detailed scenario

None
## Technical description

### Documentation
This pull request includes changes to update and expand the PHPStan rules for discouraging the use of certain WordPress functions. The key changes involve renaming a rule class, adding new discouraged functions, and updating the corresponding tests.

Updates to PHPStan rules:

* [`phpstan.neon.dist`](diffhunk://#diff-6f19df6a6307a48db0940e6897591fb08776d2db8a6134737aa708defdb5c92dL58-R58): Renamed the rule `DiscourageUpdateOptionUsage` to `DiscourageWPOptionUsage` to reflect the broader scope of discouraged functions.
* [`tests/phpstan/Rules/DiscourageWPOptionUsage.php`](diffhunk://#diff-d09912cfa3d250a8976289dec6e77b195ed4cb6a4f903f13794b7a0cf0fad698R1-R42): Created a new rule class `DiscourageWPOptionUsage` that discourages the use of `update_option`, `get_option`, and `delete_option` functions, replacing the previous `DiscourageUpdateOptionUsage` rule.
* [`tests/phpstan/Rules/DiscourageUpdateOptionUsage.php`](diffhunk://#diff-b15b3b79ba11af6dd67882c358b52c74be775812f94adec8cfd401217b65ffe5L1-L34): Removed the old rule class `DiscourageUpdateOptionUsage`.

Updates to tests:

* [`tests/phpstan/tests/Rules/DiscourageWPOptionUsageTest.php`](diffhunk://#diff-c398d1b0a6eda930525b56eeeba922079ae4141bfa0e0dbb14ca18c16033dbb2R1-R46): Added new test cases for the `DiscourageWPOptionUsage` rule to verify that errors are correctly reported for `delete_option`, `get_option`, and `update_option` functions.
* [`tests/phpstan/tests/Rules/DiscourageUpdateOptionUsageTest.php`](diffhunk://#diff-dfb9ec0dcf61e0a3b84c072309bf62454a6225142b35698783b303dbb2fc893eL1-L28): Removed the old test class `DiscourageUpdateOptionUsageTest`.
* Added new test data files for `DiscourageWPOptionUsageTest`:
  * [`tests/phpstan/tests/data/DiscourageWPOptionUsageTest/use-delete-option.php`](diffhunk://#diff-09fad2c2f6980cbc8a9b367d417a8bcac6612957d719e936ee26cc801b2f04daR1-R21): Test data for `delete_option` function.
  * [`tests/phpstan/tests/data/DiscourageWPOptionUsageTest/use-get-option.php`](diffhunk://#diff-83607591d3aa639dee7b24669577d52c61b159a2b13e7131e98906eb3be67925R1-R21): Test data for `get_option` function.
  * [`tests/phpstan/tests/data/DiscourageWPOptionUsageTest/use-update-option.php`](diffhunk://#diff-766b9a54109c1cb4a773445483d2324db58ab6f59edb8d18558df1dea1f45794R1-R22): Test data for `update_option` function.
* Removed old test data file `tests/phpstan/tests/data/DiscourageUpdateOptionUsageTest/not-valid.php`.
### New dependencies

None

### Risks

None

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

2024-11-29 14:21 UTC, wordpressfan commented
@Miraeld May I ask why do u add all of those ignores? the baseline idea doesn't work here? or maybe I miss something, can u plz explain?

2024-11-29 14:26 UTC, remyperona approved these changes

2024-11-29 15:45 UTC, Miraeld commented
> @Miraeld May I ask why do u add all of those ignores? the baseline idea doesn't work here? or maybe I miss something, can u plz explain?

I've used the baseline system, check the last commit. 

I haven't added any ignore, I've refactored the previous "update_option()" rule to include more functions related to options and that we can and should manage with our own Option object.

2024-12-01 07:16 UTC, CrochetFeve0251 commented
@Miraeld I didn't see any test outside a class. This is a test we need as we don't want to raise the alert in that scenario.

2025-01-08 12:32 UTC, wordpressfan approved these changes
One minor change request, just not to duplicate the message.
I'm going to push this change now

2025-01-08 12:32 UTC, wordpressfan commented on tests/phpstan/Rules/DiscourageWPOptionUsage.php
> +		}
```suggestion
		$discouragedFunctions = [
			'update_option' => true,
			'get_option' => true,
			'delete_option' => true,
		];

		if (isset($discouragedFunctions[$functionName])) {
			return [
				RuleErrorBuilder::message( RuleErrorBuilder::message( sprintf( 'Usage of %1$s() is discouraged. Use the Option object instead.', $functionName ) ) )
					->identifier('custom.rules.discourageOptionUsage')
					->build(),
			];
		}
```

2025-01-10 13:52 UTC, remyperona requested changes

2025-01-10 13:52 UTC, remyperona commented on tests/phpstan/Rules/DiscourageWPOptionUsage.php
There is inconsistency in code styling/formatting in this file

2025-01-10 15:09 UTC, wordpressfan commented on tests/phpstan/Rules/DiscourageWPOptionUsage.php
Good catch, Fixed.
Do u think we need to include this folder into the coverage of phpcs to catch those things?

2025-01-20 03:47 UTC, Miraeld commented
All cases are covered in https://github.com/wp-media/wp-rocket/blob/20b724bd36fd026ba17cdc443e4605f63ce31ccf/tests/phpstan/tests/Rules/DiscourageWPOptionUsageTest.php and 
![Screenshot 2025-01-20 at 04 45 42](https://github.com/user-attachments/assets/d00e4f15-f05a-4580-a11b-83d967b44089)
every tests are passing.

2025-01-27 17:01 UTC, merged