Close #6863 Add termly compatibility
wp-media/wp-rocket pull request #7198
Opened 2024-12-19 13:18 UTC by Khadreal

# Description

Fixes #6863
*Explain how this code impacts users.*

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario
Check #6863

## Technical description

### Documentation

*Explain how this code works. Diagrams & drawings are welcome.*

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

*If some mandatory items are not relevant, explain why in this section.*

2024-12-19 14:33 UTC, jeawhanlee requested changes
It's good we have a unit test for this, but I think an integration test for this scenario would be helpful for testing with a html template containing that kind of link we are trying to exclude to see if the regex works properly.

2024-12-19 14:33 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/Cookie/Termly.php
> +	}
I know the grooming required us to create a method like this, but seeing it now, it doesn't play a role, so I think we can send that logic to the method below.

2024-12-19 14:33 UTC, jeawhanlee commented on inc/ThirdParty/Plugins/Cookie/Termly.php
> +	public function exclude_defer_js( array $exclude_delay_js ): array {
This method name needs to change to something more generic and we need to update the docblock to be generic as well.

2024-12-23 15:44 UTC, Mai-Saad commented
@Khadreal Thanks for the PR. using the PR , can see that termly script is not excluded from deferjs /delay js
here https://new.rocketlabsqa.ovh/about. can you please check :pray: 
![Screenshot from 2024-12-23 17-43-32](https://github.com/user-attachments/assets/188f8478-a1f0-4c40-a765-d479bf081a4b)

2024-12-24 13:46 UTC, Khadreal commented
@Mai-Saad pushed a fix and tested that it's working now.

2024-12-25 06:55 UTC, wordpressfan approved these changes

2024-12-30 10:39 UTC, hanna-meda approved these changes
Thank you, @Khadreal.

After re-testing, I can confirm:
• We exclude https://app.termly.io/resource-blocker/ from defer and delay JS when `termly_display_auto_blocker` is enabled in the options table.
• We do not exclude https://app.termly.io/resource-blocker/ from defer and delay JS when `termly_display_auto_blocker` is disabled in the options table.

2024-12-30 10:39 UTC, merged